### ISSUE TITLE
test_sync_users can fail if the codebase has the 'de' language present.

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#100]
We have a report of the following failing unit test:

1) local_o365_usersync_testcase::test_sync_users
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'en'
+'de'

/local/o365/tests/usersync_test.php:313

There is a line in the sync code that checks whether the specified language is available to Moodle, and falls back to 'en' if it isn't. The test user involved here has their language set to 'de', but the assert checks for 'en' - looking for the fallback behavior.

This is caused by having the 'de' language pack in the Moodle codebase. Normally, we would not have any language packs other than 'en' in Moodle's /lang directory, and just install any additional packs through the UI. Installing languages through the UI puts them in moodledata, and since there's a separate phpunit moodledata, they don't appear in tests, however if it is in the /lang directory, they do. So for us, this test would pass successfully, but for someone with the 'de' pack in their codebase, this test would fail. We should revisit this test with that in mind and figure out a way to both test non-'en' language setting, and test the fallback behavior.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/107
