### ISSUE TITLE
Troubleshoot "Moodle is setting up this SharePoint site"

### ISSUE THREAD

**Issue by zckb** [Microsoft/o365-moodle#104]
Initial configuration of SharePoint Link (local_o365 | sharepointlink) never completes. Site provisioning is stuck at "Moodle is setting up this SharePoint site. This will occur during the next run of the Moodle cron." 

Please provide steps to troubleshoot.

**Comment by universam1** [comment]
confirm this is broken with the latest updates of 3.0

Found though in the report that it tries to set up a connection like https://https://mysiteblabla
Despite the clear description I omitted the https;// and now it works.
Guess that is a bug

**Comment by number33** [comment]
The Sharepoint link is validated when the user finishes typing in the URL.  A message is displayed under the setting textbox stating whether the URL entered is a valid Sharepoint site or not.

I've tried the following combinations (where <mysite> is a valid Sharepoint site).

1. https://https://<mysite>
2. https://https;//<mysite
3. https://https<mysite>
4. https://https;//<mysite>
5. https://https;<mysite>
6. https;//<mysite>
7. http><mysite>
8. https://https><mysite>

All combinations prompted the display of an error message in the settings page.

Can you specify exactly what was entered into the settings page?

Also what version of the Moodle o365 plugins are you currently running?

**Comment by branstraub** [comment]
Also having the same issue here, trying to use a existing Sharepoint site or a new one created through Moodle. Using the following versions:

Microsoft Account	2015111904	
Microsoft Office 365 Integration	2015111914	
Microsoft OneNote	2015111906	
Microsoft Services	2015111904	
Office 365 Integration	2015111910

Regards,

**Comment by number33** [comment]
@branstraub  Can you specify exactly what was entered into the settings page for your Sharepoint site?

**Comment by branstraub** [comment]
pilargentina.sharepoint.com/MoodleTest or https://pilargentina.sharepoint.com/MoodleTest when trying to create a new one 

and pilargentina.sharepoint.com/Moodle or http://pilargentina.sharepoint.com/Moodle to connect to a created Site from Sharepoint

In both cases it gets stucked in "Moodle is setting up this SharePoint site. This will occur during the next run of the Moodle cron."

**Comment by jamesmcq** [comment]
@branstraub Can you try this on the current release and create a new issue if the problem still exists? Thanks.
