### ISSUE TITLE
Add common troubleshooting steps to documentation

### ISSUE THREAD

**Issue by zckb** [Microsoft/o365-moodle#105]
Create new section in documentation, called General Troubleshooting, and provide steps to gather diagnostic/log data (and other useful information). 

Contents of this documentation section include (but not limited to):
Find Moodle version
Find Microsoft Office 365 Integration plugin version
Enable Record debug messages
View/get recorded log messages
Confirm app permissions in Azure AD management portal

**Comment by jamesmcq** [comment]
The has been included in the latest release. Thanks!
