### ISSUE TITLE
Moodle - Unable to set system API user

### ISSUE THREAD

**Issue by nevilleom** [Microsoft/o365-moodle#1083]
Hi, 

I'm unable to set the System API user.

When adding an API account with global admin office 365 and Azure I receive the following error on the moodle page:

*There was a problem logging you in. Please contact your administrator for assistance.*

Below are the related logs with this error

uthcode::handleauthresponse: Authorization error. Data: Array ( [state] => fggaCxQo96X9OgB [code] => [error_description] => AADSTS65005: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant.

azure error logs:

Failure
65005
The application required resource access list does not contain applications discoverable by the resource or The client application has requested access to resource, which was not specified in its required resource access list or Graph service returned bad request or resource not found. If the application supports SAML, you may have configured the application with the wrong Identifier (Entity). Try out the resolution listed for SAML using the link below: https://docs.microsoft.com/azure/active-directory/application-sign-in-problem-federated-sso-gallery?/?WT.mc_id=DMC_AAD_Manage_Apps_Troubleshooting_Nav#no-resource-in-requiredresourceaccess-list.

I can also confirm the ID and key is correct and required permissions are set.

**Comment by websternoble** [comment]
Hello Ghost. I have the same issue. Did you resolved it?
