### ISSUE TITLE
Moodle Office 365 User Connection Issues

### ISSUE THREAD

**Issue by pcomadmin** [microsoft/o365-moodle#1088]
Hello,

I have an issue that I do not know how to fix and need immediate assistance.

I work at a college so will be talking about student accounts

Situation:

User 1: Krillin Son (email: kson@school.edu)

User 2: KaioShin Son (email: kson_inactive@school.edu) _inactive as they are no longer a student and needed to change it so Krillin Son could use kson@school.edu account. User 2 is no longer in AD, Office 365 or Azure. This account is only in Moodle.

User 1 can login to Moodle via basic login with username kson and their password and get into their account. But when they try to login via the Microsoft SSO button with email kson@school.edu and their password. It will show User 2's account.

After investigating and going to Gear>Plugins>Local Plugins>Microsoft Office 365 Integration>Advanced>Manage User Connections. I noticed that User 2 is still showing a connections to email address kson@school.edu. I enabled the Match button on User 1 and User 2 clicked Unmatch for User 2. But when User 1 logs in with kson@school.edu it still shows User 2 account. From the Manage User Connection section I have no other changes I can make to remove User 2's connection to kson@school.edu

Any help would be great.

thanks 

Alex

**Comment by chriskincaid24** [comment]
Alex,

I have had similar issues when accounts get improperly matched.  We use
mysql for the backend database and use this script to find the records to
delete to fully unmatch a user.

set @id := 'xxxx';
select @authtoken := username from mdl_user where id = @id;

SELECT * FROM uormoodleprod.mdl_auth_oidc_token
where userid = @id;

SELECT * FROM uormoodleprod.mdl_local_o365_connections
where muserid = @id;

SELECT * FROM uormoodleprod.mdl_local_o365_objects
where moodleid = @id;


SELECT * FROM uormoodleprod.mdl_local_o365_token
where user_id = @id;

@id is the id field from the mdl_user table.
Then upload your csv into the manual matching page in moodle and you should
be in business.
