### ISSUE TITLE
User Field Mapping: Missing Manager Field

### ISSUE THREAD

**Issue by cschmelzer** [microsoft/o365-moodle#1091]
When we sync users from AD to Moodle we need to include the user's manager. Is it possible to map the Manager field in Azure AD to a Manager field in Moodle?  I don't see Manager as an option in the Azure AD drop down list of fields.  Can the field be added to the AD list with a Moodle field to which it can be associated?  thank you.

**Comment by jamesmcq** [comment]
Hi @cschmelzer - I've added this feature request to our list consideration in the future. Thanks!

**Comment by weilai-irl** [comment]
@cschmelzer,

The latest release (3.8.0.5 and 3.9.2) adds support to map "manager" field as a text. Please try it out.

Regards,
Lai
