### ISSUE TITLE
need some help on this issue with oidc throwing an error

### ISSUE THREAD

**Issue by barry-matthias** [microsoft/o365-moodle#1093]
Hi all

When logging in to moodle using the oidc sso method the user is redirected to the MS login screen and the credentials entered are correct but when returning from the MS login to moodle the following error is thrown.

This Office 365 user is connected to a Moodle account, but OpenID Connect login is not enabled for this Moodle account. Please log in to the Moodle account using the account's defined authentication method to use Office 365 features

I have checked the users involved and they are all set as oidc authenticated in their moodle profiles so i am at a loss as to what this error means.  Where is it getting this information and what conditions are required for this error too occur?

thanks in advance

**Comment by giselebrugger** [comment]
See this isse : https://github.com/Microsoft/o365-moodle/issues/249
I was with the same problem: "The Office 365 user is connected to a Moodle Account, but OpenID Connect login is not enabled for the Moodle account. Please log in to Moodle account using the accounts defined authentication method to use Office 365 features"

I solved the problem with UNMATCH -> MATCH the user

"Other than deleting the token in auth_oidc_token as you mentioned, you can also try manually disconnecting the Moodle and Office 365 users from the Moodle side (Site Admin > Plugins > Local plugins > Microsoft Office 365 Integration > Advanced > Manage user connections). Then reconnect using the new/current Office 365 user."

**Comment by barry-matthias** [comment]
Afternoon, we did inform the client it could be done this way but they mentioned this would mean you could not use the oidc module on its own as you would need to install the local o365 module as well. The client indicated they only wanted to use the oidc module and not the rest of the office integration modules. Therefore in this cases and with this error the oidc module is not a standalone module ?

**Comment by jamesmcq** [comment]
Hi all- looking into this.

**Comment by jamesmcq** [comment]
Hi all - we have released improvements to the user linking functionality in auth_oidc, and I believe that should fix this issue. If you are continuing to experience problems, please open a new issue. Thanks!
