### ISSUE TITLE
Broken link to PowerShell instructions

### ISSUE THREAD

**Issue by upats** [microsoft/o365-moodle#1097]
Running version 3.4.0.1 of local/office365. In the setup tab, there is a link to run a PowerShell script. The "Click here" link to instructions is broken. The link points to: https://aka.ms/MoodleTeamsPowerShellReadMe

![moodle1](https://user-images.githubusercontent.com/7084108/52819615-99fc0400-305e-11e9-80eb-d3ea213bccfb.png)
![moodle2](https://user-images.githubusercontent.com/7084108/52819620-9ec0b800-305e-11e9-833d-4b5671c68f2c.png)

**Comment by jamesmcq** [comment]
Thanks @upats - I'll get this fixed for next release.

**Comment by nenorojas** [comment]
https://aka.ms/MoodleTeamsPowerShellReadMe updated to working github link.
