### ISSUE TITLE
404 Segoe.ttf

### ISSUE THREAD

**Issue by nmouillet** [Microsoft/o365-moodle#1098]
Version 3.5.0.2 (2018051706) of local_o365 plugin causes three 404 errors (Moodle 3.5.4+ (Build: 20190208)) because the plugin tries to load the Segoe font on EVERY page of Moodle but the path define in style page is not valid.

Style (local\o365\style.css, lines 1 to 30):
@font-face { /* where FontName and fontname represents the name of the font you want to add */
  font-family: 'Segoe UI';
  src: url(font/segoeui.ttf) format('truetype');
  font-weight: 400;
  font-style: normal;
}
@font-face { /* where FontName and fontname represents the name of the font you want to add */
  font-family: 'Segoe UI';
  src: url(font/segoeuib.ttf) format('truetype');
  font-weight: 700;
  font-style: normal;
}
@font-face { /* where FontName and fontname represents the name of the font you want to add */
  font-family: 'Segoe UI';
  src: url(font/segoeuil.ttf) format('truetype');
  font-weight: 100;
  font-style: normal;
}
@font-face { /* where FontName and fontname represents the name of the font you want to add */
  font-family: 'Segoe UI';
  src: url(font/segoeuisl.ttf) format('truetype');
  font-weight: 300;
  font-style: normal;
}
@font-face { /* where FontName and fontname represents the name of the font you want to add */
  font-family: 'Segoe UI';
  src: url(font/seguisb.ttf) format('truetype');
  font-weight: 600;
  font-style: normal;
}

Resulting 404 Requests URL:
https://moodle.com/theme/styles.php/boost/1550214940_1538126459/font/segoeui.ttf
https://moodle.com/theme/styles.php/boost/1550214940_1538126459/font/segoeuisl.ttf
https://moodle.com/theme/styles.php/boost/1550214940_1538126459/font/segoeuib.ttf

**Comment by jamesmcq** [comment]
Thanks @nmouillet - this should be in the new theme instead of the local plugin. I'll have this fixed for next release.

**Comment by jamesmcq** [comment]
Hi @nmouillet, the fix for this has been released. Thanks for the report!
