### ISSUE TITLE
OneNote submission API error

### ISSUE THREAD

**Issue by upats** [microsoft/o365-moodle#1099]
I'm getting this error for one user. When they go to an assignment with the OneNote submission turned on and click "Work on this", they don't get the notebook but instead, see:

Error in API call: The entity name(or displayName in case of Graph endpoint) cannot start with a space.

Moodle ver: 3.4.6

O365 plugins on the site:

Office   365 Integration   local_office365 | 3.4.0.1   2017111301
OpenID   Connect   auth_oidc | 3.4.0.3   2017111304
Microsoft   block   block_microsoft | 3.4.0.1   2017111301
Office   365 Integration   local_office365 | 3.4.0.1   2017111301
Office   365   repository_office365 | 3.4.0.1   2017111301
Microsoft   OneNote   local_onenote | 3.4.0.1   2017111301
OneNote   feedback   assignfeedback_onenote | 3.4.0.0   2017111300
OneNote   submissions   assignsubmission_onenote | 3.4.0.2   2017111302

Log error output:

Microsoft   Office 365 Integration 
API   failure
local_onenote\api\base::sync_sections:577:   Error response received. Data: Array ( [code] => 20154 [message] => The   entity name(or displayName in case of Graph endpoint) cannot start with a   space. [innerError] => Array ( [request-id] => ad8a03bd-539c-41c2-a1d3-dbd7a4541654   [date] => 2019-02-15T18:41:43 ) )

**Comment by shcgitpf** [comment]
...does your user's name start with a space?

**Comment by upats** [comment]
Hi, no, I can verify that the username, first name, last name, nor email address start with a space.

**Comment by jamesmcq** [comment]
@upats Does the course name start with a space by any chance? In this section the "displayName" is referring to the course's "fullname".

**Comment by upats** [comment]
Hey James, course name definitely does not start with a space. Also, the issue is only happening for one user in the course that I can see.

**Comment by nenorojas** [comment]
Hi @upats ,

We couldn't reproduce the issue with Moodle 3.7 or Moodle 3.8. 
Can you please update the plugins to latest version and try again to see if this issue is still happening?

Regards

**Comment by upats** [comment]
Hi @nenorojas, i'm not using the OneNote submission any longer, thank you!
