### ISSUE TITLE
'Resource Owner Password Credentials Grant' and Federated Domain

### ISSUE THREAD

**Issue by thaihoangcfc** [Microsoft/o365-moodle#1100]
Hi, I'm using Moodle 3.5 with OpenID Connect at the moment. 

Currently we have several domains on our Office 365, one of them is noted as Federated domain, so every single time I try to sign in through that domain on Office 365 it will take me back to the company's ADFS for authentication. OpenID Connect with 'Resource Owner Password Credentials Grant' authentication method does not seem to work with that federated domain (while 'Authorization Code Flow' working fine), meanwhile I try with other domain the same directory (not federated), authentication works like a charm.

Are there any issues to fix this problem? It always say invalid login when I tried to authenticate through federated domain.

**Comment by jamesmcq** [comment]
Hi @thaihoangcfc - unfortunately additional domains and tenants currently require use of the Authorization code login flow. Providing support for the Resource owner password flow is not currently feasible but I am aware of the issue and keep it in on our list should be become doable in the future. Appreciate your comments!
