### ISSUE TITLE
Username/UPN missing from User Creation Restriction

### ISSUE THREAD

**Issue by svajiraya** [Microsoft/o365-moodle#1101]
Hi team, 

I'm trying to setup O365 in our testing environment and noticed that we can't restrict user sync based on username/UPN (our organisation has patterns set up for users and Service accounts and I would like to use regex patterns to restrict sync to actual users and exclude service accounts). 

Also, it would be great if we can chain multiple conditions with AND or OR operations. 

Also, allowing us to use extensionAttributes is a big plus. (make them text fields instead of Dropdowns - let the admins decide which field they want to play with). AAD has a limitation where it doesn't sync the **Description** field from OnPremises AD to AAD (this could have been solved by using Groups. But, AAD has a limitation on that as well - I believe 50,000 users per group, which I believe is not realistic considering our Organisation has about 85,000 users). These factors severely restrict our ability to control access.

![image](https://user-images.githubusercontent.com/14901456/53328128-64e49100-393d-11e9-9091-c211fd1280f6.png)

I'm aware that we can control logins using **auth_oidc | userrestrictions** regex, but we can't stop from unnecessary users being synced to Moodle from AAD. 

**System Details**: 
**Microsoft Office 365 Integration** - Version 2018051706
**Moodle** - Version 3.5.2 (Build: 20180910)

-S Vajiraya
UNSW Sydney

**Comment by jamesmcq** [comment]
Thanks for the suggestion @svajiraya - I've added this to our list for future features!

**Comment by svajiraya** [comment]
Use of **ExtensionAttributes** might require moving on from v1.0 API (Not sure if this can be achieved from v1 API itself, I couldn't find anything in v1 Graph API docs). Dataset from /v1.0/me is quite minimal compared to what we get from /beta/me. 

**/v1.0/me**:
```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "businessPhones": [],
    "displayName": "<displayName>",
    "givenName": "<givenName>",
    "jobTitle": "<jobTitle>",
    "mail": "<mail>",
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null,
    "surname": "<surname>",
    "userPrincipalName": "<userPrincipalName>",
    "id": "<id>"
}
```

**/beta/me**:
```json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users/$entity",
    "id": "b607d7fa-19e5-4849-97ce-3673b1401b4c",
    "deletedDateTime": null,
    "accountEnabled": true,
    "ageGroup": null,
    "businessPhones": [],
    "city": null,
    "createdDateTime": "2016-04-08T19:08:40Z",
    "companyName": "<companyName>",
    "consentProvidedForMinor": null,
    "country": null,
    "department": "<department>",
    "displayName": "<displayName>",
    "employeeId": "<employeeId>",
    "faxNumber": null,
    "givenName": "<givenName>",
    "imAddresses": [
        "<imAddresses>"
    ],
    "isResourceAccount": null,
    "jobTitle": "<jobTitle>",
    "legalAgeGroupClassification": null,
    "mail": "<mail>",
    "mailNickname": "<mailNickname>",
    "mobilePhone": null,
    "onPremisesDistinguishedName": "<onPremisesDistinguishedName>",
    "officeLocation": null,
    "onPremisesDomainName": "<onPremisesDomainName>",
    "onPremisesImmutableId": "8zlV5Oin4EqB0H/o5uXsow==",
    "onPremisesLastSyncDateTime": "2019-01-16T04:02:46Z",
    "onPremisesSecurityIdentifier": "S-1-5-21-3854405848-1337145201-2106073647-1025268",
    "onPremisesSamAccountName": "<onPremisesSamAccountName>",
    "onPremisesSyncEnabled": true,
    "onPremisesUserPrincipalName": "<onPremisesUserPrincipalName>",
    "otherMails": [],
    "passwordPolicies": "DisablePasswordExpiration",
    "passwordProfile": null,
    "postalCode": null,
    "preferredDataLocation": null,
    "preferredLanguage": null,
    "proxyAddresses": [
        <PROXYADDRESSLIST>
    ],
    "refreshTokensValidFromDateTime": "2019-01-16T03:10:15Z",
    "showInAddressList": null,
    "state": null,
    "streetAddress": null,
    "surname": "<surname>",
    "usageLocation": "AU",
    "userPrincipalName": "<UPN>",
    "externalUserState": null,
    "externalUserStateChangeDateTime": null,
    "userType": "Member",
    "assignedLicenses": [
        {
            "disabledPlans": [
                <PLAN LIST>
            ],
            "skuId": <SKU>
        }
    ],
    "assignedPlans": [
        <PLAN LIST>
    ],
    "deviceKeys": [],
    "onPremisesExtensionAttributes": {
        "extensionAttribute1": "<ATTRIBUTE REDACTED>",
        "extensionAttribute2": "<ATTRIBUTE REDACTED>",
        "extensionAttribute3": "<ATTRIBUTE REDACTED>",
        "extensionAttribute4": "<ATTRIBUTE REDACTED>",
        "extensionAttribute5": "<ATTRIBUTE REDACTED>",
        "extensionAttribute6": "<ATTRIBUTE REDACTED>",
        "extensionAttribute7": "<ATTRIBUTE REDACTED>",
        "extensionAttribute8": "<ATTRIBUTE REDACTED>",
        "extensionAttribute9": "<ATTRIBUTE REDACTED>",
        "extensionAttribute10": "<ATTRIBUTE REDACTED>",
        "extensionAttribute11": "<ATTRIBUTE REDACTED>",
        "extensionAttribute12": "<ATTRIBUTE REDACTED>",
        "extensionAttribute13": "<ATTRIBUTE REDACTED>",
        "extensionAttribute14": "<ATTRIBUTE REDACTED>",
        "extensionAttribute15": "<ATTRIBUTE REDACTED>"
    },
    "onPremisesProvisioningErrors": [],
    "provisionedPlans": [
        <PLAN LIST>
    ]
}
```

**Comment by mmulrthelp** [comment]
We are after this as a feature as well... +1

**Comment by jamesmcq** [comment]
Hi All - we've had a few requests for different improvements to user creation restrictions so I've created a project to keep things organized. I'll keep you updated as we further examine what we can do here.

**Comment by jamesmcq** [comment]
@svajiraya Username/UPN has been added as an options for user sync restriction in the latest version . thanks for the report! Extension attributes are on the list for future consideration.
