### ISSUE TITLE
User Provisioning (JIT and User Sync) not mapping user information

### ISSUE THREAD

**Issue by svajiraya** [Microsoft/o365-moodle#1102]
Hi, 

I'm trying to set up field mapping using local_o365 and I have the following in my configuration right now: 

![image](https://user-images.githubusercontent.com/14901456/53328866-03252680-393f-11e9-8235-a4025c9dc662.png)

However, the parameters are not being synced on login and users are prompted with **Profile Edit** page. 

**Moodle user search page**: 
![image](https://user-images.githubusercontent.com/14901456/53329191-c0178300-393f-11e9-99a8-1a611385a8a4.png)

**Moodle profile edit page (Admin User view):**
![image](https://user-images.githubusercontent.com/14901456/53329294-dfaeab80-393f-11e9-9872-d8e7158f238a.png)

I can confirm that all recommended settings mentioned on Moodle Documentation page have been enabled, still no luck. 

**System Details**: 
**Microsoft Office 365 Integration** - Version 2018051706
**Moodle** - Version 3.5.2 (Build: 20180910)

-S Vajiraya
UNSW Sydney

**Comment by jamesmcq** [comment]
Hi @svajiraya - this can happen if the plugins have an issue communicating with Office 365. Can you confirm that the plugins have been set up correctly? Check the "Verify Setup" section on the setup tab and the "Health Check" tool from the Advanced tab. 

If both of these look good, we'll need to collect some additional information to determine what might be preventing that information from coming through. Enable "Record debug messages" both from the advanced tab in the local plugin, and in the OpenID Connect authentication plugin. This will start recording additional information when the plugins encounter API errors. These messages are viewable from the Moodle logs (There's a direct link next to the "Record debug messages" setting in the local plugin).

After enabling these settings, check the logs when this problem happens again to see if there are any messages. Most messages will give you a pretty good idea of what's happening, but feel free to either post here or message me if you need some additional help figuring out what's going on. These messages can include user details and API tokens, so be sure not to share anything you want to keep private.

**Comment by svajiraya** [comment]
Hi James, 

Setup looks good. Screenshots below:

![image](https://user-images.githubusercontent.com/14901456/53505084-47632300-3b07-11e9-82bd-3ceecee82c43.png)

and 

<img width="1180" alt="screen shot 2019-02-28 at 3 13 50 am" src="https://user-images.githubusercontent.com/14901456/53505095-5053f480-3b07-11e9-945e-51c86979fea3.png">


However, I found the cause of the issue. For some reason, Token-refresh mechanism wasn't kicking in. I deleted all the stale tokens in Moodle **mdl_auth_oidc_token** table and **mdl_local_o365_token**. 

The JIT seems to be picking up the required parameters. 

![image](https://user-images.githubusercontent.com/14901456/53506867-ee958980-3b0a-11e9-8597-9b45efaa0557.png)

**Let's close this issue for now, I will re-open if the issue re-appears.** 

Regards,
S Vajiraya
Educational Intelligence & Analytics, UNSW Sydney
