### ISSUE TITLE
image_icon() introduced in Moodle 3.3, but included in earlier branches of this plugin

### ISSUE THREAD

**Issue by davosmith** [Microsoft/o365-moodle#1103]
The Moodle 3.2 and Moodle 3.1 branches of auth_oidc (and possibly others, I haven't checked) include calls to image_icon(), which was only introduced in Moodle 3.3. This gives a fatal error when running the latest version of those branches on these versions of Moodle.

See:
https://github.com/Microsoft/o365-moodle/commit/1d87da294b98445bfafb3ad20ce3353312985732
https://github.com/Microsoft/o365-moodle/commit/22af360a76d9adf06e96a9734f0bb42974e9aeeb

For the incorrect changes.

**Comment by jamesmcq** [comment]
Thanks @davosmith - I'll get that resolved for the next release.

**Comment by dustinbrisebois** [comment]
This should check if image_icon or pix_icon 

either a "if function_exists" some other handler (as Totara 12 uses a 3.2/3.3 core it needs pix_icon

**Comment by jamesmcq** [comment]
Hi all, the fix for this has been released. Thanks for the report!
