### ISSUE TITLE
Orga chart &  users info O365 sync 

### ISSUE THREAD

**Issue by kaych22** [microsoft/o365-moodle#1104]
How to sync the O365 user profile fields like reporting manager, ID, designation or role to Moodle. Also how to sync the Teams orga chart to Moodle. Thanks for the help in advance.

**Comment by jamesmcq** [comment]
Hi @kaych22 - we don't currently have support for additional fields, but it is something we're looking at in the future. Thanks for the request!

**Comment by avegys** [comment]
Hi @kaych22,

In the latest plugin versions for Moodle 3.9 and Moodle 3.10 you can set users fields mapping to sync managers, ids, roles. Managers sync allows you to re-create Teams org chart by using manager relation in Moodle.

Best regards,
Andrius
