### ISSUE TITLE
Add option to map employeeID attributes in Azure AD to Moodle ID Number in the User Field Mapping section

### ISSUE THREAD

**Issue by wielligh** [microsoft/o365-moodle#1107]
We need functionality to map an additional Azure AD attributes to Moodle ID Number in the User Field Mapping section 

An employeeID (student number/staff number) is an unique attribute that doesn't change and are part of the user profile in Moodle
Currently it is not an option to map the additional attribute in User Field Mapping section 

We select to sync these additional schema attributes/extensions from on-prem via Azure AD Connect to Azure AD

The 'User Field Mapping' section is located in "Site administration / Plugins / Local plugins / Microsoft Office 365 Integration"
 
If it is not that simple to add to the web interface is there any other way we can do it via a config file we can edit or add?

This would be handy feature if it can be simplified to add other additional or custom extensions attributes from AzureAD in the future to the Moodle user profile, scoped-affiliation, manager, and other attributres.

**Comment by jamesmcq** [comment]
Hi @wielligh - thanks for the detailed request. At the moment the field mapping tool doesn't support these additional fields from Azure AD but this is something we're looking at adding. I don't have a timeline at the moment but will keep this issue up to date as things develop.

Thanks!

**Comment by daniel-hefley** [comment]
Hi. It would be great to get some movement on this. We have numerous clients who use this integration and would like to pull in additional attributes from Azure AD, one in particular is Preferred name. That said, we are overjoyed with the recent work done on this suite of plugins. Thanks!

**Comment by weilai-irl** [comment]
Hi all,

@daniel-hefley, mapping for "Preferred name" field will be included in the next release scheduled for November 2020.

@wielligh, is there any particular field in AzureAD that you want to include in the mapping? There are quite a lot of fields returned in the user resource from Microsoft Graph API, each in a different data type. I don't think we will be able to process all of them, but if you have any field that you need in particular, we can definitely look at adding them. The full list of attributes is at https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties.

Regards,
Lai

**Comment by weilai-irl** [comment]
@daniel-hefley, could you clarify how the preferred name field is set for office 365 users please. We have implemented the logic, but having trouble setting the field for test.

Regards, 
Lai

**Comment by weilai-irl** [comment]
@daniel-hefley,

The latest release (3.8.0.5 and 3.9.2) adds support to map the "Preferred name" field. As said in my previous note, the logic has been implemented, but we couldn't test this out. Please take a look and let us know if this isn't working.

Regards,
Lai
