### ISSUE TITLE
User sync will create an account for an O365 user that is already connected to a Moodle user using the "connected account" setup.

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#111]
If a Moodle user is using the "connected/linked account" setup with an Office 365 account, the user sync will still create a new Moodle account for that Office 365 user

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/125

**Comment by jamesmcq** [comment]
Thanks - this has been reviewed and tested. Patches in wip-MSFTMPP-449-m27, wip-MSFTMPP-449-m28, wip-MSFTMPP-449-m29, wip-MSFTMPP-449-m30. This will be included in the next release.
