### ISSUE TITLE
unit test failure due to core lang string change.

### ISSUE THREAD

**Issue by danmarsden** [microsoft/o365-moodle#1112]
the core lang string changed in 
https://github.com/moodle/moodle/commit/f71537690712ec903562c9b32f4e7dc9f05e5b0d

but the local_0365 test has a hard-coded string check.

1) local_o365_webservices_onenoteassignment_testcase::test_assignment_read
Failed asserting that exception message 'Can't find data record in database table course. (SELECT * FROM {course} WHERE id = ?
[array (
  0 => -1,
)])' contains 'Can not find data record in database table course'.

also 6 or so other webservices_utile_testcase tests failing due to that issue.

**Comment by mmulrthelp** [comment]
@danmarsden Would this be what is causing our login web service to have stopped working ever since we moved to using open connect ID part of the office 365 plugin?

**Comment by danmarsden** [comment]
Unlikely that this is related to your issue.

**Comment by jamesmcq** [comment]
Thanks @danmarsden - I'll take a look. 

@mmulrthelp unlikely to cause any issues on your end as I believe this is a unit-test only issue. Do you have an open issue for the problem you're experiencing?

**Comment by jamesmcq** [comment]
This should now be resolved. Thanks!
