### ISSUE TITLE
Logout moodle but office 365 keep logged in

### ISSUE THREAD

**Issue by drqo** [microsoft/o365-moodle#1113]
Hi, 
I have an issue.
When any user login with office 365 login page, the system redirects to moodle. that´s good.
But when the user logout from moodle, the office365 account keep logged in, thats not so good for security reasons, mostly when the user forgot to logout the 365 account from a public computer.
Is there a way to fix this issue whitout loosing the bennefits of loggin that way?
-Capability to go any office 365 service in a single sign on. 

Thanks

**Comment by jamesmcq** [comment]
Hi @drqo - the plugins do not currently support this but it's something we're aware of and looking into.

**Comment by drqo** [comment]
Hi @jamesmcq , thanks for your answer.

**Comment by cbrherms** [comment]
Does anyone have a workaround for this? Just bumped in to this issue myself on open access machines.

**Comment by websternoble** [comment]
Hello @jamesmcq, any update about this issue?

**Comment by mmulrthelp** [comment]
We're thinking of creating a link to here : login.microsoftonline.com/logout.srf

**Comment by ahmadm42** [comment]
Hello Guys, I am facing this issue too in our school. Any updates please?

**Comment by cbrherms** [comment]
As a workaround I used the following plugin:
https://moodle.org/plugins/auth_loginlogoutredir

With a logout redirect to:

https://login. microsoftonline.com/common/oauth2/logout? post_logout_redirect_uri='your_moodle_homepage_url'

**Comment by ahmadm42** [comment]
@cbrherms really appreciate you great cooperation and support. Its working perfect.

**Comment by grendons** [comment]
OIDC auth plugin must to have **O365 logout option** to logout from O365 when you disconnect from Moodle instance. Similar to CAS server (SSO).

**Comment by weilai-irl** [comment]
Hi everyone,

The latest release of the plugin for Moodle 3.8 and 3.9 contains the feature to log out users from Office 365 when they log out from Moodle. There are configuration changes required for this, on both Moodle and Azure side. Please refer to instructions at https://docs.moodle.org/39/en/Office365#Single_Sign_Off for details.

The issue will be marked closed if no errors are reported.

Regards,
Lai
