### ISSUE TITLE
Login from moodle app

### ISSUE THREAD

**Issue by drqo** [microsoft/o365-moodle#1116]
Hi, 
First of all, thanks for this plugin, i don´t know if this is the place to ask you this, sorry if not, but i would like to know, if is there a way for an user to login in the moodle app with the office 365 account SSO. 
Thanks!

**Comment by jamesmcq** [comment]
Hi @drqo - it's not something we look at closely but we do use standard Moodle SSO methods, so if you're experiencing problems I'd check with the core Moodle tracker first. Thanks!
