### ISSUE TITLE
Login Works | Microsoft Block - "Connection Status"

### ISSUE THREAD

**Issue by compohara** [microsoft/o365-moodle#1117]
![Status](https://user-images.githubusercontent.com/37961382/59345079-485f3f80-8d07-11e9-8a2d-41c4b9fef203.PNG)
![Block](https://user-images.githubusercontent.com/37961382/59345084-49906c80-8d07-11e9-8383-0a8c2d1a9223.PNG)

Hello all,

I have hit a roadblock with my Office365 integration. 

We have the login fully working, the users are matched up and ready to go. The connection status in the user matching admin console reports that the user is connected.

The problem is when we view the Microsoft Block it tells us that we are not connected? Going through the steps on 'Connect Office 365' still just brings us back to this status - no errors or logs picked up. 

Any ideas would be greatly appreciated

Thanks

**Comment by compohara** [comment]
Still no closer to a solution. Rebuilt the entire system and still having the same issue. Any ideas at all?

**Comment by jamesmcq** [comment]
Hi @compohara - is this user able to access Office 365 features? i.e. calendar sync, OneDrive repository etc?

**Comment by jamesmcq** [comment]
Closing this issue during issue cleanup. If you're able to provide some additional information please open a new issue. Thanks!
