### ISSUE TITLE
B2C Integration - OpenID

### ISSUE THREAD

**Issue by carlalopez15** [microsoft/o365-moodle#1121]
Hi Team, is there any recent update to support B2C?

Thanks

**Comment by jamesmcq** [comment]
Hi @carlalopez15 - not at the moment but I've added this to our backlog. Thanks!

**Comment by WhippsP** [comment]
Integration with B2C Can be done by setting the Scope being sent the OIDC authorization endpoint. This scope needs to include the clientId. The following PR addresses this - https://github.com/microsoft/o365-moodle/pull/1239
