### ISSUE TITLE
Provide Admin Consent Error after authenticating on Office 365 

### ISSUE THREAD

**Issue by websternoble** [microsoft/o365-moodle#1122]
In Microsoft Office 365 Integration, Step 3/3: Admin consent & additional information, after I click "Provide Admin Consent" and logon with my O365 Global Admin credentials I get the following error:

There was a problem logging you in. Please contact your administrator for assistance.

Then, It takes me to this site:
[https://docs.moodle.org/37/en/error/auth_oidc/errorauthgeneral](url)

---------------------------------------------------------------------------------------------------
I have moodle 3.7 and Office 365 Integration Plugin is version 3.6.0.0.

Any idea??

**Comment by jamesmcq** [comment]
Hi @websternoble - Is the "There was a problem logging you in. Please contact your administrator for assistance." message coming from Moodle or Office 365? (i.e. are you on the Moodle site or the Office 365 login page when it occurs?)

**Comment by websternoble** [comment]
Thank you James, 

Just yesterday I was able to solve the problem. The error was presented in Moodle. The problem was due to (I do not know why) the plugin was not applying the permissions automatically in Azure when authenticating with the global administrator in the "Admin Consent" part and I had to put them manually in Azure.

**Comment by matthullulcc** [comment]
Hi James, 

I have a customer who is having this problem and the error message is coming from Moodle however, there isn't anything useful in the error log.

Can you provide any clues?

Thanks,

**Comment by Victor4455** [comment]
> Thank you James,
> 
> Just yesterday I was able to solve the problem. The error was presented in Moodle. The problem was due to (I do not know why) the plugin was not applying the permissions automatically in Azure when authenticating with the global administrator in the "Admin Consent" part and I had to put them manually in Azure.

hey Websternoble, i am facing same problem like you. could you pls help me out to solve it?
it would be a much appreciated. thanks

**Comment by mmulrthelp** [comment]
@websternoble this [blog post I wrote](https://notsomany.com/2019/10/15/moodle-office-365-azure-api-permissions/) might help toward your goal.. use this in line with what is written in the office365 moodle plugin instructions.

**Comment by Victor4455** [comment]
awesome dude.. it works. you are a legend
