### ISSUE TITLE
Sync o365 Users from Other Tenancies

### ISSUE THREAD

**Issue by scez637** [microsoft/o365-moodle#1125]
I've successfully configured multi-tenancy using this plugin. Users from my host tenancy and a guest tenancy are able to login to my Moodle instance.

My host tenancy users are synced using the usersync feature, however I don't see a way for guest tenancy users to be synced. 

* Does this feature exist somewhere?
* Is this functionality possible with the permissions requested so far to get guest tenancy login?
* If it is possible are you able to point me in the right direction so I can potentially implement this functionality?

**Comment by scez637** [comment]
This seems relevant.
https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/rest/azuread.php#L34

**Comment by jamesmcq** [comment]
Hi @scez637 - only the host tenant is supported for user sync at the moment. We are looking at expanded functionality for additional tenants but don't have a timeline as to when that may be available.

**Comment by duranchen** [comment]
Hi @scez637   we  also have multitenancy  eviroment and the same requriement - sync users with additaional tenants.  do yo get a solution for this?

**Comment by duranchen** [comment]
Hi @jamesmcq   do you have a timeline for this now?

**Comment by ranevaibhav95** [comment]
Hi Guys we too require multi tenancy in our application..do we have any timeline?@jamesmcq
