### ISSUE TITLE
Live to Test copy of Moodle - O365 Accounts not working in Test

### ISSUE THREAD

**Issue by benzini00** [microsoft/o365-moodle#1126]
Hi all,

We have just started using the O365 plugins for Moodle (excellent work to all involved in the development!) and have stumbled across an issue that doesn't appear to be covered in any documentation.

Periodically we perform a backup of our live Moodle site and restore it to a test Moodle site so that Teachers can perform modifications to their courses or test new plugins before carrying out the same in the live site.

We have two App Registrations in O365, one called 'Moodle Live' and the other called 'Moodle Test' ... very imaginative, I know ...

Once the backup has been restored to the test site we then change the 'Client ID' and 'Client Secret' in the OpenID Connect plugin to match the 'Moodle Test' App Registration, this in turn updates the same settings in the Local_O365 plugin 'Application ID' and 'Application Key'

When a user logs in to the test site they receive an error: 'There was a problem logging you in. Please contact your administrator for assistance'

I assumed this might be due to a mismatched token or the users needing to be re-sync'd due to the change of App Registration but after a full sync we're still seeing the same issue.

Any advice, hints or tips gratefully received!

Many thanks,

Ben

**Comment by mmulrthelp** [comment]
Hi Ben,

Something worth trying before someone more knowledge about such things gets back

SELECT * FROM mdl_auth_oidc_token WHERE username LIKE '**YOURUSER**%';
Find your USERS's ID in that table

Then:
DELETE from mdl_auth_oidc_token where id = **XX**;

The field that you are deleting contains your unique Microsoft ID in row 'oidcuniqid', I imagine this is tided back to your App Registration.

Hope it helps,

Regards,
Ray,

**Comment by benzini00** [comment]
Hi Ray,

Thanks for the suggestion, whilst it made absolute sense from a technical point of view unfortunately it didn't resolve the issue for us, the affected users haven't logged on to the live site yet so there wasn't a pre-existing entry for them in the mdl_auth_oidc_token table for the test site.

I asked them to log into the live site and they are able to do so without error, so it definitely feels like the issue is being caused by the change of App Registration, I'm just not sure where ...

Next move is to make another Live to Test copy tonight to see if logging into the live site means they can then log into the test site.

Many thanks,

Ben

**Comment by jamesmcq** [comment]
Hi @benzini00 - yes this could be due to the tokens stored not working for the new application. Can you enable the "Record debug messages" setting from the local plugin settings page's "Advanced" section and see if anything appears in the Moodle logs?

**Comment by benzini00** [comment]
Hi @jamesmcq - I enabled "Record Debug Messages" and asked one of the affected users to try logging in again, unfortunately nothing is getting logged.

Is there anything else we could try?

**Comment by jamesmcq** [comment]
Hi @benzini00 - I've been looking at this and it looks like the problem lies in the different client ID and secret you use on the test site. The tokens that are stored with your users are tied to the client id/secret configured on your production site, so they are rejected on your test site.

I wouldn't recommend using the production client ID/secret on the test site, and I'm not sure you could get around the different reply URL anyway. The only other option is to disconnect and reconnect all users to get new tokens. That's probably a bit of a pain but it looks like the only option.

**Comment by benzini00** [comment]
Hi @jamesmcq 

Thanks for looking in to this, I'm surprised nobody has asked about this previously, I assumed most people would have test sites running alongside their live site, maybe we're unique in the way we perform our testing.

Could you advise on the best way to disconnect & reconnect all users without removing their participation/permissions on courses?

Or alternatively, what would we need to do in order to clear out the 'test' DB so that all tokens or ties with the 'live' client ID/Secrets are removed so a new sync will provision new tokens that relate to the test app registration in Azure?

Many thanks,

Ben

**Comment by benzini00** [comment]
Hi @jamesmcq 

I realise this ticket is closed but I'd really appreciate it if you could advise on the best way to clear out tokens or ties to the 'live' client ID/Secrets that have been copied during the live to test DB copy.

I looked at disconnecting and reconnecting users but the vast majority of users hadn't previously signed in on 'live' prior to the DB copy taking place, thus the 'disconnect' option doesn't show for their account in the Moodle interface, despite having not logged in prior to the database copy the users are still unable to log into 'test'.

Many thanks,

Ben
