### ISSUE TITLE
Guest login causes redirect to home page for auth_oidc

### ISSUE THREAD

**Issue by frederickOtus** [microsoft/o365-moodle#1127]
If autologinguests is set to true, a user can be logged in a guest before they hit the login page.

Then when they click the link to log via OIDC, they will get redirected to the home page. The fix is simple, it should just be a matter of checking that the user isn't a guest. Something like this would fix it:

https://github.com/moonami/moodle-auth_oidc/commit/8a9cd46c7e7dd1ff4d40bd8591e376f2e3cbb5d7

Edit: first time I submitted, I linked to the wrong commit

**Comment by tonket** [comment]
We're having the same problem. Did that fix work for you @frederickOtus ?

**Comment by frederickOtus** [comment]
Yeah, it did

**Comment by jamesmcq** [comment]
Thanks @frederickOtus, the change you posted looks simple enough. I'll evaluate for inclusion in the next release.

**Comment by jamesmcq** [comment]
Thanks @frederickOtus! This has been fixed and released.
