### ISSUE TITLE
Course Group wont Created in O365

### ISSUE THREAD

**Issue by harajukakei** [microsoft/o365-moodle#1129]
Using Moodle 3.5, when we try to run sync group course scheduled task always have this error :

Could not create team for course #48. Reason: Error in API call: Team owner not found for 36d79f82-6b32-49f7-abc7-72ab29a60a11.

Even if we tick all permission in Azure AD  it doesnt help. Any clue about this ?

**Comment by jamesmcq** [comment]
Hi @harajukakei - can you enable the "Record Debug Messages" setting from the local plugin settings page and re-run the task? Then see if any additional information appears in the Moodle logs. Thanks!

**Comment by MustafaOzman** [comment]
Are you able to fix the above issue?

**Comment by kkiiskin** [comment]
The "Team owner not found" error seems to concern courses without teachers.
So, at least for me, adding a user with teacher role to the course fixes the problem.

**Comment by MustafaOzman** [comment]
> The "Team owner not found" error seems to concern courses without teachers.
> So, at least for me, adding a user with teacher role to the course fixes the problem.

Also, the teacher must be linked(match) to o365 to over come this issue

**Comment by jamesmcq** [comment]
Hi all - checking in on this issue. Are you able to provide any debug information? Are you still experiencing this issue?

**Comment by weilai-irl** [comment]
Hi all,

Posts made by @kkiiskin and @MustafaOzman answered the question. A Team would always require an owner, so in order for a Team to be successfully created, Moodle has to be table to find a suitable Team owner from the list of users enrolled in the course. This was done by checking for enrolled teachers before, and has been changed to checking users with "local/o365:teamowner" capability in the course context in recent versions.

I'll close this issue.

Regards,
Lai
