### ISSUE TITLE
3.7 compatibility - Plugins repository update

### ISSUE THREAD

**Issue by cbrherms** [microsoft/o365-moodle#1131]
Hi, 

Do we know when the moodle plugins repository will be updated to reflect this new version that has recently been released? At present it is still only showing the 3.6 compatible version.

-Thanks

**Comment by jamesmcq** [comment]
Hi @cbrherms - we do a phased release. The development repository is updated first, followed by component repositories, followed by Moodle.org. We typically space these out by a few days to allow for early adopter reports.
