### ISSUE TITLE
Task usersync returned a "cannot optain task lock"

### ISSUE THREAD

**Issue by RSickenberg** [microsoft/o365-moodle#1132]
Hello there, I open an issue about this particular failure.

local_o365 => 2016062015 // 3.1.0.15

`sudo -u daemon php7.0 admin/tool/task/cli/schedule_task.php --execute=\\local_o365\\task\\usersync`

=> Cannot obtain task lock

I cannot even run it when I trigger global cron.php.

Can you help me?

Regards,
Romain

**Comment by mmulrthelp** [comment]
We have the same issue on our production site when we click 'run now' within scheduled tasks on 'Sync users with Azure AD' we get :

'Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
Cannot obtain task lock' 

Previously we've managed to get around this by rebooting the server, but that was when we encountered it on our DEV site. This is no longer a viable option. 

We are running Moodle 3.6.3 with local_o365 version 3.6.0.0 : 2018120300

How can we get the scheduled task 'Sync users with Azure AD' running again?

**Comment by RSickenberg** [comment]
I figured out to simply delete the lock in the DB on mdl_lock_db (I guess), and delete the corresponding lock.

**Comment by mmulrthelp** [comment]
Have you done that by using SQL like the following, [I found this mentioned here ](https://github.com/Microsoft/o365-moodle/issues/195)?

UPDATE mdl_config_plugins SET value = "" WHERE name = "task_usersync_lastskiptoken" AND plugin = "local_o365"

**Comment by RSickenberg** [comment]
@mmulrthelp I didn't, I deleted the corresponding lock on the DB.

**Comment by mmulrthelp** [comment]
Thanks @RSickenberg, SELECT * FROM moodle.mdl_lock_db; doesn't return me any locked rows..

**Comment by jamesmcq** [comment]
Hi all - this can happen if they sync task is already running in another cron run, or if the cron task stopped prematurely in the past. If you are sure it's not running somewhere else at the same time, are you able to provide any cron logs that would point to what might have caused the cron to exit? If all else fails, the SQL posted to remove the lock from the DB should get the task running again.

**Comment by mmulrthelp** [comment]
Thanks @jamesmcq stopping a long running cron task seems to have fixed the issue we were seeing, although it seemed to take a good while before the scheduled task started again. I'll try and get some time to dig through the logs to see what caused it to stall.
