### ISSUE TITLE
Token being saved for AD User with no Moodle profile

### ISSUE THREAD

**Issue by HadynM-TWoA** [microsoft/o365-moodle#1133]
This is related to 'Getting ERROR1 for some users after update #1096'

Our build:
- Moodle 3.5.6
- local_o365 3.5.0.4
- auth_oidc 3.5.0.4

Prevent account creation when authenticating = TRUE
We have an external automation process that creates profiles for staff and students.

If a staff member or student signs into Moodle after their Azure AD account is provisioned, but before their Moodle profile is created, they receive the new error message.  If their profile is then created and they attempt to sign in again the token is already saved with a 0 for the userid in the auth_oidc_token table and errors out again.  My thinking is that if there is no matching user then the token shouldn't save.

Does the userid in the auth_oidc_token table update on each sign in?

**Comment by jamesmcq** [comment]
Thanks for the detailed description @HadynM-TWoA - I'll take a look and see if there's further improvements we can make to this area.

**Comment by jamesmcq** [comment]
The latest release should resolve this issue. Please open a new issue if you continue to experience issues. Thanks!
