### ISSUE TITLE
Manually matched users awaiting completion

### ISSUE THREAD

**Issue by Rossco88** [microsoft/o365-moodle#1135]
I have an issue, were we have used the manual matching tool to match a couple of users for testing because our moodle username and office 365 username do not match.

2 of the users went through fine however the other 5 have the following error under connection status

Matched with existing user.
Awaiting completion.

I cannot find anywhere to complete this for these users

**Comment by cb526** [comment]
Hi @Rossco88 
This feature doesn't seem to work. It's mentioned in a few issues here and also see https://notsomany.com/2019/03/23/moodle-azure-active-directory-the-trials-and-tribulations/ 
If you want your users to log in with their MS credentials and use the Microsoft Block (and not avail of other features such as Teams etc) - it might be worth investigating the Oauth2 authentication instead.

**Comment by jamesmcq** [comment]
@Rossco88 Completion happens when the user in question logs in to the site and completes the connection using the Microsoft block (add the block to a page they'll see and a message will appear in the block prompting them to complete the match).
