### ISSUE TITLE
SDS sync task emits PHP7.3 warning regarding 'continue' in a switch

### ISSUE THREAD

**Issue by fluxcorenz** [microsoft/o365-moodle#1136]
Plugin version: 3.7.0.1 / 2019052001
Moodle version: 3.7.1 (and master branch code)
PHP version: 7.3.4

The moodle/admin/cli/cron.php task ran this morning (the first after an upgrade of the moodle system and PHP) and emitted the below warning:

PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/localhost/htdocs/moodle/local/o365/classes/feature/sds/task/sync.php on line 129

Examining the code, it does look like 'continue 2' is what is intended- default+continuing out of the switch statement will result in the $role variable being unassigned, which will likely cause issues for the rest of the calls after the switch statement. A 'continue 2' would result in skipping over this item in the outer foreach loop, which looks to be more the intent.

I would make a pull request, but I think a dev should be the one to decide what functionality is correct.

https://www.php.net/manual/en/migration73.incompatible.php shows this as a new warning introduced in PHP 7.3

**Comment by jamesmcq** [comment]
Thanks @fluxcorenz - this will be fixed with the next release.

**Comment by jamesmcq** [comment]
Thanks @fluxcorenz! This has been fixed and released.
