### ISSUE TITLE
Moodle tab not appearing after being added in team

### ISSUE THREAD

**Issue by Rossco88** [microsoft/o365-moodle#1138]
We seem to be having an issue with the moodle app for teams. 

We completed all the steps in the plugin (except the bot steps as we are sorting billing our a test azure tenant), downloaded the manifest file and uploaded to teams.

When trying to add the app to a team site, we originally got the all ok but no tab appeared. See below image where you can see moodle has been added but there is no tab.

![teamsapp1](https://user-images.githubusercontent.com/43981046/63317910-f1ee2d00-c357-11e9-86fd-fa402b370f27.png)

If we try to add the app again we are prompted with a blank screen as below 

![moodleapp](https://user-images.githubusercontent.com/43981046/63317935-11855580-c358-11e9-8137-2e9b33b7d7fb.png)

The only step we haven't done at this stage is enable OIDC for the users we have manually matched via CSV as our moodle site doesn't support dual auth with OIDC and SAML currently.

Thanks

**Comment by MustafaOzman** [comment]
![Screenshot 2019-08-20 at 5 01 27 PM](https://user-images.githubusercontent.com/14904622/63335534-22da5c00-c370-11e9-8b28-cb933bcdc3b0.png)
Facing same issue as  i followed all instruction in Microsoft Teams Documentation but nothing appear.
https://education.microsoft.com/courses-and-resources/resources/microsoft-teams-moodle

Cron job for creating group is not successful 
![Screenshot 2019-08-20 at 5 16 37 PM](https://user-images.githubusercontent.com/14904622/63335772-8b293d80-c370-11e9-8e8a-2e15e6deffb7.png)
Please, advice if there is anything missing

Moodle released : 3.7.1+
local_0365 version: 2019052001
auth_oidc: 2019052001
![image](https://user-images.githubusercontent.com/14904622/63335941-d6dbe700-c370-11e9-8530-e6e8d67125f2.png)

!
![image](https://user-images.githubusercontent.com/14904622/63335928-d04d6f80-c370-11e9-819b-b3fad5fe04ec.png)
[image](https://user-images.githubusercontent.com/14904622/63335918-ccb9e880-c370-11e9-9bd4-0fdc413aa9bb.png)

![image](https://user-images.githubusercontent.com/14904622/63335909-c88dcb00-c370-11e9-8477-ed53a76b0082.png)

![image](https://user-images.githubusercontent.com/14904622/63335902-c592da80-c370-11e9-8a8d-f3f86b34f292.png)

**Comment by Rossco88** [comment]
I did some further testing on this with a different moodle site. 

MustafaOzman, can you confirm if your moodle site is open to the internet? 

The site I am currently having difficulty this issue with is only available from our on-premise network.  

A new moodle site I created did not have this issue but is open to the internet so I am thinking it because teams can't pull a site list from moodle

**Comment by MustafaOzman** [comment]
> I did some further testing on this with a different moodle site.
> 
> MustafaOzman, can you confirm if your moodle site is open to the internet?
> 
> The site I am currently having difficulty this issue with is only available from our on-premise network.
> 
> A new moodle site I created did not have this issue but is open to the internet so I am thinking it because teams can't pull a site list from moodle

Microsoft Teams app is showing blank but when i open Teams in browser , it list the courses for me. Any idea why?

Another issue, the group in Teams is created as other type instead of class type as i need assignment and notebook to be exit in the group in Teams. 
How the group can be created as class in Teams when schedule task run to create group from Moodle?

**Comment by anzaro** [comment]
I have the same problem, Moodle app in Microsoft Teams is blank, no errors, but in the browser it shows a sad face with the message "...my_moodle_url... **refused to connect**".

Has somebody faced and solved this problem already?

I don't know if it's related, but when I login to moodle using OpenID Microsoft credentials, it ends up in the user profile. There's another issue for this here, in github.

Thank you,
Antonio.
![teams moodle app error](https://user-images.githubusercontent.com/49252523/64480884-06904900-d1d1-11e9-8a6f-c42464527133.png)

**Comment by MustafaOzman** [comment]
@anzaro 
You can open Teams using browser to overcome this issue until we find the root cause of the app issue and solve it

**Comment by Rossco88** [comment]
@jamesmcq  any update on this? I am still getting this error in the app and also getting the connection refused in the browser. Can you point us in the direction of some logs to see why this being refused on the moodle side? Thanks

**Comment by Rossco88** [comment]
In the moodle site that isn't working we see the following in our access logs for moodle

- GET /local/o365/teams_tab_configuration.php HTTP/1.1" 200 103539 - "-" "https://teams.microsoft.com/_"  

But then nothing after this. In a fresh moodle environment we see the following logs (this is when it works)

- "GET /local/o365/teams_tab_configuration.php HTTP/1.1" 200 2299 "https://teams.microsoft.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "GET /local/o365/sso_end.php HTTP/1.1" 200 526 "https://url.domain/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "GET /auth/oidc/index.php HTTP/1.1" 303 800 "https://url.domain/local/o365/teams_tab_configuration.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "POST /auth/oidc/ HTTP/1.1" 303 516 "https://login.microsoftonline.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "GET /local/o365/teams_tab_configuration.php?bypassauth=1&sesskey=W56C57ui HTTP/1.1" 200 2733 "https://login.microsoftonline.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "GET /auth/oidc/index.php HTTP/1.1" 303 516 "https://url.domain/local/o365/teams_tab_configuration.php?bypassauth=1&sesskey=F9ZAJT6X9Z" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "GET /local/o365/teams_tab_configuration.php?bypassauth=1&sesskey=9qEp3780hQ HTTP/1.1" 200 2698 "https://url.domain/local/o365/teams_tab_configuration.php?bypassauth=1&sesskey=F9ZAJT6X9Z" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "GET /local/o365/teams_tab.php?id=2 HTTP/1.1" 303 1069 "https://teams.microsoft.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "GET /course/view.php?id=2 HTTP/1.1" 200 20860 "https://teams.microsoft.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

- "POST /lib/ajax/service.php?sesskey=9q34630hQ&info=core_fetch_notifications HTTP/1.1" 200 38 "https://url.domain/course/view.php?id=2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

**Comment by Rossco88** [comment]
@jamesmcq  Is there a limit to the number of units/courses that can be displayed in the iframe? I can see in developer tools that it is actually pulling a list of all our units from moodle. There is around 1700 units currently

Should the plugin only display the course you are trying to load from the team or all courses?

**Comment by Ablomarcovjk** [comment]
@jamesmcq & @Rossco88 : Any updates on this issue? We are having the same one over here. 
We want Moodle tab to show in teams but when uploading the custom app it doesn't show anything but moodle.url refused to connect error. 

Any updates on this would be amazing. 

![Screenshot from 2019-10-22 11-28-13](https://user-images.githubusercontent.com/34357656/67252527-10d77f80-f4bf-11e9-8d1d-a70a9f6bb8f7.png)

**Comment by kristian-94** [comment]
We solved this in our environment with a simple server level config change. There is an nginx config setting that allows/prevents your site being embedded in an iframe. On this page, we were getting a lot of errors in the console to do with iframes and the browser refusing to embed. 
By changing the ECS variable allow_iframe=true and rolling out a new task def with this, the nginx config in our containers updated and we no longer had this issue. 
Hopefully this helps someone else.

**Comment by jamesmcq** [comment]
@weilai-irl  Thoughts on this one?

**Comment by weilai-irl** [comment]
@Rossco88, @Ablomarcovjk, @anzaro, @MustafaOzman,

Teams integration in Moodle would require Moodle pages to be allowed to be embedded into frames on pages in other domains to work, technically this would be what happens when you try to open a Moodle tab in teams, either in app or in browser. This would be the primary reason for "refused connection" errors.

In Moodle, there is a setting to control this. It's in "Site administration" -> "Security" -> "HTTP Security" -> "Allow frame embedding (allowframembedding)", and the default value is No. This needs to be changed to Yes. Besides this, as @kristian-94 pointed out, there could be server settings blocking this as well, so it would be best to test this by creating a simple iframe with "src" to be any page of your Moodle site and host it on localhost or a server in a different domain, and confirm the embedded Moodle page can be accessed.

Could you verify this please.

**Comment by weilai-irl** [comment]
@MustafaOzman,

To answer questions in your notes:
1. Regarding the error messages of "Team owner not found" you pasted - in earlier implementation of Teams integration, Teams were created from groups, which was an existing feature for a while; however, Teams would always require at least one Team owner, while groups can exist without it. When trying to create a Team from a group without owner, you would see the "Team owner not found" error.
2. Regarding the error messages of "Could not find group object ID..." you pasted - again in earlier implementation of Teams integration, groups are created first from the course, and Teams would be created from group. Therefore it is requirement that when trying to create a Team, group exists already. When creating a group, Moodle would save its GUID into local_o365_objects table. The error you see basically means this record cannot be found. I can't tell why this happened based on the messages pasted, unfortunately.

Just to note that the logic about teams creation has changed slightly since version 2019052003. The new logic says, if at least one teacher with OIDC authentication method exists in the course when setting up group sync with Teams feature, Moodle will try to create a Team directly (i.e. not creating group first then creating a team from group), and the Team created would be using education template, thus it will be a class Team.

**Comment by weilai-irl** [comment]
Hi everyone,

In our recent investigations, we found another case where Moodle tab or configuration pages fails to display content. This happens when trying to login users using SSO, and if the action of logging in the user to Office365 would result in a prompt such as the reminder to setup multi-factor authentication, like the screenshot attached, then the error would happen because the page containing the prompt, which normally would have a URL such as https://login.microsoftonline.com/common/oauth2/authorize?redirect_uri=xxx, doesn't permit framing due to its "X-Frame-Options" attribute set to "DENY". As you see, this page is managed by Microsoft therefore changing Moodle server or application settings would have no impact on it. I can't think of an easy workaround to this.

Note this doesn't affect users who have multi-fact authentication set up - in that case, the original logging to teams.microsoft.com would have authenticated the user, and when Moodle tries to SSO, no more prompt window is to be shown, so user would see Moodle pages in tabs correctly. The only case we saw this error so far is the one in the screenshot.

![Screenshot 2020-01-30 at 09 34 40](https://user-images.githubusercontent.com/695310/73437885-0beb5d00-4345-11ea-85c1-4d6b452b2fbe.png)

**Comment by cend77** [comment]
I have the same problem, I downloaded manifest file and uploaded it to tenant's Teams store and when I add the Moodle tab to a team a blank page apperars. I deleted the app from the store and remade it and nothing changes. Please advice me what do I need to make or change? Thanks
![moodleprtscrn](https://user-images.githubusercontent.com/64138054/79974162-796cdc80-84a1-11ea-8773-e527ae9b58ae.png)

**Comment by nenorojas** [comment]
Hi @cend77 ,

Can you please confirm that you completed the multi-factor authentication for the user as @weilai-irl mentioned and if it worked for you?

![image](https://user-images.githubusercontent.com/3680797/86034360-5a0aa680-ba32-11ea-8e09-ffcfbe92dea1.png)

If doesn't work, the next step is to check server configuration as mentioned before:

> We solved this in our environment with a simple server level config change. There is an nginx config setting that adds a header that allows/prevents your site being embedded in an iframe. On this page, we were getting a lot of errors in the console to do with iframes and the browser refusing to embed.
> By changing the ECS variable allow_iframe=true and rolling out a new task def with this, the nginx config in our containers updated and we no longer had this issue.
> The specific change in nginx was to remove the header: `add_header X-Frame-Options SAMEORIGIN;`
> Hopefully this helps someone else.

With both items checked, this issue should be sorted.

Regards

**Comment by vilyams** [comment]
In our case, the moodle tab is showing 'You dont have any course to add' message briefly and then shows the Login options 'Login to Office 365' button and the 'Login Manually" button.

**Comment by weilai-irl** [comment]
Hi @vilyams,

From your description, it looks like SSO between teams and Moodle isn't working. The reason for this can vary. At the most basic level, could you confirm if the user in question can use the their Office 365 account to login to Moodle please (in a separate browser, outside of Teams).

Regards,
Lai

**Comment by bradnielsen2981** [comment]
So, in my case, I get the error where by I can see the list of courses and then it quickly flashes to the Login with Office 365 and Login Manually. 

I followed the code and for some reason in sso_login.php LINE 40. If I set $loginsuccess = true, it works. Is there any reason why the authentication code below it would return false?

$loginsuccess = true;

if ($authoidctoken = $DB->get_record('auth_oidc_token', ['oidcusername' => $payload->upn])) {
    if ($user = core_user::get_user($authoidctoken->userid)) {
        $_POST['code'] = $authoidctoken->authcode;
        $user = authenticate_user_login($user->username, $user->password, true);
        if ($user) {
            complete_user_login($user);
            $loginsuccess = true;
        }
    }
}

**Comment by vilyams** [comment]
> Hi @vilyams,
> 
> From your description, it looks like SSO between teams and Moodle isn't working. The reason for this can vary. At the most basic level, could you confirm if the user in question can use the their Office 365 account to login to Moodle please (in a separate browser, outside of Teams).
> 
> Regards,
> Lai

Hi Lai,

Yes the user is able to login to Moodle using office 365 account.

**Comment by klovsb** [comment]
Similar to our case
[https://github.com/microsoft/o365-moodle/issues/1466](url)

**Comment by dariozueger** [comment]
We also have the problem, that the user just sees a signin screen, if he wants to add the Moodle App in Teams. We adjusted all the new permissions in Azure AD. The users are abel to login to Moodle using the Office 365 account.
![image](https://user-images.githubusercontent.com/78471426/106743182-553c4f80-661e-11eb-9209-5e598e0950db.png)

**Comment by alusignan** [comment]
I am experiencing the same issue as described in #1486 

Did you solve this by any chance ?

Thank you !

**Comment by vilyams** [comment]
Yes we resolved it.

I think the maint issue was that we had to install the Teams Theme for
Moodle as a plugin. Without this, it doesn't work. After we installed this
plugin, we redid all the steps and it worked.

Regards,
William

**Comment by klovsb** [comment]
> Hi everyone,
> 
> In our recent investigations, we found another case where Moodle tab or configuration pages fails to display content. This happens when trying to login users using SSO, and if the action of logging in the user to Office365 would result in a prompt such as the reminder to setup multi-factor authentication, like the screenshot attached, then the error would happen because the page containing the prompt, which normally would have a URL such as https://login.microsoftonline.com/common/oauth2/authorize?redirect_uri=xxx, doesn't permit framing due to its "X-Frame-Options" attribute set to "DENY". As you see, this page is managed by Microsoft therefore changing Moodle server or application settings would have no impact on it. I can't think of an easy workaround to this.
> 
> Note this doesn't affect users who have multi-fact authentication set up - in that case, the original logging to teams.microsoft.com would have authenticated the user, and when Moodle tries to SSO, no more prompt window is to be shown, so user would see Moodle pages in tabs correctly. The only case we saw this error so far is the one in the screenshot.
> 
> ![Screenshot 2020-01-30 at 09 34 40](https://user-images.githubusercontent.com/695310/73437885-0beb5d00-4345-11ea-85c1-4d6b452b2fbe.png)
@weilai-irl  in our case, we do not have multi-factor but in Team Desktop / browser I am prompted to enter passwrod and the link is login.microsoftonline.com.  I can login but then nothing changes.  The 2 login buttons just stay there.
![Screenshot 2021-03-17 105655](https://user-images.githubusercontent.com/1943986/111515015-8a54bb00-870f-11eb-8f67-ed9583e30181.png)

**Comment by dariozueger** [comment]
@klovsb Do you also think, that an ADFS infrastructure could lead to the same error as described with the reminder to setup MFA?

**Comment by klovsb** [comment]
> @klovsb Do you also think, that an ADFS infrastructure could lead to the same error as described with the reminder to setup MFA?

@dariozueger I wish I know.  I am no expert in ADFS architecture or O365 administration.  In our case, the Moodle apps added to individual Team classroom before the plugin's upgrade (from 3.8.0.3) continue to work, so apparently the existing ADFS infrastructure is not breaking Moodle-Team SSO with the existing Moodle app.

**Comment by klovsb** [comment]
> Yes we resolved it. I think the maint issue was that we had to install the Teams Theme for Moodle as a plugin. Without this, it doesn't work. After we installed this plugin, we redid all the steps and it worked. Regards, William
@vilyams What is your Moodle, PHP and server environment?  Johnny

**Comment by weilai-irl** [comment]
Hi all,

The local_o365 releases for Moodle 3.9 and 3.10 that contain improvements in Moodle and Teams integration have finally arrived. The new version should fix most issues in the integration, if not all. The release notes for [Moodle 3.9](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m310) and [Moodle 3.10](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m39) are linked.

Please upgrade your plugin [local_o365](https://moodle.org/plugins/local_o365/versions) (and [auth_oidc](https://moodle.org/plugins/auth_oidc/versions) which it depends on) to the latest version and try it out. Please report back any remaining issues found in this issue. The issue will be kept open for one month from today, and will be closed if most issues are confirmed resolved.

Regards,
Lai

**Comment by lalitm14** [comment]
Hi Folks,

any definitive solution to this issue?

**Comment by weilai-irl** [comment]
Hi @lalitm14,

This is a fairly old issue, lasted for nearly 2 years and closed almost 1 year ago. There were a few issues being mentioned in this one, all of which were fixed at the time of issue closure.

If you have any particular question about the integration, please create a new issue and describe your situation - your environment, Moodle and plugin versions, and what's not working. We will then be able to help you.

Regards,
Lai
