### ISSUE TITLE
Problem with connect to Microsoft block in

### ISSUE THREAD

**Issue by demirAgovic** [microsoft/o365-moodle#1142]
I setting up a Office 365 integration to moodle and login with oidc work's fine. But when I added Microsoft block in moodle and go to connect, moodle redirect me to home page and Microsoft Block it tells us that we are not connected.

Moodle version is 3.6.3 
Microsoft Block version 3.6

https://i.stack.imgur.com/ALUuI.png

https://i.stack.imgur.com/VV4fb.png

![image](https://user-images.githubusercontent.com/50825984/63772028-8c122000-c8d8-11e9-9353-376fc7fa8ecf.png)

**Comment by jamesmcq** [comment]
Hi @demirAgovic - you mentioned login works fine, can the user access any other Office 365 features? OneDrive, Calendar sync, etc?

**Comment by avegys** [comment]
Hi @demirAgovic,

Do you still encounter this connection issue?

I think it might be the same issue like the one reported here - https://github.com/microsoft/o365-moodle/issues/1200.

What resource url is set to be used for your instance OpenId Connect authentication? You can check this by going to  Site administration -> Plugins -> Authentication -> OpenID Connect.

Best regards,
Andrius

**Comment by demirAgovic** [comment]
This is resolve when I update moodle from 3.6 to 3.8 version.
Anyway thanks...
