### ISSUE TITLE
Deploying the Moodle Bot in Azure not successful, following the steps in the documentation...

### ISSUE THREAD

**Issue by KMESupport** [microsoft/o365-moodle#1143]
i followed all the steps to deploy the moodle bot in azure but the deployment always failed showing this error:
{
"error": {
"code": "InvalidBotData",
"message": "Invalid Service Provider Id. "
}
}

to fix this i had to follow these steps:
--> delete the already created Resources or the Resourcegroup, if you created a new one for the moodle bot, to get a fresh deployment.
--> on the "custom deploymentpage", where you enter all the data to deploy the Teams Bot click "Edit template"
--> delete the following lines in the template:
--> on Line 108 delete: "serviceProviderDisplayName": "Azure Active Directory v2",
--> on Line 172 delete: "serviceProviderDisplayName": "[variables('serviceProviderDisplayName')]",

--> Click on save, to save the template
--> fill in all the required data and click on "purchase" to start the deployment once again
--> the deployment should be successful now!

please fix the template, so it does work out of the box. Also the steps to register the Teams Bot Application are not up to date any more, since you have to do this over the azure portal (App Registrations) now. Please update the manual accordingly.

Thanks a lot!

**Comment by jamesmcq** [comment]
@KMESupport Thanks for the detailed solution - are you able to submit this as a pull request so I can see exactly what you did to solve it? Thanks!

**Comment by nenorojas** [comment]
Hi, 

The last version of local_o365 now allows you to download a json with all information necessary to deploy the bot:

/admin/settings.php?section=local_o365&s_local_o365_tabs=5 
![image](https://user-images.githubusercontent.com/3680797/127196599-3e0c61a5-282a-48b8-8da6-a3b42aad4135.png)

If still doesn't work, please raise a new ticket for us to investigate. 

Regards
