### ISSUE TITLE
Group type in Teams is not class 

### ISSUE THREAD

**Issue by MustafaOzman** [microsoft/o365-moodle#1144]
The created group in during syncing the groups to Teams is as other type instead of class type as i need assignment and class notebook to be exit in the group in Teams.
How the group can be created as class in Teams when schedule task run to create group from Moodle?

**Comment by helmet33** [comment]
Did you find a workaround for this?

**Comment by MustafaOzman** [comment]
@helmet33  
Yes, i removed the line from the code which creating the teams in the plugin source code  then i run the cron job which creating the group in office 365 without adding the team. After that, lecturers need to create the team(class type) in Teams by them self but they can add the correct group from office 365 for this team which has all the enrolled students in Moodle.

**Comment by skuti-is** [comment]
Hi,
I have Moodle instance where we want all the Teams that Moodle / Teams sync creates to be of the type PLC (professional learning communities). It would be very beneficial to have this as configuration option in moodle.

**Comment by weilai-irl** [comment]
Hi @skuti-is,

If I understand it correctly, this is about the ability to create class Teams as opposed to standard Teams. The current implementation is capable of creating class Teams, but a class Team can only be created when the following condition is met:

When a course is initially synchronised to Office 365 from Moodle, it has an "editing teacher" enrolled whose Moodle account is matched to an Office 365 account in Azure. (There is a related feature request to replace the requirement of users with "editing teacher" role with capability check, which will be included in the upcoming releases).

The reason behind this condition is - Teams always require owners to exist, but groups don't. When trying to synchronise a Moodle course, it is always preferred to create class Teams, and treat course teachers as Team owner. But when teachers cannot be found, it will fall back and create groups instead. In subsequent scheduled task runs will check to see if teachers has been enrolled in the Moodle course which only has groups created by not Teams, and if teachers are found, it will call another graph web service function create a Team from the existing group. This second web service function doesn't support passing in a Team template, therefore only standard Teams can be created. From what we can see, there's no way to convert a Team to use another template after it's created either.

I confirm there is no setting in the Microsoft Moodle plugins to allow admins to select whether to create class Teams (where possible), or standard Teams, from Moodle courses. We can put this done as a feature request, and it will be processed in due course. I wouldn't treat this as critical though, as the impact will be quite limited, as in creation of class Teams will still heavily depend on the enrolments of recognisable teachers in the courses.

Regards,
Lai

**Comment by weilai-irl** [comment]
Feature request has been created at #1465. 

This one will be closed.
