### ISSUE TITLE
Enabled / Disabled Delta from Azure AD to Moodle

### ISSUE THREAD

**Issue by mmulrthelp** [microsoft/o365-moodle#1146]
Hi, does the delta sync pick up account enabled/disabled changes ?
The setting in Azure AD is called 'Block sign in' = No (Allow user), Yes (Block user)
No part of the sync seems to be pulling this information across for me.

If not, does any part of the sync do this?

Sync settings which I've currently got set are:

- Create accounts in Moodle for users in Azure AD 
- Update all accounts in Moodle for users in Azure AD

All the others sounded like they would slow the sync down to much, I've currently got it set to run every 8 mins, we have around 70,000 users in our Moodle.

The reason for wanting this is to set up a method of culling no longer needed accounts out of Moodle, using the cron and a moving target of 'account suspended' and not used for 360 days, rather than removing them straight away once removed in Azure AD, in case a mistake is made. 
If the accounts in Moodle don't receive this suspension status information like LDAP did, then I cannot do this. Doing this as a manual task will require a lot of constant hassle.

I'm sure it would help other institutions to control their accounts as well.

I assume if an account is set as blocked in Azure AD then the user doesn't even get to the Moodle level to check that there is an account there... Would that be a correct assumption?

Any help greatly appreciated.

**Comment by jamesmcq** [comment]
@mmulrthelp I don't believe this is included in the delta sync, but you are correct that is the user is blocked from logging in to Azure AD/Office 365, they would not be able to reach Moodle.
