### ISSUE TITLE
error on SDS sync

### ISSUE THREAD

**Issue by cbrherms** [microsoft/o365-moodle#1147]
Any idea what could be the cause of this?
Seems to error out towards the end of a manual sds sync with the following error:

`Scheduled task failed: Sync with SDS (local_o365\feature\sds\task\sync),Error in API call: The specified page token value has expired and can no longer be included in your request.`

A little stumped as i'm sure it was working fine yesterday

**Comment by jamesmcq** [comment]
Hi @cbrherms - A few questions:
- Are you actively using the SDS integration or was this just something noticed in the logs? 
- If you are using SDS, does sync still work or has it stopped?
- Are you using the system API user or application access?
- Do you see any other errors in the cron logs? Specifically from a task called "refreshsystemrefreshtoken"?

**Comment by cbrherms** [comment]
Hi @jamesmcq 

- We are indeed actively using the SDS integration for course creation and enrolment of users.

- So long as profile data sync is disabled then course creation and enrolment completes as expected.

- Currently, application access is checked, though we have set a system api user in the past but i believe having application access checked forces that method, correct?

- No errors relating to "refreshsystemrefreshtoken" as far as i can see.

Here is an example of the output when running sds sync manually with profile data sync enabled:

```
Execute scheduled task: Sync with SDS (local_o365\feature\sds\task\sync)
... Processing Film Television and Media
...... Processing DTFP_18
...... Processing BAPP_18
...... Processing BAIF_4_PV1441_1920
...... Processing BAPP_5_DD2444_1920
...... Processing BAPP_5_DD2442_1920
...... Processing BAPP_6_DD3441_1920
...... Processing BAIF_5_PV2444_1920
...... Processing BAIF_5_PV2445_1920
...... Processing BAPP_4_DD1442_1920
...... Processing DTFP_17
...... Processing BVFX_4_DD1412_1920
...... Processing BAIF_6_PV3444_1920
...... Processing BAIF_18
...... Processing BVFX_5_AV2410_1920
...... Processing BAPP_4_DD1444_1920
...... Processing BVFX_4_AV1411_1920
...... Processing BVFX_6_AV3410_1920
...... Processing BAPP_4_DD1441_1920
...... Processing BAIF_6_PV3441_1920
...... Processing BAPP_5_DD2443_1920
...... Processing BAPP_4_DD1443_1920
...... Processing BVFX_5_AV2411_1920
...... Processing BAPP_5_DD2441_1920
...... Processing BVFX_4_AV1410_1920
...... Processing DTFP_19
...... Processing BVFX_5_AV2412_1920
...... Processing BAIF_19
...... Processing BAIF_17
...... Processing BVFX_4_DD1430_1920
...... Processing BAPP_19
...... Processing BAPP_6_AV3403_1920
...... Processing BAPP_17
...... Processing BAIF_6_PV3445_1920
...... Processing BVFX_6_AV3412_1920
...... Processing BVFX_5_DD2430_1920
...... Processing BAPP_5_DD2445_1920
...... Processing BAPP_6_DD3443_1920
...... Processing BVFX_6_AV3411_1920
...... Processing BVFX_19
...... Processing BAIF_5_PV2442_1920
...... Processing BAIF_4_PV1444_1920
...... Processing BAIF_4_PV1443_1920
...... Processing BAIF_5_PV2441_1920
...... Processing BVFX_17
...... Processing BVFX_18
...... Processing BAIF_5_PV2443_1920
...... Processing BAIF_4_PV1442_1920
...... Running profile sync
... used 1572 dbqueries
... used 22.158766031265 seconds
Scheduled task failed: Sync with SDS (local_o365\feature\sds\task\sync),Error in API call: The specified page token value has expired and can no longer be included in your request.
```

**Comment by cbrherms** [comment]
refreshsystemrefreshtoken tasks seem to be completing successfully also:

```
Execute scheduled task: Refresh system API user refresh token (local_o365\task\refreshsystemrefreshtoken)
... Success!
... used 0 dbqueries
... used 0.021324872970581 seconds
Scheduled task complete: Refresh system API user refresh token (local_o365\task\refreshsystemrefreshtoken)
```

**Comment by weilai-irl** [comment]
Hi @cbrherms,

I know this has been reported more than 2 years ago. Sorry for not coming back to you sooner.

Let's see if this still happens after the December release. I can revisited it to take a deeper look if the problem persists.

Regards,
Lai
