### ISSUE TITLE
AAD claims firstname,lastname override Moodle User attributes

### ISSUE THREAD

**Issue by Yarden6260** [microsoft/o365-moodle#1153]
When Turning off all the options under local_o365 -> Sync Settings -> Sync users with Azure AD,
the login process via AAD still override the User's first and last name in Moodle (our users are sync from LDAP and authenticate via AAD).

**The attributes update originates in local\o365\classes\observers.php:283 :** 
`
// Extract basic information from the IDToken.

            $updateduser = new \stdClass;
            $firstname = $idtoken->claim('given_name');
            if (!empty($firstname)) {
                $updateduser->firstname = $firstname;
            }
            $lastname = $idtoken->claim('family_name');
            if (!empty($lastname)) {
                $updateduser->lastname = $lastname;
            }`

**Changing if to the code below solves the problem:**
`
//Check if user update from AAD is enabled
            $azure_sync_options = \local_o365\feature\usersync\main::get_sync_options();
            $is_user_profile_update_enabled = isset($azure_sync_options['settings_aadsync_update']) && $eventtype === 'login';

            // Extract basic information from the IDToken.

            $updateduser = new \stdClass;

            if($is_user_profile_update_enabled || $eventtype === 'create'){
                $firstname = $idtoken->claim('given_name');
                if (!empty($firstname)) {
                    $updateduser->firstname = $firstname;
                }

                $lastname = $idtoken->claim('family_name');
                if (!empty($lastname)) {
                    $updateduser->lastname = $lastname;
                }
            }`

I ran into this issue in version 3.5.0.1 (2018051701), but its exists also in version 3.7.0.0 (2019052000).

Regards,
Yarden.

**Comment by jamesmcq** [comment]
Hi @Yarden6260 - looks like a great improvement! Can you submit as a pull request? I'd love to include this.

**Comment by weilai-irl** [comment]
The issue has been fixed in 3.8.0.5 and 3.9.2 releases of the plugins in November 2020 in PR #1428 and #1429.

I'm closing this issue now.

Regards,
Lai
