### ISSUE TITLE
Issue on integration Moodle - Office 365

### ISSUE THREAD

**Issue by abrude89** [microsoft/o365-moodle#1154]
Good Morning!

Recently y started to try integrate my moodle platform with my O365 Tenant. 
Near to finish, i found an issue, when i try to verify my Azure app in moodle, i recived the next messagge:

![image](https://user-images.githubusercontent.com/55792939/65598694-65481780-df72-11e9-9ae9-c2cbb7da0e91.png)

My app is already register, and ID and Secret was imported to moodle, also, the app has permisions over Azure.

Kind regards

**Comment by mmulrthelp** [comment]
@abrude89 our installation says the same thing, but works fine.. no idea why it tells you that within Moodle.

**Comment by jamesmcq** [comment]
Hi all - this does happen sometimes and we're actually looking at removing that test as it's not really useful anymore. If you notice this affecting plugin operation, please open a new issue. Thanks!
