### ISSUE TITLE
Moodle O365 Teams integration

### ISSUE THREAD

**Issue by majidh8** [microsoft/o365-moodle#1155]
When attempting to add a Moodle course into MS Teams, we are seeing the following error message:

**The reply URL specified in the request does not match the reply URLs configured for the application.**

This happens when attempting to add a Moodle course into Teams. Initially, the view shows a list of Moodle courses but then redirects and shows the options to log in (2nd screenshot). Clicking "log into O365" then generates the error above which you can see in the screenshots attached.

There were no issues with the configuration of Moodle O365 integration nor with the Teams integration so we're unsure as to how we can resolve this...

![image001](https://user-images.githubusercontent.com/13693553/66050549-54287900-e525-11e9-83cb-1c52f7f52ed1.jpg)

![image002](https://user-images.githubusercontent.com/13693553/66050548-538fe280-e525-11e9-9751-48c36edc2cf2.jpg)

![image003](https://user-images.githubusercontent.com/13693553/66050547-538fe280-e525-11e9-9678-a3219b24c04a.jpg)

**Comment by kkiiskin** [comment]
We have this problem also. 

Should Teams URL be added as Redirect URI ( Azure > App registrations > Authentication) so that authentication is allowed? If so, what would be the URL?

**Comment by kkiiskin** [comment]
This seemd to work, I added a new Redirect URI to authetication page:
Type: Web
Redirect URI: {moodleurl}/local/o365/sso_end.php

Although I did have the Moodle course already added to the Team beforehand.

**Comment by majidh8** [comment]
We tried the same thing and it worked! Thanks for the suggestion. Just a shame it wasn't mentioned in the documentation we followed.

**Comment by jamesmcq** [comment]
@weilai-irl Thoughts on this one?

**Comment by weilai-irl** [comment]
I'll review instruction document

**Comment by weilai-irl** [comment]
Documentation is updated to include the settings.
https://docs.moodle.org/38/en/Office365
