### ISSUE TITLE
Moodle O365 - Provide admin consent error

### ISSUE THREAD

**Issue by majidh8** [microsoft/o365-moodle#1158]
When clicking "provide admin consent", the following error is shown after signing into O365 and redirecting back into Moodle:

There was a problem logging you in. Please contact your administrator for assistance.

See screenshot below:

![Screenshot 2019-10-04 at 12 02 24](https://user-images.githubusercontent.com/13693553/66203290-e48ac900-e69f-11e9-9cf9-6201698bdf84.png)

Plugin versions:
auth_oidc 2018120301
local_o365 2018120301

**Comment by Devrons** [comment]
I am having the same issue.

**Comment by jamesmcq** [comment]
@majidh8 @Devrons This is saying the Office 365 API sent us back some kind of error. We don't include the message on this page for security reasons but it is logged to the debug logs. If you enable the "Record Debug Messages" setting in both OpenID connect and the o365 local plugin, then reproduce the error, the error message coming from Office 365 should be available in the Moodle logs (follow the link in the "Record Debug Messages" setting to jump right there).

**Comment by majidh8** [comment]
@jamesmcq See below error from Apache error log:

`[Fri Nov 08 11:39:43.358563 2019] [php7:notice] [pid 28618] [client 212.219.2.4:54522] Default exception handler: There was a problem logging you in. Please contact your administrator for assistance. Debug: \nError code: errorauthgeneral\n* line 175 of /auth/oidc/classes/loginflow/authcode.php: moodle_exception thrown\n* line 107 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\\loginflow\\authcode->handleauthresponse()\n* line 105 of /auth/oidc/auth.php: call to auth_oidc\\loginflow\\authcode->handleredirect()\n* line 29 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()\n, referer: https://login.microsoftonline.com/`

Attached is the error from Moodle which includes the stack trace.

![image001](https://user-images.githubusercontent.com/13693553/68474630-d93a3880-021d-11ea-9977-e077bbe71c1b.png)

**Comment by jamesmcq** [comment]
@majidh8 Sorry to clarify - the information I'm looking for is not in the Moodle apache logs but in the internal Moodle error logs. Click the link from the setting description in the local plugin to be taken to Moodle's log viewer and look for an error log entry for the local_o365 plugin.

**Comment by majidh8** [comment]
Hi @jamesmcq - I've attached the error from the Moodle logs here.

![Screenshot 2019-11-08 at 15 23 17](https://user-images.githubusercontent.com/13693553/68487864-cb93ab80-023b-11ea-819b-d84e52d0e409.png)

**Comment by jamesmcq** [comment]
@majidh8 Great - that looks like the issue. So I'd follow along with what the error message is saying. 

- Double check the permissions are correctly set up: https://github.com/microsoft/o365-moodle/blob/master/Office365Documentation.md#register-your-moodle-instance-as-an-application-in-azure-active-directory
- Perform the consent process again (Setup tab of the local plugin)
- Double check the application ID (Setup tab of the local plugin)

**Comment by majidh8** [comment]
Thanks @jamesmcq - We will try the instructions again and report back here.

**Comment by rovebd** [comment]
Hi @jamesmcq.

I have the same error as @majidh8.

I doublechecked the permissions, application id (clientid) and secret (clientsecret). Moodle is a clean vanilla 3.5.9 (20191111 build) installation. Any idea?

![imagen](https://user-images.githubusercontent.com/53214907/69241231-a50c3380-0b9e-11ea-9bbe-299e6ca7f6fd.png)
![imagen](https://user-images.githubusercontent.com/53214907/69241336-e13f9400-0b9e-11ea-97b3-ee17fe3ecb11.png)
![imagen](https://user-images.githubusercontent.com/53214907/69241474-2a8fe380-0b9f-11ea-8d6c-fd6d43e21924.png)
![imagen](https://user-images.githubusercontent.com/53214907/69241548-56ab6480-0b9f-11ea-9327-29d4216e679e.png)

Thanks in advance,
Roberto.

**Comment by mmulrthelp** [comment]
@rovebd the fix to your issue is here on my blog : why it is not pushing this permission automatically, I'm unsure : https://notsomany.com/2019/10/15/moodle-office-365-azure-api-permissions/

**Comment by rovebd** [comment]
Thanks to @mmulrthelp I discovered that I need to give one more permission: user.read under Azure Active Directory Graph

![imagen](https://user-images.githubusercontent.com/53214907/69430685-732dd500-0d36-11ea-81ce-602ea0f5d06e.png)
