### ISSUE TITLE
Documentation should list Microsoft Graph (Unified API) permissions

### ISSUE THREAD

**Issue by zckb** [Microsoft/o365-moodle#116]
Please list in documentation all permissions to be configured for Microsoft Graph in Azure Management Portal > Azure AD > App registration for Moodle > Permissions to other applications > Microsoft Graph

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/126

This PR also contains some other doc updates besides the above fix.

**Comment by number33** [comment]
Closing this issue as the PR is was added to 20160532.
