### ISSUE TITLE
auth_oidc - Azure AD B2C - It is necessary to allow NULL on column token of table mdl_auth_oidc_token

### ISSUE THREAD

**Issue by massicos** [microsoft/o365-moodle#1161]
I got Moodle 3.6.4 on MySQL 5.7 and I install auth_oidc plugin to try to make it work with Azure AD B2C. At first, it was not working because I got this error in the logs :

```
[Tue Oct 15 10:59:10 2019] [notice] [client 10.136.34.6] Default exception handler: Erreur d'\xc3\xa9criture vers la base de donn\xc3\xa9es Debug: Unknown error 1048\nINSERT INTO mdl_auth_oidc_token (oidcuniqid,username,userid,oidcusername,scope,resource,authcode,token,expiry,refreshtoken,idtoken) VALUES(?,?,?,?,?,?,?,?,?,?,?)\n[array (\n  0 => '12345678-1234-1234-1234-123456789123',\n  1 => '8e08616e-c099-42bc-8aa1-76c2d25bf149',\n  2 => 0,\n  3 => '12345678-1234-1234-1234-123456789123',\n  4 => 'openid profile email',\n  5 => 'https://graph.windows.net',\n  6 => 'eyifQ..BF3SGPKQcM-4ldTK.7emz2L.Js4',\n  7 => NULL,\n  8 => 1571237950,\n  9 => '',\n  10 => 'eyJ0e.eyJleHNGg',\n)]\nError code: dmlwriteexception\n* line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown\n* line 1329 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()\n* line 1375 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()\n* line 470 of /auth/oidc/classes/loginflow/base.php: call to mysqli_native_moodle_database->insert_record()\n* line 459 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\\loginflow\\base->createtoken()\n* line 269 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\\loginflow\\authcode->handlelogin()\n* line 107 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\\loginflow\\authcode->handleauthresponse()\n* line 105 of /auth/oidc/auth.php: call to auth_oidc\\loginflow\\authcode->handleredirect()\n* line 29 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()\n, referer: https://OURURL.b2clogin.com/
```
So based on this error (Unknown error 1048), I change the column to allow NULL (with an ALTER TABLE) and it's work.

I don't think it's normal that I need to change this column. Also, I really don't know the impact of this change.

**Comment by jamesmcq** [comment]
@massicos That's very strange that there would be a NULL for "token" - the token is what we'd need to communicate with Office 365. That said, we unfortunately don't have official support for B2C, so there may be API differences that I'm not aware of. I'm going to leave this issue open for now as an enhancement request in case B2C gets on our roadmap. Thanks for the report!

**Comment by marbmp** [comment]
@jamesmcq were you able to find a solution for it? I am having the same issue here. Thank you

**Comment by WhippsP** [comment]
This issue relates the lack of Ability to set a scope. To enable B2C you must set the clientId as one of the scopes. I have created a PR to enable this lets see if it gets approved ;) - https://github.com/microsoft/o365-moodle/pull/1239

**Comment by ayuem** [comment]
> 
> 
> This issue relates the lack of Ability to set a scope. To enable B2C you must set the clientId as one of the scopes. I have created a PR to enable this lets see if it gets approved ;) - #1239

Do you have an example of what you mean by set clientid as one of the scopes? I am trying to configure this plugin with azure b2c connect and facing this issue too.

**Comment by weilai-irl** [comment]
Hi all,

The PR made by @WhippsP was merged and included in release over a year ago. We have some clients who have managed to integration SSO successfully between Moodle and Azure B2C since. I think this can be closed.

Please create new issues if you are still having difficulties with the integration.

Regards,
Lai

**Comment by matthewhilton** [comment]
@ayuem I realise this is 6 yrs too late, but I just ran into the same issue and to clarify, the `access_token` (what goes into the `token` field in the db) is only sent by B2C if you include the app id in the scope, i.e. scope is set to something like

`openid profile email 5aae6f6b-ba42-41b7-8df9-0742bb22e8c4`

My understanding is that the id_token is used for the user profile (i.e. openid, profile, email will be incorporated into them), but the access_token is used for resources, and in this case the resource is the app, so the app id (aka client id) will cause it to generate an access token
