### ISSUE TITLE
Add setting to redirect to openid connect straight away without loading moodle login page

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1162]
Right now, users have to load the moodle login/index.php page, and then click the button for the OpenID connect idp they want to use. 

This feature would add a config setting 'forceredirect', disabled by default. If enabled, it would redirect the user on loading any moodle page straight to the idp where they can log in. 

Adding a param in the url, either oidc=0 or noredirect=0, still allows the main login screen to show. 

This way redirection can be handled in the plugin and disabled with a url param, rather than having to use the moodle setting alternateloginurl .

**Comment by skuti-is** [comment]
Workaround for Apache webserver:
RewriteEngine on
RewriteRule /login/index.php https://moodle.example.com/auth/oidc/ [R=302,L]

**Comment by jamesmcq** [comment]
Hi @kristian-94 - we can only accept pull requests made to this repository - can you resubmit here and I'll take a look. Looks like a good new feature. Thanks!

**Comment by intelliant01** [comment]
> Adding a param in the url, either oidc=0 or noredirect=0, still allows the main login screen to show.

should be 

Adding a param in the url, either oidc=0 or **noredirect=1**, still allows the main login screen to show.

Hope this helps someone as it did to me.
