### ISSUE TITLE
README.me is outdated

### ISSUE THREAD

**Issue by luisdev** [microsoft/o365-moodle#1163]
The https://github.com/microsoft/o365-moodle/blob/master/README.md file is outdated . The "Supported Moodle versions" section says: "The plugins currently support Moodle 3.1 through 3.5." 

The latest version of Moodle is currently v3.7.2 so if the o365-moodle plugin does support this new Moodle version then the README.me file needs to be updated.

**Comment by jamesmcq** [comment]
Thanks @luisdev - this will be updated for the next release.
