### ISSUE TITLE
User photo not syncing on cron

### ISSUE THREAD

**Issue by cbrherms** [microsoft/o365-moodle#1166]
Recently noticed a couple of users in Moodle without photos, after checking on 365 they have had them uploaded already but doesn't appear to sync.
Photo refresh is currently set to 6 hours, and on cron.
Running the sync cron job, there doesn't appear to be any mention of photos being matched any more. 
Not 100% sure if the current set of users that were synced were on the previous release of the 365 plugins though.

How should i proceed with investigating / providing more info?

**Comment by bradnielsen2981** [comment]
I dont know if this is your issue, but I found out that the microsoft graph api requires photos to be squares. Any photo uploaded in office 365 without square dimensions doesn't come through into Moodle and a lot of other apps.

Regards
Brad

Sent from Outlook
________________________________

**Comment by cbrherms** [comment]
Hi Brad.
Might have been the case. 
One that was not wanting to pull in to moodle was reuploaded yesterday using the codetwo photo sync tool (that crops and adjusts photos before uploading).
Not 100% sure what the original dimensions as not in the office now until next week but the new ones are 240x240. So, can't tell just yet whether it was just the reupload of the photo that triggered it being pulled in, or a potential change in dimensions.

**Comment by anormore** [comment]
OH MY GOODNESS -- Yes! I can confirm this is the problem. I have dug and dug and dug through the code -- I even enabled legacy mode, the only thing that has worked for us.

I got down into the Moodle code, where it calls functions to get the size -- this is where it fails.

Some worked, some did not. THE SQUARE ONES! THEY WORKED!

I'll look at submitting a patch in the next little while to square the darn images on disk -- please leave this open until it's resolved.

**Comment by jamesmcq** [comment]
@anormore Glad there's a solution! Would love to have this patch, please do submit! :)

**Comment by anormore** [comment]
You bet buddy, I will for sure get it in. We've got a list of priorities at our organization, but at least this thread can be found and worked-around for SURE.

**Comment by gunnar-restorff** [comment]
Is there any update wrt. this. A lot of our Office 365 users have currently profile photos that are not square - and they seem not to sync to moodle.

**Comment by cbrherms** [comment]
@anormore  Did you ever get around to looking in to this? 
Or, do you have any further insight as to errors you saw with the function to allow others to look in to it?

**Comment by weilai-irl** [comment]
Hi all,

I think the requirement up to the last discussion one year ago was the ability to sync non-square profile photos. I have made a few attempts to set non-square profile photos for users in Microsoft 365, but I had no luck so far. All photos uploaded are automatically adjusted to square images on upload. It looks like Microsoft has "fixed" this on their court.

Could you confirm this please. If this is to the case, the issue can be closed.

Regards,
Lai

**Comment by weilai-irl** [comment]
Issue closed due to inactivity.
