### ISSUE TITLE
Error code: errorauthgeneral

### ISSUE THREAD

**Issue by MikasSQUALIO** [microsoft/o365-moodle#1167]
I am facing an issue when trying to provide admin consent. All permissions in Azure are configured correctly. Error: There was a problem logging you in. Please contact your administrator for assistance it links me to this webpage https://docs.moodle.org/37/en/error/auth_oidc/errorauthgeneral .

**Comment by mmulrthelp** [comment]
@MikasSQUALIO have you tried this, it's [a blog post that I wrote about it](https://notsomany.com/2019/10/15/moodle-office-365-azure-api-permissions/)

**Comment by MikasSQUALIO** [comment]
Hello,
yes I tried all possible fixes I found . I checked that table and there are n
![2019-10-29 10_10_02-squalio@moodledb_~](https://user-images.githubusercontent.com/57108760/67748836-78984800-fa34-11e9-843b-57a1f97a4120.jpg)
o rows with value 0.

**Comment by MikasSQUALIO** [comment]
Do you have anymore ideas?

**Comment by MikasSQUALIO** [comment]
I checked moodle logs and I see this message.
authcode::handleauthresponse: Authorization error. Data: Array ( [state] => 8wb7iajpe32NxUf [code] => [error_description] => AADSTS650056: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant. Client app ID:

**Comment by MikasSQUALIO** [comment]
![2019-10-29 10_44_17-Moodle - API permissions - Microsoft Azure](https://user-images.githubusercontent.com/57108760/67751104-2c033b80-fa39-11e9-8508-216f9f93a885.jpg)

**Comment by mmulrthelp** [comment]
@MikasSQUALIO check out my blog post again, it's because you need to manually add the Graph API access, for some reason this step is not happening automatically

It then appears above the Microsoft Graph (17) section...

![image](https://user-images.githubusercontent.com/16646247/67761360-0d9e3f80-fa3b-11e9-85c7-4552f8861bc2.png)

**Comment by kkiiskin** [comment]
Hi

did you grant the consent from Moodle or from Azure AD?

I recently got it done only from Azure (API permissions page) AND while already logged-in in Moodle as admin in the same browser.

**Comment by MikasSQUALIO** [comment]
@kkiiskin hello I tried to grant admin consent from Moodle. Clicked on that option "Step 3 grant admin consent" it redirected me to o365 log in page and then I entered global admin credentials, then it linked me to moodle page saying that there is an error.

**Comment by MikasSQUALIO** [comment]
@mmulrthelp can you share a way how to add it manually?

**Comment by MikasSQUALIO** [comment]
@kkiiskin Do you see Azure Active Directory graph (1) above Microsoft graph?

**Comment by mmulrthelp** [comment]
@MikasSQUALIO in Azure portal, find your App Registration for Moodle then the API permissions & Add a permission for Azure Active Directory Graph.. it 'should' be very simple. I'll try and add detailed instructions later if you still cannot find out how to do it

**Comment by MikasSQUALIO** [comment]
I've already done it. Thank you. Problem solved
