### ISSUE TITLE
Update default URL for Get Office link in Microsoft Block

### ISSUE THREAD

**Issue by zckb** [Microsoft/o365-moodle#117]
Update default URL for Get Office link in Microsoft Block to https://portal.office.com/OLS/MySoftware.aspx

**Comment by jamesmcq** [comment]
Fix for this included with the customizable URL change in branches wip-MSFTMPP-470-m27, wip-MSFTMPP-470-m28, wip-MSFTMPP-470-m29, wip-MSFTMPP-470-m30
