### ISSUE TITLE
Team Sync - Customise -> Enabled and then Disabled - Disabled doesn't turn off syncing

### ISSUE THREAD

**Issue by bradnielsen2981** [microsoft/o365-moodle#1170]
I'm not sure whether this bug has been fixed or not, but I haven't found any reference to it. In Team Sync -> Customise, when a Course Group is Enabled and then Disabled, the Course Group Syncing is still turned on, and any changes to the Course Enrolment are still reflected is the Office 365 Group. It seems like the Disabled doesn't work once Enabled. 

I am however installing the latest updates to the O365 plugin over Christmas, so perhaps this problem has been fixed.

regards,
Brad

**Comment by bradnielsen2981** [comment]
I haven't heard anything about this bug. Has it been fixed or is it only affecting my installation?

**Comment by weilai-irl** [comment]
Hi @bradnielsen2981,

I have ran some tests on my local 3.9 and 3.10 test sites, and I can confirm that users changes are not pushed to Teams from Moodle courses when sync is turned off.

I'll close the issue now.

Regards,
Lai
