### ISSUE TITLE
Usersync - no matching with sub UPN domains

### ISSUE THREAD

**Issue by dhu-github** [microsoft/o365-moodle#1172]
Our environment is a single O365 tenant and we intend to match existing Moodle users only.

While running the moodle schedule tasks - Sync users with azure ad (\local_o365\task\usersync) we have discovered that if the UPN is a sub domain of the O365 tenant no matches occur for;

- numeric moodle usernames
- alphanumeric moodle usernames

However - alpha only usernames will match. Examples below;

- 012345@yourdomain.com [Match]
- officetest@sub.yourdomain.com [Match]

- 012345@sub.yourdomain.com [No Match]
- o365test@sub.yourdomain.com [No Match]

We have 2000+ sub domain users that change every year, so CSV and Manual matching is not a workable solution.

Can anyone replicate this issue?

PHP 7.0.7
PGSQL 9.3.18
Moodle 3.5.1 (Build 20180709)
O365 Plugin 3.5.0.6 (Build 2018051710)

**Comment by weilai-irl** [comment]
Hi @dhu-github,

I think it has been a long time since this issue was reported.

In case you are still interested in a solution - could you clarify what is the user restriction or user creation restriction used please.

Regards,
Lai
