### ISSUE TITLE
Update documentation at https://docs.moodle.org/36/en/Office365

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1176]
There are a number of things that need to be updated, and the MS Graph API permissions are completely different to I am stuck. 

In "Plugins & Features", you mention 5 core plugin although there are only 4. 

In "Register Application in Azure", the procedure has changes very slightly in Azure. There is no "Application Type" reference, just a "Redirect URI (optional)" heading, and the drop down now only shows "web"

In "Configure application" step 5, there is no "Settings" options anymore, I guess this is now "Manage" section? This confused me being a none Azure person. Then in step 6, I believe you then need to go to the "Certificates & secrets" section, then click "New client secret". then "Add". Lastly in step 7, there is no "Required Permission" anymore under "API Access", so I guess this is now "Add permission" under "API permissions"?

However, now I am stuck..... The list for the Delegated and Application permission on MS Graph is completely different to that which I can see, so I have no idea what to choose :(

**Comment by swinster** [comment]
Right, the english permission are not filterable, so I the permissions are something like:

Delegated:
---

1. Read and write all OneNote notebooks that user can access -> `Notes.Read.All`
2. Sign in and read user profile -> `User.Read`
3. Read and write all users' full profiles -> `User.ReadWrite.All`
4. Read and write all groups -> `Group.ReadWrite.All` 
5. Read and write directory data -> `Directory.ReadWrite.All`
6. Access directory as the signed in user -> `Directory.AccessAsUser.All`
7. Have full access to user calendars -> `Calendars.ReadWrite`
8. Have full access to user files -> `Files.ReadWrite`
9. Read items in all site collections -> `Sites.Read.All`
10. Sign users in -> `openid`

Application:
---

1. Read and write domains -> `Domain.ReadWrite.All`
2. Read and write all users' full profiles -> `User.ReadWrite.All`
3. Read and write all OneNote notebooks -> `Notes.ReadWrite.All`
4. Read and write all groups -> `Group.ReadWrite.All`
5. Read directory data -> `Directory.Read.All`
6. Read and write calendars in all mailboxes -> `Calendars.ReadWrite`
7. Read and write files in all site collections -> `Files.ReadWrite.All`


I then assume you need to "grant admin consent for xxxxxx domain

![image](https://user-images.githubusercontent.com/8142964/70557590-03fc1180-1b7b-11ea-8f85-6aded8be15da.png)

**Comment by swinster** [comment]
Actually, this didn't work as I had authentication issues, so I ran the PS script downloaded via the Moodle plugin (although the link the the documentation for this is broken  - https://aka.ms/MoodleTeamsPowerShellReadMe). This show a slightly different set of permissions:

![image](https://user-images.githubusercontent.com/8142964/70562337-2181a900-1b84-11ea-9ef9-2d6c9a8ffa76.png)

**Comment by weilai-irl** [comment]
Hi @swinster,

I know it has been a long while since this was last updated. Just to give an update - we have made additional changes to the permissions required throughout the releases made last year. The latest set of permissions required are on the up-to-date document at https://docs.moodle.org/310/en/Office365#Configure_application.

The PS script hasn't been kept up to date though, it still contains a very old set of permissions. We are working closely with Microsoft on a new version of the PS file, but we don't have an ETA for it yet. It will be updated in the plugin as soon as it's available.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @swinster,

We performed a complete review of the Graph APIs used by the Microsoft Moodle plugins, and cleaned them up a bit. We then worked with the Education team in Microsoft and created a long waited update version of the PowerShell script used to create the Azure app. The PowerShell script is included in the latest release of the plugins.

We will be updating the documentation in the coming days about the Azure app permissions. I'll add a new note when it's in place.

Regards,
Lai

**Comment by nenorojas** [comment]
Hi @swinster, 

While we do not update the Microsoft Moodle 365, this is the link for the most compreensive work regarding permissions for the plugins. https://docs.google.com/spreadsheets/d/1XIFnnQ8RuFjlPGB8CiiMmK8x9Uta9XIR_icvAdx0G6k/edit#gid=0

Regards
