### ISSUE TITLE
Changing user sync options breaks delta sync

### ISSUE THREAD

**Issue by gormster** [microsoft/o365-moodle#1180]
Changing the user sync options to enable user creation in Moodle after the sync task has run at least once causes users who were ignored in the first sync task to continue to be ignored even if they should have accounts created. This is because delta sync will only fetch changes since the last sync task, meaning that the usersync task simply never sees those users.

## Steps to reproduce
1. Create a fresh instance of Moodle.
2. Enable OpenID Connect through Office 365.
3. In the Admin settings, under Microsoft Office 365 Integration > Sync Settings, enable "Update all accounts in Moodle for users in Azure AD" _only_. Do not enable "Create accounts in Moodle for users in Azure AD" or "Perform a full sync each run".
4. Log in as a user from your connected Office 365 tenant. (Ignoring #1123; maybe log out and back in to work around that.)
5. Change something on that user's profile in Office 365.
6. Wait for the sync task to run. (You might want to increase the frequency with which the task runs to every five minutes or so; you can do this by following the link to the Scheduled Tasks management page on the admin page mentioned in step 3.)
7.  In the Admin settings, under Microsoft Office 365 Integration > Sync Settings, enable "Create accounts in Moodle for users in Azure AD". Do not enable "Perform a full sync each run".
8. Wait for the sync task to run.

## Expected results
The users from O365 should be created in Moodle.

## Actual results
The users from O365 are not created in Moodle.

## Likely cause
The first time we run the task, we ask for a delta token, to make sure we only get changes to user records since the last time we asked. However, this token is only updated when running the task again. This means that the users we passed over the first time (as we were not creating user records for them) aren't present in the delta update, even though we now want to do something different with them.

## Proposed solutions
I think the simplest solution is to clear the delta token and skip token any time we make a change to the sync options. This can be achieved with a custom `post_write_settings` method for the `local_o365/aadsync` admin setting object.

However, that does mean resetting any progress that's been made, which may potentially be unnecessary. It also means we're fetching potentially a _lot_ of data that we don't need to. A different solution would be to store _all_ retrieved user objects in the `local_o365_objects` table, regardless of whether or not we currently think they represent users in Moodle. This solution would mean a much larger database table, essentially being a cache of all the user objects in AAD, but it would also mean 

a) looser coupling; the Moodle user table is only ever updated from the o365_objects table
b) clearer separation of concerns; the user sync task becomes two tasks, fetch and update. The former fetches user objects from O365, the latter updates the user tables in Moodle from the records retrieved by the former in accordance with the current set of sync options and filters.

However, this might be an overcorrection; I'm not sure what Microsoft's priorities would be in this regard. Are we more concerned with overtaxing AAD, or soaking up drive space?

**Comment by weilai-irl** [comment]
@gormster , to keep things simple, I would suggest we introduce a button which is available to site admins from the plugin settings page so that they manual press to clear the delta token. It gives the flexibility to the site admins without affecting the current workflow too much.

**Comment by weilai-irl** [comment]
Hi @gormster,

The work has been included in the latest release (v3.7.0.7, v3.8.0.3 and v3.9.0) which was made available today. A new button "Cleanup User Sync Delta Tokens" has been added to the "Maintenance Tools" section in the "Advanced" tab in the local_o365 plugin configuration page, clicking of which clears the delta token.

I'm closing this issue.

Regards,
Lai
