### ISSUE TITLE
Error from Cron Tab for duplicate mailNickname

### ISSUE THREAD

**Issue by dsiroumi** [microsoft/o365-moodle#1181]
Hi,

We have Moodle 3.5.9 with local_office365 plugin installed.

We are seeing the following errors in cron.

`An error/warning message was detected
> Message: Could not create group for course 0000062. Reason: Error in API call: Another object with the same value for property mailNickname already exists.
An error/warning message was detected
> Message: Could not create group for course 0000065. Reason: Error in API call: Another object with the same value for property mailNickname already exists.`

Any solution for this yet?
 
We can see that “mailNickname” seems to be Moodle course fullname or shortname.
In office365, it looks like the mailNickname of a group needs to be unique in a tenant, i.e. a tenant cannot have two groups both with name “test”. So when Moodle tries to create group by calling the API function, and when finding a group with the duplicate mailNickname, this is the error returned. The group cannot be created for genuine reasons but it seems that may be local_o365 doesn’t have a logic to handle situation like this. 

Regards,
Siroumi

**Comment by weilai-irl** [comment]
@dsiroumi, Thank you for reporting this.
The issue has been resolved in release 3.7.0.4 of the plugin.

https://github.com/microsoft/o365-moodle/releases/tag/v20200128_m37
