### ISSUE TITLE
Reason: Error in API call: Invalid value specified for property 'description' of resource 'Group'.

### ISSUE THREAD

**Issue by dsiroumi** [microsoft/o365-moodle#1183]
Hi,

We have Moodle 3.5.9 and we are seeing the following errors in cron.

It seems to be happening when description(Course Summary) has special characters/paragraphs etc. 

Error is: 
`Message: Could not create group for course 0000067. Reason: Error in API call: Invalid value specified for property 'description' of resource 'Group'.
> * An error/warning message was detected`

Regards,
Siroumi

**Comment by weilai-irl** [comment]
@dsiroumi, thank you for reporting the issue.
The issue has been resolved in release 3.7.0.4 of local_o365 plugin.

https://github.com/microsoft/o365-moodle/releases/tag/v20200128_m37
