### ISSUE TITLE
How to add the UserName (SPN/UPN) to the field mapping?

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1184]
Annoyingly, we are unable to populate the email field in Azure AD fully for all users. However, the UserName SPN (or UPN) is essentially the correct data. While this field is available of "User Creation Restriction" option of the the Sync, it is not available in the "User Field Mapping" section. Is it possible to add this filed to to the field mappings??

**Comment by swinster** [comment]
This is raising in interesting issue. Some users are be created with no email, yet this is a required field for user creation in Moodle, so seems like a bug. 

Then, even though the `email` field is blank in Moodle, the `username` and `ID number` of the user in Moodle are correctly poultated. I tried mapping the `Object ID` and `Employee ID`  in Azure AD to a random field in Moodle, but these came through blank

**Comment by bbusschots-mu** [comment]
I would find this mapping option very useful too.

**Comment by swinster** [comment]
This is getting to be quite a problem for us!

We are seeing continued errors with the user synchronisation, both in Moodle and our new MWP instance. This is causing a LOT of issues as users are being provisioned with the wrong email address (`domain.onmicrosoft.com`) or simply have no email address at all, This leads to failures in course allocation welcome messages and reminders, re-certification, on boarding… etc, etc. Yet, their user names (UPN) are correct.

Not all users in our AAD are provisioned with MS O365 email accounts, but IT have suggested that the relevant Email fields in the users AAD profile is set correctly (i.e. overridden to show their actual email address). 

I manually overrode the created Moodle users email address by exporting the affected users, manipulating the email in the csv, then re-importing and updating the Moodle users profiles. Whilst this initially works, If you perform a manual re-sync, the users whose email address were set to the `domain.onmicrosoft.com`, those users Moodle accounts are then reset to this address. 

However, it did appear that after updating the Moodle users whose email addresses were initially blank, then those changes stuck after a full resync. Unfortunately, I fear that this is just a temporary plaster and we will again see such issues in the future. 

What can be done here?

**Comment by Aldises** [comment]
We're facing the same issue with our installation. 
We're using the openid Connect on our Moodle installation : https://github.com/microsoft/moodle-auth_oidc 
But most of our user doesn't have an email or the right email address in the email field of the Token. 
We'd love to be able to create the moodle account based on the UPN as email value.

Do you think this  can be done ? 

All the best

**Comment by weilai-irl** [comment]
Hi @swinster and @Aldises ,

We have introduced the support for mapping upn field in the 3.8.0.5 and 3.9.2 release of the plugins. Please check it out.

Regards,
Lai

**Comment by swinster** [comment]
👍
