### ISSUE TITLE
Stop the creation of users in Moodle that are disabled/suspended in O365

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1185]
We have a lot of OnPrem user object accounts (required for various OnPrem integrations) that are suspended in O365, yet these still synchronise into Moodle. Whilst they will not be able to log on, it make a mess of the user accounts in Moodle. I manually bulk suspended them on import, but this is not ideal at all as there will be more.

**Comment by nenorojas** [comment]
Hi @swinster , 

Can you check if the latest version of the plugin sorts the issue you are having https://github.com/microsoft/o365-moodle/issues/272#issuecomment-629294564 ?

Regards

**Comment by weilai-irl** [comment]
Hi @swinster,

The latest release of the plugins for Moodle 3.9 and 3.10 introduced a new option to sync disabled status of AzureAD users. If the option is enabled, a disabled AzureAD account will be synced to Moodle, but will be suspended.

Please give it a try and confirm if this fits your need.

Regards,
Lai

**Comment by swinster** [comment]
Thanks, @weilai-irl. This should do the trick

**Comment by weilai-irl** [comment]
Hi @swinster,

Thank you for your confirmation. I'll close this issue in that case.

Regards,
Lai
