### ISSUE TITLE
Match or change AzureAD B2B users to existing user accounts in moodle

### ISSUE THREAD

**Issue by webframp** [microsoft/o365-moodle#1189]
Hi There,

In one instance using OIDC with AzureAD we have Moodle users who currently use Azure AD accounts in our tenant that will be migrated to use B2B guest user accounts and they would like to preserve course history and progress they have achieved with their current accounts.

Right now, when logging in using the new enrolled B2B account a new moodle user is created for them. What adjustments, in database or otherwise, are needed to link the new moodle user to the previous user account in moodle?

I'm looking for any suggestions on this one, even sql db updates are fine if that's what it takes.

Thanks!

**Comment by nenorojas** [comment]
Hi, 
When using OIDC authentication, by default the username in Moodle will be the email address.

**Comment by webframp** [comment]
Thanks @nenorojas I have noticed that. 

I’m wondering if there’s any option, even if it requires manual updates in the database, for a migration scenario for the auth provider of existing user accounts. 

For example: user@providerA.org exists,  has moodle history and has an identity in AzureAD for providerA. 

Now I want to migrate user@providerA.org to a new username: user@providerB.org and their identity is as an external B2B user from providerB in AzureAD providerA. 

It might sound a little confusing, but basically it’s migrating a username and identity provider for an existing moodle user. 

The azure b2b use comes into the picture just to allow me to use a single tenant with the oidc plugin, which only supports one tenant config. 

I appreciate you taking a look at the issue.

**Comment by nenorojas** [comment]
Let me see if I got this:

1) user@provideA.org exists in the AD of the office tenant A (Host tenant A), let's imagine that username=user@provideA.org and auth=oidc. 
2) You want to migrate this user to a new username user@providerB.org, that is created in external AD (Host tenant B). 

I assume that the user will only log-in to Moodle from now onwards with the new username, is that correct? 
When you said oidc plugin just allow one tenant, have you tried to add another tenant using mutiltenancy feature of the office 365 local plugin? /local/o365/acp.php?mode=tenants?

**Comment by webframp** [comment]
I wasn't aware of this multitenancy setting actually, let me make sure we're on the latest plugin release and then I'll check that setting and report back.

**Comment by adamjbradley** [comment]
Made an attempt at doing something like this for moodle-auth_oidc which you can find here https://github.com/microsoft/moodle-auth_oidc/compare/master...adamjbradley:master 

It's NOT ready (there's a lot of questions I need to ask!). Allows you to switch on "Multi-Tenant" mode and use the value of a nominated attribute which identifies the User uniquely across tenants, I'm coining it "LearnerId". Thoughts?

**Comment by webframp** [comment]
I'm just now seeing this @adamjbradley, sorry for the delay!

I'd love to discuss and debug multi-tenant mode more. We have an azuread tenant with users invited via B2B users from the second tenant show up in the primary tenant as: `user_tenant.org#ext#@primarytenant.onmicrosoft.com`

Let me know how I can help with this. We've been struggling with an issue for months where these users are not able to login to our moodle platform.
