### ISSUE TITLE
onenote submissions / pdf and other files

### ISSUE THREAD

**Issue by BenKelada** [Microsoft/o365-moodle#119]
When using onenote submission and feedback plugins
And the onenote page contains a pdf or other files
what is the expected behaviour of submissions?

currently when a teacher views a onenote submission, and tries to open/download the embedded pdf, it downloads a 0byte file. also when submitting the zip file, no other attachments other than images are included in the file.

cheers,
Ben

p.s. to clarify above, when a teacher clicks view onenote submission, and views the students onenote in the online onenote app, the teacher cannot download the uploaded pdf it is 0 bytes. The student can still download the pdf.

**Comment by jamesmcq** [comment]
Hi @BenKelada are you still experiencing this? If so please reopen/create a new issue. Thanks.
