### ISSUE TITLE
Open Moodle tabs from mobile apps fail with error message "Direct access to the page is prohibited"

### ISSUE THREAD

**Issue by weilai-irl** [microsoft/o365-moodle#1193]
This is due to a JS check to ensure Moodle tabs pages are only accessed from Teams, either from web app, desktop app, or mobile app. Recent update on the mobile app broke this check.

A solution is on the way.

**Comment by kkiiskin** [comment]
Hi

so the fix on this is coming to the mobile apps, NOT to Moodle plugins?
I encountered this on both iPad and Android mobile apps.

**Comment by weilai-irl** [comment]
@kkiiskin Fix to the issue will be made as part of the Moodle plugin, as the check is only done within the plugin.

**Comment by kkiiskin** [comment]
Hi @weilai-irl
do you have an estimate when the fix will be available?

**Comment by weilai-irl** [comment]
Hi @kkiiskin, it's likely to be fixed in April.

**Comment by kkiiskin** [comment]
Hi 

thanks for the quick reply! Is there a patch or commit that we could use at the moment?
The error is slightly annoying to users.

**Comment by weilai-irl** [comment]
Hi @kkiiskin, I understand it's annoying for users and it can affect a large number of users.

The fix will be in the form a new release of the plugins. We are still working on this release, which will include fixes of a number of other issues. There is a release procedure that we need to follow to ensure it doesn't break other features, and going through the procedure takes time. As I said, I expect the next release to be ready sometime in April.

**Comment by weilai-irl** [comment]
This issue should have been fixed in the latest release - v3.7.0.5 for 3.7, and v3.8.0.1 for 3.8 respectively.
The "direct access" check now allows access from mobile apps, so the error messages are gone.
"Silent" SSO from Moodle tab to AzureAD from mobile Teams apps may not work, which means users may need to to click a button to login. This is due to how sessions are handled in mobile Teams apps.
This doesn't affect desktop apps or accessing from browsers though.
