### ISSUE TITLE
Update outdated link and instructions for app registration in local_o365 plugin confirmation

### ISSUE THREAD

**Issue by weilai-irl** [microsoft/o365-moodle#1198]
In "Teams Settings" tab on the configuration page, the instructions contains an item which reads

"Go to the Microsoft Application Registration Portal and register a new app. Enter the Bot Application ID and Password below:"

of which "Microsoft Application Registration Portal" points to https://aka.ms/MoodleBotRegistration, which in turn redirects to https://apps.dev.microsoft.com/. According to information on the page, this page is deprecated and users are advised to manage app registrations using App registrations section of Azure Portal. Instructions need to be updated accordingly.

**Comment by kentgrav** [comment]
So glad to see this in progress.  I've been trying to configure O365 and Microsoft Teams plugins for my Moodle server for the last several weeks.  I realized the documentation was outdated but attempted to create my app anyways.  There was a lot of guesswork.  According to the moodle plugin, all of the steps have green checkmarks.  I can log in using Microsoft SSO with my domain creds.  User sync even works with my AD.  However, the Microsoft Block on the dashboard still says "You are not connected to any Microsoft services."  Even though I logged in with my domain creds using a Microsoft account.  When I select "Connect to Office 365" my connection status says the same thing.  If I go to Office 365 connection settings, I've tried selecting both options to connect.  Both of them just redirects me to my Dashboard page and nothing happens. 

For the Microsoft Teams settings, I did the best I could at creating the app myself.  It all appears to be configured correctly.  However, when I try to add the app to a tab in Microsoft Teams it says that it could not connect to my Moodle server.  It appears like there is an issue with embedding the frame; however, I ensured that embedded frames were enabled in the security settings just as the instructions said.  It's trying to access the file https://mydomain.com/local/o365/teams_tab_redirect.php but the permission is denied.  Says it cannot directly access that file.  No idea why it won't work.

I'll be looking forward to your updated documentation.  We have classes starting soon and I really need this to be working before then :/

**Comment by weilai-irl** [comment]
Hi @kentgrav,

Thank you for your comments.

The two issues you described are not directly related to this particular issue (the issue is about a link on the plugin configuration page), but I may be able to provide some help.

First of all, we have recently updated documentation about configuring Moodle and Office365 integration at https://docs.moodle.org/37/en/Office365. Please take a look first.

For issue with the block, please check the authentication type of the logged in user to ensure it is auth_oidc. If you have access to the database, you can also check if there is an entry for the user's account in local_o365_objects table, you should be looking for something like:
`SELECT * FROM mdl_local_o365_objects WHERE type="user" AND moodleid = USERID;`
You should see a record for the user, with "objectid" field to be a very long CUID, like "11111111-2222-3333-4444-ffffffffffff". The user account is only properly connected if this record exists.

Regarding the issue with Moodle tabs in Teams, please confirm the environment you access Teams from has proper JavaScript support. The URL provided is a page where people are redirected to when a Moodle check fails to verify that the access request is made from Teams. This check is done in JavaScript, thus JavaScript support is required. Please note that there is a known issue to this check for mobile apps (both Android and iOS Teams app), which we are trying to resolve. Access from all other environments - desktop Teams apps and browser, and mobile browsers - should be working. Please try from a different environment if this is your case.

If you have other questions, feel free to report them as new issues, and our team will try to answer them.

Regards,
Lai

**Comment by weilai-irl** [comment]
The issue is resolved as part of release 3.7.0.4.

https://github.com/microsoft/o365-moodle/releases/tag/v20200128_m37
