### ISSUE TITLE
After unlinking AAD account from moodle, record in local_o365_appassign table related to that AAD account not getting deleted.

### ISSUE THREAD

**Issue by sushantgawali** [Microsoft/o365-moodle#120]
When we link AAD account to moodle and then run cron to sync AAD users, it will also sync photos from that AAD account to moodle if photo sync is on and new record for that account is created in local_o365_appassign table. But when we unlink AAD account, that record related to AAD account is not getting deleted.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/122

**Comment by number33** [comment]
Closing this issue.  Fix has been released.
