### ISSUE TITLE
Incorrect hardcoded graph resource URL prevents plugin from connecting to O365.

### ISSUE THREAD

**Issue by kentgrav** [microsoft/o365-moodle#1200]
First off, I'm using the latest version of Moodle 3.8 (Which I know is supposedly not supported).  My plugins are the latest stable versions I updated just yesterday.  I have everything working now after a couple of tweaks i'll discuss below.

Symptoms:

-  Azure AD sync works great
- User authentication using SSO with my domains credentials works great
- According to the plugin settings, all of the configuration steps have green checkmarks.
- However, upon login, the Microsoft Block on the dashboard states, "**You are not connected to any Microsoft services.**" Even though I logged in with domain creds using a Microsoft account. 

<a data-flickr-embed="true" href="https://www.flickr.com/photos/186568623@N07/49420316742/in/dateposted-public/" title="Screen Shot 2020-01-21 at 11.59.27 AM"><img src="https://live.staticflickr.com/65535/49420316742_e855c0bc1d_n.jpg" width="281" height="222" alt="Screen Shot 2020-01-21 at 11.59.27 AM"></a>

When I select "Connect to Office 365", my connection status says the same thing on the next page. In the Office 365 connection settings, I've tried selecting both options to connect. Both of them just redirects me to my Dashboard page and nothing would happen.

While troubleshooting this issue I ran into this post on the Moodle forums that pointed me in the right direction:

https://moodle.org/mod/forum/discuss.php?d=387218#p1574598

Long story short, he stated that the connection issue was due to the fact that the `auth_oidc | oidcresource` value in the OpenID authentication settings was manually set to `graph.microsoft.com` versus the default value of `graph.windows.net`.  He stated it had something to do with a hardcoded value in the `local/o365/classes/rest/azuread.php` script of `graph.windows.net`.  

I had also manually set my resource value to `graph.microsoft.com`.  This was due to the fact that on Microsoft Azure my application endpoint settings states that the Microsoft Graph API endpoint should be `graph.microsoft.com`-- not graph.windows.net.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/186568623@N07/49420130546/in/dateposted-public/" title="Screen Shot 2020-01-21 at 12.16.41 PM"><img src="https://live.staticflickr.com/65535/49420130546_3517260c7b_n.jpg" width="320" height="24" alt="Screen Shot 2020-01-21 at 12.16.41 PM"></a>

I changed the value in `azuread.php` to `graph.microsoft.com` but it still didn't work.  Then I decided to see where else it was hardcoded.  I found `graph.windows.net` hardcoded in the following files:

```
htdocs/local/o365/tests/sdssync_test.php:            "odata.metadata" => 'https://graph.windows.net/contososd.com/$metadata#directoryObjects/Microsoft.DirectoryServices.AdministrativeUnit/@Element',
htdocs/local/o365/tests/sdssync_test.php:            'odata.metadata' => 'https://graph.windows.net/95b43ae0-0554-4cc5-8c22-fe219dc31156/$metadata#directoryObjects/Microsoft.DirectoryServices.Group',
htdocs/local/o365/tests/azuread_test.php:        $requesturi = 'https://graph.windows.net/users';
htdocs/local/o365/tests/azuread_test.php:        $expecteduri = 'https://graph.windows.net/users?api-version=1.5';
htdocs/local/o365/tests/azuread_test.php:        $requesturi = 'https://graph.windows.net/users?something';
htdocs/local/o365/tests/azuread_test.php:        $expecteduri = 'https://graph.windows.net/users?something&api-version=1.5';
htdocs/local/o365/tests/sharepoint_test.php:            'resource' => 'https://graph.windows.net',
htdocs/local/o365/tests/coursegroups_test.php:                'resource' => 'https://graph.windows.net',
htdocs/local/o365/classes/healthcheck/systemapiuser.php:        $graphresource = 'https://graph.windows.net';
htdocs/local/o365/classes/feature/usergroups/coursegroups.php:        $params['tokresource'] = 'https://graph.windows.net';
htdocs/local/o365/classes/feature/usergroups/coursegroups.php:                    $params['tokresource'] = 'https://graph.windows.net';
htdocs/local/o365/classes/oauth2/token.php:            if ($resource === 'https://graph.windows.net') {
htdocs/local/o365/classes/oauth2/token.php:        $aadgraphtoken = static::instance($userid, 'https://graph.windows.net', $clientdata, $httpclient);
htdocs/local/o365/classes/oauth2/token.php:        if ($resource === 'https://graph.windows.net') {
htdocs/local/o365/classes/rest/sds.php:        return 'https://graph.windows.net';
htdocs/local/o365/classes/rest/azuread.php:        return 'https://graph.windows.net';
htdocs/auth/oidc/settings.php:$configdefault = 'https://graph.windows.net';
htdocs/auth/oidc/tests/privacy_provider_test.php:        $record->resource = "https://graph.windows.net";
htdocs/auth/oidc/classes/oidcclient.php:        $this->resource = (!empty($resource)) ? $resource : 'https://graph.windows.net';
```

I then ran the following command to replace all instances of graph.windows.net with graph.microsoft.com:

```
for i in $(grep -iRl graph.windows.net moodle/htdocs/* 2>/dev/null); do echo $i; sudo sed -i 's/graph.windows.net/graph.microsoft.com/g' $i; done
```

I then restarted Moodle just in case and when I logged back in I was successfully connected to Microsoft O365.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/186568623@N07/49419627923/in/dateposted-public/" title="Screen Shot 2020-01-21 at 11.59.58 AM"><img src="https://live.staticflickr.com/65535/49419627923_fbae871728_n.jpg" width="182" height="320" alt="Screen Shot 2020-01-21 at 11.59.58 AM"></a>

Is this hardcoded value of graph.windows.net intended?  I don't know why it would allow you to manually set the resource in the OpenID connect settings if the resource was just going to be hardcoded anyways.

If you have any additional questions please let me know

**Comment by avegys** [comment]
Hi,

Thank you for reporting the issue. OpenID connect has enabled administrators to set resource manually. However, not all of the plugins were updated to use this new setting. 

Your issue was due to the inconsistency between OpenID authentication plugin setting and other plugins. Your were authenticated with your manually set Graph API resource when you logged in. However, Microsoft Block used different resource to check if you are logged in (the old way). This is why the block showed that you are not connected.

This issue will be resolved with next plugins release as all the plugins now will use this OpenID authentication plugin introduced setting. 

Best regards,
Andrius

**Comment by sgparry** [comment]
We are having this problem too.
We have OpenId auth working with a couple of already provisioned users, but we need the AAD sync to provision the users for us.
However, Azure AD sync is simply not working OOB. Running the full sync this is what we see:
```
.........  
......... Syncing user testy123@chapeltownacademy.com
......... User doesn't exist in Moodle
......... Created user #6
......... Assigning Moodle user 6 (objectid a49dd9e3-47f2-4bcb-b66d-9498551c7749) to application
......... Could not assign user "testy123@chapeltownacademy.com" Reason: No token available for usersync
.........  
```
If we try a resync, we get a similar message:
```
.........  
......... Syncing user testy123@chapeltownacademy.com
......... Assigning Moodle user 6 (objectid a49dd9e3-47f2-4bcb-b66d-9498551c7749) to application
......... Could not assign user "testy123@chapeltownacademy.com" Reason: No token available for usersync
......... The user is already using OpenID for authentication.
......... User is now synced.
......... Updating Moodle user data from Azure AD user data.
......... User is now updated.
```
and the log shows:
```
28 March 2020, 9:23 PM | Admin User | - | System | Microsoft Office 365 Integration | API failure | local_o365\oauth2\token::instance  local_o365\oauth2\token::get_for_new_resource:234: Cannot retrieve a  token for the base resource. Data: (null) | web
-- | -- | -- | -- | -- | -- | -- | --
```
Having looked into the code, I see it has many references to https://graph.windows.net as discussed here. Microsoft is retiring graph.windows.net in favour of graph.microsoft.com and because our app has been newly added to O365, I suspect it does not have full access to the older APIs and url [see this article](https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-or-azure-ad-graph/)
I tried the hack here and got this error instead:
```
28 March 2020, 9:56 PM | Admin User | - | System | Microsoft Office 365 Integration | API failure | local_o365\oauth2\token::instance  local_o365\feature\usersync\main::construct_user_api:77: Cannot  retrieve a token for the base resource. Data: (null) | web
-- | -- | -- | -- | -- | -- | -- | --
```
After digging further into the code I found an attempt to force a legacy API mentioned in the code. On a hunch I applied this additional hack:
```
diff -u o365/classes/feature/usersync/main.php.001  o365/classes/feature/usersync/main.php
--- o365/classes/feature/usersync/main.php.001  2020-03-28 22:35:06.610797277 +0000
+++ o365/classes/feature/usersync/main.php      2020-03-28 22:35:29.571360875 +0000
@@ -163,7 +163,7 @@
         }
 
         // Force using legacy api. Legacy assign user does not support app only access.
-        $apiclient = $this->construct_user_api(true);
+        $apiclient = $this->construct_user_api(false);
         $result = $apiclient->assign_user($muserid, $userobjectid, $appobjectid);
         if (!empty($result['odata.error'])) {
             $error = '';
```
and we now appear to have a successful workaround:
```
.........  
......... Syncing user testy123@chapeltownacademy.com
......... Assigning Moodle user 6 (objectid a49dd9e3-47f2-4bcb-b66d-9498551c7749) to application
......... User assigned to application.
......... The user is already using OpenID for authentication.
......... User is now synced.
......... Updating Moodle user data from Azure AD user data.
......... User is now updated.
```
I am not sure why #1110 was closed (the code changes needed were never made)

**Comment by sgparry** [comment]
Problem is that the user still cannot log in.

**Comment by avegys** [comment]
Hi,

Thank you for your input in improving Office 365 plugins. We have update resource in the latest release of auth_oidc and local_o365 plugins for Moodle 3.7 and 3.8.

Best regards,
Andrius
