### ISSUE TITLE
OneNote in the Microsoft block does not single sign on

### ISSUE THREAD

**Issue by mmulrthelp** [microsoft/o365-moodle#1202]
The Microsoft block no longer seems to SSO to your OneNote

On the block the URL is point at : http://portal.office.com/onenote

It should be pointing at : https://www.office.com/launch/onenote?auth=2

It would be a nice idea to be able set the endpoints in the GUI in case Microsoft decide to change them in the future.

**Comment by avegys** [comment]
Hi,

Thank you for reporting the issue. The link will be changed in the next plugin release. 

However, we are not planning to implement additional settings for GUI. We recommend to use local_onenote plugin which gives better user experience if you are using Microsoft OneNote Online features.

Microsoft block is using this broken link only when OneNote local plugin is not installed in Moodle.

Best regards,
Andrius

**Comment by avegys** [comment]
Hi @mmulrthelp,

The link was changed in the latest release. Thank you for reporting this issue and helping to improve the plugins.

Best rgards,
Andrius
