### ISSUE TITLE
Supported older version

### ISSUE THREAD

**Issue by BertDR** [microsoft/o365-moodle#1203]
Hi, 

This is a question about an old version - probably not supported anymore.

Setup : Moodle 3.2.9 - Build 20180517 
o365-moodle : version 3.2.0.7 - 2016120507

Should the integration with O365 still work ? When setting up local_o365 | systemapiuser, we get directed to an O365 page, the page asks permissions to read directory data etc.
However : clicking Accept just drops me back to the same page (consent page).

Can anyone confirm that this should or should not work ?

Kind regards, 

Bert

**Comment by nenorojas** [comment]
Hi Bert,

We are following the Moodle releases calendar to provide bug and security fixes:
https://docs.moodle.org/dev/Releases#General_release_calendar

The suite of plugins is complex, so we can't guarantee that it will work properly, even newer version of the plugin are not 100% bug free. 

We strongly recommend you to upgrade Moodle and the plugins to latest version.

Regards
