### ISSUE TITLE
Error: Office 365 user is already connected to a Moodle user

### ISSUE THREAD

**Issue by Rossco88** [microsoft/o365-moodle#1207]
We have multiple moodle environments. for example dev/test/uat/prod.

We are running into an issue when trying to link users from our Azure AD tenant to users in each of these different environments. If a user has been linked in dev then when trying to link in test we get the user is already connected error

Is this possible for a single azure account to be linked to multiple moodle instances?

**Comment by weilai-irl** [comment]
Hi @Rossco88,

No, there shouldn't be any restrictions on how many systems an Azure AD account can link to. In each Moodle environment you have, the mapping of the user is stored in mdl_local_o365_objects table. You can search for the mapped users by using a query like this from the environment where you see the error ("test" in your case).
```
SELECT *
FROM mdl_local_o365_objects
WHERE type = "user"
AND o365name  LIKE "EMAIL ADDRESS OF THE USER";
```
where EMAIL ADDRESS OF THE USER is the user in question. If it returns an entry, the "moodleid" field should be the ID of the user in mdl_user table. You can check if the account contains right information.

**Comment by Rossco88** [comment]
Hi @weilai-irl 

we ran that query against our test moodle environment for 2 accounts we are having this issue with.

It returned 0 results for both accounts. 

When we run it against our dev moodle environment it returns records for both accounts.

 If we clear the 2 accounts from the mdl_auth_oidc_token and mdl_local_0365_token tables in the dev moodle environment, we can then go into the test environment and link the moodle user to the office 365 user.

**Comment by nenorojas** [comment]
Hi @Rossco88 ,

Have you created a separated application in Azure AD /Enterprise application for each instance? Or are you trying to use the same application ID and secret for all instances?  

Regards

**Comment by Rossco88** [comment]
@nenorojas We have a separate application for each Moodle instance

**Comment by Rossco88** [comment]
Ok, finally worked this out. Needed to clear the following 4 tables before resyncing the users

Mdl_local_o365_token
Mdl_auth_oidc_token
Mdl_local_o365_connections
Mdl_local_o365_objects
