### ISSUE TITLE
Changed Object ID prevents logging in to Moodle

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1209]
If user's account is deleted from Azure AD but not from Moodle AND a new account is created to Azure with the same username, logging in to Moodle doesn't work.

This is because the old Object ID is stored in auth_oidc and local_o365 database tables and it of course changes in Azure. User sync doesn't change the Object ID, even though the log says "User is synced'.

This happens in some organizations (like schools), when user comes back after some time away and the account has been deleted in the meanwhile.

**Comment by Absortian** [comment]
Me ha ocurrido este problema, lo he solucionado haciendo una extracción de datos desde Azure AD donde saco email + Object ID

Con esa extracción he realizado updates masivos en base de datos en el campo oidcubiqid de la tabla auth_oidc_token filtrando por email.

Espero que sirva de ayuda para más gente, en nuestro caso ha salvado datos de más de 300 usuarios en Moodle.

**Comment by kkiiskin** [comment]
Hi

this is still a frequent problem.

Would maybe a tool in O365 settings be practical, where you could change ObjectID for users if it is not possible to update them automatically?

**Comment by harriholappa** [comment]
Are there any plans for this problem? We are experiencing this too.
