### ISSUE TITLE
AAD account is getting linked to moodle account even if it is already present in moodle.

### ISSUE THREAD

**Issue by sushantgawali** [Microsoft/o365-moodle#121]
If we run cron job and sync all AAD users to moodle and then login with existing moodle account and try to link an AAD account which is already synced, then it is getting linked to moodle account, instead it should say that 'moodle account for this AAD account already exist'

**Comment by jamesmcq** [comment]
@sushantgawali Is this the same as https://github.com/Microsoft/o365-moodle/issues/111 ?

**Comment by sushantgawali** [comment]
@jamesmcq No, actually it is opposite to #111, we should be checking if AAD account already synced with moodle before linking to moodle account.

**Comment by jamesmcq** [comment]
Gotcha - thanks for the report!

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/124

**Comment by number33** [comment]
Closing this issue as the PR has been added to the 20160523 release.
