### ISSUE TITLE
Tool to clean up tokens

### ISSUE THREAD

**Issue by nenorojas** [microsoft/o365-moodle#1210]
Scenario: UAT/Testing/Stage site is needed, so you create a second site using database backup from a site which already has auth_oidc configured and have current valid user sessions. This is common process that will end up with issue https://github.com/microsoft/o365-moodle/issues/1207. 

Requirement: Tool to clean up the tables, that will be triggered by change of app ID (because it's necessary to create a new application in Azure for each instance):
Mdl_local_o365_token
Mdl_auth_oidc_token
Mdl_local_o365_connections
Mdl_local_o365_objects

**Comment by nenorojas** [comment]
https://github.com/microsoft/o365-moodle/issues/1207

**Comment by weilai-irl** [comment]
@nenorojas, there is already feature to cleanup oidc tokens in local_o365 plugin, it's available at: "Advanced" tab -> "Maintenance" section -> "Cleanup OpenID Connect Tokens" link.
I understand it only clears up oidc tokens, but not the others. Do you think it will be enough for our use case here? or if new functions needs to be added to the maintenance section to clean up other tokens?

Lai

**Comment by weilai-irl** [comment]
The latest release (3.8.0.5 and 3.9.2) contains a change to cleanup all tokens and mapping records in the following tables in case the app ID is changed:
 - local_o365_token
 - auth_oidc_token
 - local_o365_connections
 - local_o365_objects

This should solve the issue.

Regards,
Lai
