### ISSUE TITLE
Table M_AUTH_OIDC_TOKEN has a column named as a reserved word in Oracle

### ISSUE THREAD

**Issue by cgonzalez** [microsoft/o365-moodle#1211]
There is a problem when using simultaneously Moodle with these plugins and an Oracle database.

Table `M_AUTH_OIDC_TOKEN `has a column named `RESOURCE`, but "RESOURCE" is a reserved word in Oracle (see https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm).

When the plugin inserts a record in `M_AUTH_OIDC_TOKEN ` this errors shows up:
```
Default exception handler: Error al escribir a la base de datos Debug: ORA-01747: invalid user.table.column, table.column, or column specification
```

As a workaround I've renamed the `RESOURCE` column to `RESOURCETOKEN` and I've added this "ugly fix" to `lib/dml/oci_native_moodle_database.php`:

```php
    public function insert_record_raw($table, $params, $returnid=true, $bulk=false, $customsequence=false) {
        if (!is_array($params)) {
            $params = (array)$params;
        }

        // Start of UGLY FIX
        if ($table == "auth_oidc_token") {
            if (array_key_exists("resource", $params)) {
                $params['resourcetoken'] = $params['resource'];
                unset($params['resource']);
            }
        }
        // End of UGLY FIX

        $returning = "";
```

This is only a temporary workaround and a better solution is required.

Please rename the `RESOURCE` column in `M_AUTH_OIDC_TOKEN`.

**Comment by weilai-irl** [comment]
Hi @cgonzalez,

The reported issue has been fixed in the latest release (3.9.4 and 3.10.1) of the plugins. Please try it out.

Regards,
Lai
