### ISSUE TITLE
local_o365 makes core moodle unit tests fail core_backup_async_helper_testcase::test_send_message

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1212]
Install a clean moodle 3.7 and run 
` vendor/bin/phpunit "core_backup_async_helper_testcase" backup/util/helper/tests/async_helper_test.php
`
You will get an error with the output pasted below.
This is due to our debugging line in the local plugin here: https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/observers.php#L783

> $  vendor/bin/phpunit "core_backup_async_helper_testcase" backup/util/helper/tests/async_helper_test.php
> Moodle 3.7.3+ (Build: 20191205), 081401603b9322cfd4aef6cbc949547da9c3d1b2
> Php: 7.2.27.6.18.04.1.1, pgsql: 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1), OS: Linux 4.15.0-74-generic x86_64
> PHPUnit 7.5.17 by Sebastian Bergmann and contributors.
> 
> E.                                                                  2 / 2 (100%)
> 
> Time: 5.42 seconds, Memory: 110.50 MB
> 
> There was 1 error:
> 
> 1) core_backup_async_helper_testcase::test_send_message
> Unexpected debugging() call detected.
> Debugging: SKIPPED: handle_notification_sent - incomplete settings
> * line 783 of /local/o365/classes/observers.php: call to debugging()
> * line ? of unknownfile: call to local_o365\observers::handle_notification_sent()
> * line 155 of /lib/classes/event/manager.php: call to call_user_func()
> * line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
> * line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
> * line 458 of /lib/classes/message/manager.php: call to core\event\base->trigger()
> * line 384 of /lib/classes/message/manager.php: call to core\message\manager::trigger_message_events()
> * line 349 of /lib/classes/message/manager.php: call to core\message\manager::send_message_to_processors()
> * line 346 of /lib/messagelib.php: call to core\message\manager::send_message()
> * line 180 of /backup/util/helper/async_helper.class.php: call to message_send()
> * line 74 of /backup/util/helper/tests/async_helper_test.php: call to async_helper->send_message()
> * line 1154 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to core_backup_async_helper_testcase->test_send_message()
> * line 842 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
> * line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
> * line 693 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
> * line 796 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
> * line 746 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
> * line 652 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
> * line 206 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->doRun()
> * line 162 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
> * line 61 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
> 
> 
> /var/www/site/lib/phpunit/classes/advanced_testcase.php:88
> 
> To re-run:
>  vendor/bin/phpunit "core_backup_async_helper_testcase" backup/util/helper/tests/async_helper_test.php
> 
> ERRORS!
> Tests: 2, Assertions: 11, Errors: 1.
>

**Comment by kristian-94** [comment]
Of course, our plugin isn't going to have complete settings when other parts of moodle are being tested. So we have to think of another way to send these debugging messages. We can maybe just check if we're in a unit test before sending the debugging message.

**Comment by avegys** [comment]
Hi Kristian,

Thank you for your efforts helping to improve Office365 plugins. Your code changes fixing the test has been included into latest release for Moodle 3.7 and Moodle 3.8.

Bets regards,
Andrius
