### ISSUE TITLE
Users not deleted from Moodle

### ISSUE THREAD

**Issue by bands** [microsoft/o365-moodle#1214]
Hello,

We're seeing an issue where when users are deleted from O365 they are not being deleted from Moodle. We have the sync working perfectly otherwise. 

The tickbox is ticked to delete previous users if they are removed from Azure and can see multiple instances of this happening. This has not always been an issue, it has been working until recently (not sure when, only just reported to us).

Many thanks,

Tim

**Comment by vach9** [comment]
Ahoj 
mám stejný problém, uživatele to vytvoří, synchronizuje, ale když ho smažu z AD zůstane v Moodlu. nevím kde co mám nastavit, zaškrtávací políčko je zaškrtnuto. 
Díky 
Michal

**Comment by bands** [comment]
Hello Michal,

Interestingly, I attempted to manually delete the user and it turned out they hard data related to them in a the course_completions table in mysql. I then got their user id and deleted the data in that table to do with that user and then I could manually delete the user. Which is what im suspecting broke the sync for that user. So still an issue.

**Comment by avegys** [comment]
Hi Tim and Michal,

Thank you for you reported issue. Due to API returned data changes the users deletion does not work any more. The fix is on the way to be released soon.

Best regards,
Andrius

**Comment by avegys** [comment]
Hi Tim and Michal,

We have released the new version of local_o365 plugin fro Moodle 3.7 and 3.8 which has now updated delete users feature.

Best regards,
Andrius
