### ISSUE TITLE
Unit test failure in moodle 3.7  local_o365_coursegroups_testcase::test_create_group

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1215]
The unit test failure is pasted below. 
I can see it's caused by this line that strips out a longer course description https://github.com/microsoft/moodle-local_o365/blob/master/classes/feature/usergroups/coursegroups.php#L262
That's why our two descriptions are different, one has been truncated. 

> $  vendor/bin/phpunit "local_o365_coursegroups_testcase" local/o365/tests/coursegroups_test.php
> Moodle 3.7.3+ (Build: 20191205), 18204bc14e0c577c20585239a8216b5f70c5db3b
> Php: 7.2.27.6.18.04.1.1, pgsql: 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1), OS: Linux 4.15.0-74-generic x86_64
> PHPUnit 7.5.17 by Sebastian Bergmann and contributors.
> 
> F.                                                                  2 / 2 (100%)
> 
> Time: 1.61 seconds, Memory: 56.25 MB
> 
> There was 1 failure:
> 
> 1) local_o365_coursegroups_testcase::test_create_group
> Failed asserting that two arrays are equal.
> --- Expected
> +++ Actual
> @@ @@
>          'url' => 'https://graph.microsoft.com/v...groups'
>          'options' => Array (
>              'CURLOPT_POST' => 1
> -            'CURLOPT_POSTFIELDS' => '{"groupTypes":["Unified"],"displayName":"prefix 1@:-_: Test course 1","mailEnabled":false,"securityEnabled":false,"mailNickname":"prefix1_tc_1","visibility":"Private","description":"Test course 1\nLorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla non arcu lacinia neque faucibus fringilla. Vivamus porttitor turpis ac leo. Integer in sapien. Nullam eget nisl. Aliquam erat volutpat. Cras elementum. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Integer malesuada. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Mauris elementum mauris vitae tortor. Aliquam erat volutpat.\nTemporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Pellentesque ipsum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Aliquam ante. Proin in tellus sit amet nibh dignissim sagittis. Vivamus porttitor turpis ac leo. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Aliquam erat volutpat. Nulla est.\nVivamus luctus egestas leo. Aenean fermentum risus id tortor. Mauris dictum facilisis augue. Aliquam erat volutpat. Aliquam ornare wisi eu metus. Aliquam id dolor. Duis condimentum augue id magna semper rutrum. Donec iaculis gravida nulla. Pellentesque ipsum. Etiam dictum tincidunt diam. Quisque tincidunt scelerisque libero. Etiam egestas wisi a erat.\nInteger lacinia. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris tincidunt sem sed arcu. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Aliquam id dolor. Maecenas sollicitudin. Et harum quidem rerum facilis est et expedita distinctio. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam dapibus fermentum ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Pellentesque sapien. Duis risus. Mauris elementum mauris vitae tortor. Suspendisse nisl. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim.\nIn laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Maecenas lorem. Etiam posuere lacus quis dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nam sed tellus id magna elementum tincidunt. Suspendisse nisl. Vivamus luctus egestas leo. Nulla non arcu lacinia neque faucibus fringilla. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Etiam dictum tincidunt diam. Etiam commodo dui eget wisi. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Pellentesque sapien."}'
> +            'CURLOPT_POSTFIELDS' => '{"groupTypes":["Unified"],"displayName":"prefix 1@:-_: Test course 1","mailEnabled":false,"securityEnabled":false,"mailNickname":"prefix1_tc_1","visibility":"Private","description":"Test course 1\nLorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla non arcu lacinia neque faucibus fringilla. Vivamus porttitor turpis ac leo. Integer in sapien. Nullam eget nisl. Aliquam erat volutpat. Cras elementum. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Integer malesuada. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Mauris elementum mauris vitae tortor. Aliquam erat volutpat.\nTemporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Pellentesque ipsum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Aliquam ante. Proin in tellus sit amet nibh dignissim sagittis. Vivamus porttitor turpis ac leo. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Aliquam erat volutpat. Nulla est.\n ..."}'
>              'CURLOPT_USERAGENT' => 'Moodle-groups-2019052004'
>          )
>      )
>  )
> 
> /var/www/site/local/o365/tests/coursegroups_test.php:144
> /var/www/site/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
>  vendor/bin/phpunit "local_o365_coursegroups_testcase" local/o365/tests/coursegroups_test.php

**Comment by kristian-94** [comment]
Fixed with this commit: https://github.com/catalyst/o365-moodle/commit/7267559bfc602a94b1296a1f350fdf62bafbbcd2

**Comment by tmuras** [comment]
Hi @kristian-94 , thanks for the fix.
Do you want to create PR for this (we can of course just cherry pick it).

Also - I think we should use the function from Moodle for shortening, check:
`function shorten_text($text, $ideal=30, $exact = false, $ending='...')`

**Comment by kristian-94** [comment]
Hi @tmuras  , I implemented that here: https://github.com/microsoft/o365-moodle/compare/MOODLE_37_STABLE...catalyst:issue1215?expand=1
but it won't let me make a merge request, not sure what I'm doing wrong.

**Comment by avegys** [comment]
Hi Kristian,

Thank you for your efforts helping to improve Office365 plugins. Your code changes that fixes test has been included into latest release for Moodle 3.7 and Moodle 3.8.

Bets regards,
Andrius
