### ISSUE TITLE
Error on users sync

### ISSUE THREAD

**Issue by abrude** [microsoft/o365-moodle#1217]
Hi everyone.

Recently I included a second O365 tenant on my Moodle site (3.7.2+ (build: 20190920) all add-ons are already updated), but new users don't sync.

In the records it appears:

Execute scheduled task: Synchronize users with ADF. (local_o365 \ task \ usersync)
... began 10:23:02. Current memory usage 53MB.
...... Starting synchronization
...... No skiptoken (delta) stored.
...... Using deltatoken.
...... Using delta sync.
...... Contact with Azure AD ...
...... I got a response from Azure AD
...... Store deltatoken
...... Deleting skiptoken (delta) (none received)
...... There are no users received to synchronize.
...... Synchronization process finished.
... used 5 dbqueries
... used 2.421010017395 seconds
Complete scheduled task: Synchronize users with ADF. (local_o365 \ task \ usersync)

Currently, the "Perform a complete synchronization on each execution" option is disabled, because if it is activated, it only synchronizes 100 users:

Execute scheduled task: Synchronize users with ADF. (local_o365 \ task \ usersync)
... started 10:03:03. Current memory usage 54.6MB.
...... Starting synchronization
...... Using skiptoken (complete)
...... Forcing full synchronization.
...... Contact with Azure AD ...
...... I got a response from Azure AD
...... Skiptoken storage (complete)
...... 100 users received. Synchronizing ...

Thanks for your time.
Sincerely

**Comment by avegys** [comment]
Hi Alejandro,

From your description it seems that you have a long queue of users to be synced. However, Microsoft API has a restriction of 200 users per request and by default o365 plugin is set to sync only once a day at 1 am.
In your case, first thing I would do is change sync task to run more frequently. Go to Site Administration -> Server -> Scheduled Tasks and find there local_o365 plugin task usersync. Edit it schedule to run for example each hour. This should help to clean your queue and prevent from further issues.

Best regards,
Andrius

**Comment by avegys** [comment]
Hi Alejandro,

We have released new version of the plugin for Moodle 3.7 and 3.8. It does not have 200 users limit anymore. This means you do not need to change scheduled task period and all modified or new users should be synced for you.
Please update your plugins.

Best regards,
Andrius
