### ISSUE TITLE
Add option to choose a custom theme to display in msteams tab

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1223]
We should have the option of whether to have to use the boost_o365teams theme in msteams.

**Comment by kristian-94** [comment]
https://github.com/microsoft/moodle-local_o365/pull/27

**Comment by bradnielsen2981** [comment]
Totally agree with this one. @kristian-94

**Comment by avegys** [comment]
Hi Kristian,

Thank you for your efforts helping to improve Office365 plugins. Your code changes that allows to select custom theme for Moodle in Teams tab has been included into latest release for Moodle 3.7 and Moodle 3.8.

Bets regards,
Andrius
