### ISSUE TITLE
local_o365 user sync: add ability to sync full user cohort from the UI quickly

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1228]
At the moment, we run `php admin/tool/task/cli/schedule_task.php --execute='\local_o365\task\usersync';` and only sync 100-200 users at a time. The task only takes a couple of seconds to run, but the fastest we can run it in moodle is once per minute. For thousands of students, this means we're only running the task for a tiny amount of the time, the rest we're just waiting to run the task again. 

This is especially a problem when first setting up the OIDC auth plugin and needing to swich over the entire user base at once. 

The workaround to this issue is running the task from the cli over and over with a command like:
```
for i in `seq 1000`; do (php admin/tool/task/cli/schedule_task.php --execute='\local_o365\task\usersync'; date;) >> /tmp/microsoftsync.txt; done; date
```
It would be nice to have a way to do this from the UI, with a progress bar etc. 

Alternatively it would be nice to be able to sync more than just 100-200 users at a time.

**Comment by sgparry** [comment]
I think the limit comes from Azure itself - the request sent by the php code does not specify a size limit, it just takes as many as the service will give it. So I presume M$ have reduced the limit or default from 1000 down to 100. In our case it is also painfully slow, so maybe they have rate limited it too.

**Comment by Rossco88** [comment]
@sgparry  That may be the case, the above CLI command just runs the API call to Azure faster than the cron job itself so rather than 200 users every minute it could be 200 users every 5 seconds for example

**Comment by avegys** [comment]
Hi,

We are aware of this issue with reduced API limits. The fix is on the way and will be released in the near future.

Best regards,
Andrius

**Comment by avegys** [comment]
Hi All,

Thank you for your input. We have released new version of local_o365 plugins for Moodle 3.7 and Moodle 3.8 which solves this by syncing all modified and new users in the queue instead of previous 200 limit. Please update your plugins and let us know if you are still experiencing any issues.

Best regards,
Andrius

**Comment by sgparry** [comment]
I am still having this issue - presumably because the plugin is not yet available via the moodle plugins directory. Please can you let me know when it will be available?

**Comment by sgparry** [comment]
By the looks of it the code you have added only works if you get more than 100 new users on a delta, not if you are doing a full. You have added code to the block at 130 of usersync.php but not line 95.

**Comment by sgparry** [comment]
Switch to doing delta and ran twice - which fixed the problem for now - but when we switch from pilot to live and change the group criteria, we are probably going to have the same problem all over again...

**Comment by sgparry** [comment]
@avegys can we re-open this please?

**Comment by avegys** [comment]
Hi @sgparry,

Please see #1279. The change is ready and will be released in the next release.

Best regards,
Andrius
