### ISSUE TITLE
Issue with documentation and powershell script for Moodle integration

### ISSUE THREAD

**Issue by cirrus3d** [microsoft/o365-moodle#1229]
In README.md the process of registering o365 with a Moodle application is described.
However it is not working for me in Moodle 3.8+. I got an Authentication_Unauthorized error because the tenant ID was missing.

The process to fix it was described here:
http://get-cmd.com/?p=4949

All I had to do was to add the Tenant ID in the powershell script in L17:
Connect-AzureAD -TenantId XXXX-XXXX-XXXX-XXXX

Could this be a misconfiguration from my side?

**Comment by weilai-irl** [comment]
Hi @cirrus3d,

The PowerShell script has been updated in the latest release (3.9.6 for Moodle 3.9 and 3.10.3 for Moodle 3.10). The issue described should have been fixed in it.

Please upgrade to the latest version to confirm.

Regards,
Lai
