### ISSUE TITLE
Role names are hard coded: add option to customise teacher and editingteacher roles

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1235]
Moodle allows you to customise roles and role names, so we can't have our roles as hard coded strings, eg. here https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/feature/usergroups/coursegroups.php#L575

 and here: https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/observers.php#L635

**Comment by avegys** [comment]
Hi Kristian,

Thank you for noticing this and creating a commit. However, I think  Morgan is right that we should implement this based on capabilities https://github.com/microsoft/o365-moodle/pull/1236#issuecomment-613253946
We are planning to implement this in near future.

Best regards,
Andrius

**Comment by weilai-irl** [comment]
A solution to the issue has been included in the latest release for Moodle 3.8 and 3.9.
The issue is closed.
