### ISSUE TITLE
OpenID Problems to login

### ISSUE THREAD

**Issue by lucasmellos** [microsoft/o365-moodle#1241]
I'm getting some errors on latest version of OID Connect and Moodle 38 stable when trying to signup/signin

Debug info: SQLState: 23000<br>
Error Code: 515<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'token', table 'moodle.dbo.mdl_auth_oidc_token'; column does not allow nulls. INSERT fails.<br>
SQLState: 01000<br>
Error Code: 3621<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated.<br>

Anyone facing the same problem?

**Comment by lucasmellos** [comment]
#1239 seems to fix this problem. Any intention to accept the PR?

**Comment by avegys** [comment]
Hi Lucas,

The fix is now going through our testing process and will be released soon.

Best regards,
Andrius

**Comment by avegys** [comment]
Hi Lucas,

The fix is released now for Moodle 3.7 and Moodle 3.8. Thank you for reporting the issue.

Best regards,
Andrius
