### ISSUE TITLE
creating class team fails when the course have multiple teachers.

### ISSUE THREAD

**Issue by Na0ki** [microsoft/o365-moodle#1242]
Hello.

I found that creating teams team for the course with multiple teachers is failing.
It is caused by `create_class_team` graph api request and it's failing because `create_class_team` sends multiple owners even though beta graph api does not allow mutiple owners at a moment.

Possible solution is to send only one owner at the point of creation.
The remaining owners will be added by `resync_group_membership`, which is executed right after the team creation.

Thanks.

**Comment by nenorojas** [comment]
Hi, 

That will be sorted soon in a new release: https://github.com/microsoft/o365-moodle/issues/1222#issuecomment-617029669

Regards
