### ISSUE TITLE
Can't login with users from a second tenant

### ISSUE THREAD

**Issue by cgonzalez** [microsoft/o365-moodle#1245]
I'm using the o365 plugin for authenticating users from Azure AD. When I configure the main tenant, all users can login without any issue.

Now I've added a second tenant to the o365 configuration:
![image](https://user-images.githubusercontent.com/66578/79597940-21a13080-80b1-11ea-83c3-6dce82d40bb9.png)

When I try to login with an user from the second tenant, the Microsoft login form is shown and the user is succesfuly authenticated (according to the Azure AD logs). But then I get this error from Moodle:

`Error en la llamada a la API: Resource 'xxx-yyy-zzz' does not exist or one of its queried reference-property objects are not present.`

'xxx-yyy-zzz' is the correct ID for the user in the second tenant.

After hours of digging into the code and the logs, I've found that a record is inserted in the table M_AUTH_OIDC_TOKEN for the user with the correct OIDCUNIQID, USERNAME and OIDCUSERNAME. But the USERID value is 0.

Even more: after adding a few `error_log` in the `local/o365/classes/oauth2/clientdata.php` file, I've found that all queries are send to the firts tenant end point (https://login.microsoftonline.com/FirstTenant.onmicrosoft.com/oauth2/token) even when the user is from the second tenant.

I've tried creating an user manually in Moodle and then setting the USERD value in M_AUTH_OIDC_TOKEN but the result is the same.

Note that the app is configured as "multitenant" in the first tenant.

Please help me to diagnose this problem.

**Comment by nenorojas** [comment]
Hi @cgonzalez ,

We couldn't reproduce the issue with Moodle 3.7 or 3.8. Have you tried to add the second tenant using an user that contains proper permissions in the second Azure AD tenant?
1) Go to /local/o365/acp.php?mode=tenants
2) Click on Add new tenant
3) Proceed to Office 365 login page
4) Accept the permissions
![2020-05-13 10_56_17-Sign in to your account](https://user-images.githubusercontent.com/3680797/81798929-80b76100-9508-11ea-9b84-cc9ce5503dcb.png)
5) After that the users from second Azure AD should be able to login without problem

Have you created the app ""multitenant"in the first tenant using the powershell script provided with the plugin? 
Are you aware of any other restrictions in your main tenant Azure AD to be accessed from external/guests users?

Regards

**Comment by cgonzalez** [comment]
> Have you tried to add the second tenant using an user that contains proper permissions in the second Azure AD tenant?

Yes.

> Have you created the app ""multitenant"in the first tenant using the powershell script provided with the plugin?

Yes.

> Are you aware of any other restrictions in your main tenant Azure AD to be accessed from external/guests users?

No.

I've downloaded o365-moodle from master (https://github.com/microsoft/o365-moodle/archive/master.zip) and now all is working without problems. I guess some commit has fixed the issue.
