### ISSUE TITLE
Unable to sync Guest AAD users

### ISSUE THREAD

**Issue by richardegleston** [microsoft/o365-moodle#1247]
I get the following error when syncing my users from azure AD:

Could not create user "[username]" Reason: The given username contains invalid characters.

The issue is that Azure AD appends "#EXT#" to the guest users' userPrincipalName.

Is there a workaround to getting users with User Type = Guest synced to Moodle?

Thanks!

**Comment by avegys** [comment]
Hi Richard,

It seems that there is no workaround at the moment to this issue without making code change. However, we are working on it and fix will be released in near future.

Best regards,
Andrius

**Comment by cbrherms** [comment]
I have just ran in to this issue myself while trying to set up external examiners.
Will work around it by creating local users for them but guest user syncing would be a very welcome addition.

**Comment by bayaopriol** [comment]
Hi @avegys ,

Is this feature expected in the near future?
Thank you!

Regards,
Balyao

**Comment by weilai-irl** [comment]
Hi all,

The feature to sync guest users has been included in the latest release of the plugin, with the following changes:
 - A new user sync option "Sync guest users" is added.
 - If the option is checked, guest users in the Azure AD tenant are synced to Moodle in user sync task.
 - If the option is unchecked, guest users in the Azure AD tenant are not synced to Moodle in user sync task.

We have tested and confirmed that guest users can login using their real email address and password.

Regards,
Lai
