### ISSUE TITLE
File selector problem within a task as students

### ISSUE THREAD

**Issue by vicmanflores** [microsoft/o365-moodle#1251]
Hi, I have integrated Microsoft 365 with Moodle everything is working correctly for the login and from the selector you can see OneDrive files of each user.
However when a student is going to upload a task in the file selector they can see their OneDrive files but it does not show the options to link the file or upload a copy directly to moodle.
It does not allow me to link from the file picker when loading assignments by students.
I would appreciate help with this problem.

Best regards.

**Comment by nenorojas** [comment]
Hi @vicmanflores, 

Can you please let us know which repository are you using? Is that repository_office365 or the core Microsoft OneDrive repository?

If you are using repository_office365, you only have the option the select the Onedrive file and upload a copy to Moodle.

![2020-05-13 16_00_18-TC014_ Files - Edit submission](https://user-images.githubusercontent.com/3680797/81829654-0b14ba80-9533-11ea-9d93-c22efccd245f.png)

Regards

**Comment by weilai-irl** [comment]
closed due to inactivity
