### ISSUE TITLE
Verifying admin consent between moodle and office365

### ISSUE THREAD

**Issue by FamousBern** [microsoft/o365-moodle#1252]
While i click provide admin consent link in moodle to verify permission in azure i get the following error. I need help team.

Invalid Endpoint URI received.

More information about this error

**Comment by kinnectus** [comment]
Have you ensured your OpenID Connect URLs are accurate?

E.g. https://your_moodle_url/admin/settings.php?section=authsettingoidc

Settings to consider:

- auth_oidc | authendpoint
- auth_oidc | tokenendpoint

Also consider double checking your URLs (such as redirect URL) is accurate in your Azure tenancy - make sure it has the trailing slash.

**Comment by FamousBern** [comment]
Thank you for your reply i have been waiting for this.

I have checked the auth_oidc endpoints at openID settings page they are okay.
The redirect URI is has the trailing slash also.

All users synced well from azure active directory to my moodle site. But same error is thrown when i try to login to my moodle instance using office365 credentials.

Regards,
Bernard

**Comment by FamousBern** [comment]
Thank you brother, it worked.
