### ISSUE TITLE
Feature request: map group memberships to Moodle

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1254]
Would it be possible to add user's Azure AD group memberships as an option to User Field Mapping?

For example bring group names to a designated field separated by a comma, like so:
"Personel, Finance"

**Comment by weilai-irl** [comment]
Hi @kkiiskin,

The latest release (3.8.0.5 and 3.9.2) adds support to map group memberships as text. Please try it out.

The issue is closed now.

Regards,
Lai
