### ISSUE TITLE
Choice of single or multi-tenant and "Anyone" links

### ISSUE THREAD

**Issue by kinnectus** [microsoft/o365-moodle#1255]
Please advise if this is the wrong place for this issue.

We have a tenant-wide configuration that prevents external sharing of files in SharePoint Online and OneDrive for Business. I.e. "Anyone" links are disabled, forbidden etc.

We have a Moodle instance that only our staff and students use (we are a University) and we would like to integrate OneDrive for Business to permit our students to be able to submit coursework from their OneDrive (as access controlled links), and allow our staff to add resources to their Moodle courses using the same repository functionality.

The problem we have is that, according to the Moodle documentation, we must have the following:

- **A multi-tenant Azure Application** > We don't want this because we only have one tenancy we'd like to use
- **Allow "Anyone" links** > A business decision has forbidden this and, for our use of Moodle within our business we only want users within our tenancy to be using Moodle.

We understand the rationale, however there is a need to be able to choose a prefered set of settings such as the tenancy type and whether you have certain Azure settings relating to sharing access.

**Comment by nenorojas** [comment]
Hi @kinnectus ,

Before we can determine if this is the correct place, could you please let us know which is the repository that you intend to use to allow users to upload files from Onedrive:

https://docs.moodle.org/38/en/OneDrive_repository 
or
https://moodle.org/plugins/repository_office365

As correctly described in https://github.com/microsoft/o365-moodle/issues/1220, repository_office365 doesn't allow access controlled links yet.

Moodle core Onedrive repository does, but requires you to create an oauth2 service to work: https://docs.moodle.org/38/en/OAuth_2_services (it can be the same app used for office365 authentication).

Regards

**Comment by kinnectus** [comment]
We intend to use the core (https://docs.moodle.org/38/en/OneDrive_repository) - the link is one of what we have followed.

We also followed the steps to create the Oauth2 service (and set up the system account).

We managed to successfully configure both the OneDrive repository and Oauth2 service, however it is the Azure stuff (linked to the Moodle stuff) that is causing us the trouble.

**Comment by kinnectus** [comment]
Please could we ask if there is any further consideration for this issue? It has been over a year since this issue was raised and we're still no further forward.

Thank you

**Comment by weilai-irl** [comment]
Hi @kinnectus,

I apologise for not getting back to you sooner.

Unfortunately this github project is only about plugins in the [Microsoft 365 set](https://moodle.org/plugins/browse.php?list=set&id=72) which includes repository_office365. Plugin repostiroy_onedrive is part of Moodle core, and the best place to get help with it would be Moodle forum or tracker.

I'll close this issue in that case.

Regards,
Lai
