### ISSUE TITLE
Implement travis CI automated testing

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1257]
Including a `.travis.yml` file into the root of each moodle plugin will allow travis to automatically run unit tests for each new commit. This integrates nicely with github too and helps with QA. You can see an example here: https://github.com/catalyst/moodle-tool_objectfs/commits/master

Notice the green ticks next to each commit. It's easy to see which commits make the tests start failing too.

**Comment by avegys** [comment]
Hi Kristian,

Thank you for your suggestion.

Bets regards,
Andrius

**Comment by kristian-94** [comment]
More information on this is here:
https://moodle.org/mod/forum/discuss.php?d=323384

but the short version
grab this file:
https://github.com/moodlerooms/moodle-plugin-ci/blob/master/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to:
https://travis-ci.org/profile/organisationname
Flick the switch for this repo.

**Comment by kristian-94** [comment]
We already have a travis file but it's just not turned on it looks like: https://github.com/microsoft/o365-moodle/blob/master/local/o365/.travis.yml

**Comment by kristian-94** [comment]
https://github.com/catalyst/o365-moodle/commit/d40d051995d48e03745c8c0ea607ffef36aaf401

I've implemented this over in a fork of the plugin

**Comment by weilai-irl** [comment]
Plugin filter_oembed is to be removed from the plugin set as it's not required anymore.

The issue will be closed when the change is released.
