### ISSUE TITLE
O365 Sync Groups Issue

### ISSUE THREAD

**Issue by jorfernando66** [microsoft/o365-moodle#1259]
On a Moodle site (3.6 v)  that has integration with Office 365,

when I used to create the course and its groups, these were created as groups in Office 365,

two days ago, only created the course groups, and the main no.

So I checked the scheduled tasks of Moodle, in Create User Groups in Office365, in last run,

I see the date when the integration plugin was installed, and that is not correct, as I understand.

How can I correct that?

Or how can I execute that task manually?

Thank you so much
![moodle](https://user-images.githubusercontent.com/58986356/82506788-58120700-9ac6-11ea-839f-d9b87231a31d.jpg)

**Comment by weilai-irl** [comment]
Hi @jorfernando66,

I know it has been a while since this issue was reported. Can you confirm if this is still an issue?

Regards,
Lai
