### ISSUE TITLE
Moodle LTS 3.5 support

### ISSUE THREAD

**Issue by montypanday** [microsoft/o365-moodle#1265]
Hi,

I tried setting up Teams Integration with Moodle LTS branch 3.5 and realized that it is not being supported recently. Many of the issues were only fixed in later versions. Would the maintainers of this repository be happy to accept contributions to at least fix the bugs on the Moodle 35 Stable branch.

Moodle's LTS branches are supported for security and bug fixes. I would be good if we can follow the same approach in this repository.

One particular issue I faced is #1227 one which was fixed only in later versions.

Kind Regards
Monty Panday

**Comment by nenorojas** [comment]
Hi @montypanday, 

The logic for fixing only to Moodle 3.7 and 3.8 is that we have agreed to follow Moodle releases calendar: https://docs.moodle.org/dev/Releases. 

The bug fixes and enhancements approved will only be provided for Moodle versions that are still receiving core bug fixes from Moodle HQ. 

It's the same approach for security fixes, if it would be a security fix, then it would be released for Moodle 3.5 version as well. 

If you would like to share your contribution here to benefit the community, you are truly welcomed, but we can't commit that will be merged to official code.

Kind Regards
