### ISSUE TITLE
OpenID doesn't provide middle name

### ISSUE THREAD

**Issue by troshab** [microsoft/o365-moodle#1266]
Current version of auth_oidc plugin doesn't provide middle name, could you fix that, please?

**Comment by weilai-irl** [comment]
Hi @troshab,

Could you clarify your question please? "Middle name" is neither a profile field in Moodle nor in Microsoft account as far as I know.

Regards,
Lai

**Comment by sebastianberm** [comment]
Hi @weilai-irl ,

That is not correct, see the docs @ https://docs.moodle.org/310/en/Additional_name_fields :-).
I think @troshab might mean this.

We fixed this by making a fork of this module, as there were a lot more changes our client requested...

**Comment by weilai-irl** [comment]
Hi @sebastianberm,

Thank you for pointing it out.

I think the request here is to support field mapping on the additional name fields in Moodle. We will work on this and include it in the releases in the coming months.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @troshab and @sebastianberm,

The requested feature has been included in the latest release 3.9.4 and 3.10.1 of the plugins. Please upgrade the plugins and try it out.

Regards,
Lai
