### ISSUE TITLE
auth_oidc Call to undefined method auth_oidc\oidcclient::use_chinese_api()

### ISSUE THREAD

**Issue by leonstr** [microsoft/o365-moodle#1267]
[Originally reported in the Moodle forum](https://moodle.org/mod/forum/discuss.php?d=404122).

auth_oidc version 2020020301 added a call to oidcclient::use_chinese_api() in classes/oidcclient.php:setcreds() but didn't add the corresponding method.

**Comment by weilai-irl** [comment]
Hi @leonstr,

The fix to the issue has been included release 3.9.3 and 3.10.0 which are made available today. Please check them out.

Regards,
Lai
