### ISSUE TITLE
Prevent users from changing the surname, firstname, email in Moodle profile settings

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1268]
o365-synced Users in Moodle are allowed to change their surname, firstname, and email address in their own moodle profile settings. Is there any possibility where this can be prevented? Other authentication methods (LDAP, manual accounts) offers such possibilities, I didn't find it in the o365 plugin settings.

We are using Moodle 3.5.7+; plugin o365: 3.5.0.6 (2018051710)
thx Anton

**Comment by AntonT76** [comment]
I have found two solutions:

a.) prevent users from changing their own profile
moodle/user:editownprofile --> prohibit
--> this is not very usefull, because Users are not allowed to change language settings, forum settings, etc.

b.) change code in:
https://github.com/microsoft/o365-moodle/blob/master/auth/oidc/classes/loginflow/base.php
search in line 39ff:
```
'field_lock_firstname' => 'unlocked',
'field_lock_lastname' => 'unlocked',
'field_lock_email' => 'unlocked',
```
and change it 'locked', e.g.:

```
'field_lock_firstname' => 'locked',
'field_lock_lastname' => 'locked',
'field_lock_email' => 'locked',
```

Does anyone know if there are any side effects (e.g. user sync, etc.)?

thanks, best regards, Anton

**Comment by giselebrugger** [comment]
I have the same problem. 
I need to block editing the firstname and lastname in user profile.
the solution B it didn't work out for me.
Did you succeed?

**Comment by AntonT76** [comment]
I did some tests again on Moodle 3.5.7+ and also on 3.7.1+. Solution B works in both.

**Some side effects of solution b:**
User must be synchronised from Azure to Moodle before first login OR user must exists as an oidc-user in Moodle
If not, users will be auto-created (1) and asked after first login to set firstname, lastname, e-Mail. This is no longer allowed for users. Moodle will then create a user only with username, but without firstname, lastname, e-Mail. So if this happens, Moodle Admins can add this values manually in the user settings (in 3.5.7+).

In 3.7.1+ this changes in user settings can no longer be done by a Moodle Admin (strange?). In 3.7.1+ Moodle Admins have to delete the user and re-create/re-sync OR you can do this changes in Moodle database (be aware!). I did not know, if this also happens in newer Moodle versions (3.8, 3.9).

I did not know what happens with this users after a re-sync via cron job from Moodle to Azure. Maybe the missing user details will be synchronised and you do not have to change the user data manually, but I haven't tested it.

(1) Note: to prevent auto creation, you have to set "Prevent account creation when authentication (authpreventaccountcreation)" to YES (see Administration - Plugins - Authentication - Manage authentication).

**Comment by giselebrugger** [comment]
Hello @AntonT76 , 
Thank you so much for returning.
Thank you so much for returning
The creation of users in moodle is done automatically via synchronization with the academic management system and authentication with: oidc has already been set.
Thank you so much for this discovery. Helped me a lot.
The students were editing the names.
Now it's OK. I had edited base.php but didn't save it due to a file permission.

**Comment by jbriggscmet** [comment]
We're migrating from LDAP to Azure AD and haver just come across this. We lock all fields coming from LDAP, so users don't think there's an issue if they update their details in Moodle, only for them to be overwritten. This would be a really useful (possibly essential) enhancement for us.

**Comment by weilai-irl** [comment]
Hi all,

The next release of the plugins scheduled for September will include a change to move the field mapping settings from local_o365 to auth_oidc, and allow site admins to apply locking settings on fields, similar to what other auth types are able to do.

I'll update the issue again when this is available.

Regards,
Lai

**Comment by brianlmerritt** [comment]
Hi - moving field mappings would be very useful.  Any news on the plugin(s) update?

**Comment by weilai-irl** [comment]
Hi all,

The October 2021 release of the plugins contained a major change to move the field mapping feature from local_o365 to auth_oidc plugin, and as part of the change, site admins can now control the lock status of the profile fields in the configuration page of the auth_oidc plugin.

Please upgrade to the latest release to make use of the feature.

The feature request will be closed.

Regards,
Lai
