### ISSUE TITLE
Suspended users in moodle are not removed from their microsoft team

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1269]
In our moodle we use suspensions which leave a user technically enrolled, but unable to participate in the course. 

In this case they should not have access to the microsoft team but the local_o365 user sync does not check for this, it only looks for enrolled or unenrolled.

What we should do is make a new observer to watch for the user enrolment updated event, and check if the user was suspended or not. Then we can either remove from the microsoft team or add them. 

We should also include this check when first setting up the team of users. 

I will submit an initial untested PR for this to hopefully get some feedback, I'll be testing it as well soon.

**Comment by weilai-irl** [comment]
Hi @kristian-94 ,

The PR you created has been merged to the latest release for Moodle 3.7, 3.8 and 3.9. Thank you very much for your contribution. This issue will closed now.

Regards,
Lai
