### ISSUE TITLE
Teams customizaton in Moodle: webREST function and match existing Teams with Moodle courses

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1273]
For the creation of Teams in Microsoft Teams we use the possibility to create Teams in Moodle in the settings of the o365-Plugin (Sync Settings - Teams Customization - Enable Teams). We do it manually for several courses. Our Moodle Courses will be created automatically by our Campus Management System via webREST interface. We are looking for a possibility to create Teams also automatically via webREST, but I didn't find any function in Moodle for it.

We also have the opposite case: we have some existing Teams and try to match them to Moodle courses? Are there any possibilities to do this?

We are using Moodle 3.5, maybe some of this developments will exist in newer versions.

thanks, br Anton

**Comment by tristdac** [comment]
Hi Anton

Not really related to this plugin, but i think you **may** be able to retrospectively link existing Teams with existing Moodle courses using the Skooler Moodle app within Teams once configured. https://skooler.com/

**Comment by weilai-irl** [comment]
Hi @AntonT76,

local_o365 plugin make calls to the Microsoft Graph API to create teams. If you want your webREST interface to create Teams directly, your webREST interface needs to be extended to make calls to Microsoft Graph API directly to do so.

It is on our roadmap to introduce a new feature to local_o365 to allow site admins to link a Moodle course with an existing Team. This should be included in the next 2 - 3 releases (March or May 2021).

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @AntonT76,

In the latest release 3.9.4 and 3.10.1 of the plugins, a new feature has been introduced to allow site admins to connect a course with any existing Teams in the tenant. The feature can be found at "Microsoft 365 Integration" configuration page -> "Advanced" tab -> "Manage Team Connections" link.

Please upgrade your plugins and give it a try.

Regards,
Lai
