### ISSUE TITLE
Add Office Video to the Office 365 repository plugin

### ISSUE THREAD

**Issue by vinhub** [Microsoft/o365-moodle#128]
- The Office Video item should show up at the top level along with OneDrive / Sharepoint etc.
- Clicking on it should show all the channels that the logged in user has access to
- Clicking on a channel should show videos within that channel
- An upload button should show up if upload is allowed to that channel
- We should be able to upload large videos so the chunked version of the API will be needed
- When user clicks on a video the dialog that shows up should allow downloading the video if downloading is enabled for that video.

**Comment by number33** [comment]
I've removed this issue from the milestone as per instruction from sprint planning meeting.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/138

If Office video is enabled for the subscription, then a new folder will appear inside the Office 365 repository and you will be able to browse into the channels / videos there, select videos, download / upload them or add links to them etc. If you select a video and insert a link into a page or assignment, it will get converted into an embed code if the oEmbed plugin is also enabled.

You can also upload videos into Office 365 using the repository dialog. Note that videos are usually large so you have to increase the upload file size limit in php.ini. This needs to be done even if you don't intend to upload any videos to Moodle server because the way upload to Office 365 works is that the video file gets uploaded from the browser to Moodle server first (as a temp file) and then from there to Office 365.

**Comment by brentboghosian** [comment]
Vin,

I haven't been able to enable the Office 365 Video so it shows up in the repository.
What's the easiest way to configure this?

**Comment by vinhub** [comment]
Does your Iffice 365 subscription include Video? See if it shows upon the app launcher. It is not included in the cheapest subscription. If your subscription includes it then it should show up in the file picker without any extra config in moodle.

**Comment by brentboghosian** [comment]
I don't think so (?) ... from my Subscriptions page:

Licenses
Office 365 Enterprise E1
Microsoft Planner
Sway
Yammer Enterprise
Skype for Business Online (Plan 2)
SharePoint Online (Plan 1)
Exchange Online (Plan 1)

**Comment by vinhub** [comment]
Best to check if the Video app shows up in the app launcher. 
![image](https://cloud.githubusercontent.com/assets/1817329/16124711/e790ae0a-33a4-11e6-89d8-94211c90eedd.png)

**Comment by brentboghosian** [comment]
I've got it working now with Akin's assistance - thank-you.

**Comment by number33** [comment]
@vinhub Brent experienced an error with one of the test steps

> Attempting to Create alias/shortcut to the video fails, JavaScript console includes following error:
Load denied by X-Frame-Options: https://rldev.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=p&chid=83d624dd-bc53-4058-ab3f-d5a633444f46&vid=bc639cbb-fd96-45b1-82f4-dec099213e30 does not permit cross-origin framing.

Can you check if you are getting this error on your side as well?

**Comment by brentboghosian** [comment]
That was in FireFox ...
In Chrome the error message is:

Refused to display 'https://rldev.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?a…624dd-bc53-4058-ab3f-d5a633444f46&vid=bc639cbb-fd96-45b1-82f4-dec099213e30' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by brentboghosian** [comment]
@vinhub 
The code is in the wip-MSFTMPP-475-mXY (XY = 27, 28, 29, 30) branches and has some minor changes.

**Comment by vinhub** [comment]
@brentboghosian We haven't seen this error. Any repro steps? Are you creating an alias / shotrcut while inserting a link or while attaching an additional file?

**Comment by brentboghosian** [comment]
@vinhub 
Yes, 
- Create Assignment
- Add link in Assignment Description, 
- Browse repositories, (select) Office 365, (select) Office 365 Videos, select Community (channel/folder - site specific so different for others), select an existing video 
- Choose "Create an alias/shortcut to the file" ...
- Attempt to view the Assignment (with browser's developer tools enabled to view console)

**Comment by brentboghosian** [comment]
@vinhub 
Also, the same video(s) work fine if linked and all uploaded videos are playable from the portal.

**Comment by brentboghosian** [comment]
@vinhub 
- see: http://stackoverflow.com/questions/20498831/refused-to-display-in-a-frame-because-it-set-x-frame-options-to-sameorigin

**Comment by brentboghosian** [comment]
This setting is coming from: lib/weblib.php::send_headers();
 if (empty($CFG->allowframembedding)) {
        @header('X-Frame-Options: sameorigin');
 }
so let me test again with this config setting $CFG->allowframembedding set to true;

**Comment by brentboghosian** [comment]
@vinhub 
That doesn't appear to work either.
Here's the Moodle site & page this is occurring on: 
http://kwoffice.remote-learner.net:8480/gao27_o365/mod/assign/view.php?id=3&action&rownum=0&useridlistid=0

user/pw = admin/Test123!

**Comment by vinhub** [comment]
Are you logging in using Office 365 account or local account?

**Comment by vinhub** [comment]
We have discovered that there are 2 issues here.

1. The cross domain error: This is the error Brent has reported. I am able to repro it whenever the user isn't logged in to Office 365 (e.g. if they are using the connected account scenario). The issue does not repro if user logs in using their Office 365 account.  This link throws some more light on it: https://docs.moodle.org/30/en/Video (Look for "cross domain" in this page). 

I am able to repro this issue even with a simple HTML page. I have asked an Office Video developer about it and waiting for a response. But there may not be much we can do on this except asking people to sign in using Office 365.

2. Even after you log in using Office 365, if you are trying to insert a link into the Description field, and  have selected shortcut / alias (not link or copy), there is a problem. Since Moodle thinks that the shortcut is a video, its Media embedding filter maps it to the Moodle video player and that player can not play the video because it is pointing to a link in Office video. I have verified that if I turn off the Media embedding filter, then the alias will remain as a link and then clicking on it will take you to Office 365 and play the video fine. Any ideas how we can fix this? I assume we can not turn off the Media embedding filter. Any other suggestions?

One workaround for this is, when user inserts a shortcut / alias, rename the file to some other extension which then prevents the Media embedding filter to get invoked. And a better workaround is to insert Link instead of shortcut.

Note that this issue occurs only when you insert a link into the Description field. Not if you attach the video as an "additional file". In that case, the shortcut / alias will just take you to the Office video page in a separate tab.

**Comment by number33** [comment]
@vinhub can I close this issue or does it need to be added to the next milestone?

**Comment by petersercombe** [comment]
Hey, not sure if this is the right place to report this, but I've just upgraded to the latest release of the plugins and it's breaking things badly. Moodle 2.9.

Debugging seems to be pointing to a line of code in /local/o365/classes/rest/sharepoint.php, which seems to be related to the addition of video to the repository.

Full error is:

`Parse error: syntax error, unexpected '*', expecting ')' in /path/to/moodle/local/o365/classes/rest/sharepoint.php on line 983`

The result is that it breaks the file picker altogether = can't upload any files to any repository.

**Comment by brentboghosian** [comment]
@vinhub 
Appears to be the default value of the function being = 8192 * 1024
What version of PHP did this error occur on?

**Comment by brentboghosian** [comment]
@petersercombe 
Thank-you for your post, we have confirm the error and will have a fix released shortly.

**Comment by petersercombe** [comment]
@brentboghosian - Sounds good. I'm using php version 5.5.30 currently, upgrade scheduled for next week.

**Comment by number33** [comment]
Closing this issue. Create a new issue and continue the discussion for the parse error for PHP 5.5.x.  Thanks.
