### ISSUE TITLE
Add a "My Delve" link to the Microsoft block

### ISSUE THREAD

**Issue by vinhub** [Microsoft/o365-moodle#130]
"My Delve" has a lot of useful information so it would be good to include a link to it from the Microsoft block. This link looks like https://microsoft-my.sharepoint.com/_layouts/15/me.aspx?u=c71c5ae2-0e32-4cfc-81b6-ee25233c01f0&v=work. The "u" parameter in there is the user id that you can get from "https://graph.microsoft.com/v1.0/me" API.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/132

**Comment by vinhub** [comment]
We will update this PR with a fix for issue #139 also.

**Comment by number33** [comment]
Added this issue to Release 20160613 as the this pull request https://github.com/Microsoft/o365-moodle/pull/132 will be updated to include the fix for this issue.

**Comment by vinhub** [comment]
We will send a new PR that fixes this issue as well as #139

**Comment by vinhub** [comment]
PR with fix for this issue as well as #139: https://github.com/Microsoft/o365-moodle/pull/145
