### ISSUE TITLE
Getting Error local_o365\oauth2\token::instance local_o365\oauth2\token::get_for_new_resource:234: Cannot retrieve a token for the base resource. Data: (null)

### ISSUE THREAD

**Issue by bbusschots-mu** [microsoft/o365-moodle#1300]
I'm running the latest Moodle 3.5 LTS with the most recent version of the plugin for Moodle 3.5. When I enable AAD sync I am expecting to get a few thousand users over, but instead, I just get a hundred or so, even with full sync enabled, and with debugging turned on I find the following in the Moodle log:

```
local_o365\oauth2\token::instance local_o365\oauth2\token::get_for_new_resource:234: Cannot retrieve a token for the base resource. Data: (null)
```

How do I go about trouble-shooting this problem so I can get my users synced?

**Comment by avegys** [comment]
Hi Bart,

Microsoft has introduced 100 users limit per call for their API endpoint when trying to get full list of users. I would recommend to have only modified users sync and make scheduled task to run more often.

Best regards,
Andrius
