### ISSUE TITLE
Can the Master Branch be used with Moodle 3.5 LTS?

### ISSUE THREAD

**Issue by bbusschots-mu** [microsoft/o365-moodle#1301]
I'm running Moodle 3.5 (currently under Long-term-support from Moodle HQ). My Moodle instance is managed through GIT, and I have installed this suite of plugins as a GIT sub-module. I have bound the sub-module to the `MOODLE_35_STABLE` branch. I notice it is a long way behind the `master` branch, should I be using `master` rather than `MOODLE_35_STABLE`?

**Comment by avegys** [comment]
Hi Bart,

Unfortunately Master branch can not be used with Moodle 3.5 LTS. Moodle 3.5 is security-only-supported release. This is why it is not getting latest updates.

Best regards,
Andrius
