### ISSUE TITLE
Broken Teams link and icon in local/o365/groupcp.php

### ISSUE THREAD

**Issue by jamaur** [microsoft/o365-moodle#1302]
Hi, the link in local/o365/groupcp.php toward Teams is not valid (team.microsoft.com instead of teams.microsoft.com). The icon also appears to be broken. 

Made a pull request to apply the following patch: https://github.com/jamaur/moodle-local_o365/commit/4655f70fa5323036eb12d0112d79a75f2f33aaac

**Comment by weilai-irl** [comment]
Pull request is at
https://github.com/microsoft/moodle-local_o365/pull/30

**Comment by weilai-irl** [comment]
Hi @jamaur,

Thank you for your contribution. The fix has been included in the latest release for 3.8 and 3.9.

Regards,
Lai
