### ISSUE TITLE
Functionality request: allow configurable prefix for created Teams

### ISSUE THREAD

**Issue by jamaur** [microsoft/o365-moodle#1303]
Our organization has a need to have a prefix for all Teams that get created by the local_o365 plugin. I saw in the code that there is mention of the prefix, but it was not configurable and had a colon hard-coded.

I added the functionality and it's working in our environment (Moodle 3.8).

I'll make a pull request.

**Comment by bbusschots-mu** [comment]
This would be extremely useful as we run multiple Moodle instances, and it would be great to be able to clearly associate teams with specific instances.

**Comment by ecampbell** [comment]
Rather than a prefix, a better approach might be to define a name template with placeholders, to allow more flexibility, for example "{fullname} - XX{courseid}" or "XX{id} {idnumber} - {shortname}" to allow for prefixes or suffixes

**Comment by weilai-irl** [comment]
Hi @jamaur, @bbusschots-mu, @ecampbell,

This is to inform you that the latest version of the local_o365 plugin released today (3.9.3 for Moodle 3.9, and 3.10.0 for Moodle 3.10) introduced new settings to allow site admins to configure naming convention for Teams and groups. Please check it out.

@ecampbell, please liaise with with @nenorojas Oswaldo regarding upgrading the plugins on your site.
@bbusschots-mu, the feature is only added for Moodle 3.9 and 3.10. You can try it out once your side is upgraded.

I'll mark the issue as closed for now. Feel free to report issues back on this page.

Regards,
Lai
