### ISSUE TITLE
Manage tokens page maintenance_cleanoidctokens does not display token delete links

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1305]
We can find this page at moodle/local/o365/acp.php?mode=maintenance_cleanoidctokens

`Microsoft Office 365 Integration > Advanced > View maintenance tools > Cleanup OpenID Connect Tokens`

This is just a blank page but from the code we can see it should be displaying a list of all tokens that have a userid = 0 in `mdl_auth_oidc_token` 

Next to each line should be a link to delete the incorrect token.

For us `mtrace` does not output to the html page. We need to `echo` here:

https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/page/acp.php#L1318

**Comment by kristian-94** [comment]
Turns out we use a `mtrace` wrapper for this which is why it won't print. I'd still like to see this change to echo though so it will consistently work, I can't see a reason why it shouldn't be echo instead.

**Comment by weilai-irl** [comment]
@kristian-94 

Hi Kristian, I think the use of mtrace() is intentional. If you want to see the output, you can change the "Debug messages" setting in "Site administration" -> "Development" -> "Debugging".

**Comment by kristian-94** [comment]
@weilai-irl  Moodle has a feature that lets you wrap the `mtrace` function: https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L9185

Since this function can be customised, we shouldn't rely on it, when we always want to echo in the end anyway. In our case we ship mtrace logs to custom logging servers to run more fine grained log analysis, and never echo, which is a valid use case.

**Comment by weilai-irl** [comment]
Hi @kristian-94,

The manage tokens page will be upgraded in the upcoming June 2021 release, which will include an improved UI that doesn't use the `mtrace` function. This can be finally put in by then :)

Regards,
Lai
