### ISSUE TITLE
Error when trying to access Course Group folder when group hasn't been created yet

### ISSUE THREAD

**Issue by vinhub** [Microsoft/o365-moodle#131]
Steps:
- Navigate to some course for which  course group hasn't yet been created. 
- Try to add a File resource to that course.
- Content > Select files > Add file
- In the file picker, navigate to the Course group folder and click on it
- error:
- line 253 of /local/o365/classes/rest/o365api.php: moodle_exception thrown
- line 346 of /local/o365/classes/rest/unified.php: call to local_o365\rest\o365api->process_apicall_response()
- line 560 of /repository/office365/lib.php: call to local_o365\rest\unified->get_group_files()
- line 269 of /repository/office365/lib.php: call to repository_office365->get_listing_groups()
- line 100 of /repository/repository_ajax.php: call to repository_office365->get_listing()

![image003](https://cloud.githubusercontent.com/assets/1817329/15341162/00d4a2f6-1c42-11e6-86d2-282aaf60d4c6.png)
![image001](https://cloud.githubusercontent.com/assets/1817329/15341166/075598e2-1c42-11e6-8526-5abeb2333e10.png)
![image002](https://cloud.githubusercontent.com/assets/1817329/15341172/0d097c22-1c42-11e6-8652-a252237e4727.png)
![image004](https://cloud.githubusercontent.com/assets/1817329/15341179/11ee876e-1c42-11e6-9912-2bff878a98ae.png)

**Comment by rlcharles** [comment]
@vinhub I could not duplicate this using the latest release.

**Comment by jamesmcq** [comment]
@vinhub Can you still reproduce this with the current release? If so, please reopen/create a new issue.
