### ISSUE TITLE
Enhancement request: let teachers activate Teams integration themselves

### ISSUE THREAD

**Issue by jamaur** [microsoft/o365-moodle#1312]
We use the Teams Sync and have the create teams option set to "Customize", because we have over 2,000 courses per semester and don't want to create a new Team for each one. We also don't want to add a step for profs to have to call the support desk and ask for Teams to be activated.

I propose adding a link to the Microsoft Block that lets teachers activate or disable Teams integration. Basically, taking this page that is only available to admins :
![image](https://user-images.githubusercontent.com/280567/86933498-9613ca80-c108-11ea-8423-2cc71d607bf2.png)

and offering the same thing for teachers via the MS block:
![image](https://user-images.githubusercontent.com/280567/86933767-e723be80-c108-11ea-8a9c-1c15341dd4fa.png)

![image](https://user-images.githubusercontent.com/280567/86933885-0de1f500-c109-11ea-8dba-86598a26ff8b.png)

We have this in place on our end, with the caveat that we don't offer teachers the ability to enable / disable the Calendar or Conversations options, as our testing showed that those options caused a bit too much confusion. Just putting this here to see if there is any interest. To make things generic, I could add some settings to the o365 config when the "Customize" option is selected. 

Additional options may include: "Allow teachers to enable / disable Teams integration" and maybe a multi-select box to decide which of the 5 options teachers can change (Teams, Files, Calendar, Conversations, or Class Notebook).

**Comment by weilai-irl** [comment]
Hi @jamaur,

Thank you for your proposal. This does look a very solid feature request, and will try to deliver it in the next few releases in the coming months.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @jamaur, @jbriggscmet,

The feature requested in this issue has been implemented and included in the latest 3.9.4 and 3.10.1 release of the plugins:
 - A setting "Allow configure course sync in course" has been added to the "Course Sync" section in the "Sync Settings" tab of the "Microsoft 365 Integration" configuration page.
 - If the option is enabled, users with permission to be Team owner (having "local/o365:teamowner" capability in course context) will see a link to configure course synchronisation from the Microsoft block in the course.

Please upgrade the plugins and give it a try.

The issue will be closed for now, but feel free to re-open it or create new one if you see issues in the feature.

Regards,
Lai
