### ISSUE TITLE
Feature request: option for suspending user in use sync

### ISSUE THREAD

**Issue by ghost** [microsoft/o365-moodle#1318]
Currently there is the option to 'Delete previously synced accounts in Moodle when they are deleted from Azure AD'

![o365_delete_users](https://user-images.githubusercontent.com/57189646/87169727-65659980-c29e-11ea-8ed6-8e7401c88ec2.png)

Would it be possible to have users in Moodle suspended and not deleted when they are removed from Azure AD?

Thanks!

**Comment by swinster** [comment]
I literally had the same thought and wondered "why isn't this a thing". Thanks for coming up with it fist @daniel-hefley

**Comment by swinster** [comment]
Hmm, there was this issue raised and closed back in 2016! https://github.com/microsoft/o365-moodle/issues/172

**Comment by nenorojas** [comment]
Hi @daniel-hefley  and @swinster,

This is how it works at this moment:

https://github.com/microsoft/o365-moodle/issues/272#issuecomment-629294564

Deleted users who are in the deleted users list in Azure will be suspended. Those users who are permanently deleted from Azure, first of all will be suspended with the first usersync scheduled task run (if they were not yet) and with the next usersync scheduled task run those suspended users will be deleted from Moodle.
By default this scheduled task runs once a day at 1 am. In such case, permanently deleted users first will be suspended if they were not suspended yet and suspended users will be deleted from Moodle.

Please let us know if this is working as expected.

Regards

Oswaldo

**Comment by daniel-hefley** [comment]
Hi @nenorojas,

Thank you for the clarification. This issue initially arose when a client of ours removed users from Azure and they were immediately deleted in Moodle during the next sync. I will do some testing to confirm that it is working as you describe. What we were hoping for was an option in Moodle to "Suspend previously synced accounts in Moodle when they are deleted from Azure AD". 
Again, thanks for your reply and the improvements y'all are making to this suite of plugins.

**Comment by mmulrthelp** [comment]
It suspending the delete AAD user as mentioned (which is brilliant), it just doesn't then go that one step further and remove them from Moodle. I get the following reported in the 'Sync users with Azure AD' scheduled task always at the end of the run and it crashed out when it cannot delete the first found user:

...... Checking deleted users list...
......... Could not find suspended user xxxxxxxx@xxx.ac.uk in Azure AD. Deleting user...
...... Sync process finished.
... used 1077 dbqueries
... used 9.0847370624542 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\task\usersync) 

As @daniel-hefley says if these two parts could be separate settings in 'Microsoft Office 365 Integration' 'Sync Settings' tab, that would be excellent. One to suspend and one to delete

**Comment by AntonT76** [comment]
Dear @nenorojas 
we also have the same issue "Suspend previously synced accounts in Moodle when they are deleted from Azure AD".

For us it is not very usefull, if a deleted User in Azure AD will automatically deleted in Moodle. Users should only be "suspended", because we have other rules for deleting users in Moodle than in Azure AD.

We hope that this option will be implemented in a future version of the plugin.

br, Anton

**Comment by weilai-irl** [comment]
Hi all,

This change request has been implemented in the latest release of the plugin for Moodle 3.9 and 3.10.

The following changes were made:
 - The old user sync option of "Delete previously synced accounts in Moodle when they are deleted from Azure AD" is now replaced with two options:
   - Suspend previously synced accounts in Moodle when they are deleted from Azure AD
   - Delete previously synced accounts in Moodle when they are deleted from Azure AD (requires "suspend" option above)
 - If the first one is enabled, running the user sync task will suspend deleted Azure AD user in Moodle, as before.
 - If only the second one is enabled, no Moodle user will be suspended or deleted.
 - Only if both options are enabled, the Moodle account will be deleted, providing the account is not in the list of recently deleted users like (30 days after user deletion).

Please check out the code and try the feature out.

Regards,
Lai
