### ISSUE TITLE
Teams Moodle Tab SSO

### ISSUE THREAD

**Issue by ArtAcademyofCincinnati** [microsoft/o365-moodle#1319]
Not sure if this is even possible, but when navigating to the Moodle tab, users must sign in initially as well as after a period (session token expires?).  Anyway around this?

**Comment by weilai-irl** [comment]
Hi @ArtAcademyofCincinnati,

SSO login should work in browsers for Teams web app. On desktop apps, you will need to login once, and it should remember you from then on.

Regards,
Lai

**Comment by ArtAcademyofCincinnati** [comment]
Indeed, SSO works for web app version, but the desktop app does require signing in again after some time.  Not a a deal breaker, just annoying, especially on mobile.

**Comment by weilai-irl** [comment]
Hi @ArtAcademyofCincinnati,

Thank you for your confirmation. I'm afraid this is the best SSO experience that Teams can provide with the current Teams tab SSO workflow. FYI, we constantly checking on the Microsoft documentation on Teams tab SSO, and update our implementation if new approach to provider better user experience is made available.

I'll close the issue for now.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @ArtAcademyofCincinnati, 

A updated implementation of Teams and Moodle SSO has been included in the latest release of the plugins for 3.8 and 3.9. Configuration changes are required, so please follow steps in the release note. In our test, it hugely the SSO experience a lot.

Regards,
Lai
