### ISSUE TITLE
Unable to Login to OneDrive via Moodle Tab in Teams Desktop App

### ISSUE THREAD

**Issue by ArtAcademyofCincinnati** [microsoft/o365-moodle#1320]
When attempting to sign in to access OneDrive from the Moodle tab, I get an error referencing this page https://docs.moodle.org/38/en/error/moodle/invalidsesskey with several troubleshooting steps.  None of these steps apply for our instance.

**Comment by nenorojas** [comment]
Hi @ArtAcademyofCincinnati,

Can you please provide the steps so we can try to reproduce this issue? 
Are you already logged in to Moodle using auth_oidc?
Have you added the Microsoft block to any page and tried to access Onedrive from the link available there?

Regards

![image](https://user-images.githubusercontent.com/3680797/87400384-a4eaf900-c5b0-11ea-88dd-3f96d336a570.png)

**Comment by ArtAcademyofCincinnati** [comment]
The steps are pretty straight forward:

- Use the 
- Using the desktop app, attempt to access OneDrive to submit a file for an Assignment
- Doesn't matter if already signed in or not to Moodle or to O365, same error.

We can't add the Microsoft block into an Assignment, so not sure what you want me to do there for testing.  The Microsoft block works fine in general when used in other parts of the site, though they're just links essentially.

**Comment by nenorojas** [comment]
Hi @ArtAcademyofCincinnati 

Are you trying to upload the file from repository_office365 or from Moodle core Onedrive repository?

![image](https://user-images.githubusercontent.com/3680797/87687307-7e2ded80-c77d-11ea-9f92-423ad4b67d81.png)

I could only reproduce the error via Moodle core repository, that's not part of Office 365 suite of plugins:

![image](https://user-images.githubusercontent.com/3680797/87687725-f98f9f00-c77d-11ea-942f-07a80273c088.png)

Regards

Oswaldo

**Comment by ArtAcademyofCincinnati** [comment]
Ah, was not aware of the Office365 repository.  That one worked.  I was under the impression, after reading about it, the local_o365 plugin installed all the necessary items, but that repository wasn't present in our list of available ones, so I had to manually install that one.

**Comment by nenorojas** [comment]
Hi @ArtAcademyofCincinnati 

There's indeed some confusion regarding which Onedrive repository to use, Moodle core one came earlier and requires Moodle core Oauth2 service in order to work (but even with service created the issue above happens). 
Repository Office 365 was developed later to work with OpenID. 
The plan for the moment is to bring this feature #1220  that is missing and after that core onedrive repository should be fully replaced by Office 365 repository.

Regards
