### ISSUE TITLE
Unable to sync less than full AAD

### ISSUE THREAD

**Issue by ngdngd** [microsoft/o365-moodle#1321]
Hi,

The default provisioning user (User sync) is taking everything in AAD, users, meeting rooms, etc everything. What if we want to reduce the scope to only users (ideally only Active users and not disable ones)?
Seems there is no clear option to choose users from a Group, any other solution?

**Comment by nenorojas** [comment]
Hi @ngdngd ,

There's a presentation and sample video in this page showing how to sync only a specific group of users from AD to Moodle:

https://enovation.ie/moodle-and-microsoft-office-365-integration/
https://youtu.be/5eojkIs8HeY?list=PLwy6L92VmGgnykLBOhIsp1g6i0kijVA2n

Please give it a try and let us know if it worked or not.

Regards
