### ISSUE TITLE
Legacy API checks still littered around, breaking Unified access

### ISSUE THREAD

**Issue by gormster** [microsoft/o365-moodle#1323]
We've just noticed an issue where user field mapping doesn't occur on login, even if configured to do so. The reason? `local_o365\obj\o365user` does not consider a user to be an O365 unless they have a token for the `azuread` resource. That resource is, of course, `https://graph.windows.net` - not `https://graph.microsoft.com`, the unified API resource. The `azuread` API is referred to in the plugin settings as the "legacy API".

In most other respects, the unified API works equally to the legacy API. However, there's still hard-coded references to `azuread::get_resource()` in:

* `local_o365\utils::limit_to_o365_users` (1 caller)
* `local_o365\obj\o365user::instance_from_muserid` (8 callers)

The former is a pretty limited case, just managing sharepoint access sync - though it should, of course, actually work as intended. The latter is pretty nasty - it's referenced in these vital functions:

* `local_o365\utils::is_o365_connected`
* `local_o365\utils::get_o365_upn`
* `local_o365\observers::get_additional_user_info`
* `local_o365\feature\usersync\main::assign_photo`

And, perhaps most bizarrely, `local_o365\rest\unified::get_muser_upn`, meaning that the unified API itself is requiring that a user have a token for the legacy API resource; surely, this function can never actually work?

I'm happy to write a patch fixing this issue; I don't think doing so is difficult. However, the fact that testing hasn't caught this yet is a bit worrying, isn't it? This is huge chunks of the plugin completely broken. I'm no expert at writing tests, and this feels like the kind of thing an official plugin should have covered… could the plugin maintainers write some tests covering these cases?

**Comment by cbrherms** [comment]
Has there been any luck/progress with this one?

**Comment by s4mpl3d** [comment]
Is there any progress on this issue?

**Comment by weilai-irl** [comment]
The use of legacy APIs are finally removed from the plugins in the latest release for Moodle 3.11 and 4.0.

I'm going to close this issue.
