### ISSUE TITLE
AD User Sync errors

### ISSUE THREAD

**Issue by CarrieNZ** [microsoft/o365-moodle#1326]
similar to issue #1324, we upgraded to Moodle v3.7.7 last night and took our O365 plugin version up to 3.7.0.7.

Everything appeared fine until we re-enabled the AD User Sync task and since then the logs have been full of API errors and token errors.  Initial user sync errors:

Usersync error:
`Could not assign user "******" Reason: Error in API call: Invalid version: ********`

Debug log showing cli error (among MANY web errors) :
local_o365\rest\azuread::assign_user:304: Error response received. Data: Array ( [code] => ResourceNotFound [message] => Invalid version: *****.onmicrosoft.com [innerError] => Array ( [date] => 2020-07-24T03:09:11 [request-id] => *******) )

Users now reporting "could not refresh token" when attempting to login.

All statuses green through both Moodle and Azure, our team are down to looking at the plugin code as we've drawn blank on any obvious issues.... HELP!!!

**Comment by weilai-irl** [comment]
Hi @CarrieNZ ,

First of all, I confirm the latest release doesn't contain any change in the "assign user to application" feature. There is a big chance that this particular error (not the user login one) existed before. Please see my latest note in issue #1324 as it contains a pull request that might be related to this issue.

For the user sign in issue, please try the "Cleanup OpenID Connect Tokens" feature in plugin settings -> "Advanced" tab -> "View maintenance tools" page. It will clear tokens and would resolve most user login issues in our experience.

Regards,
Lai

**Comment by CarrieNZ** [comment]
Thank you Lai, we made the the code change and ran a full sync, this has resolved the application assignment issue, we're no longer receiving the API errors.

I've removed the tokens as suggested, I don't have an account to test with and will have to wait for our IT team to assist with that.  I'll report back tomorrow to confirm if it's been resolved.

**Comment by weilai-irl** [comment]
Hi @CarrieNZ ,

Could you confirm if the login issue has been resolved for users please.

Regards,
Lai
