### ISSUE TITLE
School Data Sync broken

### ISSUE THREAD

**Issue by cbrherms** [microsoft/o365-moodle#1330]
I've commented on another issue but not sure if what i'm seeing is directly related.

From the looks of it, for an unknown amount of time (at least for the last month), school data sync appears to no longer be working.
We only really use SDS for initial course creation from our SRS, hence it not being an issue until now.

Looking at the logs, the issue seems to be in the user token creation for the task:

```
Execute scheduled task: Sync with SDS (local_o365\feature\sds\task\sync)
Could not construct system API user token for SDS sync task.
Could not construct API client for SDS task, so exiting.
... used 0 dbqueries
... used 0.022874116897583 seconds
Scheduled task complete: Sync with SDS (local_o365\feature\sds\task\sync)
```

Though this also does show up in the logs as a success, which i believe is incorrect due to the token failure and nothing running.

Current installed version of the plugin suite is 3.7.0.7, but as previously stated this has been a thing for at least the last month of logs so assuming it was introduced in a previous version.

**Comment by cbrherms** [comment]
To update:

Reauthenticated the System API User (even though we have Application access set), and this has affected the sds sync task.
Rather than erroring instantly, it now runs though a few schools that are set in SDS.

Error is now:

```
Execute scheduled task: Sync with SDS (local_o365\feature\sds\task\sync)
... Skipped SDS school 102a6a13-2e67-45fa-9d56-b2b1021ad780 because we received an error from the API
... Skipped SDS school e2a47557-b77f-46ac-a120-ea7ef09b0591 because we received an error from the API
... Skipped SDS school 900294ac-e811-4644-8029-6807d3ca96f5 because we received an error from the API
... used 2 dbqueries
... used 18.621521949768 seconds
Scheduled task complete: Sync with SDS (local_o365\feature\sds\task\sync)
```

Further to this, the SDS tab in the integration config page now takes longer to load (as it previously did), leading me to believe it is actually connecting but unable to pull down the info.
When the page loads, it still states that there are no schools available to sync.

**Comment by cbrherms** [comment]
SUCCESS!!

Issue has been introduced in the following commit https://github.com/microsoft/o365-moodle/commit/71cbf3f97fe1aeb18665b3f158d08fea4973fa84#diff-132d13bb921307b89caaaebc5d8ebaa9

Specifically the change from graph.windows.net to graph.microsoft.com local/o365/classes/rest/sds.php

I'm assuming that the SDS task has not yet been updated with the new request format?

For my own instance, commenting out the change and re-adding the previous line fixed the SDS functionality. 
I believe the other issue I had was related to the old application key expiring a few months ago, and upon having been renewed the system api user needed updating/reauthenticating.

**Comment by cbrherms** [comment]
Any news on whether there will be any further work on this to get it operational again?

**Comment by nielsenb2981** [comment]
cbrherms, I did get SDS working again with some additional features as well but that was at the start of the year and I haven't tried it since - there have been a lot of commits since then so for all I know my code no longer works.
https://github.com/bradnielsen2981/o365-moodle
I created a lot of additional options around the SDS as well, one of them being the creation of Cohorts and/or Classes.

**Comment by cbrherms** [comment]
@nielsenb2981 
Aye, did see that, and appreciate the work put in there. Plan to do a comparison at a later date to see if I can implement that on ours.
For myself, i just switched back to graph.windows.net so as to get the course creation and enrolments sorted. Also changed the tutor assigned role to editingteacher so as to fall in line with other plugins we use that are looking for that role.

I'll definitely have to have a proper look at how you implemented cohorts as that's something we'd wanted to try a while ago without success, and I know others would be wanting if it can be managed centrally.

**Comment by gd5t** [comment]
We would also be interested in seeing this resolved. 

@weilai-irl 
"This is partially due to the relatively low uptake of the SDS sync feature in Moodle"
The uptake might be a lot higher if the option would be fonctionnal at the beginning of the school year!

Thanks.

**Comment by weilai-irl** [comment]
Hi all,

FYI, there will be a major upgrade for the SDS integration feature in the upcoming December release, and the biggest change will be to use the Graph API instead of the legacy SDS API. As a result, the feature will not depend on System API user connection method any more, and will be able to work only on application access connection method.

More details will be made available in the release note.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

We have just made a release (3.9.8, 3.10.5, and 3.11.2) of the plugins which contains major changes in the SDS feature. Please refer to documentation at https://docs.moodle.org/311/en/Microsoft_365#School_Data_Sync_.28SDS.29 for feature details.

I'll keep the issue open for another month, and close it if no more issue is reported.

Regards,
Lai
