### ISSUE TITLE
Problem with Moodle Teams App

### ISSUE THREAD

**Issue by archimod95** [microsoft/o365-moodle#1332]
I follow all the guide, but when I try to add the app to a channel, it shows me the next nessage

It looks like the webpage at https://x.x.x.x/local/o365/teams_tab_configuration.php might be having issues, or it may have moved permanently to a new web address.

Any one can help on this issue?

**Comment by weilai-irl** [comment]
Hi @archimod95,

Could you clarify what's the wwwroot of your Moodle site please? And what happens if you go directly to the link https://x.x.x.x/local/o365/teams_tab_configuration.php?

Regards,
Lai
