### ISSUE TITLE
Roles used by School Data Sync and Teams creation do not match

### ISSUE THREAD

**Issue by cbrherms** [microsoft/o365-moodle#1333]
One thing i've come to notice recently while setting up for the new year is that the roles assigned when using the school data sync feature do not match up with those that the teams integration are looking for.

When a course is created by SDS, it assigns the "manager" role in moodle to whoever is listed as a teacher on that course/section in SDS.

https://github.com/microsoft/o365-moodle/blob/cf4184da56a167734070a6cf880a426e8615d6a3/local/o365/classes/feature/sds/task/sync.php#L67

But, if you are then also using the Teams feature to create the teams for you when you are ready, it is looking for people on the course with either editingteacher or teacher as role.

https://github.com/microsoft/o365-moodle/blob/cf4184da56a167734070a6cf880a426e8615d6a3/local/o365/classes/feature/usergroups/coursegroups.php#L620-L622

SDS should assign editingteacher role instead to line these up, other wise roles will have to be manually added to enable the teams to be created properly

**Comment by weilai-irl** [comment]
Hi @cbrherms,

FYI, there will be a major upgrade of the SDS integration feature in the upcoming December release of the plugins. Notably, the feature will be using the Graph APIs and will not depend on System API user connection method any more. New settings are added to allow site admins to choose student and teacher roles when syncing enrolments too.

More details will be made available in the release note.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @cbrherms,

We have just made a release (3.9.8, 3.10.5, and 3.11.2) of the plugins which contains major changes in the SDS feature. Please refer to documentation at https://docs.moodle.org/311/en/Microsoft_365#School_Data_Sync_.28SDS.29 for feature details.

I'll keep the issue open for another month, and close it if no more issue is reported.

Regards,
Lai
