### ISSUE TITLE
Error during sync

### ISSUE THREAD

**Issue by Randomix** [microsoft/o365-moodle#1334]
Hi,
I'm getting the following error while the AD sync is running causing the sync not to fully complete:

......... Updating Moodle user data from Azure AD user data.

Warning: Error while sending QUERY packet. PID=22610 in /var/www/testmoodle/lib/dml/mysqli_native_moodle_database.php on line 1246
!!! Exception - Argument 2 passed to local_o365\feature\usersync\main::apply_configured_fieldmap() must be an instance of stdClass, boolean given, called in [dirroot]/local/o365/classes/feature/usersync/main.php on line 583 !!!

Debug info:
Error code: generalexceptionmessage
Stack trace: * line 341 of /local/o365/classes/feature/usersync/main.php: TypeError thrown
* line 583 of /local/o365/classes/feature/usersync/main.php: call to local_o365\feature\usersync\main::apply_configured_fieldmap()
* line 781 of /local/o365/classes/feature/usersync/main.php: call to local_o365\feature\usersync\main->update_user_from_aaddata()
* line 171 of /local/o365/classes/task/usersync.php: call to local_o365\feature\usersync\main->sync_users()
* line 157 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\usersync->execute()

Fatal error: Uncaught coding_exception: Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
/var/www/testmoodle/admin/tool/task/cli/schedule_task.php on line 142

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory->get_lock(Resource id #621);
 $lock->release();  // Locks must ALWAYS be released like this.

 in /var/www/testmoodle/lib/classes/lock/lock.php:117
Stack trace:
#0 [internal function]: core\lock\lock->__destruct()
#1 {main}
  thrown in /var/www/testmoodle/lib/classes/lock/lock.php on line 117

Moodle Version: 3.8.4
OpenID Connect - auth_oidc - version 3.8.0.3 (2020020303)

**Comment by Randomix** [comment]
There is around 40,000 users that Moodle is trying to sync in one go. Can Moodle do this in smaller batches?

**Comment by Randomix** [comment]
So after some tweaking, I have managed to get all users to sync but I had to change the wait_timeout variable to around 50 minutes in my.cnf

It looks like the database connection doesn't automatically re initialise after dropping causing the sync to fail.

**Comment by webframp** [comment]
> There is around 40,000 users that Moodle is trying to sync in one go. Can Moodle do this in smaller batches?

I've been searching for a way to do a more controlled user sync as well. I have 10s of thousands of users and a sync will always seem to timeout right now

**Comment by weilai-irl** [comment]
Hi @Randomix and @webframp,

I confirm there are two issues in this issue:
1. The user sync scheduled task times out when processing large number of users.
2. A bug in the user sync task implementation itself, causing the error "Exception - Argument 2 passed to local_o365\feature\usersync\main::apply_configured_fieldmap() must be an instance of stdClass, boolean given.".

Both issues have been addressed in the latest release 3.9.4 and 3.10.1 of the plugins. Please upgrade the plugins to try them out.

I'll close the issue for now, but feel free to re-open if the issue reported still happens.

Regards,
Lai
