### ISSUE TITLE
Feature request: alternate logout URL option in auth_oidc

### ISSUE THREAD

**Issue by kristian-94** [microsoft/o365-moodle#1336]
It is useful to redirect a moodle user to a specific endpoint after they log out so that they can be logged out of not only their moodle session but also their IdP.

The saml2 plugin has this functionality for example. https://github.com/catalyst/moodle-auth_saml2/blob/master/auth.php#L893

I will be submitting a tested pull request for this feature.

**Comment by weilai-irl** [comment]
@kristian-94,

A different approach using observers was included in the release last week. I'll close this one.

Thank you for your contribution.

Regards,
Lai

**Comment by nbartley** [comment]
@weilai-irl For users who are using the oidc plugin for non-office 365 systems (because it works better than the moodle built in stuff), that logout feature is still required. Can it be reconsidered for inclusion?
