### ISSUE TITLE
Assumptions about roles in finding teachers

### ISSUE THREAD

**Issue by sharpchi** [microsoft/o365-moodle#1340]
This adds to #1333 
You have a function (get_teacher_ids_of_course - local/o365/classes/feature/usergroups/coursegroups.php) that gets teachers for a course, and uses the editingteacher and teacher shortnames, but this misses situations where those shortnames either have changed, or other teaching roles have been added.

A better way would be to use the archetype field in the role table.

**Comment by weilai-irl** [comment]
Hi @sharpchi,

I confirm this is a known issue and is tracked in #1235. A fix using capability check will be included in the next release, expected in September.

Regards,
Lai

**Comment by weilai-irl** [comment]
Capability checks are now used to determine team ownerships.
