### ISSUE TITLE
Moodle page is not displayed on Teams tab

### ISSUE THREAD

**Issue by lcchelpdesk** [microsoft/o365-moodle#1343]
We are setting up Moodle integration with Office 365 environment. All operations are done on a domain computer with SSO enabled. When we try to open Teams Moodle App tab in course synchronized with teams it shows this type of errors below. If I try logging in to Moodle through OpenID in a different browser tab, the tab on web based teams page starts showing Moodle content after refreshing it. We set an option to always allow displaying through iframe on Moodle's web server, but this, I think, comes from Microsoft directly. Here are example of errors:
Firefox error:
`Firefox Can’t Open This Page. 
To protect your security, login.microsoftonline.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.`
Chrome error:
`login.microsoftonline.com refused to connect.`

The Teams Moodle App tab is not displayed completely in when viewing on teams App.
Microsoft Office service support directed us to post an issue here on GitHub.
Does this behavior appear by design or we did something terribly wrong while configuring our integration instance?

P.S.: we are running Moodle 3.9 and latest set of plugins:
atto_teamsmeeting_moodle38_2020032701
auth_oidc_moodle39_2020071500
block_microsoft_moodle39_2020071500
filter_oembed_moodle39_2019112600
local_o365_moodle39_2020071500
local_office365_moodle39_2020071500
repository_office365_moodle39_2020071500
theme_boost_o365teams_moodle39_2020071500

**Comment by weilai-irl** [comment]
Hi @lcchelpdesk, 

The 2 most probable reason for the errors are:
1. Your browser is not configured to accept third party cookie. Please enable it and try again.
2. Your Moodle needs to be configured to allow "Frame Embedding", which is a setting in the "HTTP security" section.

Please give it a try and see if it solves the issue.

Regards,
Lai
