### ISSUE TITLE
Create Microsoft 365 groups without creating Teams

### ISSUE THREAD

**Issue by jbriggscmet** [microsoft/o365-moodle#1345]
We are in the early stages of investigating integration of Moodle with Microsoft 365 services. Our initial requirements are to allow creation of Teams based on Moodle courses as an opt-in.

Currently the plugin requires that either all Moodle courses are automatically created as Teams ("All Features Enabled"), or an administrator has to manually choose which courses to synchronise ("Customize"). Both of these are non-starters; we have thousand of courses that we don't want in Teams, and we can't add extra pressure on our service desk to manually select which courses to generate Teams for. The options I can think of are:

1. This plugin just creates Microsoft 365 groups for all courses, without creating the Team as well. Users in Teams can then create a Team from an existing Microsoft 365 group:

![image](https://user-images.githubusercontent.com/15365068/90040795-4c4a7100-dcc0-11ea-9791-0e993c0bd9c4.png)

2. Users can create Teams using the Microsoft block (change request already covered in issue #1312 )

Are there any known workarounds for this issue? Option 1 seems like there could be a quick fix.

**Comment by weilai-irl** [comment]
Hi @jbriggscmet,

Thank you for raising the request. I completely understand the request, and the approaches proposed.

We actually had some internal discussions about the possibility to give the control of teams creation to teachers, and we agreed that the best approach would be the proposal made in #1312. We hope to deliver it in the next 2-3 releases in the coming months.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @jbriggscmet,

Please see my comments at https://github.com/microsoft/o365-moodle/issues/1312#issuecomment-808261706.

Regards,
Lai
