### ISSUE TITLE
User sync will not synchronise all users

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1350]
since a few weeks we have serious problems with the synchronization of users from Azure to Moodle (version 3.5). Synchronising stops after about 80-90% of users (eg: 7500 users of 9200 users where synchronised). We testet it with many other settings, but without success:
- restarting synchronisation several times in a row (there will be synchronised only 100 users. It is strange, but well-known that only one hundred users are synchonised in one synchronising process, so you have to start the synchronising process several times in a row to get all the users synchronised)
- change from full sync to delta sync has no impact
- new users in Azure will not be created in Moodle (we have to create new users manually, so that's the only way that users can login in Moodle).

The output of cron job:

```
Execute scheduled task: Synchronisieren Sie Benutzer mit Azure AD. (local_o365\task\usersync)
...... Starting sync
...... No skiptoken (full) stored.
...... Forcing full sync.
...... Contacting Azure AD...
...... Error in full usersync: No token available for usersync
...... Resetting skip and delta tokens.
...... Got response from Azure AD
...... Clearing skiptoken (full) (none received)
...... No users received to sync.
...... Sync process finished.
... used 2 dbqueries
... used 0.09303092956543 seconds
```

We also did some tests in a Moodle Test Environment (version 3.5):

- download newest o365-Plugin for Moodle 3.9
- extract /loal/o365/classes/task/usersync.php --> there are some differences between usersync.php for Moodle 3.5 und Moodle 3.9
- exchange usersync.php (V3.5) to usersync.php (V3.9) in our Moodle Plugin directory
- restart synchronisation (full sync)

The outcome was that Moodle first only synchronised 7500 users, after next synchronisation all the 9200 users where synchronised. It seems to be that there is a problem with synchronising in 100-steps, maybe with skiptoken (full/delta). As far as I know synchronising in o365-plugin for Moodle 3.9 has no restrictions to the number of users --> a full sync will synchronise all users - no matter if the number of users is 500 or 5000.

I hope this is the solution for the problem. Maybe other users have the same problem or can confirm that they have used this solution. We are not able to update from 3.5 to 3.9 at the moment and the user sync is really a major problem for us. I would appreciate it if this change would also be implemented in the version for 3.5 and up to 3.8.

best regards, Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

First of all, while I understand your situation, I don't think copying some files from v3.9 to v3.5 version of the plugins is safe. There's certainly no guarantee that this will work.

For the issue itself, I think the limit on how many users to process in each usersync task run has been removed. I can't find this limit in the latest version of the local_o365 plugin for Moodle 3.9. This should mean that Moodle will try to sync all users in one go in a full sync.

I do remember there was a limit on the number of users to sync in each run before, but I can't find this logic in the code any more.


The error message you attached contains an error "No token available for usersync" . This may be related to the app token thing that I commented in the other issue you reported. Please take a look and see if the solution mentioned in that one solves this issue.

Regards,
Lai

**Comment by AntonT76** [comment]
Hi @weilai-irl ,
thanks for help. I will try to follow you advice on the other issue [https://github.com/microsoft/o365-moodle/issues/1357](https://github.com/microsoft/o365-moodle/issues/1357). We are also planning an update to 3.9 in the next weeks, we hope that will also solve our problems.
br, Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

Could you confirm if this is still an issue please.

Regards,
Lai

**Comment by AntonT76** [comment]
Dear @weilai-irl 
sorry for the late reply. The update to 3.9 has solved the problem.
br, Anton

**Comment by weilai-irl** [comment]
@AntonT76,

Hi Anton,

Thank you for your confirmation. I'll close the issue now.

Regards,
Lai
