### ISSUE TITLE
auth_oidc - failing PHPUnit test 

### ISSUE THREAD

**Issue by aspark21** [microsoft/o365-moodle#1351]
Moodle: 3.9.1
auth_oidc: latest MOODLE_39_STABLE

auth_oidc_oidcclient_testcase::test_creds_getters_and_setters
    ArgumentCountError: Too few arguments to function auth_oidc\oidcclient::setcreds(), 4 passed in /var/www/html/auth/oidc/tests/oidcclient_test.php on line 58 and exactly 5 expected
  
    /var/www/html/auth/oidc/classes/oidcclient.php:62
    /var/www/html/auth/oidc/tests/oidcclient_test.php:58
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80
  
    To re-run:
     vendor/bin/phpunit "auth_oidc_oidcclient_testcase" auth/oidc/tests/oidcclient_test.php

**Comment by weilai-irl** [comment]
The latest release contains fix to the unit test.
Issue closed.
