### ISSUE TITLE
 local_o365 - 3.9 PHPUnit errors -  Undefined index: emailsync

### ISSUE THREAD

**Issue by aspark21** [microsoft/o365-moodle#1352]
Moodle: 3.9.1
local_o365: latest MOODLE_39_STABLE

 5) local_o365_usersync_testcase::test_sync_users_create
    Undefined index: emailsync
  
    /var/www/html/local/o365/classes/feature/usersync/main.php:672
    /var/www/html/local/o365/tests/usersync_test.php:305
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80
  
    To re-run:
     vendor/bin/phpunit "local_o365_usersync_testcase" local/o365/tests/usersync_test.php
  
    6) local_o365_usersync_testcase::test_sync_users_delete
    Undefined index: emailsync
  
    /var/www/html/local/o365/classes/feature/usersync/main.php:672
    /var/www/html/local/o365/tests/usersync_test.php:344
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by weilai-irl** [comment]
The latest release contains fix to the unit test.
Issue closed.
