### ISSUE TITLE
local_o365 - PHPUnit broken test case - graph API change

### ISSUE THREAD

**Issue by aspark21** [microsoft/o365-moodle#1353]
Moodle: 3.9.1
local_o365: latest MOODLE_39_STABLE

 local_o365_coursegroups_testcase::test_resync_group_membership
    Failed asserting that two arrays are equal.
    --- Expected
    +++ Actual
    @@ @@
         0 => Array (...)
         1 => Array (...)
         2 => Array (
    -        'url' => 'https://graph.microsoft.com/beta/groups/testgroupobjectid/members/$ref'
    +        'url' => 'https://graph.microsoft.com/v1.0/groups/testgroupobjectid'
             'options' => Array (
    -            'CURLOPT_POST' => '1'
    -            'CURLOPT_POSTFIELDS' => '{"@odata.id":"https:\/\/graph...ser0"}'
                 'CURLOPT_USERAGENT' => 'Moodle-groups-2020071500'
    +            'CURLOPT_HTTPGET' => 1
             )
         )
    +    3 => Array (...)
    +    4 => Array (...)
    +    5 => Array (...)
    +    6 => Array (...)
     )
  
    /var/www/html/local/o365/tests/coursegroups_test.php:247
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80
  
    To re-run:
     vendor/bin/phpunit "local_o365_coursegroups_testcase" local/o365/tests/coursegroups_test.php

**Comment by weilai-irl** [comment]
The latest release contains fix to the unit test.
Issue closed.
