### ISSUE TITLE
System API User: no token to communicate - resetting the system API User will not work

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1357]
Hello,
we have some major problems with synchronising users from Azure to Moodle (no users will be synchronised). In the plugin settings of o365 we did a health check. The output is:

```
System API User
Moodle does not have a token to communicate with Office 365 as the system API user. This can usually be resolved by resetting the system API user.
Click here to fix
```

Our Azure Admin tried to fix it, but without success. All settings for the system API users seem to be correct.

The output of Moodle log files (API-Error):
```
usersync task: No token available for usersync Data: Array ( [file] => /data/moodle-source/instanzen3513_dev/local/o365/classes/feature/usersync/main.php [line] => 79 [message] => No token available for usersync ) 
local_o365\oauth2\token::instance local_o365\feature\usersync\main::construct_user_api:77: Cannot retrieve a token for the base resource. Data: (null)
```

We are using Moodle 3.5 and the o365-Plugin set (also 3.5). Does anyone know how we can fix this problem? Maybe there are some tricks in Moodle or some special settings in Azure for the system API user?

thanks, best regards
Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

First of all, let me clarify that the version of the plugins for Moodle 3.5 is out of support, so no active bug fixes will be made to it.

As for the issue that you are having, you can try these steps:
 - In your database, run the following script to delete the apptokens: `DELETE FROM mdl_config_plugins WHERE plugin = 'local_o365' AND name ='apptokens';`
 - Go to your Moodle site and purge cache.
 - Ask your Azure admin user to set system API user in the local_o365 plugin configuration page.
 - Ask your Azure admin user to provide admin consent.
 - Verify settings.

These steps will delete any previous tokens, and create new ones.

Taking a step back, is there a specific reason why you don't want to use application access as the connection method? Application access would be recommended, especially if Teams integration feature is used.

Regards,
Lai

**Comment by AntonT76** [comment]
Hi @weilai-irl 

thank you for the suggested solution. We will try this steps in the next days.
We do not use Teams integration at the moment and there are no specific reasons why we use an API user instead of application access. But thanks for the information, we will switch to application access method in future.

br, Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

Thank you for the update. Just a note - if you want to switch your connection method to application access from system API user, you probably need to run the first 2 steps in my last note as well, as the details of the existing system API user are saved in the "apptokens" config variables of the local_o365 plugin as well, and is cached.

Please let me know if this solves your issue.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @AntonT76,

Could you confirm if this is an issue please?

Regards,
Lai

**Comment by AntonT76** [comment]
Dear @weilai-irl 
sorry for the late reply. We did an update from 3.5 to 3.9 - and the problem was fixed with the update.
best regards, Anton

**Comment by weilai-irl** [comment]
@AntonT76 
Hi Anton,

Thank you for your confirmation. I'll close the issue now.

Regards,
Lai
