### ISSUE TITLE
Please set application credentials in auth_oidc first

### ISSUE THREAD

**Issue by Ali-Shaikh** [microsoft/o365-moodle#1365]
Keep getting this error on Moodle 3.9.1

**Comment by weilai-irl** [comment]
Hi @Ali-Shaikh,

This error basically means the OpenID Connect authentication plugin (auth_oidc) is not configured. Could you verify it's installed and configured and try again please.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @Ali-Shaikh,

Jus to check if you have this issue resolved?

Regards,
Lai

**Comment by Ali-Shaikh** [comment]
Yes the issue is resolved
