### ISSUE TITLE
"Mismatch between usernames and userids"

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1366]
Hi,

I seem to be seeing an issue for a handful of users login into Moodle via the O365 integration. The user see's:

![image](https://user-images.githubusercontent.com/8142964/93444025-5d425f80-f8c8-11ea-853c-d06623656115.png)

When I click: 

```
Microsoft Office 365 Integration -> Advanced -> Maintenance Tools -> Cleanup OpenID Connect Tokens
```

I see (well, similar to, for 4 different users:

```
217: Mismatch between usernames and userids. Userid "499" references Moodle user "user.name@example.com" but token references "user.name@exampletenant.onmicrosoft.com"
```

I have tried to resync the user using:

```
Microsoft Office 365 Integration -> Advanced -> Manage User Connections -> <example user> -> Resync
```

```
.........  
......... Syncing user user.name@example.com
......... Assigning Moodle user 499 (objectid eeb225c9-d470-4424-98c1-292894xxxxxx) to application
......... Could not assign user "user.name@example.com" Reason: No token available for usersync
......... The user is already using OpenID for authentication.
......... User is now synced.
......... Updating Moodle user data from Azure AD user data.
......... User is now updated.
```

Although this doesn't remove the `Mismatch between usernames and userids` error seen above. 

The really odd thing is that at least one of the four users successfully logged in back in April.

Any ideas on what I might need to do to rectify this?

**Comment by swinster** [comment]
I think there is a work around to this. I disconnected the users with the errors (`Microsoft Office 365 Integration -> Advanced -> Manage User Connections -> <example user> -> Disconnect`), then run a full resync on the cron job until all users have been synched (only seen to do 100 at a time, not 1000)

**Comment by weilai-irl** [comment]
Hi @swinster,

I acknowledge the issue, as I can see this happening myself from time to time. Our workaround is similar to the one that described in your note. We will look for a technical solution in the near future, either to fix it automatically, or to display the error in a nicer way.

Regards,
Lai
