### ISSUE TITLE
user account creation

### ISSUE THREAD

**Issue by gmisterk** [microsoft/o365-moodle#1367]
Hi all,
I just installed this plugin but all my azure account are "student" in user creation process.
i have a different email subdomaine. and i want to use it to identify who will be teacher / student in moodle

exemple :  (for all new account in moodle, if not exist)
user1@teacher.domaine.com    must be a course creator
user2@student.domaine.com must be a student
Anybody can help me for settings to this goall ?

I have read the doc and all i found is only one role to assign to new account in moodle

**Comment by weilai-irl** [comment]
Hi @gmisterk,

Moodle doesn't distinguish between "teacher" or "student" accounts in the system context. All Moodle users are the same when they are created. They only get their role in a specific context, e.g. a course.

It is technically possible to assign a role to a Moodle user in the system context. The Microsoft plugins don't support system role assignments in the user sync process at the moment. You can request a such feature, and it will be processed accordingly. However, considering the nature of the request, this is likely to be a low priority one, and may take a while to be processed.

Regards,
Lai
