### ISSUE TITLE
Add "Office" to available Active Directory Synch Options

### ISSUE THREAD

**Issue by LDGreg** [microsoft/o365-moodle#1380]
Would it be possible to add "Office", a primary field in Azure AD and AD, to the list of selectable Sync Options? We would map it to Institution for example to identify what location a person works at.

**Comment by weilai-irl** [comment]
@LDGreg, 

The latest release (3.8.0.5 and 3.9.2) adds support to map "Office" field. Please try it out.

Regards,
Lai
