### ISSUE TITLE
Add Ability to say what Active Directory Groups to add users from

### ISSUE THREAD

**Issue by rpowellSTUK** [microsoft/o365-moodle#1383]
Would it be possible to have an option to list what AD Groups users should be created from?

**Comment by weilai-irl** [comment]
Hi @rpowellSTUK,

Maybe the feature you are looking for is the "Office 365 Group Membership" filter in the "User Creation Restriction" setting? See screenshot attached.

Regards,
Lai
![Uploading User Creation Restriction.png…]()
