### ISSUE TITLE
Error in API call: The specified api-version is invalid. The value must exactly match a supported version.

### ISSUE THREAD

**Issue by narmertechnology** [microsoft/o365-moodle#1385]
I'm getting the following error whenever we try to sign users in, or perform auth actions inside of the Admin consent & additional information settings.

Error in API call: The specified api-version is invalid. The value must exactly match a supported version.

<img width="939" alt="Screen Shot 2020-09-27 at 3 42 50 PM copy" src="https://user-images.githubusercontent.com/52138958/94376563-6c9b8700-00d8-11eb-8b06-f27e6dcf9792.png">

When we uninstall the plugin, the single sign on works properly. But we obviously would love the plugin to be able to leverage user sync, etc.

**Comment by weilai-irl** [comment]
Hi @narmertechnology,

I remember seeing this error a while ago, but possibly in an old version of the plugins. Could you please provide more details, like the version of Moodle and the plugins, when you see this, what's working and what's not please.

Regards,
Lai

**Comment by StasOne1992** [comment]
Try to set the Resource value "https://graph.microsoft.com" in the OpenID Connect plugin settings

**Comment by weilai-irl** [comment]
Hi @narmertechnology,

Would you have more details of this issue?

Regards,
Lai

**Comment by cl1ent-s1de** [comment]
> Try to set the Resource value "https://graph.microsoft.com" in the OpenID Connect plugin settings

I had the same issue above and this solution resolved the problem.
