### ISSUE TITLE
Setting the correct user time zone from AAD to Moodle when provisioning.

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1389]
How is it possible to ensure that the correct timezone is set of a Moodle user that has been provisioned from a sync via the MS365 plugin? We have global user and without timezones being set correctly, various Moodle feature such as appointment schedules, do not work as expected.

**Comment by weilai-irl** [comment]
Hi @swinster,

Release 3.8.0.5 and 3.9.2 of the plugins introduced the support for syncing Outlook timezones. The option is available in the sync settings tab in the local_o365 plugin settings pages. Please see screenshot attached.

Please note that permission changes are required to be able to use this feature. See https://docs.moodle.org/39/en/Office365#3.8.0.5_and_3.9.2_release for details.

Regards,
Lai
![timezone-sync](https://user-images.githubusercontent.com/695310/99548665-cc176400-29b0-11eb-8d4c-ac862e3d55c3.png)

**Comment by swinster** [comment]
👍 Nice

**Comment by swinster** [comment]
@weilai-irl Just tried this with a demo Moodle deployment and demo MS Tennant, but couldn't;t get it to work I expected

1. Created a local Outlook profile for the user on Windows 10 machine (this happens to be the global Azure tenant admin)
2. Opened up Outlook with this profile
3. Logged in via OpenID to Moodle, 

Check the Moodle account setting, the user time zone is still set to the server timezone (UTC), obviously the default. 

"Sync Outlook timezone to Moodle on login" is checked

Permissions were added for the Graph API: 

- Delegated permissions
- - MailboxSettings.Read
- - MailboxSettings.ReadWrite
- Application permissions
- - MailboxSettings.Read
- - MailboxSettings.ReadWrite

The re-consented, via Azure and just in case, Moodle.

**Comment by swinster** [comment]
Ok, bit more investigation, I didn't realise that the Micorosft Block needed to be visited by a user when syncing via login, and it appears that a "Full sync" is required when running the corn job. 

Anyhow, looks like we have lift off now.
