### ISSUE TITLE
Add option to not create groups when syncing courses without owners

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#1397]
The plugin should provide an option in the settings that controls whether a course without an owner should have a group created first, and then a team should be created based on the group.
I believe having a group without a team attached to it is usually not the intended use for the integration. Also, creating groups first has some disadvantages (depending on how you see them), since members are visible to others, and the team created based on the group uses a different template (education vs basic).

**Comment by weilai-irl** [comment]
Hi @darius-m,

I agree this feature request makes a lot of sense, and will be useful.

We will consider it and include in upcoming releases.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @darius-m,

A new setting has been added in the latest release 3.9.3 for Moodle 3.9, and 3.10.0 for Moodle 3.10, to control whether to fall back to creating groups if Teams sync is enabled for a course, but no suitable Team owner can be found. The setting is called "Group creation fallback", and can be found in the "Advanced settings" section in the "Advanced" tab of the plugin configuration page.

Please check it out.

I'll mark the issue as closed for the moment. Feel free to report back issues.

Regards,
Lai
