### ISSUE TITLE
Unknown team owner who is not in the group

### ISSUE THREAD

**Issue by jcernohorsky** [microsoft/o365-moodle#1398]
Hi,
in our school we have an interesting problem when synchronizing courses from Moodle to MS Teams.
All course participants are synchronized as team members, the teacher is synchronized as a team owner.
But in most teams we have a second owner (only in MS Teams), who is not in the Moodle course and even the user is not a member of such a group in AAD.
An example is attached:
"Nechanický Zbyšek" is "Manager" in Moodle (global group). "Tochjan Aramis" is "Manager" in Moodle, but is also Teacher in course "Výchova k podnikání - 3.C".
In AAD, "Nechanický Zbyšek" is not member of group "Výchova k podnikání - 3.C", but in Teams is owner. 
In AAD, "Nechanický Zbyšek" is owner of group "Výchova k podnikání - 3.C", as well as "Tochjan Aramis".

And I do not know why. I thing, this is a bug in sync.

![2020-10-05 23_28_04-Nechanický Zbyšek - Centrum pro správu Azure Active Directory](https://user-images.githubusercontent.com/72417121/95134441-2e9b0480-0763-11eb-95b9-456b445c0ab9.png)
![2020-10-05 23_27_16-Manage team - Microsoft Teams admin center](https://user-images.githubusercontent.com/72417121/95134442-2f339b00-0763-11eb-80c1-bc0aa9ebcf28.png)
![2020-10-05 23_26_46-Manage teams - Microsoft Teams admin center](https://user-images.githubusercontent.com/72417121/95134443-2fcc3180-0763-11eb-8028-44fc7142e7c6.png)

In AAD group log is:
![2020-10-05 23_42_27-Výchova k podnikání - 3 C - Centrum pro správu Azure Active Directory](https://user-images.githubusercontent.com/72417121/95135380-9c93fb80-0764-11eb-94b4-1852ef5d07b2.png)

It looks like MS Teams will directly assign this user ("Nechanický Zbyšek") as the owner, and only then will o365sync add the teacher as the owner ("Tochjan Aramis").

**Comment by weilai-irl** [comment]
Hi @jcernohorsky,

I may know the reason behind this. In the "Step 2/3: Choose connection method" section in the local_o365 plugin configurations in Moodle (https://URL.TO.MOODLE/admin/settings.php?section=local_o365, "Setup" tab), if you choose "System API User" rather than "Application access", the system API user selected will be added to all Teams created as owner.

Could you confirm if this is the case please.

This is known to us, and I don't think there's a solution to it. All features should work using "Application access", and there have definitely more focus put on it over "System API user" connection method during development and testing before release. Therefore unless your organisation has a specific reason why "System API user" is preferred, we would highly recommend you using "Application access" for connection.

Regards,
Lai

**Comment by jcernohorsky** [comment]
Hi @weilai-irl ,
thank you for your reply.
I am using "Application access" for connection:
![2020-10-06 10_41_52-SSPŠ Moodle_ Správa_ Moduly_ Lokální moduly_ Integrace Microsoft Office 365](https://user-images.githubusercontent.com/72417121/95179232-a6e3e300-07c0-11eb-8a7a-43447840caa9.png)

I found that these unsolicited "owners" are all in the global "Manager" group in Moodle and are randomly assigned to teams.
I tried to remove the "local / o365: teamowner" setting from the "Manager" group in Moodle.
![2020-10-06 10_45_49-SSPŠ Moodle_ Správa_ Uživatelé_ Oprávnění_ Definovat role](https://user-images.githubusercontent.com/72417121/95179641-34273780-07c1-11eb-837b-f058bb667731.png)

Regards,
Jan

**Comment by weilai-irl** [comment]
Hi @jcernohorsky,

Thank you for your confirmation. This might explain it.

The latest release of the plugins included a change in how course owners are determined. It would treat all users with "local/o365:teamowner" capability in the course context as Team owner. Roles with arthetype manager would have this capability by default, and as the manager role can be assigned in the system context, this would mean that all users with manager role in the system context would be treated as owner in all course Teams created from Moodle.

Your solution to remove the capability for the manager role should solve the problem in all future course Teams creations. You may need to manually fix it for existing Teams though.

Regards,
Lai

**Comment by weilai-irl** [comment]
I think it makes sense to remove the local/o365:teamowner capability from manager archetype by default.

This will be included in the next release.

**Comment by weilai-irl** [comment]
@jcernohorsky,

We have removed the teams owner capability from manager archetypes by default. The change has been included in the latest release (3.8.0.5 and 3.9.2). Please check it out.

Regards,
Lai
