### ISSUE TITLE
not able to sign in moodle app and save it as a tab

### ISSUE THREAD

**Issue by Fugazi90** [microsoft/o365-moodle#1399]
Hi,

after successfull integration of office365 with moodle I can't login in to the Moodle app in Teams. When I try to login in office365, it shows a small windows for a second and then drop. When I try the manual login, I'm able to get to the moodle site, but after fill the login credentials and confirm it throws me the back to choosing the login methods and the tab can't be saved at all. I tested communication between Azure AD and Moodle and everything was succesfull. I'm also able to login in Moodle as a Office365 user without any problem. Synchronization in Scheduled tasks is also working. Could someone gave me an advice to this frustrating problem? Thanks in advance and sorry for my bad english. Michael.
![Moodle](https://user-images.githubusercontent.com/72453674/95212967-934f7100-07ee-11eb-8b83-ec1e72e6182b.jpg)

**Comment by matthew-armitage** [comment]
We're seeing the exact same thing after an upgrade from Teams app 1.2.2 to 1.3, and Moodle Plugin update to 2.9.1. I've reviewed and made all the changes noted in the documentation for the upgrade, but now the Teams app just shows this every time.
![image](https://user-images.githubusercontent.com/73185977/96610003-01e10400-12b0-11eb-9464-1b3e45f98477.png)

**Comment by matthew-armitage** [comment]
I will note that everything else works, and I have auth_oidc | forceredirect set to enabled, which in conjunction with the forcelogin set to enabled means that all access to the site redirects to an AzureAD login prompt, or silently does SSO.

**Comment by matthew-armitage** [comment]
If I click on the "Login to Office 365" button I get an login prompt (which does SSO and disappears). If I click the "Login manually" button I get a very brief (1-2 rendered frames) view of the courses where I am assigned the Teacher role, but it immediately returns to the above screen.

**Comment by Fugazi90** [comment]
Thanks for the confirmation of the same problem. I almost thought that I'm the only one. Now we have to get some solution of this nasty thing. Did you find some advices from antother users?

**Comment by matthew-armitage** [comment]
We haven't yet found a solution to this, and our staff are essentially abandoning the teams integration.

**Comment by nenorojas** [comment]
Hi @matthew-armitage , @Fugazi90 ,

A updated implementation of Teams and Moodle SSO has been included in the latest release of the plugins for 3.8 and 3.9, please see issue #1319 . Configuration changes are required, so please follow steps in the release note. In our test, it hugely the SSO experience a lot.

Regards
