### ISSUE TITLE
Wrong use of CAP_ALLOW in local/o365/classes/observers.php

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#1400]
A recent commit changed the way team owners are identified by adding the local/o365:teamowner capability.
However, when fetching the roles with the capabilities in local/o365/classes/observers.php, CAP_ALLOW is used as a string instead of a macro.

Pull request #1387 fixes this issue.

**Comment by weilai-irl** [comment]
Hi @darius-m,

Thank you for your contribution. The fix has been included in the latest release 3.8.0.5 and 3.9.2.

Regards,
Lai
