### ISSUE TITLE
Groups / teams are not properly deleted when the course is deleted

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#1401]
The event listener for course delete relies checks if sharepoint sync is active, despite course groups / teams not being linked to the deprecated sharepoint sites.

Pull request #1395  fiexes this issue.

**Comment by weilai-irl** [comment]
@darius-m 

Hi Darius,

The issue and the pull request make sense to me.
It will be included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @darius-m,

The pull request has been merged and included in the release 3.8.0.5 and 3.9.2. Thank you again for your contribution.

Regards,
Lai
