### ISSUE TITLE
Inconsistent user unenrolment functionality in event listener

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#1402]
The `handle_user_enrolment_updated` uses the `get_suspended_userids` function, that according to [a comment above the function](https://github.com/moodle/moodle/blob/master/lib/accesslib.php#L7591) is deprecated. The issue with this function is that it appears to not always function properly in the handler for the event.

Steps to reproduce the issue:
 - enrol a user to a course
 - use course users through the upload users functionality (using a CSV file - it must be a re-enrolment for the handler to trigger)
 - the handler is called when the event handler is generated by [update_user_enrol](https://github.com/moodle/moodle/blob/master/lib/enrollib.php#L2111) function
 - the event handler uses `get_suspended_userids` to get the list of suspended users
 - the function returns the user who is currently being updated, possibly due to a race condition caused by the fact that the user information is updated after the after the event is triggered

**Comment by weilai-irl** [comment]
Hi @darius-m,

The pull request has been merged and included in the release 3.8.0.5 and 3.9.2. Thank you again for your contribution.

Regards,
Lai
