### ISSUE TITLE
Maintain Teams owner status if roles allow it during role unassign

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#1406]
The plugin checks only if the user's role that was removed is among the roles that has team owner capabilities before making the user a regular member. This is an issue if a user had multiple roles that can be owners before removing one of them.

Steps to reproduce the issue:
 - add a user who has two roles that can be team owners (e.g., teacher and non-editing teacher should be enabled by default)
 - remove one of the roles from the user
 - the user is demoted to regular user, despite having another role that allows them to remain an owner.

**Comment by weilai-irl** [comment]
@darius-m,

Hi Darius,

I think your change makes sense. It will be included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @darius-m,

The pull request has been merged and included in the release 3.8.0.5 and 3.9.2. Thank you again for your contribution.

Regards,
Lai
