### ISSUE TITLE
Multitenancy: problem adding new tenant

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1426]
We have fully set up O365 integration in Moodle (version 3.5 at the moment) and have enabled multitenancy in the app registered in host tenant.

When trying to add first additional tenant, after logging in with the new tenants global admin, in returns to 
https://host/auth/oidc with error "There was a problem logging you in. Please contact your administrator for assistance."

oidc-auth is disabled as per instructions.

Is there some other settings or actions that need to be done?

**Comment by kkiiskin** [comment]
Any comments on this?

This is from the errorlog: 
"AADSTS650056: Misconfigured application. This could be due to one of the following: the client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, the admin has not consented in the tenant. Or, check the application identifier in the request to ensure it matches the configured client application identifier. Or, check the certificate in the request to ensure it's valid. "

Login works with a user from the host tenant, so it is configured properly. I understand from the instructions that no configuration is needed in the additional/client tenant?

**Comment by Urpokarhu1** [comment]
any progress on this? @weilai-irl

**Comment by weilai-irl** [comment]
Hi, @Urpokarhu1, @kkiiskin 

Thank you for reporting the issue.

We are currently working on the November release of the plugins, and probably won't have time to look into this until after the release. You will see updates in the issue when we have progress.

Regards,
Lai

**Comment by kkiiskin** [comment]
Hi

can you at least confirm if the instructions in 'Configure additinal tenats' page are correct and sufficient?
Or if multitenancy should work at all? 
There seems to be nothing about it in the docs: https://docs.moodle.org/39/en/Office365

**Comment by kkiiskin** [comment]
Hi @weilai-irl

any comments on the multitenancy problem?
If the feature should work, we could use up-to-date instructions to set it up, so we can be sure we don't have any configuration issues.

**Comment by kkiiskin** [comment]
Hi

this seems to be Moodle 3.5 issue, in 3.9 adding tenant worked.

But loggin in with user from client tenant didn't:
     Resource 'ObjectID of the user' does not exist or one of its queried reference-property objects are not present. 

It still saved the ObjectID to auth_oidc_token table, but with userid 0.

**Comment by kkiiskin** [comment]
Hi @weilai-irl

this issue can be closed as far as I'm concerned, seems to be working with Moodle 3.9.
