### ISSUE TITLE
Mechanism for Excluding Some Courses and Features when Teams Sync is set to All?

### ISSUE THREAD

**Issue by bbusschots-mu** [microsoft/o365-moodle#1436]
Is there a mechanism to have local_o365 create Teams for all newly created courses, and, to be able to mark some courses not to get a Team?

My reading of the sync setting page is that "Customize Groups" settings page only applies when the `local_o365 | createteams`  setting is set to _Customize_ — is this correct?

If the Customize Groups page does not work when `local_o365 | createteams` is set to _All_, is there another mechanism to remove a Team for a course in such a way that it would not get re-created by the _Recreate deleted Office 365 groups_ maintenance utility? Or, should a Team be deleted in error, is there a way to only re-create that one Team so we never have to use the _Recreate deleted Office 365 groups_ utility under any circumstance?

Also, is there a way of globally removing some features from all Groups? We really only want Teams created for all our courses, nothing more.

Finally, is there a way to customise the features for a specific course when `local_o365 | createteams` is set to _All_?

**Comment by weilai-irl** [comment]
@bbusschots-mu 
Hi Bart,

To answer your questions:
 1. In the latest release of the plugin (3.9.3 for Moodle 3.9 and 3.10.0 for Moodle 3.10), a new setting has been introduced to allow sync to be enabled by default on all new courses created after the setting is saved. It will keep sync status of all existing courses unchanged. This should meet the requirement.
 2. You are right in understanding that the settings applied on the "Customize groups" page are only applied if `local_o365 | createteams` is set to "Customize".
 3. Regarding the issue described in the paragraph "If the Customize Groups page...", Feature described in point 1 above should solve it. 
 4. The latest release has removed all other options from the "Customize groups" page, except for "enabled" and "Teams". Those options actually don't have any impact on the creation of the group/team, and don't affected services made available to the group/Teams created in any way.
 5. Regarding your question in the last paragraph - no, there isn't a feature to allow for that. "All" means all in this case. However, a new option has been added to the "Customize groups" page to allow site admins to enable all features on all courses using one button click. It would be the same as set `local_o365 | createteams` to all, but after that, you can disable sync on individual courses. Combine it with the feature to enable syncing on new courses by default, you should be able to achieve what you described.

Regards,
Lai
