### ISSUE TITLE
filter_oembed doesn't fully impement oEmbed specification

### ISSUE THREAD

**Issue by alexmorrisnz** [microsoft/o365-moodle#1443]
With oembed you can have a endpoint scheme such as `"spotify:*"` but this doesn't work with filter_oembed.
One point in the code that this breaks is here: https://github.com/PoetOS/moodle-filter_oembed/blob/1dcf9cc2abbd505233b2c121e2764cef3d6a822d/classes/provider/provider.php#L214

**Comment by weilai-irl** [comment]
Hi all,

The filter_oembed plugin is not a part of the Microsoft plugins suite for Moodle anymore. Please report the issues about the plugin according to links on https://moodle.org/plugins/filter_oembed.

Regards,
Lai
