### ISSUE TITLE
Integration with Moodle Workplace (specifically, multitenancy) - Security Issue!

### ISSUE THREAD

**Issue by swinster** [microsoft/o365-moodle#1452]
We are running MWP with the O365 plugins. Is there a way to define in which tenant in MWP users are created when we sync with AAD?

**Comment by swinster** [comment]
Clarification. In the short term, an ability to sync a single AAD tenant to a specific Moodle tenant (that is **NOT** the default Tenant) would be required.

The default Tenant should be used to collect all the waifs and strays as people self enrol. Unfortunately, this would add them currently into our internal Tenant, which has massive security implications.

**Comment by swinster** [comment]
Hi guys, I wonder if this was anything that anyone was working on? It's seriously impacting our use of MWP as the only way we can currently operate is to ensure that our **corporate internal tenant** is set as the default MWP tenant, however, we have experienced numerous security incidents where users that are NOT part of our AAD synchronisation have also made their way into this default tenant (which of course, is normal Moodle behaviour).

Honestly, if we can't specify a tenant for which users from the AAD synchronisation are added to, I think the whole project is dead int the water :(.

**Comment by swinster** [comment]
Hi Guys, sorry to bug, but we are kinda desperate. Without the ability for the MS365 plugin to allow AAD user provisioning to be directed to a specific MWP tenant, we are pretty much lost. Security implication are huge as users that sign up will get directed to the same default MWP tenant as internally provisioned users. 

Would love to get an understanding on of this is even being looked at.

**Comment by nenorojas** [comment]
Hi @swinster, 

Moodle Workplace and Totara are not on the list of applications to provide support sponsored by Microsoft, only for Moodle standard versions that are still receiving bug fixes or security fixes by Moodle HQ. 

I will check if there are any plans to extend the list of supported applications in the future, but for the moment the quickest approach to get a solution for Workplace is engaging with your Moodle Partner to estimate a fix for Moodle Workplace, creating a custom version of the plugin. 

Regards

**Comment by swinster** [comment]
@nenoroja, I appreciate your feedback. Many thanks.

Unfortunately, this does put us, and indeed many organisations that would look to use Moodle Workplace with AAD, in a bit of a sticky wicket. I can only hope that if Moodle HQ themselves wish Moodle Workplace to actually succeed, they can see that this is essential for enterprise use. It is crucial that users are provisioned ahead of time, and not JIT via Moodle's native Oauth and a user's login action (which can't be guaranteed), in order that they are properly allocated to onboarding, compliance and role-based training automatically and as soon as the object is created in AAD.

Perhaps Moodle HQ will read this and understand its importance for MWP going forward. I wish we could have understood this potential direction 3 months ago to plan for alternative approaches. I see @weilai-irl has been assigned a milestone, so perhaps there is light at the end of the tunnel, but I fear it will be too late for us. 

Again, I thank you for the feedback.

**Comment by nenorojas** [comment]
Hi @swinster,

That milestone was added by mistake. Please note that the process to get access to Moodle Workplace code is not straightforward, not all Moodle plugin maintainers have access to the code, only certified partners after following certain process with Moodle HQ.

I'm closing this case for the moment because there's no plans to be supported via this channel, if circumstances change, we will reopen. As mentioned before, if it's critical, the quickest approach is to contact a Moodle Partner to fork these plugins and provide a custom version compatible and fully tested with Moodle Workplace. 

Regards

Oswaldo

**Comment by swinster** [comment]
Thanks, Oswaldo,

TBH, I think this needs to be taken on by Moodle HQ as this will be critical for them to penetrate the enterprise market with MWP. Our Moodle partner is very aware of the situation. 

Anyhow, thanks for your input
