### ISSUE TITLE
Feature request: identify application with certificate instead of client secret

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1453]
At the moment you can only use Client secret to identify the Moodle integration application to Azure AD

There should be option to use certificate.  Azure AD even recommends this: 
"For a higher level of assurance, we recommend using a certificate (instead of a client secret) as a credential."

**Comment by kkiiskin** [comment]
Hi @audrieMSFT 

is there any progress on this and do you have estimate if/when this could be implemented?

There might be security issues with the Client Secret approach so the certificate identification would be great improvement.

**Comment by weilai-irl** [comment]
Hi all,

The requested feature has been included in the release from today for Moodle 3.11 and 4.0. Please upgrade your plugins to the latest version to make use of the feature.

I'm going to close the issue.

Regards,
Lai
