### ISSUE TITLE
Cannot retrieve a token for the base resource when using application access

### ISSUE THREAD

**Issue by ajo-sc** [microsoft/o365-moodle#1455]
Moodle 3.8.5+ (Build: 20201030)
local_365 - 3.8.0.4 (2020020306)
oidc - 3.8.0.3 (2020020303)

Hi, I have a new install of local_365 on Moodle 3.8 - everything is set up in Azure and I've selected application access based on the recommendation but when I try to either detect the Azure AD Tenant or OneDrive for Business URL, or if I click Update in the Verify section, I get the following message:

_'Could not get a system API user token, please run the health check, ensure that your Moodle cron is running, and refresh the system API user if necessary.'_

When I run the health check it tells me that Office 365 API calls are executing at full speed. The cron is running and I haven't added a system API user as I have application access ticked. 

In the debug logs, I get this error message: 

**_local_o365\oauth2\token::instance local_o365\page\ajax::mode_checksetup:372: Cannot retrieve a token for the base resource. Data: (null)_**

This seems similar to an issue reported here: https://github.com/microsoft/o365-moodle/issues/1271 but that was apparently fixed for the version I've installed. 

Any help anyone could offer would be very much appreciated, thank you!

**Comment by weilai-irl** [comment]
Hi @ajo-sc,

This is most likely an issue caused by your app configuration. The most probable settings missing would be the API permissions. Could you go to the "API permissions" page of your app, and ensure that an Azure AD admin has granted admin consent for your organisation please.

i.e. in the attached image, an admin user has clicked the "Grant admin consent for [organisation name]", and a check appears for all the permissions.
![API permissions](https://user-images.githubusercontent.com/695310/98133346-62c62a00-1eb5-11eb-8ff8-7e8c84fbf337.png)

Regards,
Lai

**Comment by ajo-sc** [comment]
Hi, 

Thank you very much for your reply. I've double checked Azure and consent is ticked for all of the API permissions. 

The only difference between our set-up and the screenshot is the permission for AzureActiveDirectoryGraph - I followed the manual set up process instructions and that only listed permissions to add for Microsoft Graph. Do I need to add the AzureActiveDirectoryGraph permission as well?

Thank you, 

Amanda

**Comment by ajo-sc** [comment]
I've just tried adding in the Azure Active Directory Graph permission as well just in case, but I'm still getting the same '_could not get a system API user token_' error and it's still logging '_Cannot retrieve a token for the base resource._' error messages when I try to connect or sync.

Is there anything else I can try to get it working? All the permissions are definitely green ticked and consent is granted for them. 

Thank you!
