### ISSUE TITLE
Create a sharing link when creating a shotrcut/alias to a file attachment to Office files

### ISSUE THREAD

**Issue by vinhub** [Microsoft/o365-moodle#146]
At present, the shortcut / alias link that gets created for a file attachment (e.g. when you attach "Additional files" to an assignment and select "Create alias/shortcut" when attaching it) is a regular link to the file, not a sharing link. We should create a sharing link for that and return it as the attachment link. This is similar to issue #115.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/152

Note that a sharing link can be created only for OneDrive files and only when using the Unified api. For other cases, the code continues to create the shortcut / alias the same way as before.

**Comment by brentboghosian** [comment]
@vinhub 
Can you please confirm that, in the first if-block of the commit, in the do_embedding() method:

 +        if (($reference['source'] === 'onedrive') && ($this->unifiedconfigured === true)) {
 +            return false;
 +        }
so, if $this->unifiedconfigured === true the method is suppose to return false? 
I thought this check should be reversed (?)

**Comment by brentboghosian** [comment]
For testing, I assume selecting a OneDrive file in the Moodle editor (i.e. for Course Assignment Description link, browse repositories, ...) and chose an existing file, selecting _Create and alias/shortcut of the file_
Is there a particular way to confirm it is using the new sharing link?

**Comment by nimojg-microsoft** [comment]
The users in the Moodle course in which you are creating the Resource should be able to access the file (associated to the Resource).  The behavior should be such that the sharing link is a One Drive for Business link permissioned such that all the users in the Moodle course can access it.

Let me know if this helps.

**Comment by brentboghosian** [comment]
Could you please provide step by step testing instructions for validation.
Also, when selecting 'Create an alias/shortcut to the file' is selected for a OneDrive file, it's inserting a link to drat files (?)
i.e.
http://kwoffice.remote-learner.net:8480/gao27_o365/draftfile.php/5/user/draft/864103328/lighthouse_b.jpg

This appears to be a 'Copy of the file' and not the sharing link (?)
(This is using the changes in commit as is)

**Comment by vinhub** [comment]
Testing instructions:
- login as teacher for a course
- add an assignment and add a file attachment to the assignment (additional files)
- save
- log in as student enrolled in that course and view the stacked file. Student should be able to access the file. 

It is true that the link for a copy looks similar to that of an alias (when inserting as a link) but I case of alias it should take you to the file in office 365, not moodle.
