### ISSUE TITLE
AzureAD group policy is stopping the plug-in to create Team (Group)

### ISSUE THREAD

**Issue by mattmajedi** [microsoft/o365-moodle#1469]
We are looking at using Moodle teams plug-in. We currently have an Azure AD group naming policy which enforces a suffix (_GRP) on to user-created groups. We implemented this policy so that Teams that are created by users have a suffix on them. Unfortunately, the Moodle Team plug-in is failing to create the groups because of this policy. It cannot create the group even when we have the moodle course with the suffix to comply with the policy. Has anyone faced this problem?

**Comment by nenorojas** [comment]
Hi @mattmajedi ,

Could you please let us know what's the Moodle version you are using?

Regards

**Comment by mattmajedi** [comment]
it is 3.8.2.

Thanks


> Hi @mattmajedi ,
> 
> Could you please let us know what's the Moodle version you are using?
> 
> Regards

it is 3.8.2

**Comment by weilai-irl** [comment]
Hi @mattmajedi,

First of all, release 3.9.3 and 3.10.0 of the plugins (from Jan 2021) for Moodle 3.9 and 3.10 respectively introduced a new feature to allow site admins to configure naming conventions of Teams (name field) and groups (both displayName and mailNickname fields). If possible, please upgrade your Moodle site and Microsoft plugins to the versions mentioned or later to try these features.

In case you have to stick with your current Moodle version, you may still get this work.
 - Group naming policy doesn't apply to Teams, so if you confirm the integration to create Teams from courses directly, providing suitable Team owners present, Teams can always be created.
 - When creating groups (not Teams), before 3.9.3/3.10.0 release, the integration would use course short name as mailNickname, and course full name as displayName. If you see the required prefix in both course short name and full name, group creation will work.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @mattmajedi,

Could you confirm if this issue can be closed please.

Regards,
Lai

**Comment by mattmajedi** [comment]
Hi @weilai-irl, since we are not in a position to upgrade the version of moodle at this point I cannot confirm if this issue has been resolved, but if you are confident that the new version of the plug-in solved this issue, go ahead and close this issue.

Regards

**Comment by weilai-irl** [comment]
Hi @mattmajedi,

Thank you for informing us. I'll close this issue in that case. If you have any question about this after upgrade, please report back here.

Regards,
Lai
