### ISSUE TITLE
Moodle teachers are not being set as admins for the o365 group

### ISSUE THREAD

**Issue by number33** [Microsoft/o365-moodle#147]
@vinhub here is the issue to set Moodle teachers as admins to the o365 group.  As I understood, the issue to create the OneNote class notebook is still being worked on.  I may make sense as part of that work to include a fix for this issue.  Let me know if that works for you and I will close this issue.

Also I don't see an issue for the OneNote class notebook.  Did you create that issue yet?

**Comment by vinhub** [comment]
Yes, the Class notebook integration is issue #149. I think it makes sense to combine this issue with that one.

**Comment by number33** [comment]
@vinhub Thank you.  I will close this issue.

**Comment by number33** [comment]
Removed this issue issue #149 will be included in the next milestone.
