### ISSUE TITLE
Unable to log in via OIDC after upgrading to latest version of moodle-auth_oidc

### ISSUE THREAD

**Issue by tekhnee** [microsoft/o365-moodle#1472]
The update of the plugin from 3.9.0 to 3.9.2 was uneventful, with no error messages.

Logging in fails, however, with the following error:

`Exception - Class 'local_o365\feature\usersync\main' not found`

Running Moodle on the `MOODLE_39_STABLE` branch (`a348c5f420d`) as a standalone installation (i.e. without Azure or the `local_o365` plugin).

**Comment by weilai-irl** [comment]
Hi @tekhnee ,

Thank you for reporting the issue. I confirm this is a bug in the auth_oidc plugin, in which it assumes the presence of local_o365 plugin, and would throw this error if local_o365 is not installed. I'll fix this in a new version in the next 2 days.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @tekhnee,

The bug should have been fixed in the latest version of the plugin, release 3.9.2, version 2020071502. Please check it out and confirm if it works.

Regards,
Lai

**Comment by tekhnee** [comment]
@weilai-irl this now works as expected; thank you for the timely fix.
