### ISSUE TITLE
Teams creation failed with error from Microsoft Graph API

### ISSUE THREAD

**Issue by weilai-irl** [microsoft/o365-moodle#1475]
We started noticing this issue since 23rd of November, 2020.

The issue is, local_o365 plugin uses Microsoft Graph API function at https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http to create Teams from courses for courses that are configured to be synced. The parameter used are similar to example 6 or 7, in which custom template "educationClass" are used to create class teams. This was working before, but since today, the API call returns with errors now.

When trying the exact example 6 on the API function document page with the following params:
`{
    "template@odata.bind":"https://graph.microsoft.com/beta/teamsTemplates('educationClass')",
    "displayName":"My Class Team",
    "description":"My Class Team’s Description","visibility":"HiddenMembership"
}
`
 the following error returned:
`{
    "error": {
        "code": "BadRequest",
        "message": "Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/emea/templates/api/team, Request Method: POST, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: max-age=2592000\r\nx-operationid: ebbba9445cb60a429b0c461c4bb5dc2c\r\nx-telemetryid: 00-ebbba9445cb60a429b0c461c4bb5dc2c-4b6f088f92fbb444-00\r\nX-MSEdge-Ref: Ref A: 70596FE38B994E809908AE716F23D3B0 Ref B: AM3EDGE1015 Ref C: 2020-11-23T12:59:32Z\r\nDate: Mon, 23 Nov 2020 12:59:32 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"'Team Definition. Visibility' should be equal to 'HiddenMembership'.\"}],\"operationId\":\"ebbba9445cb60a429b0c461c4bb5dc2c\"}",
        "innerError": {
            "date": "2020-11-23T12:59:32",
            "request-id": "227576eb-6def-4110-b77b-7ba1cd230df7",
            "client-request-id": "2af30bd1-d5c2-4c69-e95d-b7f4a00d681f"
        }
    }
}
`
Notably, the error message is 'Team Definition. Visibility' should be equal to 'HiddenMembership'.'.

I have tried to add `visibility` property in the request, so the parameters look like this:
`{
    "template@odata.bind":"https://graph.microsoft.com/beta/teamsTemplates('educationClass')",
    "displayName":"My Class Team",
    "description":"My Class Team’s Description",
    "visibility":"HiddenMembership"
}
`
The error returned is '"Team Visibility must be one of known types: [Private,Public,HiddenMembership]."'. It looks like the API function is not recognising the visibility value passed in to the API call.

This seems to be a change in Graph API function, and will need to be fixed by Microsoft. There seems to be other reporting of the same issue, from other developers using the API function (not Moodle related), e.g. https://techcommunity.microsoft.com/t5/teams-developer/microsoft-graph-api-create-team-visibility-hiddenmembership/m-p/1922405.

**Comment by Partovic** [comment]
Same issue was reported here: [#10777](https://github.com/microsoftgraph/microsoft-graph-docs/issues/10777)

(Sorry, wasn't able to link it correctly)

**Comment by weilai-irl** [comment]
Update 24 November, 2020:

The issue is still not resolved. It's also being discussed at [Teams Developer Tech Community](https://techcommunity.microsoft.com/t5/teams-developer/microsoft-graph-api-create-team-visibility-hiddenmembership/m-p/1926611)

Our suggestion is to wait for Microsoft to provide a solution. There is a chance that Microsoft will revert the API function to how it worked before, which means no change is required in the plugins; however, it is also possible that when Microsoft fixes the issue, they will request all applications using the API function to make changes to the parameters used in the call. If this is the case, we will roll out these changes to all release versions of the plugins, and other supported versions like yourself. It's simply too early to say now.

Lai

**Comment by weilai-irl** [comment]
Update 25 November, 2020:

The issue has been fixed by Microsoft, and all Graph API calls to create class teams are successful now. No code change is required from the Moodle plugins.

I'll keep the issue open for another few days to ensure this is still working.

Regards,
Lai

**Comment by weilai-irl** [comment]
The fix made by Microsoft seems stable. There has been no new reporting of the issue.
Closing call.
