### ISSUE TITLE
Moodle tab not added to the Team created from synced courses by default

### ISSUE THREAD

**Issue by weilai-irl** [microsoft/o365-moodle#1479]
We have noticed cases in which the Moodle tabs fail to be added by default to the Teams created from synced Moodle courses. We have found the root of the issue, please read on.

In the complete Teams integration workflow, an important step in the process is to provision the Moodle Teams app to the Teams created from Moodle courses, so that the Moodle tab can be created in the "General" channel of the Team. This "provisioning" step effectively installs the Moodle app in the Teams.

This is achieved by calling the [Add app to Team API function](https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-add?view=graph-rest-1.0&tabs=http), and this has always been successful previously. However, we have noticed recently that some calls to the API function would return with status code 404 and error "Not found". This resulted in the Moodle app not being installed in the Team, therefore the created Team wouldn't have a "Moodle" tab created by default.

After investigation, we concluded that this is caused by the delay between the creation of the Team from the course, and the time when the "Add app to Team API function" can recognise the newly created Team. The solution to the issue is to detect this error, and retry the attempt to provision the Moodle app after a short delay.

The solution to the issue will be included in the next release for Moodle 3.9 and 3.10, and will ensure all Teams created from that time on not being affected by this issue; however, it will not be able to fix existing Teams that might have been affected by this issue.

For existing Teams that don't have the "Moodle" tab created by default, the following manual steps need to be taken:
- Log in to Teams as the owner of an affected Teams.
- Go to the "General" channel, or whichever channel the "Moodle" tab needs to be added to.
- Click the plus sign to add a tab.
- From the list of tabs, select the Moodle app. This should be called "Moodle" by default, but can be a custom value of your site admin chooses to do so when creating the app.
- If the app hasn't been installed to your Team before, you will be asked to confirm the installation.
- You will be asked to choose the course to which the Moodle tab is connected. The list will consist all courses the user is enrolled into, but in practice, only the course that links to the Team should be chosen.

Following these steps will ensure it achieves the same effect as automatically creating the "Moodle" tab by the integration tool.

Lai

**Comment by klovsb** [comment]
We follow the exact steps listed about manually adding Moodle tab but unfortunately fail.  We have both 3.8.0.4 (build 2020020306) on Moodle 3.8 and 3.9.2 (build 2020071504) on Moodle 3.9.  They both demonstrate the same behavior when we try to add a course to Team through the Moodle App API.
It normally goes like this:

1. After click on the Moodle App in Team, it prompts for login.
2. It says you have no course to add.
3. In less than a second the screen changes to the API's login prompt (where you can choose to login to O365 or login manually).
4. Trying to login to O365 usually doesn't do anything.
5. Trying to login manually the screen change to the standard Moodle login page where you can choose OpenID connect.
6. Using OpenID Connect "may" show you the course you can add.  If you have lightspeed mouse hand you can quickly click on the course you want and your save button becomes available before your list disappear and change to the API's login prompt.
7. Click login manually again it will remind you that you are already login and ask you to confirm logout.
8. Confirmed logout and login manually again, you'll get the Moodle site Frontpage inside that tiny API popup.

We are not using any sync feature.

**Comment by bjoerrrrn** [comment]
I have the same problem. Did you solve this? :-(

**Comment by weilai-irl** [comment]
I'll close this as the issue that this is about has been fixed in the latest release 3.9.3 and 3.10.0.

@klovsb and @bjoerrrrn, the issue you described seems to be the same as in #1486, please use that issue for tracking.

Regards,
Lai
