### ISSUE TITLE
local_o365 usersync_test.php phpunit test fail

### ISSUE THREAD

**Issue by OscarNadjar** [microsoft/o365-moodle#1485]
Hi all, i'm getting this error when running the usersync_test.php test any ideas why this could happend?
local_o365_usersync_testcase::test_create_user_from_aaddata with data set "fulldata" (array('Microsoft.WindowsAzure.Active...y.User', 'User', '00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Toronto', 'CA', 'Dev', 'Test', 'testuser1@example.onmicrosoft.com', 'testuser1@example.onmicrosoft.com', 'User1'), array('oidc', 'testuser1@example.onmicrosoft.com', 'Test', 'User1', 'testuser1@example.onmicrosoft.com', 'Toronto', 'CA', 'Dev', 'en', '1', '0', '1'))
moodle_exception: Please set application credentials in auth_oidc first.

**Comment by OscarNadjar** [comment]
Hi, i fix the issue for me, you are using the class declaration for main 
local/o365/classes/feature/usersync/main.php
Line 452. 
<img width="983" alt="Screen Shot 2020-11-30 at 9 23 44 AM" src="https://user-images.githubusercontent.com/66019712/100622109-774be580-32ee-11eb-9f0f-b6892420fdcb.png">
This is for using the internal functions later but it's causing errors for PHPunit, i fix the issue deleting that and using self:: instead 
Lines: 478, 480, 482, 485
<img width="972" alt="Screen Shot 2020-11-30 at 9 27 12 AM" src="https://user-images.githubusercontent.com/66019712/100622371-c7c34300-32ee-11eb-9761-a03b99868465.png">

**Comment by weilai-irl** [comment]
The latest release contains fix to the unit test.
Issue closed.
