### ISSUE TITLE
Unable to make silent SSO work after update

### ISSUE THREAD

**Issue by alusignan** [microsoft/o365-moodle#1486]
I updated the integration plugin from 3.8.0.3 to 3.8.0.4 and since then I am unable to make silent SSO work. I followed the instructions mentioned on the Moodle site for this particular version, but it is still not working. 

Users are prompted to "Connect with Office 365" or "Login manually". The first option doesn't even seems to work while the login manually does.

I can't seem to find what I did wrong here because it was working just fine before the update.

**Comment by bjoerrrrn** [comment]
Seems like this is my problem, too. 

Any news on this?

**Comment by bradnielsen2981** [comment]
I have just installed the Moodle App on Teams, and I also have this problem. I might try reverting the sso files to 3.8.0.3 version see what happens.

**Comment by weilai-irl** [comment]
Hi @alusignan, 

3.8.0.4 upgrade contains a major change in SSO integration, and would require Azure app changes as well as Moodle Teams app upgrade. Please refer to https://docs.moodle.org/310/en/Office365#3.8.0.4_and_3.9.1_release for details. The behaviour in your description suggests it's quite likely that not all required actions were performed.

Please give it a try and let us know if it fixes the issues for you.

Regards,
Lai

**Comment by bradnielsen2981** [comment]
Hi Lai, in your documentation, it says:
3.8.0.4 and 3.9.1 release of the plugins on 29 September 2020 introduced improvements on SSO integration for Moodle in Teams as well as Single Sign Off support, but requires additional actions from Moodle and Azure admins.

What are the **additional actions required?**

**Comment by weilai-irl** [comment]
Hi @bradnielsen2981,

It's the section after the title, up until the next section with title "3.8.0.5 and 3.9.2 release". The document is a bit lengthy, if you look at the ToC of the document, you can get a better idea of what's covered in the additional actions.

Regards,
Lai

**Comment by alusignan** [comment]
I completed the steps in the Azure AD Teams Moodle Integration apps as mentioned in the article (including Teams app update). I double and triple checked. I also upgraded to 3.8.0.5, same issue. I did the installation with another client and we also had the same issue (this one was done from scratch). 

Maybe I am missing something, but I cannot find it at all. 

I don't know if I should open another issue, but it seems like I cannot automatically connect existing accounts to the plugin without using the Microsoft Block, is that normal? I found that in the testing phase it seemed like I was able to do that.

**Comment by bradnielsen2981** [comment]
Same here. I think it might be related to the SSO_end or perhaps Moodle web services. For some reason, briefly the Moodle Tab in Teams shows a list of Moodle courses before it bounces back to: 
"Connect with Office 365" or "Login manually"

**Comment by bradnielsen2981** [comment]
@alusignan did you have any luck? I just tried out the settings changes again and still no luck.

**Comment by bradnielsen2981** [comment]
Ok so I went a little crazy and added so many reply URLs in Azure that it's not funny. But it seems to work. The only other thing I did was delete Expose API section and do it again (exactly the same). Anyway it now seems to work now...
![Capture](https://user-images.githubusercontent.com/38126504/104918322-4def3200-59e0-11eb-863b-cfffbdb7574c.JPG)

The reply URLs included:

https://progressivelearning.bitnamiapp.com/local/o365/sso_login.php
https://progressivelearning.bitnamiapp.com/local/o365/sso_start.php
https://progressivelearning.bitnamiapp.com/local/o365/sso_end.php

**Comment by alusignan** [comment]
Hi Brad, sorry for the delay in my reply.

I did not had the chance to test the solution, I will try to add the reply URL you mentioned in your post and let you know if that does the trick for me as well. 

Thank you very much for keeping me updated with your findings !

**Comment by alusignan** [comment]
@bradnielsen2981 Are you using the "Connect Manually" or "Connect with Office 365" button?
In my case, the manual one redirects to an ADFS login page which won't "iFrame" in Teams, but that shouldn't be a problem, at least I was hoping... because I thought that I could simply use the Connect with O365" which still does nothing :-(

The thing that frustrates me with this is that we configure all of this plugin for the SILENT SSO !... I could simply cutover my ADFS to Azure AD using SAML2 and then add a "Website" tab in Teams, then the user would click the "Sign-in" button and would be connected "Seamlessly". Basically I try to save my user that one click. 

@weilai-irl  I followed the instructions multiple time, I even tried from "scratch" in a test environment and I get the same results. Can we have more details on this login flow? Where should I be looking for debug errors?

Thank you !

**Comment by alusignan** [comment]
I ran the DevTools to check, maybe someone can help me understand a little more:

When I add the apps in Teams, I get a 401 for the sso_login.php page
![image](https://user-images.githubusercontent.com/11092168/104965404-a7d60480-59ac-11eb-9cce-98973d68db6b.png)
And this is the error associated with the 401 in the console:
![image](https://user-images.githubusercontent.com/11092168/104965713-4febcd80-59ad-11eb-92f2-2e5eaa459aca.png)

By looking at the code, it seems that it is simply unable to do the SSO;

Source: https://github.com/microsoft/moodle-local_o365/blob/master/sso_login.php
![image](https://user-images.githubusercontent.com/11092168/104965558-ee2b6380-59ac-11eb-869b-66fa7b0183b0.png)

Then, when I click on "Connect with Office365" there a is quick pop-up page, but really nothing happens. This is what I see in the console:
![image](https://user-images.githubusercontent.com/11092168/104965631-1c10a800-59ad-11eb-9775-26846af339f4.png)

I am a little out of idea on where to look/what to do. I've checked the documentation multiple times, added / removed all reply URL, added more than required, permissions are good, Teams app updated, IDs good. 

Any help is appreciated.

**Comment by bradnielsen2981** [comment]
@alusignan Actually now its not working for me again :(. It's interesting that if a Moodle Tab is setup in a course (which somehow worked last night) it has no problem going to that course, if you are logged into Moodle. But if you are adding a Moodle Tab, it tries to show a list of courses, **then seems to quickly timeout** and move to the Login buttons page. Im wondering if the issue is a delay in response, so the SSO_login moves to the Login buttons before the response has come back.

**Comment by alusignan** [comment]
My guess is that you were already logged in when you setup / accessed the page. The Moodle creds are cached in the browser so if you open the Moodle app from the Teams Web App those creds will pass through since it is really just an iFrame of the Moodle web page and it "sees" your cached credential.. At least all my testing seems to demonstrate this behavior. If I use another form of authentication I could also use the "Login Manually" method since it would redirect me to /login/index.php (OAuth2.0, SAML2).. but the Moodle App is expecting / using OpenID and it is what it's expecting to complete the SSO. 

I was able to make all that work successfully a couple months ago with version 3.8.0.3, but since the update, none of the SSO works if the user isn't logged in to Moodle beforehand.

Hopefully we find something sooner or later. There may be bugs, but at this pointI am 99.99% certain that I did the configuration correctly on both end.

**Comment by klovsb** [comment]
I have exactly the same issue after upgrading from 3.8.0.3 to 3.8.0.4 or 3.8.0.5 for that matter.  #1466

**Comment by alusignan** [comment]
@weilai-irl  any update ?? Still unable to make it work. I followed ONCE AGAIN line by line the procedure and still doesn't work.

**Comment by weilai-irl** [comment]
Hi @alusignan,

Please give the following steps a try.
1. Could you confirm the login flow used in the auth_oidc plugin configuration please. The Teams SSO would only work when using auth code login flow.
2. Could you confirm that the user experiencing this has logged into Moodle before please, i.e. they have an account, and has a token record saved in mdl_auth_oidc_token table (with "userid" field matching the ID of the user).
3. If both above points are confirmed, could you add the following code to DIRROOT/local/o365/sso_login.php, line 41 please. It will write the upn field data in the access token to the server error log. Check your server error log to get the value, and try to follow the code from line 42 to 51 to see why $loginsuccess is not set to true.
`error_log($payload->upn);`

Please give it a try and let me know how it goes.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

We just made a new release of plugin local_o365 for Moodle 3.9 and 3.10 that contain improvements in Moodle and Teams integration. The new version should fix most issues in the integration, if not all. The release notes for [Moodle 3.9](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m310) and [Moodle 3.10](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m39) are linked.

Please upgrade your plugin [local_o365](https://moodle.org/plugins/local_o365/versions) (and [auth_oidc](https://moodle.org/plugins/auth_oidc/versions) which it depends on) to the latest version and try it out. Please report back any remaining issues found in this issue. The issue will be kept open for one month from today, and will be closed if most issues are confirmed resolved.

Regards,
Lai

**Comment by weilai-irl** [comment]
Issue closed one month after release.
