### ISSUE TITLE
Teams-Integration: Can't choose course from Moodle-App

### ISSUE THREAD

**Issue by dsteiner17** [microsoft/o365-moodle#1487]
Hi everyone

I'm trying to install moodle server with office 365 integraton in our intranet. 

Moodle Server is working (Moodle 3.9.3 (Build: 20201109)).

Office 365 integration (v3.9.2 2020071504, OpenID Connect v3.9.2 2020071502): Users are synced from o365. Groups and teams will be created from new courses.  Login with OpenID Connect is working.

My problem is the moodle bot or moodle app: If i try to add the moodle app to a created team i can't choose a course  and the save button is greyed out ( see picture).
<img width="407" alt="moodle" src="https://user-images.githubusercontent.com/75475548/101146512-5e5b7100-361b-11eb-9ce2-eb219c48233f.PNG">
What I tried so far:

- Did install steps from Bot and Settings twice->no change

- Find logs, moodle server logs nothing noticeable

- Maybe its a firewall issue, that teams can not connect to the moodle server (Intranet). Server is allowed to go to the internet

I'm stuck at the moment, I'm grateful for any help.

Grettings from Germany 

Dominik

**Comment by bjoerrrrn** [comment]
I have the same problem. Did you solve this? :-(

**Comment by weilai-irl** [comment]
Hi @dsteiner17,

This is most likely caused by a misconfiguration. Could you go to the site administration section of your site, go to settings for the local_o365 plugin, go to the "Teams Settings" tab, and confirm the first few steps are all followed please.

Namely:
- Go to Manage authentication and enable OpenID Connect.
- Go to HTTP security and enable Frame Embedding.
- Go to Advanced features and Enable Web Services.
- Go to Manage protocols and Enable Rest protocol.
- Go to External Services to enable Office 365 Webservices.
- Go to Editing role 'Authenticated user' to set "Create a web service token" to "Allow".
- Go to Editing role 'Authenticated user' to set "Use Rest Protocol" to "Allow".

Please give it a try and let us know if this solves the problem.

Regards,
Lai

**Comment by bradnielsen2981** [comment]
Lai, I think this might be the same error as the "silent SSO not working: issue below.
[https://github.com/microsoft/o365-moodle/issues/1486]

**Comment by dsteiner17** [comment]
Hello Lai
I checked all the steps again and settings are OK.
Go to Manage authentication and enable OpenID Connect.
[cid:image001.jpg@01D6E8C1.601E50E0]

  *   Go to HTTP security and enable Frame Embedding.
[cid:image003.jpg@01D6E8C1.601E50E0]

  *   Go to Advanced features and Enable Web Services.
[cid:image005.jpg@01D6E8C1.601E50E0]


  *   Go to Manage protocols and Enable Rest protocol.
[cid:image007.jpg@01D6E8C1.601E50E0]


  *   Go to External Services to enable Office 365 Webservices.
[cid:image009.jpg@01D6E8C1.601E50E0]


  *   Go to Editing role 'Authenticated user' to set "Create a web service token" to "Allow".
[cid:image010.jpg@01D6E8C1.601E50E0]


  *   Go to Editing role 'Authenticated user' to set "Use Rest Protocol" to "Allow".
[cid:image011.jpg@01D6E8C1.601E50E0]

Any other ideas. Thanks for your help so far.

Regards

___________________________________________

Dominik Steiner

Winnen - Ges. für Elektro- und
Kommunikationstechnik mbH

Stich 30c - 52249 Eschweiler
Deutschland
Tel.....: +49 (2403) 7046-17
E-Mail..: mailto:dsteiner@winnen.de

Sitz der Gesellschaft: Eschweiler
Handelsregister Aachen - HRB 11001
Geschäftsführer: Hans Winnen, Rainer Winnen

Von: Lai Wei <notifications@github.com>
Gesendet: Donnerstag, 7. Januar 2021 16:54
An: microsoft/o365-moodle <o365-moodle@noreply.github.com>
Cc: Steiner, Dominik <dsteiner@winnen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/o365-moodle] Teams-Integration: Can't choose course from Moodle-App (#1487)


Hi @dsteiner17<https://github.com/dsteiner17>,

This is most likely caused by a misconfiguration. Could you go to the site administration section of your site, go to settings for the local_o365 plugin, go to the "Teams Settings" tab, and confirm the first few steps are all followed please.

Namely:

  *   Go to Manage authentication and enable OpenID Connect.
  *   Go to HTTP security and enable Frame Embedding.
  *   Go to Advanced features and Enable Web Services.
  *   Go to Manage protocols and Enable Rest protocol.
  *   Go to External Services to enable Office 365 Webservices.
  *   Go to Editing role 'Authenticated user' to set "Create a web service token" to "Allow".
  *   Go to Editing role 'Authenticated user' to set "Use Rest Protocol" to "Allow".

Please give it a try and let us know if this solves the problem.

Regards,
Lai

**Comment by nenorojas** [comment]
Hi @dsteiner17, 

Can you please double check if you have modified the Azure App with the extra details from this page:

![image](https://user-images.githubusercontent.com/3680797/104581225-2f8edc80-5656-11eb-9601-639f73c62a11.png)

https://docs.moodle.org/310/en/Office365#Update_Azure_app_settings

![image](https://user-images.githubusercontent.com/3680797/104581314-4cc3ab00-5656-11eb-8c51-670455e64df9.png)

![image](https://user-images.githubusercontent.com/3680797/104581341-59480380-5656-11eb-96ab-80b4d9cce4c9.png)

![image](https://user-images.githubusercontent.com/3680797/104581368-61a03e80-5656-11eb-90ae-be9fde02d08c.png)

The items above are not yet implemented by the powershell script provided with the plugin, so they need to be done manually if you are using the latest versions of the plugins. 

After you double check that all items above are done, you need to generate a new manifest file to replace the Moodle app on your Teams:

![image](https://user-images.githubusercontent.com/3680797/104581565-a926ca80-5656-11eb-8a1b-a881f226f563.png)

Please let us know if this works for you.

Regards

Oswaldo

**Comment by bradnielsen2981** [comment]
@dsteiner17  did you have any luck? I feel like I have followed the instructions above a dozen times and still no success..

**Comment by dsteiner17** [comment]
For me it worked partially. I followed all the steps, URL in exposed-API  and Json-file of the teams app is the same. Teams-Web-App is working without problems.
Teams desktop app is not. Here i have no course to choose as before. If i install the app with webapp in desktop app the tab is emtpy. I tried from different locations so i can exclude the firewall as point of failure. Any other ideas? Thanks for all of your help so far.

Regards Dominik


___________________________________________

Dominik Steiner

Winnen - Ges. für Elektro- und
Kommunikationstechnik mbH

Stich 30c - 52249 Eschweiler
Deutschland
Tel.....: +49 (2403) 7046-17
E-Mail..: mailto:dsteiner@winnen.de

Sitz der Gesellschaft: Eschweiler
Handelsregister Aachen - HRB 11001
Geschäftsführer: Hans Winnen, Rainer Winnen

Von: Brad Nielsen <notifications@github.com>
Gesendet: Freitag, 15. Januar 2021 10:19
An: microsoft/o365-moodle <o365-moodle@noreply.github.com>
Cc: Steiner, Dominik <dsteiner@winnen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/o365-moodle] Teams-Integration: Can't choose course from Moodle-App (#1487)


@dsteiner17<https://github.com/dsteiner17> did you have any luck? I feel like I have followed the instructions above a dozen times and still no success..

**Comment by nenorojas** [comment]
@dsteiner17, a few more items to check: 
1) Please check if there's no problems with SSL certificates, you can use this site to check: https://www.ssllabs.com/ssltest/ 
2) You might be facing the same issue of this related case #1138  , so please check if don't need to change server configuration: https://github.com/microsoft/o365-moodle/issues/1138#issuecomment-545733385
3) Please also check if you have completed the MFA configuration for your test user https://github.com/microsoft/o365-moodle/issues/1138#issuecomment-651245736, if it's working on the Teams-Web-App and not working on the Desktop, that might be the case.

**Comment by nenorojas** [comment]
Hi @dsteiner17 ,

Could you please confirm if you could sort this issue after checking the 3 items mentioned above?

Regards

**Comment by nenorojas** [comment]
And if possible, please confirm if you have the Teams theme https://moodle.org/plugins/theme_boost_o365teams https://github.com/microsoft/o365-moodle/issues/1138#issuecomment-804383288

**Comment by weilai-irl** [comment]
Hi all,

We just made a new release of the local_o365 plugin, which contains improvements in Moodle and Teams integration. The new version should fix most issues in the integration, if not all. The release notes for [Moodle 3.9](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m310) and [Moodle 3.10](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m39) are linked.

Please upgrade your plugin [local_o365](https://moodle.org/plugins/local_o365/versions) (and [auth_oidc](https://moodle.org/plugins/auth_oidc/versions) which it depends on) to the latest version and try it out. Please report back any remaining issues found in this issue.

The issue will be kept open for one month from today, and will be closed if most issues are confirmed resolved.

@dsteiner17, please also note that if your Moodle site is not publicly accessible, you will not be able to access it via Moodle tab from Teams desktop or mobile app, but you can access it using the Teams web app. Could you confirm this is your case please.

Regards,
Lai

**Comment by andrewbroekman** [comment]
Good evening all,

I am trying to integrate the Teams bot with Moodle. I have followed all steps supplied on the Moodle site at https://docs.moodle.org/311/en/Microsoft_365.

**Version Information**
- Moodle Version: 3.10.5+ (Build: 20210723)
- local_o365 Version: 3.10.3 (Build: 2020110904)
- local_office365 Version: 3.10.3 (Build: 2020110904)
- auth_oidc Version: 3.10.2 (Build: 2020110903)

**Checklist**
- Users can sign-in using SSO
- Users sync is working
- Create a Moodle Application
- Create a Moodle Teams Application
- Setup/ Verify Setup
    - Reply URL Correct
    - Microsoft Graph API active.
    - Application Permissions are correct.
    - Delegated Permissions are correct.
- Teams Settings/ Check Moodle settings
    - Open ID Connect was already enabled
    - Webservices were already enabled and frame embedding is also allowed
    - REST Protocol was already enabled
    - O365 Webservices were already enabled
    - Permission to create a web service token was already granted
    - Permission to use REST Protocol was already granted

I have enabled App Service Logs on Azure and attached the output to this ticket. I noticed at the top that there are _[onTurnError]: Error: Refresh access token failed with status code: 400_ errors. 

When testing the bot from Azure itself, I also observe the attached errors of the application trying to read the property '__' of undefined.

Currently we are unable to give the bot any command, i.e. Help of Feedback.

I have revalidated all the steps in the documentation from _Teams Settings/Register Application in Azure_ to _Team Settings/Add Moodle app to Teams_. Any assistance would be appreciated in confirming whether the issue is my side or possibly in the plugin.

[app_service.log](https://github.com/microsoft/o365-moodle/files/6895974/app_service.log)

Regards,
Andrew

    -

**Comment by weilai-irl** [comment]
Hi @andrewbroekman, 

Please log your questions in a separate issue, as it's a different from the questions raised in this github issue.

Regards,
Lai

**Comment by weilai-irl** [comment]
Original issue closed one month after release.
