### ISSUE TITLE
Error in API-Call: Ivalid Version in Azure AD Application Registration

### ISSUE THREAD

**Issue by thrombus77** [microsoft/o365-moodle#1489]
Since the Update to Moodle 3.9.3 und Plugin Version 3.9.2 our users can't login anymore with their Office 365 Account. We've created another App in Azure AD (manual and with the script) to ensure that it's not a faulty configuration in the App but get the same error-message:

Fehler bei API-Aufruf: Invalid version: xxx.onmicrosoft.com (where xxx is our domain)
Weitere Informationen über diesen Fehler

×Debug-Info:  
Error code: erroro365apibadcall_message
×Stack trace: 
line 288 of /local/o365/classes/rest/o365api.php: moodle_exception thrown
line 406 of /local/o365/classes/rest/azuread.php: call to local_o365\rest\o365api->process_apicall_response()
line 136 of /auth/oidc/classes/loginflow/base.php: call to local_o365\rest\azuread->get_user()
line 205 of /auth/oidc/auth.php: call to auth_oidc\loginflow\base->get_userinfo()
line 4099 of /lib/moodlelib.php: call to auth_plugin_oidc->get_userinfo()
line 4582 of /lib/moodlelib.php: call to update_user_record_by_id()
line 154 of /login/index.php: call to authenticate_user_login()

Moodle Health Check shows no errors. In Azure AD the App shows a successful login of the user, but I think that the moodle-plugin does not receive the user ID. 
We really need our users to be able to login with their Office365-Account. What can we do?

**Comment by djbren** [comment]
Hello, i also have same error with moodle 3.9.2 not 3.9.3 and Moodle Health Check shows no errors 

local_o365\rest\azuread::get_application_info:123: Error response received. Data: Array ( [code] => ResourceNotFound [message] => Invalid version: 
thanks

**Comment by weilai-irl** [comment]
Hi @thrombus77, 

Based on the error details pasted, it looks like you are calling the Azure AD Graph API for authentication. This was how it was done before, but the plugin has mostly moved to use the Microsoft Graph API for most of its calls now. The reason you still make calls to the old Azure AD Graph API might be a hardcoded site-wide setting. Could you check the config.php of your Moodle site, and look for a setting with name "local_o365_forcelegacyapi". If you see it, please remove the line, purge cache, and try again. If you can't find it, you may want to check your mdl_config table to see if it's saved in the database. This cannot be set from the site administration section from UI.

Please give it a try and let us know if it solves the problem.

Regards,
Lai

**Comment by thrombus77** [comment]
Hello Lai,
thanks a lot! It was an old entry in the config.php. "local_o365_forcelegacyapi=true". Our Site is working again!
Greets
Sam
