### ISSUE TITLE
error/auth oidc/exception tokenemptyuserid

### ISSUE THREAD

**Issue by claw801010** [microsoft/o365-moodle#1500]
#######VERSION AND SUMMARY#####
New integration of Moodle 3.10+ (Build: 20201211) and the latest suite of o365-moodle integration plugin 3.9.2 2020071504  on NAME="Ubuntu" VERSION="18.04.3 LTS (Bionic Beaver)". Experiencing userid=0 in db entry for auth_oidc table and error message of "The existing token for this user does not contain a valid user ID." on Moodle.

Client key and secret key are correct, service enabled and able to get to o365 redirect, but when Azure RMS redirects back to the moodle instance, we receive the error message:
The existing token for this user does not contain a valid user ID. Please contact your administrator.

Upon clicking on the link is when I see the error/auth oidc/exception tokenemptyuserid on the moodle.org site displayed.

If there are more detailed logs, please direct me to collecting them. I have tried in /var/log and the reports/logs on the Moodle UI.

I did check the mariadb and saw my initial user had userid of 0, so I deleted it and tried again, but the exact same issue happens and the user is re-created with userid =0:
select * from mdl_auth_oidc_token where userid=0;
| id | oidcuniqid | username | userid | oidcusername  | scope  | resource   | authcode |

|  1 | b257d127-1008-487e-bfba-994260ac2751 | username@domain.com |      0 | username@domain.com | Calendars.ReadWrite Directory.AccessAsUser.All Directory.ReadWrite.All email Files.ReadWrite Group.ReadWrite.All MailboxSettings.Read MailboxSettings.ReadWrite Notes.ReadWrite.All offline_access openid profile Sites.Read.All User.Read User.ReadWrite.All | https://graph.microsoft.com | AUTHCODEREMOVEDFORGITHUBPOST

The 365 sync was not happening before indicating the system token error, but as of this morning it is happening:
Scheduled task complete: Refresh system API user refresh token (local_o365\task\refreshsystemrefreshtoken)
Execute scheduled task: Process Match Queue (local_o365\task\processmatchqueue)
... started 10:29:46. Current memory use 4.9MB.
... used 2 dbqueries
... used 0.0066819190979004 seconds
Scheduled task complete: Process Match Queue (local_o365\task\processmatchqueue)
Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
... started 10:29:46. Current memory use 4.9MB.
...... Starting sync
...... No skiptoken (full) stored.
...... Forcing full sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Clearing skiptoken (full) (none received)
...... 1039 users received. Syncing...

####START DETAILED LOGS FROM MOODLE GUI#######

Time | User full name | Affected user | Event context | Component | Event name | Description | Origin | IP address
-- | -- | -- | -- | -- | -- | -- | -- | --
16 December 2020, 11:11 AM | - | - | System | System | User login failed | Login failed for user ‘username@domain.com'.   User does not exist (error ID '1'). | web | 192.168.10.145
16 December 2020, 11:11 AM | - | - | System | OpenID Connect | Debug message | oidcclient::rocredsrequest: Error in   rocredsrequest request Data: (string)Error in OpenID Connect: AADSTS50076:   Due to a configuration change made by your administrator, or because you   moved to a new location, you must use multi-factor authentication to access   '00000003-0000-0000-c000-000000000000'. Trace ID:   9cf5fa8e-a05c-4c7b-aea0-2ba3b6952100 Correlation ID:   29fdc971-76fa-4e50-8cf2-4eeb1896c2fb Timestamp: 2020-12-16 18:11:57Z | web | 192.168.10.145
16 December 2020, 11:11 AM | - | - | System | OpenID Connect | Debug message | auth_oidc\oidcclient::rocredsrequest:239:   Error response received. Data: Array ( [error] => interaction_required   [error_description] => AADSTS50076: Due to a configuration change made by   your administrator, or because you moved to a new location, you must use   multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.   Trace ID: 9cf5fa8e-a05c-4c7b-aea0-2ba3b6952100 Correlation ID:   29fdc971-76fa-4e50-8cf2-4eeb1896c2fb Timestamp: 2020-12-16 18:11:57Z   [error_codes] => Array ( [0] => 50076 ) [timestamp] => 2020-12-16   18:11:57Z [trace_id] => 9cf5fa8e-a05c-4c7b-aea0-2ba3b6952100 [correlation_id]   => 29fdc971-76fa-4e50-8cf2-4eeb1896c2fb [error_uri] =>   https://login.microsoftonline.com/error?code=50076 [suberror] =>   basic_action ) | web | 192.168.1
#######END DETAILED LOGS######

NOTE: Yes, this user has MFA and I complete the MFA correctly. I have also tried this with a user without MFA and receive the same issue with userid0 in the db table.

#############IN CLOSING#################
Your assistance and guidance is greatly appreciated. Please direct me to the right location for more detailed logs and any insight you may have to the root cause of the issue. Thank you!

**Comment by weilai-irl** [comment]
Hi @claw801010,

First of all, could you confirm which "Authentication Method (auth_oidc | loginflow)" setting is used on the "OpenID Connect" plugin configuration page please. Is it "Authorization Code Flow" or "Resource Owner Password Credentials Grant"?

Assuming "Authorization Code Flow", which is the recommended option is used, when syncing a new user, it will create a new record in mdl_auth_oidc_token table with userid 0 first, then immediately it will try to determine the userid of the user. If one is found, the record will be updated using the userid immediately; otherwise, the record with userid 0 will be deleted immediately. If you see a record in the table with userid, it would indicate this logic is broken at some point, and you may need to dig it deeper to see what caused this.

I hope this helps.

Regards,
Lai

**Comment by barry-matthias** [comment]
we too are seeing this in the database for the oidc tokens table as the tables default is too set the user id too 0 even tho in the lms there is no user id 0 and can never be this value. I would have thought setting this value to null would have been the norm?

we checked the mdl user table for the username which matches the entry in the oidc token table and the user id is there to take however for some reason the module doesnt find it and fails to delete the userid of 0 from the table causing the issue when the user next attempts to login to the site using oidc authentication.

I do not know how the oidc module works as i am not a dev but i can say setting the default user id to be 0 should not be the default
