### ISSUE TITLE
Users who bookmark the o365 login page, will get the error "unknown state"

### ISSUE THREAD

**Issue by BenKelada** [Microsoft/o365-moodle#151]
# Users who bookmark the o365 login page, will get the error "unknown state"

As the auth method is storing its own token and matching the return token, if the user bookmarks a "stale" login page, the next time they visit the bookmark it will receive the unknown state error.
Clicking continue usually does the redirects to get them logged in successfully but its not a great user experience.
suggestions to fix: instead of "unknown state" maybe populate a moodle popup notification and then forward them to the default login page? 

oidc/classes/loginflow.php:143-145
instead of: 

``` php
        if (empty($staterec)) {
            throw new \moodle_exception('errorauthunknownstate', 'auth_oidc');
        }
```

``` php
        if (empty($staterec)) {
            redirect(get_login_url());
        }
```

**Comment by jamesmcq** [comment]
@BenKelada Users should be able to bookmark [moodlesite]/auth/oidc/ (remember the ending "/") and complete the regular Office 365 login process.
