### ISSUE TITLE
Azure AD permissions with Moodle 3.9

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1530]
We have installations with only mimimum permissions granted in the Azure AD Application, namely User.Read.
This has worked previsously in Moodle 3.5 to allow users to log in, which is all that is needed.

However, in Moodle 3.9 creating Moodle account while logging in the first time dosn't work (logging in with existing accounts still does). It seems to require User.ReadWrite.All permission for both delegated and application permissions to work.

Is this right? What has changed that makes needs permissions?
And why does the itegration need Write permissions at all when it doesn't write anything from Moodle to Azure AD?

**Comment by kkiiskin** [comment]
Hi @weilai-irl 

thanks for this answer and looking forward to the more detailed guide.

I have found out some of the requirements by consulting Graph Api documentation and by trial and error :)
Like that you need Group.Read.All if you are using O365group membership as restriction in usersync.

**Comment by weilai-irl** [comment]
Hi @kkiiskin,

The document update finally happened. Please find more information about Azure app permissions in new section in the document at https://docs.moodle.org/311/en/Microsoft_365#Azure_app_permissions.

I'll close this ticket for now.

Regards,
Lai
