### ISSUE TITLE
O365 site and Groups created from Moodle Groups

### ISSUE THREAD

**Issue by ChrisCYC** [microsoft/o365-moodle#1533]
Hi,

When a user joins a group within a Moodle course that has not been selected for Teams import , a SharePoint group and site automatically gets created for that Moodle group. Is there anyway to stop this from happening?

What is even more surprising is that this is happening on Moodle courses that I haven't selected for Teams creation in the Teams customization sync settings option.  

Moodle 3.9,
Microsoft Office 365 Integration 3.9.1

I think it is coming from the scheduled task Create user groups in Office 365 \local_o365\task\groupcreate. But this also controls Team creation from selected Moodle courses.

Any ideas?

**Comment by weilai-irl** [comment]
Hi @ChrisCYC,

First of all, let me describe the current behaviour in relation to Moodle course group creations:
 - If sync is disabled on the course in which a course group is created, nothing will happen.
 - If sync is enabled on the course in which a course group is created, then regardless of "Teams" option is enabled for the course, an Office 365 group is always going to be created, which will result in creation of all resource related to the group.

The action to create Office 365 groups from Moodle course groups are triggered from an observer function in Moodle listening to the group created event, so it happens immediately after the Moodle course group is created, and is not triggered by the scheduled tasks.

I confirm there is no configuration setting to disable this feature currently. You can log this as a feature request if needed.

Regards,
Lai

**Comment by ChrisCYC** [comment]
Hi @weilai-irl ,

Thank you for that. I now see where my issues lie. All the best,

Kind regards

Chris
