### ISSUE TITLE
Microsoft Office 365 SSO setup giving exception error on login

### ISSUE THREAD

**Issue by hadimiqbal** [microsoft/o365-moodle#1538]
Microsoft Office 365 SSO setup giving exception error on login
I have setup the plugins and reauthenticated several times with all the necessary permissions granted as per the checks
I  still get the exception error when i use the microsoft account with the oidc plugin.

Exception - Call to undefined method local_o365\feature\usersync\
![image](https://user-images.githubusercontent.com/77441749/104587221-b8d7fa80-56ba-11eb-8388-55b69b5239b2.png)
main::fieldmap_require_graph_api_call()

**Comment by weilai-irl** [comment]
Hi @hadimiqbal,

Could you please confirm if local_o365 plugin is installed please.
 - auth_oidc can work without local_o365 plugin, when doing so, please ensure there is no records about local_o365 in any database tables in your database, especially in mdl_config_plugins table.
 - if local_o365 is used, please ensure it has the latest version.

Regards,
Lai

**Comment by hadimiqbal** [comment]
Yes i have the latest local_o365 installed

Cheers Hadi
![image](https://user-images.githubusercontent.com/77441749/104648773-c1a2ed80-5707-11eb-9686-921b5c310f48.png)

**Comment by hadimiqbal** [comment]
I think i have sorted the error, i had the Legacy api on aswell
