### ISSUE TITLE
Support for Microsoft Forms in oEmbed plugin and addition of 'My Forms' to the Microsoft Block

### ISSUE THREAD

**Issue by nimojg-microsoft** [Microsoft/o365-moodle#154]
The URL to link to from the Microsoft block should be: https://forms.office.com/Pages/DesignPage.aspx# 

For embedding, you should be able to test with the following link: 

<iframe width="640px" height= "480px" src= https://forms.office.com/Pages/ResponsePage.aspx?id=NGbdODEQUEyptNFs2dl9V4fmgU9B6epOrkq3vPxu0DVUQlJDRU9ITDNRN1FSOUZTSzI1UEpZOVhPNi4u&embed=true frameborder= "0" marginwidth= "0" marginheight= "0" style= "border: none; max-width:100%; max-height:100vh"allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>

**Comment by vinhub** [comment]
Icons to use: 
![forms logo_favicon_16](https://cloud.githubusercontent.com/assets/1817329/16404945/088ad560-3d21-11e6-83ba-84117609d067.png)
![officeforms_0365launcher_128px-01](https://cloud.githubusercontent.com/assets/1817329/16404948/0dc3a91c-3d21-11e6-8774-56d7348750c3.png)

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/164

**Comment by aashaymz** [comment]
Test Cases:

- If Office forms is enabled for the subscription,
a) **For Microsoft block** -> one need to enable Show "My Forms" settings from Microsoft block settings. Microsoft Forms link start showing up in block which takes one to the Microsoft Forms i.e. https://forms.office.com/Pages/DesignPage.aspx#

b) **For oEmbed plugin** -> one need to enable "Forms" settings from oEmbed Filter settings. Now you can add the the form URL(https://forms.office.com/Pages/DesignPage.aspx#FormId=a_DsJJKJ2km8GskiRM982qLF7QyHsAJGpW2seB5dl65UNkhHQlNSMlQ3MzdGVFhRR0hHNlEzNk0yTi4u) in any assignment which will get swap with an embedded version using code. It will also works with multiple Microsoft Forms links are added in an assignment.
