### ISSUE TITLE
New events in Outlook calendar should have a link back to the corresponding Moodle event

### ISSUE THREAD

**Issue by vinhub** [Microsoft/o365-moodle#155]
When calendar sync results in creating new events in Outlook, those events should have a link back to the original Moodle event e.g.  (http://wwedudemo.westus.cloudapp.azure.com/moodle/calendar/view.php?course=5&view=day&time=1464850800#event_87)

This is the remaining part from https://github.com/Microsoft/o365-moodle/issues/143

**Comment by amygroshek** [comment]
To be cherry-picked into MSFTMPP-519, which contains documented and PRed in the following github issues: 
* Github issue: https://github.com/Microsoft/o365-moodle/issues/143
* PR: https://github.com/Microsoft/o365-moodle/pull/153

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/158
