### ISSUE TITLE
Problem with Teams that have more than 100 members

### ISSUE THREAD

**Issue by jamaur** [microsoft/o365-moodle#1552]
Hi,

I ran into an issue with the teams integration when there were more than 100 members. Let's say there is a course with 105 users. The cronjob would only get the first 100 from the Graph API and then "re-add" the 5 members. The users would then get a notification in teams that they've been added every time the cron ran.

The issue was with classes/rest/unified.php, function get_group_members. I saw the function is only called in the resync_group_membership function in the coursegroups.php class. My solution was to re-write get_group_members to handle pagination and return all of the members and not just the top 100.

Here is the specific patch:
https://github.com/jamaur/moodle-local_o365/commit/963f8b7b3fcf929febf452d297c22a307cabedc5

I found an easy way to test is to change line 521 and add the $top parameter. Something like this:

 $endpoint = '/groups/'.$groupobjectid.'/members?$top=2';

Where 2 is the number of results that the Graph API will return ;) .

Hope that's useful!

**Comment by weilai-irl** [comment]
Hi @jamaur,

Thank you for reporting the issue. I have developed a fix to the issue using a slightly different approach, and include it in the latest 3.9.4 and 3.10.1 release. Please check it out.

Regards,
Lai

**Comment by jamaur** [comment]
Hi @weilai-irl,

Thanks for the follow-up. I was doing a rebase of the latest release and the fix appears to have a type in the odata.nextLink. I created a [pull request to fix the issue](https://github.com/microsoft/moodle-local_o365/pull/33).

**Comment by weilai-irl** [comment]
Hi @jamaur,

Thank you for reporting this. The fix will be included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @jamaur,

Thank you again for reporting this, and for providing a solution. The fix has been included in the latest release of the plugins.

The issue will be closed now.

Regards,
Lai
