### ISSUE TITLE
Error code: errorcouldnotrefreshtoken when accessing Calendar sync settings

### ISSUE THREAD

**Issue by ghost** [microsoft/o365-moodle#1555]
While not widespread, we are seeing certain users on 2 sites receive this error when accessing their Outlook calendar sync settings in the Microsoft block. Both sites running version 3.9.2 and users are not using OIDC for login, but an alternative login method. Users are matched via sync and connected. We have tried un-matching them, purging the database tables of all relevant information and matching again. The result is the user can access the settings one time only and then the error returns. Any insight into this would be greatly appreciated. Thanks!!

Stack trace:
Could not refresh token

More information about this error

×Debug info:
Error code: errorcouldnotrefreshtoken
×Stack trace:
line 448 of /local/o365/classes/oauth2/token.php: moodle_exception thrown
line 116 of /local/o365/classes/rest/o365api.php: call to local_o365\oauth2\token->refresh()
line 150 of /local/o365/classes/rest/o365api.php: call to local_o365\rest\o365api->checktoken()
line 140 of /local/o365/classes/rest/unified.php: call to local_o365\rest\o365api->apicall()
line 834 of /local/o365/classes/rest/unified.php: call to local_o365\rest\unified->apicall()
line 348 of /local/o365/classes/feature/calsync/main.php: call to local_o365\rest\unified->get_calendars()
line 73 of /local/o365/classes/page/ucp.php: call to local_o365\feature\calsync\main->get_calendars()
line 144 of /local/o365/classes/page/base.php: call to local_o365\page\ucp->mode_calendar()
line 30 of /local/o365/ucp.php: call to local_o365\page\base->run()

And in the error logs this:
local_o365\oauth2\token::get_for_new_resource: Problem encountered getting a new token. Data: Array ( [tokenresult] => Array ( [error] => invalid_grant [error_description] => AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2021-01-15T15:45:09.2437003Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2021-01-29T18:27:40.0000000Z'. Trace ID: 5208b946-8e9b-403d-9ca8-1af3f6284200 Correlation ID: 2a0862bd-91ce-4717-8242-96f6eecb3d19 Timestamp: 2021-02-01 16:55:25Z [error_codes] => Array ( [0] => 50173 ) [timestamp] => 2021-02-01 16:55:25Z [trace_id] => 5208b946-8e9b-403d-9ca8-1af3f6284200 [correlation_id] => 2a0862bd-91ce-4717-8242-96f6eecb3d19 [error_uri] => https://login.microsoftonline.com/error?code=50173 ) [resource] => https://graph.microsoft.com )

**Comment by weilai-irl** [comment]
The issue is caused by the fact that the integration used to use each users' own token for calendar sync. If the user's token gets expired  and cannot be refreshed, calendar sync would fail with this error.

The calendar sync feature has been updated to use application token, so as long as the application is not expired, this shouldn't happen any more.

Regards,
Lai
