### ISSUE TITLE
Locking firstname, lastname, email in base.php will not work in 3.9

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1557]
Dear community,

to prevent users from changing their first name, last name and email in the moodle profile we did some changes in the base.php-file (/auth/oidc/classes/loginflow/base.php). Eg, in line 46, 48, 50 we changed it from 'unlocked' to 'locked':

```
 ];
        $storedconfig = (array)get_config('auth_oidc');
        $forcedconfig = [
            'field_updatelocal_idnumber' => 'oncreate',
            'field_lock_idnumber' => 'unlocked',
            'field_updatelocal_lang' => 'oncreate',
            'field_lock_lang' => 'unlocked',
            'field_updatelocal_firstname' => 'oncreate',
            'field_lock_firstname' => 'locked',
            'field_updatelocal_lastname' => 'oncreate',
            'field_lock_lastname' => 'locked',
            'field_updatelocal_email' => 'oncreate',
            'field_lock_email' => 'locked',
        ];

```
It will work in older Plugins for Moodle 3.5, but in 3.9 users is still allowed to change the settings although the settings will be done. See also https://github.com/microsoft/o365-moodle/issues/1268

Any ideas what's wrong?

thanks, br Anton

**Comment by AntonT76** [comment]
please note: I checked some settings in plugin-settings in Moodle:

User Field Mapping (local_o365|fieldmap):
- change firstname/lastname/email to "on login & creation" --> field can be edited by users
- change firstname/lastname/email to "on creation" --> field cannot be edited by users, but any changes in Azure AD (change names, e-mail, etc.) will not be synchronised to Moodle
- change firstname/lastname/email to "on login" --> field can be edited by users, field will be updated at user login, but fields have no entries if new users will be synchronised to Moodle

so, it would be nice if there is a possibility where users a.) are not allowed to change this fields and b.) any user changes in Azure AD will be synchronised to Moodle and c.) new users will be synchronised to Moodle.

br, Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

The next release of the plugins will include the long waited change to move field mapping settings from local_o365 to auth_oidc. Site admins can use the standard Moodle authentication integration feature to control whether mapped user profile fields are locked or not. This should answer the questions asked in this one.

I'll update the issue when the release is made, or if you want, you can try it out using the linked pull requests.

Regards,
Lai

**Comment by kang17** [comment]
Hi @weilai-irl , do you know when this next update that includes this fix will be released- this is a big problem for us as many students have since changed their names to unidentifiable names.

**Comment by weilai-irl** [comment]
Hi @kang17,

The next release will be in place by the end of September.

Regards,
Lai
