### ISSUE TITLE
Teams SSO login not working when adding app manually

### ISSUE THREAD

**Issue by ghost** [microsoft/o365-moodle#1580]
Hi all,

3.10.0 plugin suite
Moodle 3.10.1
Using full integration with OpenID Connect authentication
Ran full sync to create user accounts in Moodle
User logs into Moodle and accesses Teams via Microsoft block

In testing we found the following:
In the Teams web app, the Moodle app tab is added to newly created teams via the integration teams sync and when clicked the course page is embedded, so this piece is working properly.

However,

In the Teams web app for pre-existing teams (not created via the integration), when the Moodle app is added manually, a list of courses appears briefly and disappears being replaced by two login buttons, manual and o365. Logging in does not produce the list of courses.

In the Teams desktop app, the Moodle tab is being added to new teams created via the teams sync, but when clicked, the popup just shows two login buttons - manual and o365. Logging in does not produce the list of courses.

Have triple checked all steps of configuration. Run PowerShell script and made additional config changes as per the new instructions.

**Comment by weilai-irl** [comment]
Hi @daniel-hefley,

What you described is very strange indeed.

Technically as long as you are using the same Moodle app for Teams created by Moodle, the SSO integration functions work in the same way regardless of how a Moodle tab is created, i.e. they refer to the same file, and call the same function.

The fact that you see different behaviours suggests that you may be using different Moodle apps. Could you check your Teams app catalog, go to the "Built for YOUR ORGANISATION" section to see uploaded apps, and see if you have multiple items there please. The latest version of the plugin allows Moodle site admins to customise app names as well as internal IDs which would help you distinguish between apps created from different Moodle sites, e.g. UAT and live.

Please give it a try and see if this is the issue you experienced.

Regards,
Lai

**Comment by alusignan** [comment]
@daniel-hefley did you have any luck with this, I am facing the same issue where I just see the login buttons but nothing happens after that..
It's really strange even though I too checked multiple times the configuration, I cannot make it work.. 
Any way if you more information, it would be appreciated!

**Comment by daniel-hefley** [comment]
@alusignan Sorry, not yet. This is happening with all our client sites which have upgraded the o365 suite to 3.9.1+ or 3.10+  @weilai-irl Taking into consideration what you said about the possibility of having different Moodle apps in Teams since in some cases clients had 2 apps,  we removed one and still experienced the same behavior. At this point we've also configured additional clients with only one Moodle app in Teams and are still running into the problem. I am attaching the debug data package from one site. Would you mind taking a look at it, if anything just to verify that all looks good? Thanks!
[debug_data_package.txt](https://github.com/microsoft/o365-moodle/files/6148631/debug_data_package.txt)

**Comment by alusignan** [comment]
Thank you for your reply.. Let me know if you find anything. I also tried with a few clients the integration using either Moodle 3.8 or 3.9 with proper plugin. I gave up on trying to making it work for them right now, hoping a new patch will fix everything, but here we are months later with no answers to this problem. There are multiple issues on GitHub stating it. What sucks is that it was working with 3.8.03, like a charm..

Again, let me know if you find anything, I'll do the same as well.

Please note that on another issue, someone told me that they installed Teams Theme for
Moodle as a plugin in issue #1138 .. And it made it work.

**Comment by weilai-irl** [comment]
Hi @daniel-hefley,

If you send me an email with your details, I can try to arrange a call with you to look through the SSO issue in this one.

Regards,
Lai

**Comment by daniel-hefley** [comment]
Hi @weilai-irl,

Thank you for the offer. Very much appreciated. I'll contact you via your email.

**Comment by weilai-irl** [comment]
Hi @daniel-hefley,

Thank you for getting in touch back in March/April. Following the investigations we performed during our call, we have implemented a number of improvements to the Moodle and Teams integration, and they are now included in the latest release of the local_o365 plugin for Moodle 3.9 and 3.10. The new version should fix most issues in the integration, if not all. The release notes for [Moodle 3.9](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m310) and [Moodle 3.10](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m39) are linked.

Please upgrade your plugin [local_o365](https://moodle.org/plugins/local_o365/versions) (and [auth_oidc](https://moodle.org/plugins/auth_oidc/versions) which it depends on) to the latest version and try it out. Please report back any remaining issues found in this issue. The issue will be kept open for one month from today, and will be closed if most issues are confirmed resolved.

Regards,
Lai

**Comment by weilai-irl** [comment]
Issue closed one month after release.
