### ISSUE TITLE
Clean up the text related to User Groups

### ISSUE THREAD

**Issue by vinhub** [Microsoft/o365-moodle#160]
1) We should be calling them “Course Groups” instead to maintain consistency. Here’s how it should read (refer to the image below):
- Disabled: Disables all Course Groups (i.e. Office 365 Groups) integration for all Moodle courses.
- Customize: Allows you to select which courses to create Course Groups (i.e. Office 365 Groups) for, as well as select which Group features are exposed in the Microsoft block for each course.
- Enable All: Enables Course Groups (i.e. Office 365 Groups) for all courses and exposes all Group features in the Microsoft block for all courses.
- We should indicate somewhere that it is “Default: Disabled”.
- Update text: 
"If enabled, this will create and maintain an Office 365 Group for every course on the site. This will create any needed Groups each cron run (and add all current members). After that, group membership will be maintained as users are enrolled or unenrolled from Moodle courses.  Note: This feature requires the Microsoft Graph API to be enabled. "

![image003](https://cloud.githubusercontent.com/assets/1817329/16405019/dd8f3166-3d21-11e6-8731-020df1ddad45.jpg)

2) Also, in the Options tab  – Remove following links to documentation:
- user sync documentation.
- Setup instructions and documentation.
- Read more about connecting Moodle and SharePoint.
 
3) Under “User Sync” there is a misspelling of “frequency”

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/162

**Comment by aashaymz** [comment]
Test Cases:

- User Groups to Course Groups
- Text have been changed for all the 3 radio btton options
- Updated the description text for User Groups
- Corrected the typo for 'frequency'
- Removed mentioned links to documentation
