### ISSUE TITLE
Number of Unread Outlook Messages in Microsoft Block

### ISSUE THREAD

**Issue by nimojg-microsoft** [microsoft/o365-moodle#161]
A nice feature would be to list the number of unread email messages and link to a users Outlook from the Microsoft block.

**Comment by gunnar-restorff** [comment]
It would be very nice if O365 users could see the most recent email/messages - or at least no. of unread emails - when they log in to moodle. So this would be really nice - is there any progress wrt. this?

**Comment by nimojg-microsoft** [comment]
@gunnar-restorff We don't have any immediate plans to add this. Any chance you might able to contribute this feature? We'll happily review your PR

**Comment by nenorojas** [comment]
Hi @nimojg-microsoft , @gunnar-restorff , 

This enhancement request is not in the plans for the foreseeable future, so I'm closing this request.

Regards
