### ISSUE TITLE
Error when a deleted user tries to log in via OIDC

### ISSUE THREAD

**Issue by jbriggscmet** [microsoft/o365-moodle#1613]
## Steps to reproduce:

1. Sign in with OIDC / Azure AD [user account created in Moodle automatically]
2. As administrator, delete the previously created account via the Moodle user management pages.
3. As the user in step 1, attempt to log in again using OIDC.

The following error shows:

![image](https://user-images.githubusercontent.com/15365068/110455262-218e9280-80c0-11eb-81f2-e5ef1609e824.png)

This appears to be due to the fact that rows a left lingering in the `mdl_auth_oidc_token` even after a user is deleted.

## Expected outcome

The user should be able to log in again, and have an account automatically provisioned again.

Possible resolution is to remove all rows from `mdl_auth_oidc_token` for the affected user when their account is deleted. This can be achieved by listening for the `core\event\user_deleted` event.

**Comment by weilai-irl** [comment]
Hi @jbriggscmet,

A solution to the issue has been included in the latest release 3.9.4 and 3.10.1 of the plugins. Please upgrade the plugins to try them out.

The issue will be marked closed for now. Feel free to reopen it if the issue is not fixed.

Regards,
Lai
