### ISSUE TITLE
Feature Request: Enable suspended users during sync

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#1618]
Hello,

we have some users, who have temporarily access to our Moodle and the Azure AD-group. Sometimes we disable this users directly in Moodle and they will also removed manually from the Azure AD group. After adding them again to the Azure AD-Group, the user will not be enabled in Moodle during sync.

There should be an option in sync setting: "enable suspended users automatically during sync".

thanks, br Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

Is it to say that you want to unsuspend Moodle users who are suspended when the user is received from Azure AD in user sync?

Regards,
Lai

**Comment by AntonT76** [comment]
Hi @weilai-irl ,

> Is it to say that you want to unsuspend Moodle users who are suspended when the user is received from Azure AD in user sync?

yes, that's right.

In addition the following function would also be useful/required: "Suspend user in Moodle if they are removed from Azure AD", see issue https://github.com/microsoft/o365-moodle/issues/1318

thanks
br, Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

The requested feature has been included in the latest release.

For technical details:
 - A new user sync option is added. The option is "Re-enable suspended accounts for users in Azure AD".
 - If the option is checked, when running user sync task, for an Azure AD user with a connected Moodle account, if the user's Azure AD account is active, but the Moodle account is suspended, the Moodle user will be unsuspended.

Regards,
Lai

**Comment by AntonT76** [comment]
Hi @weilai-irl, many thanks for the implementation.
br, Anton
