### ISSUE TITLE
User Sync feature request - allow Azure fields to be mapped to any Moodle field

### ISSUE THREAD

**Issue by jtsafran** [microsoft/o365-moodle#1619]
In the fieldmap setting (User Field Mapping local_o365 | fieldmap), you currently have a pair of drop downs to map available fields in Azure to fields in Moodle.  However, the fields provided for Moodle are not the full list of default fields nor does it allow for custom user fields.  It would be great if this was changed in one of two ways:

1. Have the Moodle drop down populated at load time and include all Moodle user fields, both core and custom profile fields that have been added to a site
2. Change the mapping config to match more closely with those of other Moodle plugins like LDAP, CAS, External Database, etc so a user can map fields manually.  This might not work as well with Azure since the values that can be passed are somewhat static and having the drop down of available attributes is preferred to reduce errors, but it would match the standards of other plugins.

**Comment by weilai-irl** [comment]
Hi @jtsafran,

The upcoming release contains a change to move the field mapping features from local_o365 to auth_oidc, and it will use the standard Moodle authentication plugin integration, which includes all fields.

I'll update the issue again when the change is release, or if you want, you can try the feature out using the linked PRs.

Regards,
Lai
