### ISSUE TITLE
The Moodle plugin does not allow selecting the course to be placed in the Teams tab

### ISSUE THREAD

**Issue by yuryrodrigues** [microsoft/o365-moodle#1620]
In the screen to select the course that will be displayed in the Teams tab, the screen disappears in less than 1 second, which prevents the course from being selected.

Microsoft 365 Integration - 3.9.3
OpenID Connect - 3.9.3
Moodle - 3.9.1

Below is evidence of the problem:

![Aba do Moodle não permite a seleção do curso (1)](https://user-images.githubusercontent.com/7195945/110989112-28333900-8350-11eb-9b61-e1800f26c28b.gif)

**Comment by klovsb** [comment]
@weilai-irl @nenorojas  Exactly what happened to me on #1466.  Great video recap.  Still happening.

**Comment by kkiiskin** [comment]
Hi

We are experiencing this too, same plugin versions but Moodle 3.9.5.

**Comment by kkiiskin** [comment]
Here's what the devtools console outputs for me when the course list disappears:

> POST https://MOODLEURL/sso_login.php 401 (Unauthorized)
successCallback	@	teams_tab_configuration.php:125
r.GlobalVars.callbacks.<computed>	@	MicrosoftTeams.min.js:1
u	@	MicrosoftTeams.min.js:1
n.processMessage	@	MicrosoftTeams.min.js:1
t	@	MicrosoftTeams.min.js:1

**Comment by weilai-irl** [comment]
Hi @yuryrodrigues, @kkiiskin,

The following troubleshooting steps apply to both of you.
 1. Could you confirm the login flow used in the auth_oidc plugin configuration please. The Teams SSO would only work when using auth code login flow.
 2. Could you confirm that the user experiencing this has logged into Moodle before please, i.e. they have an account, and has a token record saved in mdl_auth_oidc_token table (with "userid" field matching the ID of the user).
 3. If both above points are confirmed, could you add the following code to DIRROOT/local/o365/sso_login.php, line 41 please. It will write the upn field data in the access token to the server error log. Check your server error log to get the value, and try to follow the code from line 42 to 51 to see why $loginsuccess is not set to true.

`error_log($payload->upn);`

Please give it a try and let us know how it goes.

Regards,
Lai

**Comment by kkiiskin** [comment]
Hi 

I can confirm that in our setup we use Authorization Code Flow and the user has logged in Moodle before (and is in fact logged in in the same browser while testing Moodle app in Teams). Token record is also correct.

I tried earlier logging the sso_login.php and i seemed that it doesnt even recieve the headers when it tries with  apache_request_headers() on line 33.
Both the $headers and $payload are empty arrays when printed to the log.

**Comment by weilai-irl** [comment]
Hi @kkiiskin,

Thank you for the update. It does lead us closer to the the issue - if the authorization header is missing, there's no way the user can be authorised.

The next step would be to find out why it's missing:
 - When it calls function apache_request_headers() at line 33, does it report any errors.
 - Maybe you can try adding error_log(function_exists('apache_request_headers')); before the line to confirm the function exists?
 - When I Googled "apache_request_headers authorization missing", there are a few answers suggesting the authorization header could be hidden by mod_rewrite rules, and editing .htaccess may make it available, e.g. https://stackoverflow.com/a/34472533, http://docs.php.net/manual/en/features.http-auth.php#114877. However, it seems that only the authorization header was missing in those cases, and in your case no header was returned, which could be different. Could you investigate please.
 - It looks that the only other alternative of calling apache_request_headers() is to use $_SERVER. Please try the steps above first and suggest if we need to go down that route.

Regards,
Lai

**Comment by bradnielsen2981** [comment]
I have tested this now and found a solution for me. In answer to your question..

1. There are no errors with the apache_request_headers() function
2. the function does exist
3. The issue is in the Headers allowed into the Server. When I output the apache_request_headers() the Authorisation key was missing.

So this is what I did to get this working on my test server.

I edited the http.conf file although I believe you can edit the htaccess file to include the following lines:

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
SetEnvIf Content-Type "(.*)" HTTP_CONTENT_TYPE=$1
SetEnvIf Accept "(.*)" HTTP_ACCEPT=$1

<Directory "/opt/bitnami/moodle/local/o365/">
  Header set Access-Control-Allow-Origin "*"
  Header set Access-Control-Allow-Methods "GET, OPTIONS, POST"
  Header set Access-Control-Allow-Headers "origin, x-requested-with, content-type, accept, Authorization"
</Directory>

This seems to work...

**Comment by kkiiskin** [comment]
This worked for us too, thanks @bradnielsen2981 !

But what has changed and where to make these new configurations necessary?

**Comment by yuryrodrigues** [comment]
The procedure not work for me ;/

Here's what the devtools console outputs for me when the course list disappears:

![image](https://user-images.githubusercontent.com/7195945/114195735-1b8e0a80-9927-11eb-84c3-307bbaadf4de.png)

**Comment by yuryrodrigues** [comment]
Bellow follow the error message in plain text:

0-angular-jquery.min-eee9041.js:114 
2021-04-09T14:28:30.936Z AUTHMSAL: Event: adal:tokenRenewFailure, code: invalid_resource|AADSTS500011: The resource principal named api://canalazure.com.br/399ae3eb-1fb7-4161-bd70-192521d07cc5 was not found in the tenant named 4013ef5b-a41a-4410-902b-0b74327c5b0f. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 60c28a3f-af0e-4573-aa53-ad0154e8b301
Correlation ID: 903cfea0-4231-49a9-a268-b60905f06dde
Timestamp: 2021-04-09 14:29:00Z, resource: api://canalazure.com.br/399ae3eb-1fb7-4161-bd70-192521d07cc5, action: resourceDisabled
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
e.logMessage @ 3.2-app.min-5dc2fb6.js:1
e.error @ 3.2-app.min-5dc2fb6.js:1
n.logTokenResponse @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:142
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
$evalAsync @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
g @ 0-angular-jquery.min-eee9041.js:127
$$reject @ 0-angular-jquery.min-eee9041.js:130
reject @ 0-angular-jquery.min-eee9041.js:129
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
Promise.then (async)
n.getPromiseWithTimeout @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
n.acquirePromise @ 3.1-app.min-74276cf.js:1
n.acquireTokenInternal @ 3.1-app.min-74276cf.js:1
n.acquireToken @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
e.retry @ 3.2-app.min-5dc2fb6.js:1
e @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.acquireTokenPostCheckCache @ 3.2-app.min-5dc2fb6.js:1
e.acquireTokenForResource @ 3.2-app.min-5dc2fb6.js:1
p @ 3.2-app.min-5dc2fb6.js:1
t.startTokenRetry @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokensInternal @ 3.2-app.min-5dc2fb6.js:1
e.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:155
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
f @ 0-angular-jquery.min-eee9041.js:155
e.baseMessageHandler @ 3.2-app.min-5dc2fb6.js:1
t.processSDKMessage @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:246
d.<computed> @ 0-angular-jquery.min-eee9041.js:79
e.onMessageCallback @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1

0-angular-jquery.min-eee9041.js:114 
2021-04-09T14:28:30.939Z AUTHMSAL: Attempting to handle auth response: error:invalid_resource|AADSTS500011: The resource principal named api://canalazure.com.br/399ae3eb-1fb7-4161-bd70-192521d07cc5 was not found in the tenant named 4013ef5b-a41a-4410-902b-0b74327c5b0f. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant., resource:api://canalazure.com.br/399ae3eb-1fb7-4161-bd70-192521d07cc5, error mapped to action:resourceDisabled
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
e.logMessage @ 3.2-app.min-5dc2fb6.js:1
e.error @ 3.2-app.min-5dc2fb6.js:1
n.handleAuthError @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:142
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
$evalAsync @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
g @ 0-angular-jquery.min-eee9041.js:127
$$reject @ 0-angular-jquery.min-eee9041.js:130
reject @ 0-angular-jquery.min-eee9041.js:129
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
Promise.then (async)
n.getPromiseWithTimeout @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
n.acquirePromise @ 3.1-app.min-74276cf.js:1
n.acquireTokenInternal @ 3.1-app.min-74276cf.js:1
n.acquireToken @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
e.retry @ 3.2-app.min-5dc2fb6.js:1
e @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.acquireTokenPostCheckCache @ 3.2-app.min-5dc2fb6.js:1
e.acquireTokenForResource @ 3.2-app.min-5dc2fb6.js:1
p @ 3.2-app.min-5dc2fb6.js:1
t.startTokenRetry @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokensInternal @ 3.2-app.min-5dc2fb6.js:1
e.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:155
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
f @ 0-angular-jquery.min-eee9041.js:155
e.baseMessageHandler @ 3.2-app.min-5dc2fb6.js:1
t.processSDKMessage @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:246
d.<computed> @ 0-angular-jquery.min-eee9041.js:79
e.onMessageCallback @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1

0-angular-jquery.min-eee9041.js:114 
2021-04-09T14:28:30.940Z AUTHMSAL: Attempting to handle auth response: error:invalid_resource|AADSTS500011: The resource principal named api://canalazure.com.br/399ae3eb-1fb7-4161-bd70-192521d07cc5 was not found in the tenant named 4013ef5b-a41a-4410-902b-0b74327c5b0f. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant., resource:api://canalazure.com.br/399ae3eb-1fb7-4161-bd70-192521d07cc5, error mapped to action:resourceDisabled
(anonymous) @ 0-angular-jquery.min-eee9041.js:114
e.logMessage @ 3.2-app.min-5dc2fb6.js:1
e.error @ 3.2-app.min-5dc2fb6.js:1
n.handleAuthError @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:142
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
$evalAsync @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
g @ 0-angular-jquery.min-eee9041.js:127
$$reject @ 0-angular-jquery.min-eee9041.js:130
reject @ 0-angular-jquery.min-eee9041.js:129
(anonymous) @ 0-angular-jquery.min-eee9041.js:126
Promise.then (async)
n.getPromiseWithTimeout @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.1-app.min-74276cf.js:1
n.acquirePromise @ 3.1-app.min-74276cf.js:1
n.acquireTokenInternal @ 3.1-app.min-74276cf.js:1
n.acquireToken @ 3.1-app.min-74276cf.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
e.retry @ 3.2-app.min-5dc2fb6.js:1
e @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.retry @ 3.2-app.min-5dc2fb6.js:1
t.acquireTokenPostCheckCache @ 3.2-app.min-5dc2fb6.js:1
e.acquireTokenForResource @ 3.2-app.min-5dc2fb6.js:1
p @ 3.2-app.min-5dc2fb6.js:1
t.startTokenRetry @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokensInternal @ 3.2-app.min-5dc2fb6.js:1
e.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
t.getAuthTokens @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 3.2-app.min-5dc2fb6.js:1
f @ 0-angular-jquery.min-eee9041.js:127
(anonymous) @ 0-angular-jquery.min-eee9041.js:127
$eval @ 0-angular-jquery.min-eee9041.js:142
$digest @ 0-angular-jquery.min-eee9041.js:139
v.$digest @ 3.2-app.min-5dc2fb6.js:1
$apply @ 0-angular-jquery.min-eee9041.js:142
(anonymous) @ 0-angular-jquery.min-eee9041.js:155
e @ 0-angular-jquery.min-eee9041.js:41
(anonymous) @ 0-angular-jquery.min-eee9041.js:44
setTimeout (async)
Zf.k.defer @ 0-angular-jquery.min-eee9041.js:44
f @ 0-angular-jquery.min-eee9041.js:155
e.baseMessageHandler @ 3.2-app.min-5dc2fb6.js:1
t.processSDKMessage @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1
(anonymous) @ 0-angular-jquery.min-eee9041.js:246
d.<computed> @ 0-angular-jquery.min-eee9041.js:79
e.onMessageCallback @ 3.2-app.min-5dc2fb6.js:1
e.onMessageReceived @ 3.2-app.min-5dc2fb6.js:1

0-angular-jquery.min-eee9041.js:114 
2021-04-09T14:28:30.942Z ExtensionTabService: getAuthTokenForApp: Failed with error - resourceDisabled

**Comment by weilai-irl** [comment]
Hi all,

We have made a new release for the local_o365 plugin for Moodle 3.9 and 3.10 that contain improvements in Moodle and Teams integration. The new version should fix most issues in the integration, if not all. The release notes for [Moodle 3.9](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m310) and [Moodle 3.10](https://github.com/microsoft/o365-moodle/releases/tag/v20210629_m39) are linked.

In particular, the improved Moodle and Microsoft 365 integration adds support to web servers that don't support `apache_request_headers()` function, or if the function doesn't return the expected results. It should help improving SSO workflow.

Please upgrade your plugin [local_o365](https://moodle.org/plugins/local_o365/versions) (and [auth_oidc](https://moodle.org/plugins/auth_oidc/versions) which it depends on) to the latest version and try it out. Please report back any remaining issues found in this issue. The issue will be kept open for one month from today, and will be closed if most issues are confirmed resolved.

Regards,
Lai

**Comment by totore86** [comment]
Hi @weilai-irl, I have updated all the plugins but I have the same issue with Teams Insider Linux App, instead with browser I have 2 issues:

- "you don't have any courses to add" 
- sometime the course list is loaded but when I choose the course I can't save the tab. The screen below shows an error on microsoftTeams ot onCoursechange an row 88 of teams_tab_configuration.php

![image](https://user-images.githubusercontent.com/5445022/124445270-b314c500-dd7f-11eb-8135-bc93fd07a53c.png)

The oidc works and if we add a browser tab to moodle with link to moodle course it works well.

**Comment by weilai-irl** [comment]
Hi @totore86,

Based on your message, I have a few questions/comments:
1. Is your Moodle site publicly available, and having a valid SSL cert? If not, they won't be accessible from desktop/mobile Teams app, but will be accessible from Teams web app (browser).
2. When using Teams web app, if the browser already has a valid Moodle session, i.e. there's a user logged in on the Moodle site, when you access Moodle tab from Teams, Moodle will simply use the user in the existing session, and will not try to log in using the Teams user via SSO. These could well be two different users, who have access to different courses in Moodle.
3. The error "microsoftTeams is not defined..." on the first line in console suggests that the Microsoft Teams JavaScript API cannot be loaded. It's the very basis of the Teams integration feature, and without it the Teams integration won't work. On the teams_tab_configuration.php page, it's included by something like `<script src="https://statics.teams.microsoft.com/sdk/v1.9.0/js/MicrosoftTeams.min.js" crossorigin="anonymous">`. Could you investigate on your side why this doesn't work please. Maybe try to check the "network" tab to see if there's any error getting the resource?

Regards,
Lai

**Comment by totore86** [comment]
> Hi @totore86,
> 
> Based on your message, I have a few questions/comments:
> 
> 1. Is your Moodle site publicly available, and having a valid SSL cert? If not, they won't be accessible from desktop/mobile Teams app, but will be accessible from Teams web app (browser).
Yes is publicly available and we have a valid SSL cert.

> 2. When using Teams web app, if the browser already has a valid Moodle session, i.e. there's a user logged in on the Moodle site, when you access Moodle tab from Teams, Moodle will simply use the user in the existing session, and will not try to log in using the Teams user via SSO. These could well be two different users, who have access to different courses in Moodle.

Ok, thanks


> 3. The error "microsoftTeams is not defined..." on the first line in console suggests that the Microsoft Teams JavaScript API cannot be loaded. It's the very basis of the Teams integration feature, and without it the Teams integration won't work. On the teams_tab_configuration.php page, it's included by something like `<script src="https://statics.teams.microsoft.com/sdk/v1.9.0/js/MicrosoftTeams.min.js" crossorigin="anonymous">`. Could you investigate on your side why this doesn't work please. Maybe try to check the "network" tab to see if there's any error getting the resource?
We have a Saas moodle instance so we check the crossorigin parameters because we don't see also the login buttons.

> 
> Regards,
> Lai

Thanks a lot!

Best regards!
Salvatore

**Comment by weilai-irl** [comment]
Issue closed one month after release.
