### ISSUE TITLE
User authentification vs Teams integration

### ISSUE THREAD

**Issue by Tunisieno** [microsoft/o365-moodle#1634]
Hello,
In moodle we use auth_shibboleth as an authentication method.
When we setup the integration, the synchronization of teams does not work (No team Owner).
When I switch my teacher account to OIDC and sign in once using my Azure AD account, the sync works after for my course.
I switch my account back to shibboleth and the synchronization is still working.
Do the integration work only with OIDC authentication ?
Will users necessarily have to get a token to make  the synchronization work?
If not, is there a solution to not force my users to connect to OIDC at least once?

Plugin local_o365 3.9.3  2020071505
Moodle version : Moodle 3.9.6 (Build: 20210325)

Thank you for your help

**Comment by weilai-irl** [comment]
Hi @Tunisieno,

At the simplest, the integration is only designed to work for users using auth_oidc authentication method.

At lower level, the check to see if a course has suitable Team owners would check to see if for all users with "local/o365:teamowner" capability in the course context, and check if any of them is connected to a Microsoft 365 account, by querying the "mdl_local_o365_objects" table using conditions "type = 'user' AND moodleid = 'USER_ID'". If at least user with the permission is found, the Team creation will go ahead. Therefore the key is to have Team owner users that are connected to Microsoft 365.

All users using auth_oidc authentication method are essentially connected, thus would have a record in the table. The only other way to connect a user is to use the "Manage user connection" feature in the "Advanced" tab. In short, site admins will set up the connection, and the user will confirm the connection on their login from the Microsoft block. Users can retain their original authentication method (providing the "Log in with Microsoft 365" option is not checked).

Please note that only Moodle users who are connected to Microsoft 365 can have their course enrolments synced to Team memberships, i.e. if you want students enrolled in a Moodle course to be automatically added as Team members, you will need to ensure that the Moodle accounts of all students are connected to Microsoft 365 using the method above.

Regards,
Lai

**Comment by Tunisieno** [comment]
Hello Lai,
Thank you very much for your explanation!
to sum up to make the integration working, users need to use OIDC.
Regards,
