### ISSUE TITLE
Exisiting o365 Course groups not retrospectively set to private following upgrade to plugin version Moodle 3.0: v20160620

### ISSUE THREAD

**Issue by petersercombe** [Microsoft/o365-moodle#166]
In the latest release of the plugin (Moodle 3.0: v20160620) the following bug fix is listed:

- "o365 Course groups are now created with private visibility setting"

However when I go and check the existing course groups they are all still set to public visibility. Does this bug fix only apply to newly created groups?

I am in a position where I can delete the groups that have been created (as they are not in use yet) and let the cron task recreate them, however it would be great to have some instructions on the correct process for this so I don't break anything.

**Comment by nimojg-microsoft** [comment]
Yes, this bug fix only applies to newly created groups.

**Comment by petersercombe** [comment]
For those looking to update the setting for pre-existing groups, it is possible to user Exchange Online Powershell.

[Connect to Exchange Online PowerShell](https://technet.microsoft.com/en-us/library/jj984289(v=exchg.160).aspx)

First, list the Office 365 groups created by your Moodle site:

`Get-UnifiedGroup -Identity "<siteshortname>*"`

You may need to tweak the <siteshortname> to find something to identify the Moodle groups with. Next change the visibility for the groups from public to private:

`$moodlegroups=Get-UnifiedGroup -Identity "<siteshortname>_*" | Select Identity`

`$moodlegroups | foreach {Set-UnifiedGroup $_.identity -AccessType Private}`

Obviously replacing <siteshortname> with whatever you used in the first command.

Given this issue isn't relevant to the current release of plugins, I'll mark it as closed.
