### ISSUE TITLE
local_o365\oauth2\token::instance local_o365\feature\usersync\main::construct_outlook_api:109: Cannot retrieve a token for the base resource. Data: (null)

### ISSUE THREAD

**Issue by travnettech** [microsoft/o365-moodle#1665]
I am facing a issue in the integration. But user syc not working. 
local_o365\oauth2\token::instance local_o365\feature\usersync\main::construct_outlook_api:109: Cannot retrieve a token for the base resource. Data: (null)

Please check the screen sort.
![Error](https://user-images.githubusercontent.com/61828449/115530180-71e63c00-a28b-11eb-8267-9d4111ad24e2.png)

**Comment by weilai-irl** [comment]
Hi @travnettech,

Could you specify the following please:
 - the version of Moodle site.
 - the version of your Microsoft plugins, specifically auth_oidc and local_o365.
 - whether the user sync task works in general.

Regards,
Lai
