### ISSUE TITLE
O365 does not sync/match all users and cannot use Office 365 username search function in User Connection

### ISSUE THREAD

**Issue by AklElie** [microsoft/o365-moodle#1666]
Hi,

I currently have moodle 3.8 with 62000 users synced from our LDAP server, we want to use OpenID for authentication now with Azure so i have installed the plugin and set it all up using the powershell script but i'm having some issues with the sync settings,  these are the sync settings set up
![image](https://user-images.githubusercontent.com/52348828/115990085-1937db80-a5ca-11eb-9280-3db3ac9ecb44.png)
![image](https://user-images.githubusercontent.com/52348828/115990183-982d1400-a5ca-11eb-8408-f2318e55e5b5.png)

The issue is when the cron job launches automatically or i launch it does not match any users at all unless i manually match it with a csv file but also does not sync any user to the application not even the matched ones at all, even tho i have tried to run the cron multiple times, I have tried to manually edit the profile of 1 user to use OpenID and it synced the user into the application but the rest of the time it does not sync anything at all not even users.
![image](https://user-images.githubusercontent.com/52348828/115990162-821f5380-a5ca-11eb-8446-94fe2f8e1494.png)

Even without the match option if a user was synced from the User Creation Restriction group and i delete that user from the moodle interface and try to sync again the plugin would not sync the user back, it would sync new users but never the deleted one, i think the user is not being deleted entirely from the database.

Another issue is whenever i am trying to search for a user in the Microsoft Office 365 Integration plugin --> Advanced --> Manage User Connections --> Office 365 username filter i get an error, i have turned on debugging and saw this:
`Debug info: ERROR: column "o365username" does not exist
LINE 9: ... WHERE u.deleted = 0 AND u.username != $2 HAVING o365userna...
^
HINT: Perhaps you meant to reference the column "aotok.oidcusername".
SELECT count(1) from (SELECT u.id AS userid,u.firstname AS userfirstname,u.firstnamephonetic AS userfirstnamephonetic,u.lastname AS userlastname,u.lastnamephonetic AS userlastnamephonetic,u.middlename AS usermiddlename,u.alternatename AS useralternatename,u.auth AS userauth,aotok.oidcusername AS toko365username,o365match.aadupn AS matchedo365username,o365match.uselogin AS matcheduselogin,objects.o365name AS objectso365name,COALESCE(aotok.oidcusername, o365match.aadupn, objects.o365name) AS o365username
FROM mdl_user u
LEFT JOIN mdl_auth_oidc_token aotok
ON aotok.userid = u.id
LEFT JOIN mdl_local_o365_connections o365match
ON o365match.muserid = u.id
LEFT JOIN mdl_local_o365_objects objects
ON objects.moodleid = u.id AND type = $1
WHERE u.deleted = 0 AND u.username != $2 HAVING o365username ILIKE $3 ESCAPE '\') a
[array (
0 => 'user',
1 => 'guest',
2 => '%elie%',
)]
Error code: dmlreadexception`

I think the error is related to the (COALESCE aotok.oidcusername, o365match.aadupn, objects.o365name AS o365username) code line and i am using postgresql-10.

I have already tried to install a new machine with an empty database also Postgresql with the latest Moodle version and latest OpenID plugin version and i still face the exact same errors.

**Comment by AklElie** [comment]
Also when specifying a group in User Creation Restriction it still tries to sync from the whole Azure AD and filter by the group instead of actually just searching in the group, i get messages that it finds users but it will not sync/create since they are not part of the group, should i add the group in the application users/groups?

**Comment by AklElie** [comment]
Update:
Tried to remove the plugin clear all database columns related to OpenID and tried to match users using the match tool and ran sync for the first time this is the log.
![image](https://user-images.githubusercontent.com/52348828/116215211-2383e200-a750-11eb-8324-04df1eae1451.png)

It seems that PDO is limited to 65535 so probably the queries should be split to chunks for DBs with more than 65535 entries?

**Comment by weilai-irl** [comment]
Hi @AklElie,

This is the same issue as #1359, which has been fixed for Moodle 3.9 and 3.10. Support for the Microsoft plugins for Moodle 3.8 had stopped before the fix was rolled out, so the issue is not fixed for 3.8.

If upgrading to later Moodle versions is not possible, you can manually apply the commits in the pull requests linked to the other issues. It should have the same effect and fix the issue.

Regards,
Lai
