### ISSUE TITLE
Problems with Teams integration using CloudFlare CDN

### ISSUE THREAD

**Issue by antoniopanella** [microsoft/o365-moodle#1667]
We have introduced recently Cloud Flare Proxy support for our Moodle 3.9 and 3.10 sites.

From that moment SSO Teams Integration of our courses stop to works.
The users receive a screen that request to re-authenticate.
- Login to Microsoft 365
- Login manually
Clicking the options, the users will be re-prompt indefinitelly.

Normal Site Authentication with Azure still working correctly.

The problems affect all users (more than ten thousand).

The problem affect all versions of Teams (desktop, mobile and browser) 

The only error we see in Browser console is relative to Angular:
ExtensionTabService: getAuthTokenForApp: Failed with error - App webApplicationInfo or resource not defined in manifest

**Comment by weilai-irl** [comment]
Hi @antoniopanella,

The issue sounds very specific and potentially would be hard to investigate.
 - First of all, we don't any an environment using Cloud Flare proxy, so I may not be able to reproduce the exact issue.
 - The fact that users are asked to choose login method indicate Moodle and Teams SSO failed. If this was working before, it could be the Cloud Flare proxy change that broke it. The latest release of the plugin (3.9.6 and 3.10.3) contained some improvements in the Moodle and Teams integration, including changes in SSO workflow. Please apply it if possible. It may not solve the SSO issue, but at least the you can take advantages of other improvements.
 - The error in the last part of your reporting seems related to the Moodle Teams app manifest file. Could you find the Moodle app in your Teams app catalogue, locate the Moodle app, and find the version of the app please. The latest version should be 1.3, which should contain the "webApplicationInfo" section. If you see earlier versions (e.g. 1.2 or 1.2.1), please download the manifest file from Moodle, and upgrade the app in Teams app catalogue.

Regards,
Lai
