### ISSUE TITLE
Parse error: syntax error (sharepoint.php on line 983)

### ISSUE THREAD

**Issue by tijixv** [Microsoft/o365-moodle#167]
When we try to add new course or edit couse we will get the following error

Parse error: syntax error, unexpected '*', expecting ')' in /local/o365/classes/rest/sharepoint.php on line 983

**Comment by Jarvil** [comment]
Any ideas what is causing this?

**Comment by anieminen** [comment]
A quick fix for the syntax error is to change that line 983 from:
```php
public function upload_video($channelid, $videoid, $filename, $offsetsize = 8192 * 1024) {
```
to:
```php
public function upload_video($channelid, $videoid, $filename, $offsetsize = 8388608) {
```

**Comment by rlcharles** [comment]
This will be fixed in the next release, branch wip-MSFTMPP-530-m## has the patch if you need an immediate fix.
