### ISSUE TITLE
"Clean up OIDC state and invalid token" Task Issue

### ISSUE THREAD

**Issue by aboarken** [microsoft/o365-moodle#1679]
There is an issue with "Clean up OIDC state and invalid token" schedule task. It runs but always get failed. Please check the attached pictures.

![task_issue](https://user-images.githubusercontent.com/18500882/118345585-306d4780-b53e-11eb-9452-2b846e0234db.png)
![auth_oidc_task_error](https://user-images.githubusercontent.com/18500882/118345586-32370b00-b53e-11eb-9571-6bc9ea3c2f04.png)

**Comment by grantcolin** [comment]
Fix is here:

https://github.com/microsoft/o365-moodle/commit/27cd3b72a748849a81f16c16071b153a1c64c823

**Comment by weilai-irl** [comment]
This is duplicate of #1638 and will be fixed when the pull request linked to the issue are merged, in the June 2021 release.

**Comment by weilai-irl** [comment]
Hi all,

The issue is fixed in the latest release. I'll close the issue now.

Regards,
Lai

**Comment by aboarken** [comment]
@weilai-irl Thank you.
