### ISSUE TITLE
Sync users with Azure AD failing after a few successful runs (when scheduled for high frequency)

### ISSUE THREAD

**Issue by petersercombe** [Microsoft/o365-moodle#168]
I've set user sync up on a schedule to run 2 hourly as we have >6000 users and I want to ensure any new user has a Moodle account by the next day. This runs fine for the first few days, and then it stops syncing.

Attempting to run the sync manually via CLI using the following command:

`sudo -u daemon php /path/to/moodle/htdocs/local/o365/classes/task/usersync.php
`
Returns the following error:

`PHP Fatal error:  Class 'core\task\scheduled_task' not found in /path/to/moodle/htdocs/local/o365/classes/task/usersync.php on line 29
`

As similar issue was reported [here](https://moodle.org/mod/forum/discuss.php?d=317284) however the root cause identified in that case is not the issue in this one. The tool is successfully running a few times before failing (rather than failing from the beginning).

Running latest release of plugins at time of posting, Moodle 3.0.4, php 5.6.

Also running multi-tenancy o365, if that is important.

**Comment by rlcharles** [comment]
If you temporary set Debug messages in Site administration / ► Development / ► Debugging and display debug messages does any errors appear ?

**Comment by petersercombe** [comment]
Where should I be looking for the errors? In the html page (which is what the 'display debug messages" setting toggles)?  I get no errors there, and none in the php logs, even with debugging mode set to developer.

**Comment by rlcharles** [comment]
Look for errors when you execute the scheduled task. Depending on your configuration you may want to add -u apache or -u httpd for the sudo to run the task as the web server user.

`sudo -u apache php /path/to/moodle/admin/tool/task/cli/schedule_task.php --execute=\\local_o365\\task\\usersync`

**Comment by petersercombe** [comment]
I'm with you now. 

The error about obtaining a Cron lock appears to be as a result of running the task via CLI as the wrong user (root). Adding "-u daemon" (webserver user) triggered the task.

However, I also gave the server a reboot earlier today (prompted by one article I've linked to above), after which it seems to have successfully run a user sync via Cron. I may have thus missed the opportunity to debug this issue properly.

I am getting some error messages coming through with the CLI run of the task. I'll post details once it's finished running the task.

**Comment by petersercombe** [comment]
Here's what I've found. There are a few error messages with the following pattern:

```
Syncing user ********@******************.edu.au
PHP Notice:  Undefined index: @odata.mediaEtag in /path/to/moodle/local/o365/classes/feature/usersync/main.php on line 170
PHP Notice:  Undefined index: @odata.mediaEtag in /path/to/moodle/local/o365/classes/feature/usersync/main.php on line 187
User is already synced.
```

And also a few of the following:

`Could not assign profile photo to user "***********@****************.edu.au" Reason: Error in API call.`

I'm not too concerned about the profile photo issue - in fact I may disable it for now. Errors have had identifying information removed.

**Comment by petersercombe** [comment]
Interesting. Having just disabled profile photo sync in Cron has brought the time taken to run the task down from >1hour to <1min.

One thing I should mention is I'm using Graph API (to make use of Office 365 Groups).

**Comment by rlcharles** [comment]
The could not assign profile photo error is typically for when there is no profile for user and will be investigated in the future.

The cron sync of photos is expected to take a long time for a large amount of users. Two options are to extend how long before a profile photo is checked. By default it is 24 hours, the setting is "Profile photo time to live" in Site administration / ► Plugins / ► Local plugins / ► Microsoft Office 365 Integration / Options

The second option is to add the microsoft block to the front page and use "Sync Office 365 profile photos to Moodle on login" only. This updates a users photo when the login.

One possibility is the cron job is being terminated before it completes.

**Comment by jamesmcq** [comment]
@petersercombe Are you still experiencing this issue? If so, please comment and/or reopen.

**Comment by RSickenberg** [comment]
I have this issue, can we reopen this?
