### ISSUE TITLE
"Remove temporary write access from controlled links" Task issue

### ISSUE THREAD

**Issue by aboarken** [microsoft/o365-moodle#1680]
There is an issue with "Remove temporary write access from controlled links" schedule task. It runs but always get failed. Please check the attached pictures.

![onedrive_error](https://user-images.githubusercontent.com/18500882/118345642-9a85ec80-b53e-11eb-8155-c06631dbbaec.png)
![Onedrive_Issue](https://user-images.githubusercontent.com/18500882/118345644-9c4fb000-b53e-11eb-9937-38b067a1190d.png)

**Comment by weilai-irl** [comment]
Hi @aboarken,

The task you mentioned belong to plugin repository_onedrive, which is delivered as part of Moodle core, and is not part of the Microsoft Moodle plugins. Please report the issue to Moodle bug tracker https://tracker.moodle.org/.

Regards,
Lai
