### ISSUE TITLE
User Field Mapping issue

### ISSUE THREAD

**Issue by jonik-sys** [microsoft/o365-moodle#1681]
We are currently using the Moodle plugin for synchronisation in a hybrid On-Prem/on-line solution, so our SMTP addresses are mastered in On-Prem. The Moodle plugin appears to be using the UPN to match/create the Moodle account, causing issues with matching these users with their pre-existing Moodle accounts which are based on their On-Prem email addresses. 

-------------
**User field mapping setting in the Moodle plugin:**

![User field mapping config](https://user-images.githubusercontent.com/84326677/118493312-dffe1180-b718-11eb-9795-71125b66f39b.png)

**When signing in with a test account to Moodle and checking its the username and email address:**

![User field mapping issue](https://user-images.githubusercontent.com/84326677/118495232-e9887900-b71a-11eb-8e11-66005d8a87de.png)

**Comment by weilai-irl** [comment]
Hi @jonik-sys,

Could you provide the following additional information about the issue please.
 - Moodle release and version.
 - local_o365 plugin version.
 - Using the Microsoft Graph explorer, the return value of a "GET" request to "v1.0" version to request "https://graph.microsoft.com/v1.0/users/aaw938@qmul.ac.uk".

Regards,
Lai
