### ISSUE TITLE
Observer handle_course_update throws an exception when auth_oidc is not enabled

### ISSUE THREAD

**Issue by tmas0** [microsoft/o365-moodle#1682]
Hi folks,
I'm running the current latest version, 3.9.4 (2020071506), and l have an exception on _classes/observers.php_, at line 621.

The problems occur when **auth_oidc** is **not** enabled, but is configured (it has rows in {prefix}_config_plugins).

The call `$apiclient = \local_o365\feature\usergroups\utils::get_graphclient();` return false, and `$coursegroups = new \local_o365\feature\usergroups\coursegroups($apiclient, $DB, true);` expects a `\local_o365\rest\unified` instance.

This problems throws an exception, and all updates to any course fails.

Regards

**Comment by weilai-irl** [comment]
Hi @tmas0,

This has been reported in #1646 and #1651. The fix is in the pull requests linked in the two issues, and will be included in the upcoming release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @tmas0,

The fix to the issue has been included in the latest release (v3.9.5 and v3.10.2).

I'm closing this issue now.

Regards,
Lai
