### ISSUE TITLE
Missing `userid` index for the `auth_oidc_token` table  

### ISSUE THREAD

**Issue by AndreasSko** [microsoft/o365-moodle#1683]
We are operating a Moodle instance with around 130k users (and  >1Mio O365 objects). Users reported that they are not able to access the `Manage User Connections` page (local/o365/acp.php?mode=userconnections) as it timed out after 15 minutes. 
While investigating the problem I found that there is a index missing for the `mdl_auth_oidc_token` table on the `userid` column. After adding this one with `CREATE INDEX manually_created_idx_userid ON mdl_auth_oidc_token (userid);`, the page loaded in a few seconds. Unfortunately I don't have much knowledge about where to define this index so I'm opening the issue here.

**Comment by AndreasSko** [comment]
I just noticed that there is also an index missing for the `username` column, which resulted in logins taking over 10s in some cases. After running `CREATE INDEX manually_created_idx_username ON mdl_auth_oidc_token (username);` the requests were sped up significantly. Maybe something good to know for others facing similar issues :)

**Comment by weilai-irl** [comment]
Hi @AndreasSko,

Index has been added to the table as requested in the latest release. Please check out the latest version.

Regards,
Lai

**Comment by AndreasSko** [comment]
Thank you so much for your work! :slightly_smiling_face:
