### ISSUE TITLE
Event synchronization fails when Graph API is on

### ISSUE THREAD

**Issue by rimas-kudelis** [Microsoft/o365-moodle#169]
When my test Moodle installation attempts to synchronize users' calendars with Outlook, here's what I get in the log:

> local_o365\rest\unified::get_events:681: Bad response received Data: (string)﻿{ "error": { "code": "RequestBroker-ParseUri", "message": "The DateTimeOffset text '2016-07-13T22:55:02' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.", "innerError": { "request-id": "c96e2a22-85d9-4f7b-b798-161808f9c695", "date": "2016-07-13T19:56:04" } } }

I suppose it might be an error in the API itself, although I'm not sure. Could it be that the API doesn't accept dates in the `2005-08-15T15:52:01+00:00`  (a.k.a. `DATE_ATOM`) form for some reason?

For the record, this happens when the Graph API is on. I initially thought that changing Moodle timezone to UTC would help alleviate the issue, but it doesn't seem to have any effect:

> local_o365\rest\unified::get_events:681: Bad response received Data: (string)﻿{ "error": { "code": "RequestBroker-ParseUri", "message": "The DateTimeOffset text '2016-07-13T20:08:01' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.", "innerError": { "request-id": "bdb22eb5-1fa0-4115-9fd7-69851f803c93", "date": "2016-07-13T20:09:02" } } }

**Comment by petersercombe** [comment]
I am experiencing the same error:

`local_o365\rest\unified::get_events:681: Bad response received Data: (string)﻿{ "error": { "code": "RequestBroker-ParseUri", "message": "The DateTimeOffset text '2016-07-14T08:50:15' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.", "innerError": { "request-id": "ccedb2a6-54a6-4ed7-b90f-5f27ff8beac1", "date": "2016-07-13T22:51:02" } } }`

Also on import of events from outlook:

`importfromoutlook: Error syncing events: Error in API call. Data: Array ( [file] => /path/to/moodle/local/o365/classes/rest/o365api.php [line] => 231 [message] => Error in API call. [debuginfo] => [errorcode] => erroro365apibadcall [module] => local_o365 )`

**Comment by jamesmcq** [comment]
Thanks all - added this to our internal backlog.

**Comment by rimas-kudelis** [comment]
@jamesmcq, do you have any estimation on when this might be fixed?

**Comment by jamesmcq** [comment]
Can you both try with the latest (v20160721) release and let me know if you are still experiencing the problem? I tried this out specifically during release testing and didn't encounter any problems. Could be a specific situation I didn't encounter in which case more investigation will be needed, but I want to eliminate the possibility this is already fixed. Thanks!

**Comment by rimas-kudelis** [comment]
Same error:

> local_o365\rest\unified::get_events:731: Bad response received Data: (string)﻿{ "error": { "code": "RequestBroker-ParseUri", "message": "The DateTimeOffset text '2016-07-23T09:53:04' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.", "innerError": { "request-id": "455b3bbd-62cb-4c97-9b10-3deedc0deb21", "date": "2016-07-23T06:54:02" } } }

**Comment by rimas-kudelis** [comment]
And same error if I set my timezone to UTC:

> local_o365\rest\unified::get_events:731: Bad response received Data: (string)﻿{ "error": { "code": "RequestBroker-ParseUri", "message": "The DateTimeOffset text '2016-07-23T07:03:02' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.", "innerError": { "request-id": "14841aa2-e4c9-450f-8287-b42bbe1978b7", "date": "2016-07-23T07:04:02" } } }

**Comment by rimas-kudelis** [comment]
Changing Moodle timzone to UTC and then replacing `DATE_ATOM` with `'Y-m-d\Th:m:s\Z'` in `unified.php` works, but that is a very ugly workaround.

**Comment by petersercombe** [comment]
Likewise - I am still receiving the error. The workaround suggested by @rimas-kudelis isn't workable for us.

**Comment by rimas-kudelis** [comment]
The error is still there:

> local_o365\rest\unified::get_events:731: Bad response received Data: (string)﻿{ "error": { "code": "RequestBroker-ParseUri", "message": "The DateTimeOffset text '2016-08-11T14:26:03' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.", "innerError": { "request-id": "6dde31ab-5807-4a65-8fb2-1f17a4e0e5e4", "date": "2016-08-11T11:27:01" } } }
