### ISSUE TITLE
Moodle Assistant Bot responding as "Sorry, the answer to this question is not available for now"

### ISSUE THREAD

**Issue by tharunbabu** [microsoft/o365-moodle#1694]
ISSUE RELATED TO MOODLE BOT INTEGRATION WITH TEAMS.
I had followed every step from the documentation https://docs.moodle.org/310/en/Microsoft_365 and configured everything the same in moodle as well as in azure AD.

But, when it open chat in moodle assistant bot it asks for a login and after logging in it says "Sorry, the answer to this question is not available for now". Even if I enter help I get the same response as "Sorry...".

**Comment by nenorojas** [comment]
Hi @tharunbabu , the issue you have raised is probably related to this issue that was fixed in October/2021.

We inform that the bot functionality will be decommissioned from the plugins, so we are closing the related tickets.
