### ISSUE TITLE
Unit Test failures in Course Groups

### ISSUE THREAD

**Issue by tlock** [microsoft/o365-moodle#1701]
https://github.com/microsoft/o365-moodle/blob/6a210db3779a6da9db544139ccb4e0d12873d199/local/o365/tests/coursegroups_test.php#L211

This function triggers the failure that occurs further down because the set response data isn't compatible with unified::get_group:364 that cause the array to grow to 12 elements than the 3 expected.

2) local_o365_coursegroups_testcase::test_resync_group_membership
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (...)
     1 => Array (
-        'url' => 'https://graph.microsoft.com/beta/groups/testgroupobjectid/members/user2/$ref'
+        'url' => 'https://graph.microsoft.com/v1.0/groups/testgroupobjectid/owners'
         'options' => Array (
-            'CURLOPT_CUSTOMREQUEST' => 'DELETE'
-            'CURLOPT_USERPWD' => 'anonymous: noreply@moodle.org'
             'CURLOPT_USERAGENT' => 'Moodle-groups-2020110901'
+            'CURLOPT_HTTPGET' => 1
         )
     )
     2 => Array (
-        'url' => 'https://graph.microsoft.com/beta/groups/testgroupobjectid/members/$ref'
+        'url' => 'https://graph.microsoft.com/v1.0/groups/testgroupobjectid'
         'options' => Array (
-            'CURLOPT_POST' => '1'
-            'CURLOPT_POSTFIELDS' => '{"@odata.id":"https:\/\/graph...ser0"}'
             'CURLOPT_USERAGENT' => 'Moodle-groups-2020110901'
+            'CURLOPT_HTTPGET' => 1
         )
     )
+    3 => Array (...)
+    4 => Array (...)
+    5 => Array (...)
+    6 => Array (...)
+    7 => Array (...)
+    8 => Array (...)
+    9 => Array (...)
+    10 => Array (...)
+    11 => Array (...)

Debugging shows:

Created group group1 for course #2
Recorded group object (group1) into object table with record id 1
Syncing group membership for course #3
Syncing to group "testgroupobjectid"
... Checking if group is setup ...
...... Received: Error in API call: Invalid structure received. No "id" - {"value":[{"id":"user1"},{"id":"user2"}]} (local_o365\rest\unified::get_group:364
)
...... Retry #1
...... Received: Error in API call: Invalid structure received. No "id" - {"value":[{"id":"user1"},{"id":"user2"}]} (local_o365\rest\unified::get_group:364
)
...... Retry #2
...... Received: Error in API call: Invalid structure received. No "id" - {"value":[{"id":"user1"},{"id":"user2"}]} (local_o365\rest\unified::get_group:364
)
...... Retry #3
...... Received: Error in API call: Invalid structure received. No "id" - {"value":[{"id":"user1"},{"id":"user2"}]} (local_o365\rest\unified::get_group:364
)
...... Retry #4
...... Received: Error in API call: Invalid structure received. No "id" - {"value":[{"id":"user1"},{"id":"user2"}]} (local_o365\rest\unified::get_group:364
)
...... Retry #5
...... Received: Error in API call: Invalid structure received. No "id" - {"value":[{"id":"user1"},{"id":"user2"}]} (local_o365\rest\unified::get_group:364
)
Owners to remove: 2
... Removing user1...Error!
...... Received: (string){"value":[{"id":"user1"},{"id":"user2"}]}
... Removing user2...Error!
...... Received: (string){"value":[{"id":"user1"},{"id":"user2"}]}
Members to remove: 1
... Removing user2...Error!
...... Received: (string){"value":[{"id":"user1"},{"id":"user2"}]}

Running:
vendor/bin/phpunit "local_o365_coursegroups_testcase" local/o365/tests/coursegroups_test.php

**Comment by tlock** [comment]
With dummy prefix removed from the expected object which was missed in this code cleanup, the test still fails:

Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         'url' => 'https://graph.microsoft.com/v...groups'
         'options' => Array (
             'CURLOPT_POST' => 1
-            'CURLOPT_POSTFIELDS' => '{"groupTypes":["Unified"],"displayName":"Test course 1","mailEnabled":false,"securityEnabled":false,"mailNickname":"p
refix1_tc_1","visibility":"Private","description":"Test course 1\nLorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla non arcu lacinia neque fa
ucibus fringilla. Vivamus porttitor turpis ac leo. Integer in sapien. Nullam eget nisl. Aliquam erat volutpat. Cras elementum. Mauris suscipit, ligula sit 
amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Integer malesuada. Nullam lectus justo, vulputate eget mollis sed, tempo
r sed magna. Mauris elementum mauris vitae tortor. Aliquam erat volutpat.\nTemporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saep
e eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Pellentesque ipsum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. 
Aliquam ante. Proin in tellus sit amet nibh dignissim sagittis. Vivamus porttitor turpis ac leo. Duis bibendum, lectus ut viverra rhoncus, dolor nunc fauci
bus libero, eget facilisis enim ipsum id lacus. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Aliquam erat volutpat. Nulla est.\n ..."}'
+            'CURLOPT_POSTFIELDS' => '{"groupTypes":["Unified"],"displayName":"Test course 1","mailEnabled":false,"securityEnabled":false,"mailNickname":"t
estcourse1","visibility":"Private","resourceBehaviorOptions":["HideGroupInOutlook","WelcomeEmailDisabled"],"description":"Test course 1\nLorem ipsum dolor 
sit amet, consectetuer adipiscing elit. Nulla non arcu lacinia neque faucibus fringilla. Vivamus porttitor turpis ac leo. Integer in sapien. Nullam eget ni
sl. Aliquam erat volutpat. Cras elementum. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. I
nteger malesuada. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Mauris elementum mauris vitae tortor. Aliquam erat volutpat.\nTemporibu
s autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Pellentesqu
e ipsum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Aliquam ante. Proin in tellus sit amet nibh dignissim sagittis. Vivamus porttitor tu
rpis ac leo. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. In sem justo, commodo ut, suscipit a
t, pharetra vitae, orci. Aliquam erat volutpat. Nulla est.\n ..."}'
             'CURLOPT_USERAGENT' => 'Moodle-groups-2020110901'
         )
     )
 )

**Comment by weilai-irl** [comment]
The latest release contains fix to the unit test.
Issue closed.
