### ISSUE TITLE
Create "Class" Teams instances (not standard)

### ISSUE THREAD

**Issue by nenorojas** [microsoft/o365-moodle#1708]
Plug-in should create “Class” Teams instances (not standard). This team type is only available for Education A SKUs. 
We will need to evaluate the SKU first: if it’s Education then create Class Teams type, otherwise create standard Teams instance. 
TBD if Graph API ties Education to Tenant Type.

**Comment by weilai-irl** [comment]
@nenorojas,

Where does this requirement come from? The integration already creates class team, although it doesn't check for Education SKU.

Regards,
Lai
