### ISSUE TITLE
Documentation required for "User Creation Restriction" syntax

### ISSUE THREAD

**Issue by petersercombe** [Microsoft/o365-moodle#171]
I am attempting to restrict the creation of new users to only those who have the Given Name field populated (this will cut out the creation of 'users' such as meeting rooms and contacts).

I haven't been able to find a wildcard syntax that will work. Regardless of what I have attempted to use, I still get the following behaviour for users which have given names.

```
Syncing user *********@student.************.edu.au
User doesn't exist in Moodle
Cannot create user because they do not meet the configured user creation restrictions.
```

**Comment by jamesmcq** [comment]
This should now be resolved - the user creation restriction setting now supports regular expressions.

**Comment by idigorasu** [comment]
Hello,

I know this issue is closed but still it isn't clear for me how the wildcard syntax should work.

The documentation says:

> During user sync, by default, all users from Azure AD will be created in Moodle. This setting allows you to set a required field and value that a user must have in Azure to have an account created in Moodle. For example, if you wanted to only have users from the "IT" department syncing into Moodle, you would choose the "Department" field, and enter "IT".


But what if I want to sync only the users whose email address ends with `@example-email.com`? Should I write that in the field or add a `*` character like `*@example-email.com`?

If you could clear this question would be great.

**Comment by michael-LTS1** [comment]
There is a lot of documentation around about regex just have a search and its not too hard to learn.  If you want to limit to specific domain something like this should work (?im)^[A-Z0-9._%+-]\@(email\.com)$

**Comment by onlinelearningDPFEM** [comment]
Please document the syntax implemented in User Creation Restriction. The documentation links to the Wiki article about regular expressions. It is not clear which syntax rules apply in this plugin. "The specific syntax rules vary depending on the specific implementation, programming language, or library in use. Additionally, the functionality of regex implementations can vary between versions. " https://en.wikipedia.org/wiki/Regular_expression#Patterns_for_non-regular_languages
