### ISSUE TITLE
Name pulled from Microsoft

### ISSUE THREAD

**Issue by ellathewitch** [microsoft/o365-moodle#1711]
Hi,

Currently this connector pulls only the Legal Name from Office 365. Is there any way we could be given an option to use the Display Name instead of the Legal Name? In my organization, lots of people have a preferred nickname and don't like going by their legal name but on Moodle it always shows the incorrect name.

**Comment by weilai-irl** [comment]
Hi @ellathewitch,

You may want to explore the user field mapping feature that comes with local_o365, from where you can configure mapping selected AzureAD user profile fields to Moodle user profiles. The feature can be found in the "Sync Settings" tab of the Microsoft 365 Integration configuration page.

Regards,
Lai

**Comment by ellathewitch** [comment]
Thank you that's what I needed.
