### ISSUE TITLE
Sync users with Azure AD error

### ISSUE THREAD

**Issue by surajpkr** [microsoft/o365-moodle#1712]
Received Error Scheduled task failed: Sync users with Azure AD. (local_o365\task\usersync),set_time_limit() expects exactly 1 argument, 0 given in moodle 3.11

**Comment by weilai-irl** [comment]
Hi @surajpkr,

Thank you for reporting the issue. This will be fixed in the upcoming release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @surajpkr,

The issue should be fixed in the latest release of the plugin.

Thank you again for reporting the issue. I'll close it for now.

Regards,
Lai
