### ISSUE TITLE
Error connect to Azure AD and user sync

### ISSUE THREAD

**Issue by malitup** [microsoft/o365-moodle#1715]
Connecting to Azure AD and user sync not working after upgrade plugins. Existing users can still log in.
auth_oidc 3.10.2 (2020110902) and local_o365 3.10.2 (2020110902). Moodle version Moodle 3.10+ (Build: 20201224)

Error in API call: Access token validation failure. Invalid audience.
![error](https://user-images.githubusercontent.com/86727954/123973264-4a66ca80-d9c4-11eb-9402-8c86c38a3ac3.PNG)

**Comment by weilai-irl** [comment]
Hi @malitup,

It looks like the application token stored in your site is invalid.

Please do the following check to confirm.
 1. Get access token.
   1.1 If you are using "application access" connection method, go to your database and run `SELECT value FROM mdl_config_plugins WHERE plugin = 'local_o365' AND name = 'apptokens';`
   1.2 If you are using "System API user" connection method, go to your database and run `SELECT value FROM mdl_config_plugins WHERE plugin = 'local_o365' AND name = 'systemtokens';`
 2. Use an online unserialize tool, e.g. https://www.unserialize.com/, to unserialize the value returned in the query. The result should be an array, like in the screenshot attached.
 3. Make sure there's an item with key "https://graph.microsoft.com" in the result. If there isn't one, you will need to do the cleanup steps below.
 4. If array item with key "https://graph.microsoft.com" exists in step 3, copy the content of the "token" item, and use https://jwt.ms/ to decode the token. Make sure the "aud" attribute decoded contains "https://graph.microsoft.com", as it's the "audience" that the error message talks about. If it contains different value, you will need to do the cleanup steps below.

Cleanup steps:
 1. In your database, delete existing app tokens. Run `DELETE from mdl_config_plugins WHERE plugin = 'local_o365' AND name in ('apptokens', 'systemtokens');`
 2. Go back to your Moodle site, login as site admin, and purge all caches.
 3. Go to the Microsoft 365 integration configuration page, select connection method, save changes.
 4. On the same page, provide admin consent.
 5. On the same page, in the "Verify setup" section, click "Update" to verify set up again.

This should reset your tokens and ensure everything is back working again.

Please give it a try and let me know if it fixes your issue.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @malitup,

Would you have any updates on this?

Regards,
Lai

**Comment by malitup** [comment]
Hi,
Thanks for the instructions.
I have been on holiday. I solved problem before your first email. I forced uninstalled and re-installed all office 365 plugins and reconfigured settings. That helps me.

Regards
Mikko

Hanki Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
Kohteesta: Lai Wei ***@***.***>
Lähetetty: maanantaina 26. heinäkuuta 2021 klo 18.49
Vastaanottaja: microsoft/o365-moodle
Kopio: Alitupa Mikko; Mention
Aihe: Re: [microsoft/o365-moodle] Error connect to Azure AD and user sync (#1715)


Hi @malitup<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmalitup&data=04%7C01%7Cmikko.alitupa%40riveria.fi%7Cc592ccee89c84985142408d9504cf327%7Cfc6182b0837144ccb3d6b86404016ba5%7C0%7C0%7C637629113705324023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t7dYnkrEo6evS8ZthBFflNLIOirS3wRE3ijf4WfRxz4%3D&reserved=0>,

Would you have any updates on this?

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @malitup,

Thank you for your confirmation.

Yes, uninstalling and re-installing would delete all existing tokens, and create new ones, so it would solve the issue.

I'll close the issue now.

Regards,
Lai

**Comment by kkiiskin** [comment]
ping @weilai-irl 

Don't know if comments even come through from closed issues :)

**Comment by weilai-irl** [comment]
Hi @kkiiskin,

I did get notification on your first note :) Apparently I get notification on all comments of all issues in this project.

I'll investigate and get back to you. It may take some time, but it's on my list.

Regards,
Lai

**Comment by kkiiskin** [comment]
Hei @weilai-irl 

thank you! For more informations, we did have server maintenance when the problem started.
So is it maybe possible that some task to do with the apptoken failed at that time?
