### ISSUE TITLE
Error updating auth_oidc to latest version

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#1716]
Hi

minor error when upgrading to the latest auth_oidc in 39-branch -  3.9.4 (2020071504) -> 3.9.5 (2020071505)
When trying to rename the tokenendpoint, the script is trying to get string instead of config.
As a result, tokenendpoint is not renamed, but authendpoint is. 

auth_oidc/db/upgrade.php, l. 255:
```
$tokenendpoint = get_string('auth_oidc', 'tokenendpoint');
if ($tokenendpoint == 'https://login.microsoftonline.com/common/oauth2/token') {
    $tokenendpoint = str_replace('common', $aadtenant, $tokenendpoint);
    set_config('tokenendpoint', $tokenendpoint, 'auth_oidc');
}
```

**Comment by weilai-irl** [comment]
Hi @kkiiskin,

Thank you for reporting it.

I'll try to fix it asap.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @kkiiskin,

I have updated the release in github and Moodle plugin repository to fix this.

Thank you again for spotting and reporting the bug.

Regards,
Lai
