### ISSUE TITLE
Enhancement: Add option to "Suspend" previously synced accounts in Moodle when they are deleted from Azure AD

### ISSUE THREAD

**Issue by petersercombe** [microsoft/o365-moodle#172]
Many authentication methods that have user sync (e.g. ldap) have a soft option to manage users who are removed from the original directory. This provides some flexibility in the event that a user is accidentally removed, and retains the user's data. Admins can then manually remove suspended users that haven't accessed the site in x many days, etc.

Ideally, if the user is recreated in Azure AD, they would be matched again to the suspended user and un-suspended.

**Comment by mmulrthelp** [comment]
Does the plugin suite suspend and unsuspend account according to whether active in Azure AD? Am I missing something?

**Comment by prawnz** [comment]
This should also take into account if a user that has been blocked sign in to be suspended in Moodle too.

**Comment by nenorojas** [comment]
Hi @mmulrthelp, @prawnz ,

We believe this issue is related to this case https://github.com/microsoft/o365-moodle/issues/272#issuecomment-629294564. 

If it's still an issue, please raise a new request.

Regards
