### ISSUE TITLE
Upgrading Moodle 3.6 to 3.9 gives error Class 'local_o365\obj\o365user' not found

### ISSUE THREAD

**Issue by rvreugde** [microsoft/o365-moodle#1720]
Hello,

We upgraded from Moodle 3.6 to 3.9 and updated our plugins, but trying to logon with our o365 account gies an unexpected error:
![image](https://user-images.githubusercontent.com/38208623/124657038-4514ee80-dea2-11eb-86be-bb05914ca4db.png)

More info about this error gives:
![image](https://user-images.githubusercontent.com/38208623/124657182-755c8d00-dea2-11eb-9ca3-9ae928d8d102.png)

Does anybody have any idea why this error occurs?

**Comment by weilai-irl** [comment]
Hi @rvreugde,

Could you purge site cache and retry please. If you still have the issue, please check to ensure file /local/o365/classes/obj/o365user.php exists.

Regards,
Lai

**Comment by rvreugde** [comment]
Hi Lai,

Caches cleared
![image](https://user-images.githubusercontent.com/38208623/124662284-e69f3e80-dea8-11eb-8a4b-0e3af4379214.png)
**`/local/o365/classes/obj/o365user.php`** does NOT exist in the latest release () !?!?!

**Comment by weilai-irl** [comment]
Hi @rvreugde,

It definitely is. See https://github.com/microsoft/o365-moodle/blob/MOODLE_39_STABLE/local/o365/classes/obj/o365user.php. Could you check your dirroot to confirm please.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @rvreugde,

Could you confirm if the file exists in your version please. I checked the release code again (downloading from Moodle plugin repo https://moodle.org/plugins/local_o365) and it is definitely included.

Regards,
Lai

**Comment by rvreugde** [comment]
Hello Lai,

It seems that the obj folder was missing with the o365user.php file.
We repaired this and logging on works perfectly now.

Thanks a lot for your support!
