### ISSUE TITLE
Changes to course roster/enrolments are not reflected in the associated Class Notebook in the Office 365 group

### ISSUE THREAD

**Issue by petersercombe** [microsoft/o365-moodle#173]
Hi all, just testing the new class notebook integration in groups feature and it is a fantastic development.

I have however noticed that users who are enrolled into the course after the creation of the group & notebook do not seem to be added to the course notebook.  It also doesn't seem possible to manually add them as a student using the usual approach as the notebook doesn't appear in the teacher's course notebooks (either owned or co-owned).

I haven't had a chance to test what happens when a student is removed either.

**Comment by petersercombe** [comment]
Perhaps the addition of some observers required.

**Comment by petersercombe** [comment]
Possibly of use: https://blogs.office.com/2016/02/17/automate-onenote-class-notebook-creation-and-roster-changes-with-new-apis/

Just taking a stab here. I definitely fall into the category of 'power user' rather than sysop or developer. Really keen to get this feature working as it is revolutionary.

**Comment by nenorojas** [comment]
Hi @petersercombe ,

This enhancement request is not in the plans for the foreseeable future, so I'm closing this request.

Regards
