### ISSUE TITLE
"Microsoft 365 Group Membership" user creation restriction no longer creating users

### ISSUE THREAD

**Issue by todog** [microsoft/o365-moodle#1747]
New users are not being created during the Azure AD sync using 3.9.6 (2020071509).  

The failure started only after the plugin was updated from 3.9.4 (2020071506).

The sync is set to Microsoft 365 Group Membership in the User Creation Restriction option.  Users are being updated successfully and users can be created if we change the User Creation Restriction option to Department.

Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
... started 11:56:35. Current memory use 18.8MB.
...... Starting sync
...... No skiptoken (delta) stored.
...... Using deltatoken.
...... Using delta sync.
...... Contacting Azure AD...
...... Got response from Azure AD
...... Storing deltatoken
...... Clearing skiptoken (delta) (none received)
...... 22 users received. Syncing...
...... 22 users in chunk. Syncing...
.........  
......... Syncing user 123456@mood.uk
......... User doesn't exist in Moodle
Cannot create user because they do not meet the configured user creation restrictions.

I don’t know if this is relevant but adding var_dump($users) during the sync doesn’t include any details about group membership. 

Are you aware of any reasons why version 3.9.6 is failing to create new users from Azure groups?

Thanks for any help you can give.

**Comment by weilai-irl** [comment]
Hi @todog,

This is a known bug introduced in the last release. See issue #1719 for details. The pull requests linked to the issue will fix the bug. The fix will be included in the next release.

Regards,
Lai

**Comment by todog** [comment]
Hi Lai

Thanks for the speedy response, 

I've applied the fix and the sync is now working
