### ISSUE TITLE
User Group Restriction

### ISSUE THREAD

**Issue by sumitrathi95** [microsoft/o365-moodle#1748]
Hello Team,
I am trying to use auth-oidc plugin in Moodle. I am able to connect and authenticate it with Keycloak, but I want the specific group of users should be able to access the application.

**Comment by weilai-irl** [comment]
Hi @sumitrathi95,

I'm afraid it is not possible to limit only users from certain groups to use auth_oidc for login when integrating with Keycloak.

If you are using Azure AD, this is possible by using certain user sync settings in the local_o365 plugin, i.e. disable account creation from authentication plugins, configure user sync in local_o365, and apply user creation conditions to limit to certain group. But such facility isn't available for Keycloak IdP, and there is no plan to support it at the moment.

Regards,
Lai
