### ISSUE TITLE
Moodle Teams app not loading the content on the Desktop App

### ISSUE THREAD

**Issue by boroj** [microsoft/o365-moodle#1766]
We have followed the Microsoft Teams Integration process for Moodle. Everything works as expected, the Moodle Teams App opens the courses on Mobile, Web, but not on the Desktop app.

We analyzed the issue and saw that once we access the Moodle Teams app, it follows this flow:
/local/o365/teams_tab.php?id=27755
/local/o365/sso_start.php
/local/o365/sso_end.php
/auth/oidc/index.php

and then it redirects to 

https://login.microsoftonline.com/XXXXXXXXXXXXX/oauth2/authorize

After this we do not see any interaction from the Teams Moodle App with the Moodle instance.

**Comment by weilai-irl** [comment]
Hi @boroj,

Could you clarify the version of your Moodle site, and the version of the Microsoft plugins (local_o365 in particular) please.

Also, is your Moodle site publicly accessible?

Regards,
Lai

**Comment by boroj** [comment]
Moodle 3.11.2 (20210729)
auth_oidc 3.10.2 (2020110903)
local_o365 3.10.3 (2020110904)

The moodle site is publicly available but is configured for forced login, and it is not visible without a login.

**Comment by weilai-irl** [comment]
Hi @boroj,

Thank you for your confirmation. Based on your description, this sounds like an issue with Moodle and Teams SSO.

Could you share maybe share a screen capture (video) of what your users see in the process please? If you don't want to share it publicly, feel free to send it to my email which can be found in my profile.

The desktop app should work in the same way as the mobile app, so it's quite strange to know that it works in the mobile app but not the desktop one. I'll investigate deeper after seeing the video.

Regards,
Lai

**Comment by boroj** [comment]
Hi Lai,

did you had the chance of reviewing the videos I sent to you.

Regards,
Boro.

**Comment by weilai-irl** [comment]
After a call with @boroj, the issue is caused by missing Azure app settings change as described at https://docs.moodle.org/311/en/Microsoft_365#Moodle_and_Teams_SSO_integration. After the changes are applied to the Azure app, SSO in both desktop/mobile apps and web app worked fine.

Lai
