### ISSUE TITLE
Onenote is not available in Active Directory 

### ISSUE THREAD

**Issue by yogeshbl** [Microsoft/o365-moodle#177]
In order to integrate with Office365 & Moodle. I added my office365 AD to Azure AD as existing one. Then I created an APP to complete the process. While, adding the applications, I did not get the Onenote as my application in the list. I was able to add other mentioned services but not the other Onenote.

**Comment by jamesmcq** [comment]
@yogeshbl While OneNote should be available for everyone, I have seen this happen in some tenants. If you have the OneNote desktop application available, logging in to this application with your Office 365 account information should get it to appear in the list. Unfortunately that is all on the Office side and outside the scope of the plugins, should that not work I suggest getting in contact with Office support.
