### ISSUE TITLE
Microsoft 365 Integration sync suspending incorrect users

### ISSUE THREAD

**Issue by mmulrthelp** [microsoft/o365-moodle#1771]
Hi @weilai-irl we've gone live on our production with the following sync options:

Create accounts in Moodle for users in Azure AD
Update all accounts in Moodle for users in Azure AD
**Suspend previously synced accounts in Moodle when they are deleted from Azure AD
Re-enable suspended accounts for users in Azure AD**
Sync disabled status

We have the code you fixed in #1719 added, which is working.

What now appears to be happening when **Suspend previously synced accounts in Moodle when they are deleted from Azure AD** & **Re-enable suspended accounts for users in Azure AD** are ticked, it initially on first run correctly suspended 30,000 accounts which no longer exists in our AD. But it is also slowly suspending ones which are still in AD (around 1000). I think part of the code does not seem to be checking Within our Transitive / Nested AD security group for these users and it is suspending X amount of these accounts on a daily basis, as I think it cannot look whether these accounts exist within the control AD group used in our user creation restrictions.

Could this be happening in your code?

We see entries like this for accounts which do exist
`......... Could not find user xxxxxxxx@xx.xxx.ac.uk in Azure AD. Suspending user...`

We've since turned off  **Suspend previously synced accounts in Moodle when they are deleted from Azure AD** for the time being & have bulk unsuspended the wrongly suspended 1000 accounts.

Slowly the daily sync is now 'Re-enabling users' who I missed with my bulk unsuspend, but it only seems to be doing 30 or so per day, can this amount be increased ? 

Our UAT site is still running the code and options to suspend. I can see that AD accounts which are full active user accounts are being suspended, ones which are older accounts are not being suspended - Both the active and old accounts are in our AD control group, so not sure what the difference is. I've tried to cross check them in Graph API and cannot see a difference to why some are being suspended and others are not.

Many thanks,
Ray.

**Comment by chrisfosterelli** [comment]
We're also seeing this shortly after updating to the latest version of the plugin.

Some users are shown to sync:

```
2021-10-12T13:02:03.764739654Z ......... Syncing user <EMAIL>
2021-10-12T13:02:04.106066586Z ......... The user is already using OpenID for authentication.
2021-10-12T13:02:04.106091847Z ......... User is now synced.
2021-10-12T13:02:04.106097947Z ......... Updating Moodle user data from Azure AD user data.
2021-10-12T13:02:04.273429826Z ......... User is now updated.
```

and then immediately suspended during the suspension check:

```
2021-10-12T14:15:18.326600542Z ......... Could not find user <EMAIL> in Azure AD. Suspending user...
```

Similarly, some users are repeatedly un-suspended, even though there's no indication they were suspended:

```
2021-10-13T13:58:39.933267369Z ......... Syncing user <OTHER EMAIL>
2021-10-13T13:58:40.381896500Z ......... The user is already using OpenID for authentication.
2021-10-13T13:58:40.381921071Z ......... User is now synced.
2021-10-13T13:58:40.381926661Z ......... Updating Moodle user data from Azure AD user data.
2021-10-13T13:58:40.386223139Z ......... User is now updated.
```

followed by:

```
2021-10-13T14:20:30.617469806Z ......... Re-enabling user <OTHER EMAIL>...
```

They were re-enabled the day before as well.

These patterns only seem to show up about a day or two after updating the plugin. Is this the same issue?

**Comment by chrisfosterelli** [comment]
@weilai-irl Thanks for the clarity on this and the upcoming fix. Much appreciated!

**Comment by mmulrthelp** [comment]
--- I thought I'd write this in both #1771 & #1719 just in case it is relevant to others ---

@weilai-irl I'm, testing whether the latest code now unsuspends accounts which got suspended by mistake by the pervious code release. I've a list of 40 odd accounts it occurred to and I'm watching these.

The only problem is it only ever seems to unsuspend 26 or so accounts every run & these runs only occur every 24 hrs, so a final 'it works' results could be a long way off. Is there anyway of getting it to run more often than once every 24hrs?

This is what appears in my sync task log:

...... Start suspend/delete users feature...
...... Suspending deleted users...
......... Could not find user 11111111@xx.xxx.ac.uk in Azure AD. Suspending user...
......... Could not find user 22222222@xx.xxx.ac.uk in Azure AD. Suspending user...
......... Could not find user 33333333@xx.xxx.ac.uk in Azure AD. Suspending user...
......... Could not find user 44444444@xx.xxx.ac.uk in Azure AD. Suspending user...
......... Could not find user 55555555@xx.xxx.ac.uk in Azure AD. Suspending user...
......... Could not find user 66666666@xx.xxx.ac.uk in Azure AD. Suspending user...
...... Re-enabling suspended users...
......... Re-enabling user 10000001@xx.xxx.ac.uk...
......... Re-enabling user 10000002@xx.xxx.ac.uk...
......... Re-enabling user 10000003@xx.xxx.ac.uk...
......... Re-enabling user 10000004@xx.xxx.ac.uk...
......... Re-enabling user 10000005@xx.xxx.ac.uk...
......... Re-enabling user 10000006@xx.xxx.ac.uk...
......... Re-enabling user 10000007@xx.xxx.ac.uk...
......... Re-enabling user 10000008@xx.xxx.ac.uk...
......... Re-enabling user 10000009@xx.xxx.ac.uk...
......... Re-enabling user 10000010@xx.xxx.ac.uk...
......... Re-enabling user 10000011@xx.xxx.ac.uk...
......... Re-enabling user 10000012@xx.xxx.ac.uk...
......... Re-enabling user 10000013@xx.xxx.ac.uk...
......... Re-enabling user 10000014@xx.xxx.ac.uk...
......... Re-enabling user 10000015@xx.xxx.ac.uk...
......... Re-enabling user 10000016@xx.xxx.ac.uk...
......... Re-enabling user 10000017@xx.xxx.ac.uk...
......... Re-enabling user 10000018@xx.xxx.ac.uk...
......... Re-enabling user 10000019@xx.xxx.ac.uk...
......... Re-enabling user 10000020@xx.xxx.ac.uk...
......... Re-enabling user 10000021@xx.xxx.ac.uk...
......... Re-enabling user 10000022@xx.xxx.ac.uk...
......... Re-enabling user 10000023@xx.xxx.ac.uk...
......... Re-enabling user 10000024@xx.xxx.ac.uk...
......... Re-enabling user 10000025@xx.xxx.ac.uk...
......... Re-enabling user 10000026@xx.xxx.ac.uk...
...... Sync process finished.

Other runs show

...... Suspend/delete users feature disabled because it was run less than 1 day ago.
...... Sync process finished.

**Comment by mmulrthelp** [comment]
@weilai-irl Slight testing update, last night it re-enabled 296 users.. so not sure what decides how many it is going to do each run.

**Comment by weilai-irl** [comment]
Hi @mmulrthelp,

First of all, to force run user suspension/deletion on every user sync scheduled task run, you will need to add a line
`$rundelete = true;`
before https://github.com/microsoft/o365-moodle/blob/874ec85125a4b35f6eec172f73b0a066f31a39c1/local/o365/classes/task/usersync.php#L205.

Before you do it, please let me clarify a few points:
 - If you have the "Suspend previously synced accounts in Moodle when they are deleted from Azure AD" option in user sync section checked, when running the user suspension/deletion, the task will always try to get the full list of users for account suspension/deletion, regardless if you have choose to run delta sync or full sync. (Note this forced full sync only applies to account suspension/deletion, and not applied to the normal sync of user profiles.
 - Could you confirm if you see the same set of users who appear on the "Re-enabling user ..." list every time? If so, could you confirm the status of these accounts please? e.g. are the accounts enabled in Azure AD site?
 - When running the user sync task,
    - The task will first process normal user sync, which for existing matched users, it will try to suspend the user if the "suspend" option is enabled, AND the user received has "accountEnabled" set to be false. Note that if you have delta sync enabled, only users included in the delta (whose accounts are changed since the last delta sync) are processed in this section.
    - After processing user sync in the section above, it will start processing specific user suspension and deletion task, which involves getting all users from Microsoft (regardless of delta sync setting), check if the "suspend" option is enabled, and if it is, it will try to find the Moodle users who are currently suspended, but whose mapped Microsoft account have "accountEnabled" set to be true, and un-suspend them.

Please check your users against this logic to see what could have caused the issues in your case.

Just some thoughts:
 - It looks like your normally daily user sync task runs would suspend some users throughout the day, and your first user sync task run of the day, which contains the "Start suspend/delete users feature..." would un-suspend them. That would explain why you see different numbers everyday. If this is the case, the question is then why these accounts were suspended in the first place.

Hope this helps.

Regards,
Lai

**Comment by mmulrthelp** [comment]
@weilai-irl the daily sync is no longer suspending incorrect accounts, just going through and un-suspending the ones which the older code incorrectly suspended, at the time I think it just could not delve into nested groups. It seems to be slowly going through our mdl_user table, where there are 376,140 rows .. its on row 337,775 as of the last of last nights Re-enabling user sync.. so I'll leave this UAT instance to work through them slowly. 

I'll try the above hack on a DEV instance and see what the outcome is. But this version has most likely not got the incorrectly suspended users! But I should see if its runs each sync run.

**Comment by weilai-irl** [comment]
Hi @mmulrthelp,

Would you have any updates on the testing on your dev instance?

Regards,
Lai

**Comment by mmulrthelp** [comment]
Hi @weilai-irl I'm pretty sure all is now well, just on our UAT instance it hasn't un-suspended all of the 38 accounts we noted that had been suspended by mistake by the older code - I was waiting for this instance to naturally finish the task - It just taking it sweet time about it ! 

I did not really want to set the above to run the suspended process each time as this is our like for like instance. I have changed it on our DEV instance and there all 38 ID are in a not suspended state (which is correct) - but they were not suspended to start with!

Before I run with the option on our production I'd like to see more than 50% of the 38 accounts now marked as visible (un-suspended). its currently un-supended 17 of 38! It changed another one on this mornings run, so it is slooooowly still working its way through them. 

Once there I'd be happy to close the ticket

Regards.

**Comment by mmulrthelp** [comment]
Hi @weilai-irl After ticking ‘Perform a full sync each run’, I could then see all the users I was waiting for to show the correct Azure AD status of active. The Delta sync was taking to long to bring them back.

With this we are now going to use it on our production site, come Monday next week after our students have left for Christmas holidays. Hopefully I’ll be able to close this ticket after confirming success then.

Regards,
Ray.

**Comment by weilai-irl** [comment]
Hi @mmulrthelp,

Thank you for the update. Please do keep this post updated. I'm eager to close this issue as it's the only one left open in the Release 2021-10 milestone.

Regards,
Lai

**Comment by mmulrthelp** [comment]
Morning @weilai-irl we went live with this, this morning and it suspended 4,600 accounts.. 

But some we're still active in AAD and in the correct nested control group. 

As a quick fix for today I've used the Moodle GUI to display accounts who have logged in in last 90 days and are suspended and un-suspended those. I'll see what tomorrow's run brings, to see if it re-suspends those 1000 odd accounts.

Happy to show you our side if you have time.

Regards,
Ray.

**Comment by weilai-irl** [comment]
Hi @mmulrthelp,

Please keep me posted on how it goes. If the inconsistency continues, we can definitely look at setting up a call to dig it deeper, but this needs to be in the new year I'm afraid.

Regards,
Lai

**Comment by mmulrthelp** [comment]
Hi @weilai-irl I think we do need to setup a call for the new year, I un-suspended the 2,023 users and switched on a full sync, this ran this morning and it suspended a further 31 users, 4 of which were active accounts.

Hope to speak to you in 2022 - Have a great break.

**Comment by mmulrthelp** [comment]
Hi @weilai-irl today's run it has suspended the same 4 active accounts since yesterday, which tells me it does not like these users being active. So I'll investigate those on our side (one does not have a email address in AAD, which could be the issue - although they should have)

This leaves me to think that the first initial run is more thorough or it does not correct drill down into our Transitive / Nested AD security group & the subsequent ones do. Could there be any truth in that?

**Comment by weilai-irl** [comment]
Hi @mmulrthelp,

Happy New Year.

Am I right to understand that the only remaining issue is that 4 accounts that should be active are suspended on the first run of the user sync task everyday? i.e. is everything else working fine?

If it's the case, could you explain the "oddities" to them please.

I'm not sure if the "transitive / nested security group" thing is relevant in this case. The group restriction check is only performed when determining if a new Moodle account needs to be created for an account existed in Azure AD. It's not checked for existing Moodle accounts.

I'm available for call next week. Please email me directly to arrange a time.

Regards,
Lai

**Comment by mmulrthelp** [comment]
Just to confirm that everything is working fine now when using the December release code.

One part about the suspend / delete process in last 24 hrs spotted and you are picking this up as a separate future development.

Many thanks for you time today.
Ray.
