### ISSUE TITLE
Plugin Authorization method

### ISSUE THREAD

**Issue by jtali** [microsoft/o365-moodle#1779]
Hi

Is it possible change plugin autorization method to basic auth.
Example:

POST /oidc/token HTTP/1.1
Host: xxx.ee
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

grant_type=authorization_code&
code=SplxlOBeZQQYbYS6WxSbIA&
redirect_uri=https%3A%2F%2eteenus.xxx.ee%2Fback

Thank You

**Comment by weilai-irl** [comment]
Hi @jtali 

I know it's a long shot, sorry for not replying you sooner.

I think what you are looking for is best implemented as a local patch. I don't think it's going to be a wildly used feature, and adding it to the release version of the plugin would cause more confusion for the vast majority users who don't need this.

Regards,
Lai
