### ISSUE TITLE
Problem encountered getting a new token. New users won't be created.

### ISSUE THREAD

**Issue by AlexNewson** [microsoft/o365-moodle#1809]
Hey,

I'm encountering an issue within the debug logs where it looks like the token has expired and it can't get a new one.

    local_o365\oauth2\token::get_for_new_resource: Problem encountered getting a new token.
    Data: Array (
    [tokenresult] => Array (
      [error] => invalid_grant
      [error_description] => AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-07-20T11:00:57.6553701Z and was inactive for 90.00:00:00. Trace ID: e0337baf-d3e2-430e-b602-ee9395c26900 Correlation ID: 5e611db9-093b-4347-ba05-9f8560688726 Timestamp: 2021-09-07 12:24:40Z
      [error_codes] => Array ( [0] => 700082 )
      [timestamp] => 2021-09-07 12:24:40Z
      [trace_id] => e0337baf-d3e2-430e-b602-ee9395c26900
      [correlation_id] => 5e611db9-093b-4347-ba05-9f8560688726
      [error_uri] => https://login.microsoftonline.com/error?code=700082 )
    [resource] => https://graph.microsoft.com )

Things I've tried:

- Checked and updated to the latest Microsoft Graph permissions and granted admin consent
- Created a new client secret and added to OpenID connect settings
- Cleaned up existing tokens as mentioned in issue #1715 (interestingly, I don't have an entry for 'systemtokens')
- Used the 'Cleanup OpenID Connect Tokens' and 'Cleanup User Sync Delta Tokens' tools
- I've gone through the [installation steps](https://docs.moodle.org/310/en/Microsoft_365) and double-checked all my settings
- Neither Application Access or System API User seems to be working

This all started when I realized no new users were being created, however login still works for already existing Office 365 users.

Any help would be appreciated, thanks.

**Comment by weilai-irl** [comment]
Hi @AlexNewson,

It's the first time that I see this error. Without a way to reliably reproducing the issue, it will be hard for me to give you an exact solution to it, but I can try to provide some hints that may help you finding the source of the issue.

It looks like the "refresh token" in question might be stored in the mdl_local_o365_token table. Could you check the records in the table of your Moodle site, and see if you can spot anything suspicious from it please? Maybe check the record with user_id 0?

Regarding your question about entry with "systemtokens" doesn't exist, this is expected if you are using "Application access" connection method. Actually, the only proper way to turn off "System API user" connection method is to delete the entry from mdl_config_plugins table with name "systemtokens". If you are using application access connection method, I'd strongly suggest you remove the "systemtokens" entry if it exists, or at least set the value to be empty.

Regards,
Lai

**Comment by AlexNewson** [comment]
Hey @weilai-irl,

Thanks for the quick reply.

For some reason my `mdl_local_o365_token` table is empty, should there be at least one record I can put in to allow the plugin to update it? Not sure what the default state should be.

Thanks,
Alex

**Comment by AlexNewson** [comment]
Interestingly, I've just created a new user on our Moodle installation who is in our Azure AD and the plugin managed to pick them up and assign their o365 account to their Moodle account.

Could the error it's throwing in the log be completely unrelated to the plugin not creating new users? The scheduled task shows:

```
......... Syncing user <email>
......... User doesn't exist in Moodle
Cannot create user because they do not meet the configured user creation restrictions.
```

However I'm 99% sure the user creation restrictions is correct, it being set to `Microsoft 365 Group Membership` and the group name has been copied and pasted from Azure AD. This setting hasn't changed since setup.

Thanks,
Alex

**Comment by weilai-irl** [comment]
Hi @AlexNewson,

The issue in your last comment is a known issue, it's a bug being introduced in the last release. See #1719 for details. The solution is linked from the issue, and will be included in the next release of the plugins, scheduled by the end of the month.

Regards,
Lai

**Comment by AlexNewson** [comment]
Hey @weilai-irl,

That's really helpful, thanks for letting me know. For now I'll create new users manually and let the plugin sync existing accounts and wait for the update at the end of the month.

Not sure what the error is affecting then, but I'll re-open this issue if I find out what it is, but for now everything seems to be functioning correctly.

Thanks again for all your help :)
- Alex
