### ISSUE TITLE
Bug in Onenote submission

### ISSUE THREAD

**Issue by kkiiskin** [Microsoft/o365-moodle#181]
Table "mdl_onenote_assign_pages" has apparently been changed to "mdl_local_onenote_assign_pages" at some point.

But in mod/assign/submission/onenote/locallib.php, function save(), old name is still used (twice) and it causes an error when student is trying to saving submission.

Example locallib.php line 205 or so:
...
// Get OneNote page id.
$record = $DB->get_record('onenote_assign_pages', 
array("assign_id" => $submission->assignment, "user_id" => $submission->userid));

**Comment by jamesmcq** [comment]
This should now be resolved. Thanks for the report!
