### ISSUE TITLE
CRON tasks failing

### ISSUE THREAD

**Issue by ghnewport** [microsoft/o365-moodle#1812]
I have had this plugin fail on CRON processing for some time now. I have just upgraded to Moodle 3.11.2 from 3.9 and ensured that I have the latest version of your plugin but this is still occuring?

Fail delay: 1 day - Process Match Queue (local_o365\task\processmatchqueue)
Fail delay: 8 hours 32 mins - Refresh system API user refresh token (local_o365\task\refreshsystemrefreshtoken)

**Comment by weilai-irl** [comment]
Hi @ghnewport,

Please turn on debugging and paste task output with errors.

Regards,
Lai

**Comment by ghnewport** [comment]
I have the following log…

**Comment by ghnewport** [comment]
Equally, I had this one for the other task…

**Comment by weilai-irl** [comment]
@ghnewport,

Looks like github strips emails. Please add again from github website.

Regards,
Lai

**Comment by ghnewport** [comment]
I did wonder. :)

[local_o365_task_processmatchqueue-29120883.log](https://github.com/microsoft/o365-moodle/files/7128918/local_o365_task_processmatchqueue-29120883.log)
[local_o365_task_refreshsystemrefreshtoken-29119029.log](https://github.com/microsoft/o365-moodle/files/7128919/local_o365_task_refreshsystemrefreshtoken-29119029.log)

**Comment by weilai-irl** [comment]
Hi @ghnewport,

Looks like the plugin doesn't have a valid token to communicate with Microsoft Graph API endpoint.

Please try the following steps:
- Delete existing token records from DB using the following SQL scripts: `DELETE FROM mdl_config_plugins WHERE plugin = 'local_o365' and name in ('apptokens', 'systemtokens');`
- Purge cache.
- In the "Setup" tab of the "Microsoft 365 Integration" configuration page, click "Provide admin consent" again.
- On the same page, click the "Update" button for the "Azure AD setup" setting in the "Verify setup" section, and ensure no error is reported.

This should remove all invalid token records and ensure a new one is created. After the steps, please run the tasks again to see if they work.

Regards,
Lai
