### ISSUE TITLE
Missing parameter: code_challenge_method

### ISSUE THREAD

**Issue by Sectorus** [microsoft/o365-moodle#1815]
Hi!

I tried to configure our moodle testing environment with keycloak via OIDC. Appearently this authentication fails as the logs show an entry with 
`"authcode::handleauthresponse: Authorization error. Data: Array ( [state] => ... [code] => [error_description] => Missing parameter: code_challenge_method ) "`

I was told to enter S256 as PKCE, but I didn't find any setting to set this.

**Comment by weilai-irl** [comment]
Hi @Sectorus,

If I understand it correctly, "code_challenge_method" is an optional parameter in the draft version of specification International Government Assurance Profile (iGov) for OpenID Connect 1.0 (https://openid.net/specs/openid-igov-openid-connect-1_0-02.html). It's not part of the core OpenID Connect specification. The current plugin doesn't support it, and probably will no support it in the near future. I'm afraid you will need to develop custom code to either allow configuring this parameter, or hardcode it somehow.

Regards,
Lai
