### ISSUE TITLE
Moodle - User Creation Restriction issue (Group Membership)

### ISSUE THREAD

**Issue by Anthony-la** [Microsoft/o365-moodle#182]
Hi all, 

We're an educational establishment planning on using Moodle as our learning platform.
We would like to be able to create users through a group and not a particular attribute.
Therefore, we've set "Office 365 Group Membership" as the user creation restriction in the Office 365 plugin. However, this doesn't seem to work. Some fields work, some don't. If we don't choose any creation restriction, all the users are created as requested : this is of course not what we're aiming for.

We have two questions : 
- the user creation restriction field refers to "Group Membership" but what kind of group is it? 
  Azure Active Directory Security group or Office 365 working group?
- In Moodle, some fields in the user creation restriction have a different name from the Azure Directory (for instance company and and companyName). Is it possible that there might be a mapping issue? 

Thank you in advance for the time spent on this issue.

Best regards,

Anthony

**Comment by Eddii11** [comment]
Hi all, 

I have a similar problem. I also want only part of my O365 users to be synced to Moodle. 
I created an O365 group for users who need to synced but it was not working, so I tried to separate them by their email address ending. I want those to be synced which has a @mba.seed-uni.com ending (we are using @stud.seed-uni.com ending for different users). I do not know what is the right "formula" to insert to User Creation Restriction. Should I insert a * before the email address or anything else needed?

![image](https://cloud.githubusercontent.com/assets/24940137/21686260/0a3d31de-d365-11e6-9132-bd07a39ce4d5.png)

I look forward to hearing from you soon, 
Edit

**Comment by jamesmcq** [comment]
Hi @Anthony-la @Eddii11 - thanks for the report. I've had a few requests for some more clarity around this issue so I'm going to make some improvements to our documentation and see what can be done in the UI. Just to keep everything organized I'm going to close this issue and refer you to #171. Please follow that for updates. Thanks!

**Comment by jamesmcq** [comment]
This should be resolved in the latest release. I have clarified the information needed for this setting, and added support for regular expressions. Thanks for the report!
