### ISSUE TITLE
O365 Sync is creating new users in Moodle that are outside the group

### ISSUE THREAD

**Issue by marghar** [microsoft/o365-moodle#1826]
Hello,

For some reason the O365 Sync is creating new users in Moodle that are outside the group.

We have created an application on cloud and we have assigned groups that allow users to use the application. Inside the group its only entitled to students and teachers from @contoso.com. But moodle is syncing people from outside the group for example @hotmail @gmail @shoumaken. Is there any explanation for this weird behavior ?

P.S. We are using
Moodle 3.11+ (Build: 20210701),
OIDC 3.11.0 (Build: 2021051700)
O365 3.11.0 (Build: 2021051700)

Thanks in Advanced.
Mario.

**Comment by weilai-irl** [comment]
Hi @marghar,

This could be related to a known issue as reported in #1734. A solution has been provided in the pull requests linked to the issue, and will be released soon.

Regards,
Lai
