### ISSUE TITLE
Feature Request: Add Manager Mail Attribute

### ISSUE THREAD

**Issue by r1chm0** [microsoft/o365-moodle#1833]
Hello Team,

I would like to request the ability to sync the manager's mail attribute in addition to the manager's displayName.  

This would be useful as we would like to send notifications to a user's manager.

Thanks for your consideration.

**Comment by r1chm0** [comment]
Hello Team,

There was some activity on this feature request last year, including assignment to audrieMSFT, but as I am not a regular github user I don't know how long this process might take.

I am bumping this to know if there is any update that can be offered.  Please advise.  Thank you.

**Comment by audrieMSFT** [comment]
Adding @Mike ***@***.***> who may be able to help with this.

Thank you,
Audrie

**Comment by mmast-msft** [comment]
Approved enhancement.

**Comment by weilai-irl** [comment]
Hi @r1chm0 and @kkiiskin 

The requested feature has been included in the release from today ([3.11.6](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m311), [4.0.3](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m400) and [4.1.1](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m410)). I'll mark this issue closed.

Feel free to reopen if the change doesn't work for you.

Regards,
Lai
