### ISSUE TITLE
Problems when teachers try to view submission or even feedback

### ISSUE THREAD

**Issue by antton** [Microsoft/o365-moodle#186]
I'm reciving the following error from onenote.

Output buffer: { "@odata.context":"https://www.onenote.com/api/beta/$metadata#me/notes/notebooks('1-0520edf0-4b2b-4277-b1f1-969d1ba90aa7')/sections(parentNotebook(id,name,self),parentSectionGroup(id,name,self))","value":[ ] }{ "error":{ "code":"20155","message":"The name of the entity is too long. The entity name must be fewer than 50 characters.","@api.url":"http://aka.ms/onenote-errors#C20155" } }

Error in API call the name of the entity is too long.  The entity name must be fewer than 50 characters.

Any advice. I try as student to change the onenote note name but as I see moodle download it as zip file, so the problem must be different.

Thanks

**Comment by jamesmcq** [comment]
Hi @antton - this is fixed in the newest release. Thanks for the report!
