### ISSUE TITLE
Integration with SDS for Sync with SIS

### ISSUE THREAD

**Issue by audrieMSFT** [microsoft/o365-moodle#1864]
This is a reminder to re-enable the preview feature related to SDS for account synchronization.

**Comment by weilai-irl** [comment]
Hi @audrieMSFT ,

We have just made a release (3.9.8, 3.10.5, and 3.11.2) of the plugins which contains major changes in the SDS feature. Please refer to documentation at https://docs.moodle.org/311/en/Microsoft_365#School_Data_Sync_.28SDS.29 for feature details.

I'll close this issue.

Regards,
Lai
