### ISSUE TITLE
oidc: optional_param on authcode strips period char sent by Keycloak leading to invalid authcode

### ISSUE THREAD

**Issue by rwasef1830** [Microsoft/o365-moodle#187]
Hello,
The OIDC plugin does not work with [Keycloak identity server](http://www.keycloak.org) because it returns authcodes that contain the period (```.```) character which is filtered out by the use of optional_param with the ```PARAM_ALPHANUMEXT``` parameter (only allows [A-Za-z0-9_-]*) in the ```handleredirect``` function in the ```authcode``` class.

The authcode is corrupted by removal of the period character and keycloak then responds with ```code is invalid``` in the second step (exchange of authcode with tokens).

Maybe use ```PARAM_RAW``` here ? There is no point of messing with the ```code``` or the ```state``` values as they are supposed to be opaque string blobs returned from the IdP.

**Comment by rwasef1830** [comment]
Any update on this ? Literally a whole year has passed since I reported this and it is still broken as of the latest release. @jamesmcq

**Comment by jamesmcq** [comment]
Hi @rwasef1830 - sorry for the lack of communication on this. PARAM_RAW is not advisable for parameter cleaning as it can be insecure. Is the "." character the only one causing you problems here?

**Comment by rwasef1830** [comment]
@jamesmcq For keycloak, yes only the "." period character is the problem, but I suggest also allowing colons and other characters that could be used for base64. Technically the openid spec allows this to be anything, so PARAM_RAW would be the ideal solution in my opinion, I don't see how this could be insecure unless the consumers of the parameter do atrocious things like SQL concatenation or other insecure behaviors.

**Comment by jamesmcq** [comment]
Thanks @rwasef1830 I think base64 should be doable and solve problems for most users. You're right that SQL concatenation would be quite bad, and we don't do that, but keeping input to a somewhat known set of values keeps everything safer. I try to keep PARAM_RAW usages to an absolute minimum. Keep an eye out for something next release.

**Comment by jamesmcq** [comment]
The latest release should resolve this. If you have any more issues on this, feel free to open a new issue. Thanks for the report!
