### ISSUE TITLE
Problems setting system API user intoduced in v20161111

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#189]
Version v20161111 introduced a problem setting the system API user for new setups. 

This was caused by a fix to OpenID Connect that resolved a potential situation where a user could have their authentication method changed to OpenID Connect without explicitly requesting it.

v20161202 is being prepared to resolve this issue.

**Comment by jamesmcq** [comment]
This has now been resolved and released in suite version 20160202, auth_oidc v27.0.0.28, v28.0.0.27, v29.0.0.19, v30.0.0.12, v3.1.0.3

**Comment by slc-ddownes** [comment]
I still have the same issue after updating to the latest version.
Using the Bitnami Ubuntu install on a fresh system 3.1.3 Build: 20161202
