### ISSUE TITLE
local_o365 plugin Verify section - show permission names

### ISSUE THREAD

**Issue by tim1mw** [microsoft/o365-moodle#1899]
The "Verify" section of the local_o365 settings page handily lists out the missing application permissions. eg:
![verify](https://user-images.githubusercontent.com/11174402/144448114-e194f0af-c288-429c-b394-053ba83a3d02.png)

however, this only gives the permission description, not it's name and the descriptions frequently fail to give any results when searching for the permission in the "Add Permission" function, eg:

![Screenshot_2021-12-02_15-09-22](https://user-images.githubusercontent.com/11174402/144448685-8d7d0ab4-293c-432b-b16e-219d7244bd76.png)

Forcing the user to trawl through the permissions manually to find one with a matching description. It would be really handy if the permission name was used here instead of (or in addition to) the description so that they can be found quickly.

**Comment by weilai-irl** [comment]
Hi @tim1mw,

I have made a mini release to fix this issue. Please download the latest version of the plugins to see this change.

Regards,
Lai
