### ISSUE TITLE
tablefield resource was not renamed to tokenresource during upgrade process

### ISSUE THREAD

**Issue by nenorojas** [microsoft/o365-moodle#1901]
Daniel Miericke has commented on a plugin you are contributing to:
---------------------------------------------------------------------

Hi,
probably there is a bug in latest 3.9.8 version. The tablefield resource was not renamed to tokenresource during upgrade process. The part in upgrade.php is maybe the $result:
if ($result && $oldversion < 2020071504) {
...

---------------------------------------------------------------------
Plugin link: https://moodle.org/plugins/auth_oidc

**Comment by weilai-irl** [comment]
Hi @nenorojas,

I have made an emergency release of auth_oidc for Moodle 3.9 to fix this bug.

Changes are at https://github.com/microsoft/o365-moodle/commit/427d2a4f9dd3a20b11bc434accbb53a9a795f5b5#diff-08194c6c8adfb99c0fef2b88b10e4cd38c454d76a7e7849c8c6100c1f88599ab

Regards,
Lai
