### ISSUE TITLE
SDS - Error in API call: Required roles claim values are not provided.

### ISSUE THREAD

**Issue by nenorojas** [microsoft/o365-moodle#1902]
If you try to access "School data sync" tab without the changes above to the app, you will get this error message: "Error in API call: Required roles claim values are not provided."

This is expected issue if you are using latest version 3.9.8, 3.10.5 or 3.11.2 and have not updated the app with the following API permissions: https://docs.moodle.org/311/en/Microsoft_365#3.9.8.2C_3.10.5_and_3.11.2_release

Error message should be improved to something more obvious.

**Comment by weilai-irl** [comment]
@nenorojas,

I have made another mini release to fix this issue.

Regards,
Lai
