### ISSUE TITLE
Site Errors and Login Problems changing accounts from manual to openid

### ISSUE THREAD

**Issue by Gonthim** [Microsoft/o365-moodle#191]
I'm not sure where else to ask/discuss this, but I updated the plugin and started getting unexpected behavior so here goes.

First is the error I suppose.

> local_o365\oauth2\token::instance local_o365\oauth2\token::get_for_new_resource:174: Cannot retrieve a token for the base resource. Data: (null)

I've got a lot of manual-login user accounts that are actually linked to Office365 accounts, but I hadn't switched them to OpenID Connect during the fall semester. I'm seeing this error in my logs and it matches the number of user accounts on 'manual' login. When I successfully switched one over to OpenID the count went down, so I believe that matched accounts are checking Office365 tokens even if they're not using OpenID for some reason. Any thoughts?

Unexpected Behavior:

#189 mentions a change that prevents admin from changing a users login method from Manual to OpenId unless the user requests it. I can still do the change in their account profile, but that just locked the user out completely. When they attempt to login with the manual password or the office365 password it errors out and says:

> To sign into this application the account must be added to the graph.windows.net directory.

My main question about this is that the Office365 Integration Options still has 'Switch matched users to Office 365 (OpenID Connect) authentication'. If I hit that check box to switch the users over using the cronjob am I going to lock all the users out like what happened when I did it manually? Or does the plugin use a different process when that box is checked?

Thanks.

**Comment by jamesmcq** [comment]
Hi @Gonthim - To switch an existing user to OpenID Connect, you'll need to use the Microsoft block. The best way to do this as an administration is to use Moodle's "login as" feature. The page you used to link the accounts also provides an option to migrate to an OpenID Connect connection. 

Changing the user's authentication method via the user's profile, as you described, can indeed cause problems. The tokens and connections needed to property operate are only set up when the plugins themselves change the authentication method.

One thing to note: The "Switch matched users to OpenID Connect" option only applies to newly matched users that are processed during the user sync. Existing users not altered. Based on what you've described, I think the best way to switch these users will be to use Moodle's "Login as" feature to switch the user, or to instruct the user how to do this themselves.

**Comment by naldo-gomes** [comment]
Hello guys!

I have a problem to macht users in moodle.

When trying to access with the user we received the message that "OpenID Connect, you'll need to use the Microsoft block" needs to be configured
However, the user is an end user and does not have access to the Microsoft block.
We have already changed the user id directly in the bank, linking to the id that was previously 0.
I need help to solve this problem.

**Comment by naldo-gomes** [comment]
Hello guys!

I have a problem to macht users in moodle.

When trying to access with the user we received the message that "OpenID Connect, you'll need to use the Microsoft block" needs to be configured
However, the user is an end user and does not have access to the Microsoft block.
We have already changed the user id directly in the database, table - **mdl_auth_oidc_token**  linking to the id that was previously 0.
I need help to solve this problem.
This is the error that is occurring

![image](https://user-images.githubusercontent.com/75033869/100260469-2f147800-2f28-11eb-8cba-3258c0b5eb31.png)
