### ISSUE TITLE
filter_oembed: Implement privacy provider

### ISSUE THREAD

**Issue by golenkovm** [microsoft/o365-moodle#1919]
Hi team,

Core privacy testsuite is failing with the plugin installed:

```
root@4a9a6ab84ac7:/siteroot# vendor/bin/phpunit --testsuite=core_privacy_testsuite
Moodle 4.0dev+ (Build: 20211207), 5ee0b620ae99bebeca9ee2c18078ee010913ae65
Php: 7.4.3, mysqli: 5.7.31, OS: Linux 5.4.0-91-generic x86_64
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.

~
~
~

1) provider_test::test_all_providers_compliant with data set "filter_oembed" ('filter_oembed', 'filter_oembed\privacy\provider')
Failed asserting that false is true.

/siteroot/privacy/tests/provider_test.php:178
/siteroot/lib/phpunit/classes/advanced_testcase.php:80
```

**Comment by weilai-irl** [comment]
Plugin filter_oembed is to be removed from the plugin set as it's not required anymore.

The issue will be closed when the change is released.

**Comment by weilai-irl** [comment]
Hi all,

The filter_oembed plugin is not a part of the Microsoft plugins suite for Moodle anymore. Please report the issues about the plugin according to links on https://moodle.org/plugins/filter_oembed.

Regards,
Lai
