### ISSUE TITLE
calendar outlook-moodle sync problems, two way

### ISSUE THREAD

**Issue by tamaserdelyi** [Microsoft/o365-moodle#192]
Hi, I´ve just tested the calendar sync funcionality with moodle version 2.8.12, unfortunately if I change an entry in my outlook calendar, the entry is not changed in my moodle calendar, after running the cronjob.

**Comment by nimojg-microsoft** [comment]
Have you tested this with the latest version of the plugins? Also have you checked the cron settings?

**Comment by jamesmcq** [comment]
This issue was closed as part of an automated cleanup of old issues. If you are still experiencing a problem, please feel free to create a new issue with any recent developments. Thank you!
