### ISSUE TITLE
theme_boost_o365teams: Implement privacy provider

### ISSUE THREAD

**Issue by golenkovm** [microsoft/o365-moodle#1923]
Hi team,

The theme_boost_o365teams plugin breaks core unit tests once installed due to missing GDPR support.

Kind regards,
Mikhail

**Comment by chrisoconnor** [comment]
Hi @golenkovm 
Thank you for your contribution it has been merged into the release 3.9.9, 3.10.6, 3.11.3 on 06/04/2022.
I'll close this ticket.

Chris
