### ISSUE TITLE
Match users o365 with moodle users

### ISSUE THREAD

**Issue by gmisterk** [Microsoft/o365-moodle#193]
Hi, 
I need some info about this plug in (something gone wrong with this, i don't know if it's a bug)

i have a moodle account, and a office 365 account
my moodleuser is enrolled in two courses.
I put in tool tab>  match user > uplaod a cvs file with this data :+1: 
moodleuser; jim.cake@onmicrosoft.com;1

so, now when i login with jim.cake@onmicrosft.com, I arrive in edit profile page, and i am not enorroled in any cours.

how can use independamently moodleuser / jim.cake@onmicrosoft.com to arrive in the same profile, with the same acount, and the same courses enrollement.

regards

**Comment by rimas-kudelis** [comment]
(Coming from #180)
I haven't tested CSV matching, but assuming that it works, I would guess that either there was a typo in your Moodle username, or in your Office 365 username, or that the CSV import requires you to use commas as separators, and you used semicolons, but in that case, you should see errors like this above the file drop area when you click "Add Data File to Match Queue":
````
Line #1 contained invalid data. Each line in the CSV file should have two items: the Moodle username and the Office 365 username.
Line #2 contained invalid data. Each line in the CSV file should have two items: the Moodle username and the Office 365 username.
````

**Comment by gmisterk** [comment]
yes sorry, i used comma and not this symbole  ";" in my file.
I have tried with this data :
moodleuser, jim.cake@onmicrosoft.com,1 

but when i upload, i get a blank page !

and nothing is added to the datatable : mdl_local_o365_matchqueue

I can add manually the info in this table but with no success, when i log in with jim.cake and don't arrive in moodleuser page.

It's stange.....

**Comment by rimas-kudelis** [comment]
Check the error logs for PHP and your web server. If PHP logging is not enabled, you may want to enable it.

**Comment by gmisterk** [comment]
Hi i have check php log, but nothing in it.

I foget to say you that my moodleuser have not the same name that o365user (names are differents)

**Comment by jamesmcq** [comment]
Hi @gmisterk - the blank page definitely indicates a PHP error somewhere, can you make sure developer debugging is enabled in Moodle when you try the upload? Having that enabled should show any errors that may have occurred. Since nothing is added to the matchqueue table, as you mentioned, and the user is not being matched (as indicated by the new user created), it's likely an error in the upload process is preventing the match from continuing.

**Comment by gmisterk** [comment]
Hi yes thanks jamesmcq,  now when i enable debug mode i see this error after upload

Fatal error: Class 'finfo' not found in D:\TRA\www\moodle\local\o365\classes\page\acp.php on line 145

**Comment by gmisterk** [comment]
ok so, now i found that fileinfo php extention was not enabled.

now upload is success but the problem still running.....

in debug mode after upload is see this error : 
Error: mdb->get_record() found more than one record!•line 1539 of \lib\dml\moodle_database.php: call to debugging()
•line 47 of \auth\oidc\classes\loginflow\rocreds.php: call to moodle_database->get_record_sql()
•line 72 of \auth\oidc\classes\loginflow\rocreds.php: call to auth_oidc\loginflow\rocreds->check_objects()
•line 96 of \auth\oidc\auth.php: call to auth_oidc\loginflow\rocreds->loginpage_hook()
•line 90 of \login\index.php: call to auth_plugin_oidc->loginpage_hook()

and when user365 log in he arrive in new profile page and not in usermoodle page

thans for any help

**Comment by nimojg-microsoft** [comment]
@gmisterk  Are you still seeing the issue with the latest version of the plugins?

**Comment by jamesmcq** [comment]
@gmisterk That error would indicate that the user in use is connected to multiple Moodle users, or vice-versa. We have a new user connections page in the "Tools" tab of the settings page that will help you sort that out - search for the Office user or Moodle user and observe the connections - delete the one you don't want. Hope that helps! I'm going to close this issue for now but feel free to open a new issue if you continue to have problems or encounter anything else. Thanks!
