### ISSUE TITLE
Setup Issue - Provide Admin Consent - Error: AADSTS650056

### ISSUE THREAD

**Issue by nafees-ukim** [microsoft/o365-moodle#1942]
Hello,

Moodle Version: 3.10+ (Build: 20201127) (2020110900.03)
Microsoft Office 365 Integration - 3.5.0.1 (2018051701)

I am trying to do complete the setup on a Moodle service hosted by a party. I have admin access both to Moodle and Azure instances. I have followed the instructions for the manual setup of permissions, however I get the following error when clicking on the 'Provide Admin Consent' option.

"There was a problem logging you in. Please contact your administrator for assistance."

Via the Moodle debug logs I see the following corresponding entry:

"...AADSTS650056: Misconfigured application. This could be due to one of the following: the client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, the admin has not consented in the tenant. Or, check the application identifier in the request to ensure it matches the configured client application identifier. Or, check the certificate in the request to ensure it's valid. Please contact your admin to fix the configuration or consent on behalf of the tenant..."

I have tried adding and removing the permissions but still get the same error. Going by past comments (back in 2019) a potential fix was to add 'Azure Active Directory Graph' permissions. However it is no longer possible to do this. Here is my permissions list:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/82222384/150170829-b3d0b120-eaac-4243-845f-c6a966e6e02b.png">

Please can someone help troubleshoot?

Thanks,

Nafees

**Comment by weilai-irl** [comment]
Hi @nafees-ukim,

Please download the latest version of the plugins for your Moodle version (3.10 in your case) from Moodle plugin repository. For local_o365 it's at https://moodle.org/plugins/local_o365/versions. 3.5.0.1 is fairly old version and has been out of support for some time (2+ years) now.

Regards,
Lai

**Comment by weilai-irl** [comment]
Thank you for posting your solution @jcchinnu.

Since this is for an unsupported version of the plugin, and there is a possible solution to it already, I'm closing this issue.

Regards,
Lai

**Comment by nafees-ukim** [comment]
Thanks Lai (and jcchinnu!), apologies for the slow update. You were correct the issue was down to the out of date plugin, I tested on the latest version on Moodle and it worked. I managed to get the service provider to update their plugin for their platform to enable the successful integration.
