### ISSUE TITLE
Issue with Start suspend/delete users sync features timing

### ISSUE THREAD

**Issue by mmulrthelp** [microsoft/o365-moodle#1944]
Hi Lai, 

A ticket to mention (& so I can track progress) what we spoke about where the timing of the once per 24 hr run of **Sync users with Azure AD** occasionally does not Start the suspend/delete users feature. This is because each run takes 10 mins on average on a large site and it adds up those 10 minute runs and eventually will skips a day as the time taken is over 1 hour.

I've found a way around this by one running the sync for 1-5 days (Monday to Friday) in **Day of week** setting on the sync, but even with this in place it has still already skipped a day.

To Note: I now only have the sync set to run once per day in the early hours of the morning.

Many thanks,
Ray.

**Comment by mmulrthelp** [comment]
You can see that its got itself into a pickle twice this week already
![image](https://user-images.githubusercontent.com/16646247/150556512-d1f186f6-2680-4206-904c-c7d51bf19b19.png)

I've changed it to now run 7 days per week and twice a day, to see if that helps until the fix comes.

**Comment by weilai-irl** [comment]
Hi @mmulrthelp,

The latest 3.9.9, 3.10.6 and 3.11.3 release of the plugins from 04/06/2022 contains the improvements in limiting the number of account suspension/deletion runs in the user sync task. Please check them out.

Regards,
Lai

**Comment by mmulrthelp** [comment]
This is all working now. I just forgot to update this ticket. Many thanks.
