### ISSUE TITLE
Question: Office 365 & Moodle Integration 

### ISSUE THREAD

**Issue by arianalidagarcia** [Microsoft/o365-moodle#196]
Hi Team, 

I would like to know if it is possible to implement an Office 365 & Moodle Integration having 2 different domains (one for teachers and the other for students)

Example: Students have an alumni.edu Office 365 account and teachers teacher.edu. 
Both domains are included in the same tenant/subscription. 

Can we make the Moodle integration having 2 different domains?  

Thanks in advance for any guidance. 

Regards,

**Comment by petersercombe** [comment]
Hi @arianalidagarcia, I'm not an official rep for the team who've created this plugin, but we are running this plugin set with nearly 20 domains that are all in the same tenant without issues. I think you'd run into trouble if you had different tenants/subscriptions.

We have multiple schools in the same tenant with entirely different domains. Students are all on subdomains of each schools' primary domain.

**Comment by arianalidagarcia** [comment]
Hi Peter, 

Thanks for your response. 

Have you tried a Moodle & Office 365 integration among 2 completely different schools subdomains in the same tenant/subscription? 

Basicaly, I would like to know if it is possible a Moodle with Office 365 Integration where **teachers who have a primary domain** (in the same tenant/subscription) and **students who have a subdomain completely different to teachers's domain** (in the same tenant/subscription) **can coexist sharing and interacting in one unique Moodle with Office 365 integration** 

Due to manage and security matters, teacher and students will probably be in different domains. 

Thanks in advance for any guidance.

**Comment by petersercombe** [comment]
Yes, I believe what you're asking is possible. 

For more context, we have 11 individual schools (some in different states of Australia), each with their own domain (e.g. school1.qld.edu.au, school2.sa.edu.au, etc). We all use the same moodle (https://learner.link). The key is that all the schools are in the same Office 365 tenant - which I understand is the way you have things configured, so I'm fairly confident what you're asking will work.

**Comment by jamesmcq** [comment]
Thanks @petersercombe - yes you are correct. If everyone is in the same tenant there should be no problem. Multiple tenants is possible as well, but gets a little trickier. Thanks all!
