### ISSUE TITLE
Linked accounts and changing usernames

### ISSUE THREAD

**Issue by mrbryce2000** [Microsoft/o365-moodle#198]
This is a development on the classic problem of institutions having to change user login names.

In this particular university:
- we use LDAP authentication for Moodle
- we setup the Office 365 integration, but **did not change** the authentication method
- we use the Microsoft Block on the dashboard to manually link to Office 365

My question is this:  what will happen to the established link if the username for the account changes in Active Directory? This can happen with a marriage/divorce, or an adoption, for example. The username and email address will change for authentication, but will we have to make sure the old account is un-linked in Moodle first? Otherwise, with a different username, Moodle may report that that the account is already linked.

Related to that, is there a way to view all linked accounts in the Office 365 Integration local plugin?

**Comment by jamesmcq** [comment]
@mrbryce2000 There can be issues with changing usernames in Azure AD which I'm currently working to resolve. The most reliable way is to disconnect the Moodle and Azure AD users (using the option in the Moodle plugins), make whatever username changes you need, then connect them back together.
