### ISSUE TITLE
Not a valid 5 segment tokent

### ISSUE THREAD

**Issue by berthelemy** [Microsoft/o365-moodle#200]
[Issue moved from https://moodle.org/mod/forum/discuss.php?d=278647#p1399981]

We're using the OpenID Connect plugin to hook up to an Azure Active Directory (B2C)

When the token comes back we get the error:

Error in OpenID Connect: ###: The provided JWE '[very long token string]' is not a valid 5 segment token. 

### Debug info: 

Error code: erroroidccall_message

Stack trace:

·         line 54 of \auth\oidc\classes\utils.php: moodle_exception thrown
·         line 252 of \auth\oidc\classes\oidcclient.php: call to auth_oidc\utils::process_json_response()
·         line 177 of \auth\oidc\classes\loginflow\authcode.php: call to auth_oidc\oidcclient->tokenrequest()
·         line 84 of \auth\oidc\classes\loginflow\authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()
·         line 105 of \auth\oidc\auth.php: call to auth_oidc\loginflow\authcode->handleredirect()
·         line 29 of \auth\oidc\index.php: call to auth_plugin_oidc->handleredirect()

**Comment by jamesmcq** [comment]
Hi Mark - Thanks for the detailed information. This is a part of the code where we are essentially passing an authorization code from Azure AD back to a different Azure AD API - the error message you posted is coming from Azure AD. It seems Azure AD is not accepting information it previously sent. I've contacted Microsoft to get more information on this.

**Comment by berthelemy** [comment]
Hi James, just to let you know we've tried authenticating against a brand new normal Azure AD and it works fine. So it seems to be something to do with Azure B2C.

**Comment by SyedAli14** [comment]
Hi James, It appears as when a policy with policy endpoints are used we get the JWE error. I've tried the same test with just Azure AD and Azure B2C without a policy which I understand is the same as Azure AD on the backend and all works as expected.

Does the plugin support using policy endpoints with a Azure B2C set-up?

**Comment by jamesmcq** [comment]
Hi All, I've looked in to this and at the moment Azure B2C uses a newer endpoint than we support, and this looks to be the cause of the problems you're seeing. I've added this to our future consideration list but we don't currently have a timeline for B2C support.

**Comment by xfreakx** [comment]
@jamesmcq could you at least point me what should be changed? Maybe i can help to solve this...

**Comment by xfreakx** [comment]
@jamesmcq found a first bug ...

authcode.php, line 80

 'code' => optional_param('code', '', PARAM_ALPHANUMEXT),

Token is changed while being sanitized

**Comment by xfreakx** [comment]
@jamesmcq  the other change you need to make is adding clientId to the "scope" to obtain access_token ... and it works

**Comment by paul4devon** [comment]
Hi Folks, we are also looking to make use of this plugin for Azure B2C.. This chain suggests that there is a fix or work around...  Would really appreciate your support/advice?  Cheers, Paul

**Comment by GopalSharma** [comment]
Hello everyone, I know its a very old issue but We are facing the same issue, really appreciate any help.
Do we have any update on the **Azure B2C** using the [OpenID Connect](https://moodle.org/plugins/auth_oidc) plugin?
Is there any other plugin which we can use to achieve this?
 Thank you,
Gopal

**Comment by AfsarP1** [comment]
I'm receiving the same error. I've built a custom data connector to use it with power BI. I've tried adding client_id to the scope and it made no difference. 

Has there been any progress and any suggestion now which could help.

**Comment by dharmikvyas** [comment]
> Hello everyone, I know its a very old issue but We are facing the same issue, really appreciate any help.
> Do we have any update on the **Azure B2C** using the [OpenID Connect](https://moodle.org/plugins/auth_oidc) plugin?
> Is there any other plugin which we can use to achieve this?
> Thank you,
> Gopal

have you found any solution for OpenID?
