### ISSUE TITLE
User match tool not working

### ISSUE THREAD

**Issue by nairial** [Microsoft/o365-moodle#201]
I'm using Moodle 3.2.1+ and the latest 3.2 office 365 plug ins.  I'm trying to use the user matching tool, but it's creating a new user with a blank profile instead of linking users.

User "testuser2" already exists in moodle, and I want to link him to an o365 user.
I upload a file that looks like this:

testuser2,testuserjr@wiccanseminary.edu,1

On refreshing, the page says everything is green and worked.  I also logged cron, and it reported this:

Scheduled task complete: Sync o365 events in to Moodle (local_o365\feature\calsync\task\importfromoutlook)
Execute scheduled task: Process Match Queue (local_o365\task\processmatchqueue)
... started 20:04:02. Current memory use 31.5MB.
Processing testuser2/testuserjr@wiccanseminary.edu
Adding o365 object record for user.
Updating user authentication record.
Match record created for userid #3591 and o365 user testuserjr@wiccanseminary.edu
... used 7 dbqueries
... used 0.31554102897644 seconds
Scheduled task complete: Process Match Queue (local_o365\task\processmatchqueue)
Cron script completed correctly

However, when I log in as testuserjr@wiccanseminary.edu a blank profile page comes up.  If I fill out the blank profile page I end up creating a totally new user in Moodle.  (If I don't fill out the blank profile page, a blank user is created.)  If I edit the user's profile as admin, I see that the username testuserjr@wiccanseminary.edu is greyed out, and OpenID Connect is the authentication method.

The original moodle testuser2 account remains disconnected from o365, although its authentication method has been changed to openid connect, it's greyed out username is still testuser2.

Suggestions?  I've turned on debugging, but don't see anything.

**Comment by giselebrugger** [comment]
I have the same problem
Moodle 3.4.1+ (Build: 20180118) with last upgrade (https://github.com/Microsoft/o365-moodle.git)
[ https://qsnapnet.com/snaps/3b5mfva5rc8oajo]

A new user in moodle is created after o365 login.
See my configuration

![moodle_ administration_ plugins_ authentication_ openid connect](https://user-images.githubusercontent.com/5620195/35773085-3e24b1b0-092f-11e8-96f8-127943884e7b.jpg)

![moodle_ administration_ plugins_ local plugins_ microsoft office 365 integration](https://user-images.githubusercontent.com/5620195/35773114-e2363d3c-092f-11e8-96a9-d257df6e379d.jpg)


![moodle_ administration_ plugins_ local plugins_ microsoft office 365 integration_options](https://user-images.githubusercontent.com/5620195/35773130-35eabb88-0930-11e8-914a-5e1d99dadf12.jpg)

![microsoft office 365 integration administration control panel_health_check](https://user-images.githubusercontent.com/5620195/35773137-801293de-0930-11e8-9494-55e159541c28.jpg)

**Comment by nimojg-microsoft** [comment]
Have you tested using the latest release? Are you still seeing the same issue?

**Comment by jamesmcq** [comment]
Hi All, this can happen if the plugins cannot retrieve the user's information. The posted screenshot indicates the system API user is able to communicate, so it may be a permissions issue - is the system API user an administrator?

I'm going to close this issue due to age, but if you're still experiencing problems please create a new issue. Check out the troubleshooting section of the documentation as well (https://github.com/Microsoft/o365-moodle/blob/master/Office365Documentation.md#troubleshooting) for instructions on gathering additional debug information that will help any future investigation.
