### ISSUE TITLE
Bug : Can't init phpunit tests

### ISSUE THREAD

**Issue by levemar** [microsoft/o365-moodle#2018]
When I install auth_oidc and local_o365, if I run "php admin/tool/phpunit/cli/init.php" at the end of the initialisation process I get the following error : 

!!! Please set application credentials in auth_oidc first. !!!
!! 
Error code: erroracpauthoidcnotconfig !!
!! Stack trace: * line 102 of /local/o365/classes/oauth2/clientdata.php: moodle_exception thrown
* line 43 of /local/o365/classes/feature/sds/utils.php: call to local_o365\oauth2\clientdata::instance_from_oidc()
* line 451 of /local/o365/settings.php: call to local_o365\feature\sds\utils::get_apiclient()
* line 67 of /lib/classes/plugininfo/local.php: call to include()
* line 780 of /admin/settings/plugins.php: call to core\plugininfo\local-&gt;load_settings()
* line 8917 of /lib/adminlib.php: call to require()
* line 8943 of /lib/adminlib.php: call to admin_get_root()
* line 522 of /lib/installlib.php: call to admin_apply_default_settings()
* line 468 of /lib/phpunit/classes/util.php: call to install_cli_database()
* line 150 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()
 !!

This prevents me to run any phpunit test in my Moodle instance, which is really an important bug!

I am using the last version of both plugins, and Moodle 3.11.5

Thanks!
Marie-Eve

**Comment by levemar** [comment]
I made further tests and the bug occurs with version 3.11.2 of the plugins, but not with version 3.11.1

**Comment by levemar** [comment]
Hi @chrisoconnor 
I see that this issue is assigned to you. Do you think there will be a possibility for me to cherry-pick the commit before the official release that seems to be for july? 
Thanks, 
Marie-Eve

**Comment by weilai-irl** [comment]
Hi @levemar,

Yes, pull requests will be made available and linked to this issue as soon as development is done. Feel free to cherry-pick and apply to your environment.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @levemar,

The error reported in this issue has been fixed in the latest release from today. I'll close the issue now.

Thank you again for reporting the issue.

Regards,
Lai
