### ISSUE TITLE
Recreating 365Group\Teams site after 30 days hard delete - but teams course record still in [mdl_local_o365_objects] table

### ISSUE THREAD

**Issue by geobuc1** [microsoft/o365-moodle#2019]
Not sure where to ask this question (of if even appropriate on Github), as not strictly an issue more of an unknown. Forgive me as I have just been asked to look into this as previous developer\admin has left suddenly. $plugin->release = '3.9.0';$plugin->version = 2020071500; Moodle version 3.9. Situation where a Teams site that was created via Moodle To teams integration but has been hard deleted (over 30 days ago) before teachers flagged so cannot restore via 365 admin . 

However, within the [mdl_local_o365_objects] tbl 
where (type = 'group') the course team record still exists (subtype= course; courseteam) but no 365 group or Teams site. I am unsure of how to recreate i.e. recreate the linked site this if already exists in [dbo].[mdl_local_o365_objects] table? I going to hazard a guess than absolutely not as straightforward as deleting from the is table. Any advice would be greatly appreciated (or pointing me in the right direction would be greatly appreciated)
Thanks in advance.

**Comment by weilai-irl** [comment]
Hi @geobuc1,

Sorry for not getting back to you sooner. We have been busy with the latest release of the plugins.

In short, the easiest option is to delete the connection record of the course from the mdl_local_o365_objects table, and let the next course sync scheduled task run (\local\o365\groupcreate) to create a new group/team. You can use SQL statement such as this one:
`DELETE FROM mdl_local_o365_objects WHERE type = 'group' AND moodleid = COURSE_ID;`

Please post back if this answers your question.

Regards,
Lai

**Comment by geobuc1** [comment]
Hi Lai,

No need to apologise  as I can fully appreciate how busy you are! Thank you
for the reply. This worked and solved my problem. 365 group\Team recreated
on the next cron run.

Many thanks for your help and good luck with the latest release of plugins.

Regards

George
