### ISSUE TITLE
Error Upgrading local_o365 (Moodle 2020071552) on Moodle 3.9.12+

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#2022]
Hello,

after upgrading to the newest o365-plugin set we will get this error message by upgrading the local_o365 (Moodle 2020071552). We are not able to finish the upgrading process.
![error_local_o365](https://user-images.githubusercontent.com/66412602/162722367-2bd2f139-0517-4e3e-a8a3-12387e7c899c.png)

We are using Moodle 3.9.12+. We did an update directly from an older plugin version (Moodle 2020071543). All other updates (auth_oidc, repository_office365, theme_boost_o365teams) works fine.

Any ideas whats wrong?

thanks, best regards
Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

I have updated the latest release of the local_o365 plugin with a fix to the issue. Please use this new version. Note the release is still called 3.9.9 but it has a new version number.

Regards,
Lai

**Comment by AntonT76** [comment]
Dear @weilai-irl
thank you for quick bug fixing. I have just installed the new version, now everything is running correctly.
br, Anton

**Comment by weilai-irl** [comment]
Hi Anton,

Thank you for your confirmation. I'll close the issue then.

Regards,
Lai
