### ISSUE TITLE
Further improvements in the logic to limit number of runs in user suspension/deletion part of user sync scheduled task

### ISSUE THREAD

**Issue by weilai-irl** [microsoft/o365-moodle#2023]
In https://github.com/microsoft/o365-moodle/issues/1841#issuecomment-1097237199, @tlock pointed out that there are two issues in the logic to limit number of runs in user suspension/deletion part of user sync scheduled task, which was updated in the 3.9.9/3.10.6/3.11.3 releases in April 2022.
- "tomorrow midnight" sets as UTC which means it will run during the day because we are in Australia
- execution on test, stage and prod environment run all at the same time making the issue worse

This will be addressed in the next release.

**Comment by tlock** [comment]
Hi Lai,

Another issue we are seeing which would be resolved by this suggestion is every couple of days the sync time slips forward a hour scheduled execution time so I have to reset manually to 1am again.

**Comment by weilai-irl** [comment]
The issue is fixed in the latest release (4.0.1, 3.11.4, 3.10.7 and 3.9.10).

Closing call.
