### ISSUE TITLE
404 error on Moodle when authenticating

### ISSUE THREAD

**Issue by logicexpertise** [microsoft/o365-moodle#2030]
We are using the 3.11.1 version of the OIDC plugin on a Moodle 3.11.3+ site. Authorization code flow.

We have encountered an issue whereby users successfully authenticate on the OIDC server, however on redirecting to Moodle, the following error is displayed:
![image](https://user-images.githubusercontent.com/3681574/163918064-f074a4b7-d7ce-499d-81e9-6e4ef59dd8ff.png)

The browser console shows this:
![image](https://user-images.githubusercontent.com/3681574/163918465-35cd8d45-6ff1-43b6-8786-666d6279facb.png)

With debugmode turned on in OIDC plugin settings, the following is logged to Moodle log:

![image](https://user-images.githubusercontent.com/3681574/163926945-9deae0dc-78ab-45c8-9ef7-e4e4308f14f0.png)

The issue affects all users using OIDC authentication method.

**Comment by weilai-irl** [comment]
Hi @logicexpertise,

It looks the error is about the authentication process failed to get an ID token from the IdP. Could you verify that your "Token Endpoint" (auth_oidc/tokenendpoint) configuration of the auth_oidc plugin is configured correctly according to your IdP please.

For a bit of technical details - the "auth code" received in the authentication request is used in the function `tokenrequest()` at https://github.com/microsoft/o365-moodle/blob/c31f00339d02c1fa38bbcf3720544eb14b7e31a1/auth/oidc/classes/oidcclient.php#L277-L293 to get an ID token. Your error suggests that the "auth code" was received correctly in the authentication request, but you didn't receive an ID token as expected.

Please verify your settings and let me know if that solves the issue. We can dig deeper if that wasn't the issue.

Regards,
Lai

**Comment by logicexpertise** [comment]
@weilai-irl 
Apologies for the delay in providing an update to this.

The issue turned out to be a misconfiguration on a server downstream of the IdP.

I'm going to close this issue.

Thanks for your patience.
