### ISSUE TITLE
boost_o365teams error moodle 4.0

### ISSUE THREAD

**Issue by grantcolin** [microsoft/o365-moodle#2032]
boost_o365teams does not work on moodle 4.0

error in class theme_boost_o365teams_mod_assign_renderer extends.....

I change to core_renderer and seems to work now.

**Comment by aviationhacker** [comment]
Ahh! @grantcolin thanks for posting this, as you've just saved me a heap of hassle - it seems Moodle does some sort of check with the theme if you login via OAuth, and will throw this error even if the theme isn't in use, making this fix useful if you want your site to work at all with 4.0 and the 365 plugins installed!

**Comment by grantcolin** [comment]
yeah dont change it to core_renderer as it will break your main theme.

can anyone else come up with a fix ?

**Comment by weilai-irl** [comment]
Hi all,

FYI, we will be working on the first version of the plugins for Moodle 4.0 in the next few weeks. A rough estimate when it will be available is towards end of May or early June.

Regards,
Lai

**Comment by dmid20** [comment]
Hi,
they have moved the classes in mod_assign.
As workaround I had to fix theme/boost_o365teams/renderers.php like this:

--- renderers.dist      2022-04-26 14:59:20.537927512 +0200
+++ renderers.php       2022-04-26 14:57:41.077032739 +0200
@@ -25,7 +25,7 @@
 defined('MOODLE_INTERNAL') || die();

 require_once($CFG->dirroot . '/course/renderer.php');
-require_once($CFG->dirroot . '/mod/assign/renderer.php');
+require_once($CFG->dirroot . '/mod/assign/classes/output/renderer.php');
 require_once($CFG->dirroot . '/mod/quiz/renderer.php');
 /**
  * mod_assign
@@ -34,14 +34,14 @@
  * @copyright  2018 Enovation Solutions
  * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
  */
-class theme_boost_o365teams_mod_assign_renderer extends mod_assign_renderer {
+class theme_boost_o365teams_mod_assign_renderer extends \mod_assign\output\renderer {
     /**
      * Render the header.
      *
      * @param assign_header $header
      * @return string
      */
-    public function render_assign_header(assign_header $header) {
+    public function render_assign_header(mod_assign\output\assign_header $header) {
         $o = '';

         if ($header->subpage) {

Regards,
Daniel

**Comment by michaelsmith1234** [comment]
> Hi, they have moved the classes in mod_assign. As workaround I had to fix theme/boost_o365teams/renderers.php like this:
> 
> --- renderers.dist 2022-04-26 14:59:20.537927512 +0200 +++ renderers.php 2022-04-26 14:57:41.077032739 +0200 @@ -25,7 +25,7 @@ defined('MOODLE_INTERNAL') || die();
> 
> require_once($CFG->dirroot . '/course/renderer.php'); -require_once($CFG->dirroot . '/mod/assign/renderer.php'); +require_once($CFG->dirroot . '/mod/assign/classes/output/renderer.php'); require_once($CFG->dirroot . '/mod/quiz/renderer.php'); /**
> 
> * mod_assign
>   @@ -34,14 +34,14 @@
> * @copyright  2018 Enovation Solutions
> * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
>   _/
>   -class theme_boost_o365teams_mod_assign_renderer extends mod_assign_renderer {
>   +class theme_boost_o365teams_mod_assign_renderer extends \mod_assign\output\renderer {
>   /_*
>   
>   * Render the header.
>   
>   * @param assign_header $header
>   * @return string
>     */
>     -public function render_assign_header(assign_header $header) {
>     +public function render_assign_header(mod_assign\output\assign_header $header) {
>     $o = '';
>     if ($header->subpage) {
> 
> Regards, Daniel

Would it be possible to share the full overriding code and it path

**Comment by dmid20** [comment]
Hi @michaelsmith1234 ,
Sorry - my code was reformatted when I posted it. The changes (three lines) are in the file
moodle/theme/boost_o365teams/renderers.php

In line 28
change 
require_once($CFG->dirroot . '/mod/assign/renderer.php'); 
to
require_once($CFG->dirroot . '/mod/assign/classes/output/renderer.php');
as the renderer.php was moved to another location.

In line 37 change
class theme_boost_o365teams_mod_assign_renderer extends mod_assign_renderer {
to
class theme_boost_o365teams_mod_assign_renderer extends \mod_assign\output\renderer {

And in line 44 change 
public function render_assign_header(assign_header $header) {
to
public function render_assign_header(mod_assign\output\assign_header $header) {

That's all I had to make it work again.

**Comment by weilai-irl** [comment]
Hi all,

Official Moodle 4.0 support of the plugins has been release with a permanent fix to the issue. Please check out at https://moodle.org/plugins/browse.php?list=set&id=72.

Regards,
Lai
