### ISSUE TITLE
The plugins 'assignsubmission_onenote' and 'assignfeedback_onenote' have a PHPUnit test with a non-existent required file

### ISSUE THREAD

**Issue by Julian-Tovar** [microsoft/o365-moodle#2033]
Good day team.

These two plugins: 'assignsubmission_onenote' and 'assignfeedback_onenote' have a PHPUnit test in which a `require_once` call requires a non-existent file. This file is '/mod/assign/tests/privacy_test.php', which does not exist in Moodle Core, as can be seen here: https://github.com/moodle/moodle/tree/master/mod/assign/tests.

I wonder, how do you guys run these tests? Under which environment do they pass? Do you have a public CI/CD platform where the results of these tests can be seen?

# assignsubmission_onenote

This line shows the issue: https://github.com/microsoft/o365-moodle/blob/master/mod/assign/submission/onenote/tests/privacy_test.php#L28

Perhaps the intention was to write (this is a possible fix):

Line 28: `require_once($CFG->dirroot.'/mod/assign/tests/privacy/provider_test.php');`
Line 38: `class assignsubmission_onenote_privacy_testcase extends \mod_assign\privacy\provider_test {`

# assignfeedback_onenote

This line shows the issue: https://github.com/microsoft/o365-moodle/blob/master/mod/assign/feedback/onenote/tests/privacy_test.php#L29

Perhaps the intention was to write (this is a possible fix):

Line 29: `require_once($CFG->dirroot.'/mod/assign/tests/privacy/provider_test.php');`
Line 39: `class assignfeedback_onenote_privacy_testcase extends \mod_assign\privacy\provider_test {`

Please let me know if there is a way to execute and make pass these tests using a vanilla Moodle system as is. If that's the case, then the issue would be that you should document that way to execute these couple of tests.

**Comment by Julian-Tovar** [comment]
Ahhh thank you very much @weilai-irl  .. yeah, I was referring to the master branch from Moodle (so the nearest version would be Moodle 4.0). .... I will edit this comment later though, after I confirm your findings (because I got the failing test in a branch that stems from 3.11, so just to be sure... but I think you are right).

**Comment by weilai-irl** [comment]
Hi @Julian-Tovar,

I confirm privacy.php was moved to privacy/provider_test.php in 3.11.5 release of Moodle core. I'll update the unit tests in the plugin to reflect it.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @Julian-Tovar,

The latest release of the plugins from today contain the fix to the reported issue. Unit tests for the two plugins are now passed. I'll close the issue now.

Thank you again for reporting the issue.

Regards,
Lai
