### ISSUE TITLE
A few 'local_o365' testscases fail

### ISSUE THREAD

**Issue by Julian-Tovar** [microsoft/o365-moodle#2039]
Good day. As stated in the name of this issue, there are a few testcases, from the 'local_o365' plugin, that fail when executed.

# The `local_o365_coursesyncutils_testcase` testcase

This testcase, in 'local/o365/tests/coursesyncutils_test.php' is failing with this error: `Fatal error: require_once(): Failed opening required '/webservice/tests/helpers.php`.

This is because the global variable $CFG is not available within the scope of the testcase. A very simple fix would be to add the line `global $CFG;` right before the line `require_once($CFG->dirroot.'/webservice/tests/helpers.php');` in the file 'local/o365/tests/coursesyncutils_test.php'.

Here is a screenshot of the failure:
<img width="1397" alt="Screen Shot 2022-05-02 at 2 21 07 PM" src="https://user-images.githubusercontent.com/89230550/166312663-9e220acb-8eed-4c4b-99f8-b07117a5a2cf.png">

And here is a screenshot of the fix:
<img width="1396" alt="Screen Shot 2022-05-02 at 2 30 26 PM" src="https://user-images.githubusercontent.com/89230550/166312821-6d909b26-84d7-499d-9ff1-5d92ce04c718.png">

I would send a PR, but I think that way would be slower (still, I can send the PR if requested).

# The `local_o365_webservices_onenoteassignment_testcase` testcase

Same as before, this testcase also fails due to a lack of `global $CFG;` before this require `require_once($CFG->dirroot.'/lib/externallib.php');`. This testcase is located in the file 'local/o365/tests/webservices_onenoteassignment_test.php'

Thank you.

**Comment by weilai-irl** [comment]
Hi @Julian-Tovar,

The issues reported have been fixed in the latest release of the plugins from today. I'll close the issue now.

Thank you again for reporting the issue.

Regards,
Lai
