### ISSUE TITLE
Office Video not showing in repository

### ISSUE THREAD

**Issue by ajo-sc** [Microsoft/o365-moodle#204]
Hi, we're using Moodle 3.1 and the Office 365 repository plugin 3.1.0.5 but we're having trouble getting Office Video to show up in the repository list. OneDrive appears and is working fine, but no sign of Video even though it's definitely part of our subscription. 

Is there something in the settings either in Moodle or Office that I need to do to activate it? 

Thank you very much,

Amanda

**Comment by jamesmcq** [comment]
Hi @ajo-sc - Have you set up the SharePoint link in your plugins? SharePoint is required for Office Video in the repository.

**Comment by ajo-sc** [comment]
Hi, no, I didn't realise that the Sharepoint link needed to be set for Office Video to work. The only thing now is that when I put in the link to our main Sharepoint site it says it already exists and that Moodle may conflict with existing content. 

I have Sharepoint Site Creation set to No - will Moodle still be creating content on there that could cause problems with our current content? 

Thank you very much for your help,

Amanda
