### ISSUE TITLE
The Moodle Core test '\enrol_self_testcase::test_can_self_enrol' fails on 3.11

### ISSUE THREAD

**Issue by Julian-Tovar** [microsoft/o365-moodle#2040]
Good day team, the PHPUnit test '\enrol_self_testcase::test_can_self_enrol' from Moodle Core is failing on 3.11. It fails with this error: `Debugging: Can not execute event observer '\local_o365\observers:handle_enrol_instance_updated' * line 164 of /lib/classes/event/manager.php: call to debugging()`. (the test can be seen here https://github.com/moodle/moodle/blob/MOODLE_311_STABLE/enrol/self/tests/self_test.php)

As can be seen from the error, the problem is that the event observer is misnamed, it should be written as '\local_o365\observers::handle_enrol_instance_updated' with double colon between class and method as per PHP syntax.

This can be fixed with just one change to the file 'local/o365/db/events.php:115', because there the event observer is registered with a single colon. Adding the other colon makes the test pass.

Note: this also fixes another Core test in `enrol_self_testcase::test_show_enrolme_link`

**Comment by weilai-irl** [comment]
Hi @Julian-Tovar ,

The issues reported have been fixed in the latest release of the plugins from today. I'll close the issue now.

Thank you again for reporting the issue.

Regards,
Lai
