### ISSUE TITLE
Moodle 4 support for auth_oidc + local_o365

### ISSUE THREAD

**Issue by matthewblabey** [microsoft/o365-moodle#2047]
We are running a Moodle 4 instance for testing and we are wanting to set up our single sign-on as we do in our production environment using the auth_oidc and local_o365 plugins. The latest release is for 3.11 but is there scope for support for Moodle 4 in the pipeline or if the latest release will just work on Moodle 4 if you know at all. We have tried installing it but we are not getting the expected notifications in _Site administration > General > Notifcations_ which makes us think it will not work on Moodle 4.

**Comment by weilai-irl** [comment]
Hi @matthewblabey,

We are working on upgrading the plugins to officially support Moodle 4.0. ETA is next 2-3 weeks.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @matthewblabey,

The new version of the plugins for Moodle 4.0 has been released. Please download from [Moodle plugins directory](https://moodle.org/plugins/).

Regards,
Lai
