### ISSUE TITLE
SDS moodle integration 

### ISSUE THREAD

**Issue by mmk-79** [Microsoft/o365-moodle#205]
Hello all. Is there an integration already done where the roster data synced from ant SIS into office 365  by SDS can be automatically created in Moodle? I am searching for a way to directly map roster data from my SIS into Moodle without doing a lot of development. 
Thanks

**Comment by jamesmcq** [comment]
Hi @mmk-79 - Yes SDS is supported as a preview feature by the plugins. From the local plugin settings page (Site Administration > Plugins > Local Plugins > Microsoft Office 365 Integration), you will see a tab that says "School Data Sync". You can configure the integration from there. This is a preview feature so do some testing before going live with it - and I'd love some feedback on it if you have any!

**Comment by mmk-79** [comment]
Thank you jamesmcq. I will try it and get back to you
