### ISSUE TITLE
What's happening with regards to moodle 3.3

### ISSUE THREAD

**Issue by michaelvperry** [Microsoft/o365-moodle#206]
Apologies if this is the wrong place to ask but from what I can see they are pulling at least some of this functionality into the core product. Will this remain a separate option or be part of that?

I know it's early days yet but potentially I'll be building a production server before September, and O365 integration of some type will be part of it.

**Comment by jamesmcq** [comment]
Hi @michaelvperry - I'm aware of some of the work around this, but haven't got a chance to dive too deeply. Once I'm able to get a full picture of what was done for 3.3 we'll see how that affects the plugins. As of right now there are no plans against releasing a 3.3 version of the plugin set, we'll just have to see what kind of modifications make sense.

**Comment by petersercombe** [comment]
So - Moodle 3.3 has landed now, and it appears, from what I can gather, that the Microsoft/OneDrive integration is for personal Microsoft accounts, not Office 365.

**Comment by michaelvperry** [comment]
It seemed to work for work accounts but is very barebones. We'll be using this one on 3.2 for now and then move to 3.3 when it is either established that the current versions work on it or 3.3 specific versions are available.
