### ISSUE TITLE
Office 365 session dont close

### ISSUE THREAD

**Issue by Viccent** [Microsoft/o365-moodle#207]
When the moodle session expired, dont close the session of Office 365. If you press f5 can connect again without login.

Information:

Moodle 3.1.4.+ / auth_oidc 3.1.0.4.
Login flow: Username/Password Authentication

**Comment by jamesmcq** [comment]
Hi @Viccent - this is expected operation. Unfortunately there is no way for use to close the Office 365 session from Moodle. If your users are on a shared computer, we recommend logging out of both Moodle and Office 365.
