### ISSUE TITLE
Teams theme - custom view does not work on the android mobile app

### ISSUE THREAD

**Issue by malaka13** [microsoft/o365-moodle#2078]
Hello!

Teams theme custom view does not work on the android mobile app but works perfectly on Windows and Mac versions of MS Teams App.  We are using moodle 3.11.6.

Android App View

![WhatsApp Image 2022-06-14 at 8 13 28 AM](https://user-images.githubusercontent.com/10679389/173483070-ccb23037-f41e-48aa-b863-ae5b9e3ab5d4.jpeg)

Desktop App View

![image](https://user-images.githubusercontent.com/10679389/173483279-9a096a51-f46c-478e-9e71-0109c60e7604.png)

**Comment by arborrow** [comment]
So I believe that I am experiencing the same issue although mine seems to be related to version 1416/10.0.2022395202. I am using the latest version of Moodle 4.0 with up to date Microsoft plugins installed. I run Linux and the Teams app in Linux seems to display correctly as well as going through the webbrowser via teams.microsoft.com. But when viewing through the Teams app in Android it does not work. I will go ahead and send an email to the Android app team and see if they have any ideas. Peace - Anthony

-- Moodle 4.0 + Teams Integration is working 
[
![Screenshot from Linux Teams app](https://user-images.githubusercontent.com/532371/198843500-8a16bec0-d3b9-46ec-9c2b-962e25265460.png)
![Screenshot from Web teams.microsoft.com](https://user-images.githubusercontent.com/532371/198843502-a3318734-ed85-4f5f-b928-e4d72b9f5966.png)
](url)

But unfortunately the teams theme is not used when using the Android Teams app
![Screenshot from Android App1](https://user-images.githubusercontent.com/532371/198843646-8b6de97f-c6e6-410d-af34-ae662f2a42cf.jpg)

**Comment by arborrow** [comment]
Just a word about testing, in Moodle I changed the theme to the Microsoft 365 Teams theme for mobile. When viewing on Firefox via my phone (Android) it looked much the same as within the Teams app in Android. So it is using the correct theme but the theme itself is not displaying nicely. When I switched Mobile back to Boost Union it displays nicely in Firefox but via the Android Teams app it is still not displaying nicely.

**Comment by arborrow** [comment]
Lai - Many thanks for your work on identifying the issue and working on a fix. Much appreciated! I will actually fly to Dublin on Friday and be at Microsoft on Monday afternoon and then attending the Power Conference the rest of the week. Let me know if you will be around for me to treat you to a beer.

**Comment by weilai-irl** [comment]
Hi all,

The solution to this issue has been included in the latest release of the plugins from today. I'm going to close this issue.

@arborrow Thank you for your offer. You are so kind. I'm afraid it's a bit too late now I suppose, so maybe next time.

Regards,
Lai

**Comment by arborrow** [comment]
@weilai-irl - Thank you for your work to resolve the issue and update the plugin. Yes, we missed each other in Dublin but I certainly hope to get back at some point. If you ever find yourself in Rome just let me know and I will take you out for gelato or coffee.
