### ISSUE TITLE
Idnumber mapping hardcoded in usersync

### ISSUE THREAD

**Issue by kkiiskin** [Microsoft/o365-moodle#208]
When usersync creates a new user to Moodle from Azure AD data, the new user for some reason gets username as it's idnumber

in local_o365/classes/feature/usersync/main.php, around line 382:
$newuser->idnumber = $newuser->username;

This sould be configurable option, maybe in User field mappings.?
Or is there some specific reason for this?

**Comment by kkiiskin** [comment]
Is there a reason for this?

I'd like to remove that line, because it's a bit confusing.

**Comment by gunnar-restorff** [comment]
I like this feature, but it would be nice if it were configurable. There is one problem with this, though: the ID number gets overwritten with emptystring when a user logs in: see https://github.com/Microsoft/o365-moodle/issues/218

**Comment by jamesmcq** [comment]
Hi All, this will be resolved along with #218 in the next release. Thanks!

**Comment by jamesmcq** [comment]
The latest release should resolve this. If you have any more issues on this, feel free to open a new issue. Thanks for the report!
