### ISSUE TITLE
Azure Active Directory Moodle Apps

### ISSUE THREAD

**Issue by ross-lovell** [microsoft/o365-moodle#2081]
On our Moodle site we setup the Microsoft 365 integration following the instructions in the [Microsoft 365 Moodle Docs page](https://docs.moodle.org/400/en/Microsoft_365) and as per the instructions we created Azure apps ([Azure app creation](https://docs.moodle.org/400/en/Microsoft_365#Azure_App_Creation_and_Configuration)) for our Moodle site and Teams integrations.

Recently I came across the below message stating that we have to upgrade our applications to _Microsoft Authentication Library (MSAL) and Microsoft Graph_ before the end of 2022.

> Starting June 30th, 2020 we will no longer add any new features to Azure Active Directory Authentication Library (ADAL) and Azure AD Graph. We will continue to provide technical support and security updates but we will no longer provide feature updates. Applications will need to be upgraded to Microsoft Authentication Library (MSAL) and Microsoft Graph.

Digging further I found these links 

* [Migrate Azure AD Graph apps to Microsoft Graph]([https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview])
* [Azure AD: Change Management](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-change-management-simplified/ba-p/2967456)

After reading through everything I’m still unsure what I need to do and how to upgrade my Moodle Azure apps to _Microsoft Authentication Library (MSAL) and Microsoft Graph_. Does anyone have any advise on how best to go about this?

**Comment by weilai-irl** [comment]
Hi @ross-lovell,

I confirm that there's absolutely nothing you need to do about it.

The initial version of the Microsoft Moodle plugins were developed before the Microsoft Graph API even existed, so the early versions were using separate APIs provided by individual subsystems, e.g. Azure AD Graph API, Calendar API, and OneNote API. These APIs are now referred to as legacy APIs. The vast majority of the API calls made by the integration have been migrated to the unified Microsoft Graph APIs long time ago (at least 3 years), and all new development are only using the new unified Microsoft Graph APIs. Some of the codes using the legacy APIs are still hanging around the in the plugins, but they are actually not used at all. A plan is in place to remove them in the near future.

I hope this clarifies the situation.

Regards,
Lai
