### ISSUE TITLE
Error in API Call - Outlook Calendar Sync Settings

### ISSUE THREAD

**Issue by aboarken** [microsoft/o365-moodle#2082]
I am getting the following error below when I try to access the Outlook Calendar Sync Settings menu. How can I resolve it. I am using Moodle Moodle 3.9.14 (Build: 20220509)

![Error](https://user-images.githubusercontent.com/18500882/177153634-73a8cf16-1b4b-42b4-8bcb-0cd65f80d58e.png)

**Comment by aboarken** [comment]
Thank you @weilai-irl and sorry for my late reply. I will check it and get back to you as soon as possible. I have another question: Can I enable or force the "Outlook Sync Setting" for all users?

**Comment by aboarken** [comment]
Soft Reminder Please @weilai-irl

**Comment by weilai-irl** [comment]
Hi @aboarken,

Regarding your question "Can I enable or force the "Outlook Sync Setting" for all users?", the answer is no.

A Moodle user can have write access to many calendars in Moodle (user, group, course, or site), and likewise, a Microsoft user may have access to many calendars in Outlook too (user default, user created calendars, and subscribed calendars). There is no safe "default" setting when setting up the sync between calendars in this case. This needs to be set up on a case by case basis.

Regards,
Lai

**Comment by aboarken** [comment]
Hello @weilai-irl, really thank you for your great cooperation and support. The issue has been resolved. It was fixed with a certain number of users who their accounts were deleted in the past and recreated with the same username and email. God Bless you. Please feel free to close this issue.

**Comment by weilai-irl** [comment]
Hi @aboarken 

Thank you for your confirmation. I'll close the issue now.

Regards,
Lai
