### ISSUE TITLE
Error when resetting a course

### ISSUE THREAD

**Issue by synergylearning-github** [microsoft/o365-moodle#2092]
1. As a manual user (eg admin) add some activities to a course. 
2. Set completion expected dates for the activities. 
3. Reset the course.

Result:

Exception - Argument 8 passed to local_o365\rest\unified::create_event() must be of the type string, null given, called in [dirroot]/local/o365/classes/feature/calsync/main.php on line 348

[More information about this error](http://docs.moodle.org/311/en/error/moodle/generalexceptionmessage)

×Debug info:
Error code: generalexceptionmessage
×Stack trace:
line 1221 of /local/o365/classes/rest/unified.php: TypeError thrown
line 348 of /local/o365/classes/feature/calsync/main.php: call to local_o365\rest\unified->create_event()
line 120 of /local/o365/classes/feature/calsync/observers.php: call to local_o365\feature\calsync\main->create_outlook_event_from_moodle_event()
line ? of unknownfile: call to local_o365\feature\calsync\observers::handle_calendar_event_created()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 556 of /calendar/lib.php: call to core\event\base->trigger()
line 964 of /calendar/lib.php: call to calendar_event->update()
line 120 of /completion/classes/api.php: call to calendar_event::create()
line 1176 of /course/lib.php: call to core_completion\api::update_completion_date_event()
line 1155 of /course/lib.php: call to course_module_calendar_event_update_process()
line 5611 of /lib/moodlelib.php: call to course_module_bulk_update_calendar_events()
line 75 of /course/reset.php: call to reset_course_userdata()

**Comment by weilai-irl** [comment]
Hi @synergylearning-github,

Please specify Moodle version and local_o365 plugin version in your environment.

Regards,
Lai

**Comment by synergylearning-github** [comment]
Manual users and deleted auth_oidc users have no record in auth_oidc_token

**Comment by weilai-irl** [comment]
@synergylearning-github ,

I acknowledge the issue.
A fix is on the way in the next release.

Regards,
Lai

**Comment by synergylearning-github** [comment]
Thank you,, that's great. And very quick!

Amanda

**Comment by mccork91** [comment]
@weilai-irl - would you be able to indicate when the next release of the plugin will be available with this fix in it - thanks

**Comment by weilai-irl** [comment]
Hi @mccork91,

The next release is expected to be before end of September. The pull request will be made available before that and linked to this issue. I'm hoping to have this ready in the next week or so. When it's available, you can manually apply it to you environment. 

Regards,
Lai

**Comment by synergylearning-github** [comment]
Hi @weilai-irl, 

This issue is currently affecting one of our customer's production applications, please can you advise when the next release will be that contains the fix? 

We are unable to apply the pull request that is available so are awaiting release. 

Many thanks,

Patrice

**Comment by weilai-irl** [comment]
Hi @synergylearning-github 

The ETA for the release is by the end of the month. This cannot be changed due to the amount of testing required before the release.

The only way to get around the issue before the release would be to apply the PR.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

The fix to the issue has been included the release from today. Please upgrade your plugins to the latest version to see the fix.

I'm going to close the issue.

Regards,
Lai
