### ISSUE TITLE
Error when sync "roles" field

### ISSUE THREAD

**Issue by glennarcher-nz** [microsoft/o365-moodle#2099]
Exception - Argument 1 passed to local_o365\rest\unified::get_directory_objects() must be of type string, array given, called in {dirroot]/local/o365/classes/feature/usersync/main.php on line 463

This does not allow any one to login via Azure.

Reverting the plugin from 4.0.1 to 3.11 fixes this problem

Can someone provide a clue on how to update the plugin to the latest version without getting this error

**Comment by weilai-irl** [comment]
Hi @glennarcher-nz,

Thank you for reporting this.
I confirm this is a bug when processing the sync of "roles" remote field in user field matching. It can happen in either user login or user sync scheduled task run. Temporarily remove mapping to the "roles" remote field will ensure the error is not triggered. I'll work on a solution and include it in the next release.

Regards,
Lai

**Comment by glennarcher-nz** [comment]
Thanks for the information Lai

**Comment by weilai-irl** [comment]
Hi all,

The fix to this issue has been included in the release from today. Please upgrade your plugins to the fix.

I'm going to close the issue now.

Regards,
Lai
