### ISSUE TITLE
User Roles or Group claims sent from AAD; persist in moodle?

### ISSUE THREAD

**Issue by chadcarlton** [microsoft/o365-moodle#210]
Azure Active Directory can be configured to send additional attributes, "roles" and "groups".

Can these be put into moodle somehow, and then used for enrollment purposes?

**Comment by chadcarlton** [comment]
I also have some other attributes (~5) our AAD system is sending. Can these be mapped into Moodle?

is "local_o365 | fieldmap" a hardcoded/fixed list?

**Comment by jamesmcq** [comment]
@chadcarlton The custom Azure AD fields is definitely something on our list for the future. I don't have a timeline unfortunately. I think the other items you mentioned - roles and groups, could work alongside the custom Azure AD fields as well - put into Moodle custom user fields then used for enrolment via a different plugin.

**Comment by avegys** [comment]
Hi @chadcarlton,

The latest plugin version for Moodle 3.9 and 3.10 allows you to sync roles and groups. You have to set these fields mapping in local_o365 plugin settings. Unfortunately, each additional field has to be added separately to "local_o365 | fieldmap" list as it is not so straight forward to get additional data with Microsoft API. Please check latest fieldmap list and let us know if you are still missing anything. In near future we are planning to add ability to sync extension fields (please track issue https://github.com/microsoft/o365-moodle/issues/237 where we will inform when extensions fields are available for mapping).

Best regards,
Andrius
