### ISSUE TITLE
Graph API was not found - Invalid error or incomplete info

### ISSUE THREAD

**Issue by mhaney-yec** [Microsoft/o365-moodle#211]
When enabling Graph API support in Moodle (local_o365 | enableunifiedapi) and confirming Azure AD has the correct permissions we are receiving the error below. (section 5.4.4, https://docs.moodle.org/30/en/Office365#Configure_your_Azure_Active_Directory_Application).

local_o365 | azureadsetup
The Microsoft Graph API was not found in this application.

There are no further messages or documentation presented with the error, and I have tried walking through the code (with limited understanding) but cannot determine what could be causing the issue.  Ideally the "Update" button functionality should produce further details on what the error is, or perhaps there is a bug in this version which does not properly detect if Graph is associated to our Azure AD application for this site?

Using Moodle v2.7.15 (Build 20160711) with O365 plugins
assignsubmission_onenote: 27.0.0.10
assignfeedback_onenote: 27.0.0.10
block_microsoft: 27.0.0.18
repository_office365: 27.0.0.22
local_office365: 27.0.0.32
local_onenote: 27.0.0.13

**Comment by nimojg-microsoft** [comment]
Have you tested using the latest release? Are you still seeing the same issue?

**Comment by mhaney-yec** [comment]
It seems to have been corrected since this post was put up almost a year ago, we are on a much more recent version (2017051500 | 3.3.0.0) and are not experiencing this error now.
