### ISSUE TITLE
How to uninstall OpenID Connect

### ISSUE THREAD

**Issue by skappes** [Microsoft/o365-moodle#213]
There is no uninstall option for this plugin. How can I remove it completely?

**Comment by nimojg-microsoft** [comment]
Moodle will not let you uninstall plugins if another plugin depends on it, so you have to uninstall plugins like the Office 365 repository (which nothing else depends on) first. In the plugins overview page, the "Notes" column lists plugins that depend on a given plugin, so those must be removed before you'll be able to uninstall a plugin.
