### ISSUE TITLE
Usersync Error in API Call

### ISSUE THREAD

**Issue by nbozhkov-ucl** [microsoft/o365-moodle#2140]
Hi all,

Moodle 3.11.8+ (20220812)
auth_oidc 3.11.4 (2021051725)
local_o365 3.11.4 (2021051725)
mysql 5.7.26
php 7.3.29

OpenIDConnect works fine with authentication. However when we try to sync users with AAD we get the following errors in local_o365\task\usersync.

AAD admin has granted admin consent by clicking the button within Moodle. However the only api permission that have been added is User.Read.
<img width="939" alt="image" src="https://user-images.githubusercontent.com/107557440/185375150-c1c7e22f-ae6e-423f-95bf-c9141f89febc.png">

Initially it was showing 0 reads & writes and we were getting:

"Microsoft 365 not configured" with debug message:

"local_o365\oauth2\token::instance:111: Cannot retrieve a token for the base resource. Data: (null)"

The above was running as on schedule. After trying to run it manually using "Run now" button the read& writes changed to single digits e.g. 5 and 3 and the error changed to:

"Error in delta usersync: Error in API call: Insufficient privileges to complete the operation." with debug message:

"local_o365\task\usersync::execute: Error in API call: Insufficient privileges to complete the operation. Data: Array ( [file] => /data/apache/htdocs/PREVIEW_311_AAD-1/local/o365/classes/rest/o365api.php [line] => 293 [message] => Error in API call: Insufficient privileges to complete the operation. [debuginfo] => [errorcode] => erroro365apibadcall_message [module] => local_o365 )"

When we tested the plugins a couple of months ago granting admin consent by AAD admin was creating a lot more permissions in AAD. Also the admin consent button in Moodle had green tick if I remember correctly or something to mark it was done - this is no longer the case.

Based on the above and the testing done the following questions are coming to mind:
- Is pressing the admin consent button triggering other actions in the backend of Moodle to enable to integration to talk to AAD e.g. storing the required credentials in the right moodle db tables, etc.?   
- Or adding the required permissions in AAD manually and getting AAD admin to grant within AAD is simply enough?
- Or in other words if you have a configured & working app registration in AAD can you just point your Moodle instance to it? 

Any advise on how to overcome the above issue is welcomed. Thanks.

**Comment by weilai-irl** [comment]
Hi @nbozhkov-ucl,

It looks like the Azure app you use for the integration doesn't have any permissions added. Please follow the configuration instructions again at https://docs.moodle.org/310/en/Microsoft_365#Azure_App_Creation_and_Configuration, or recreate the Azure app using the PowerShell script.

Regards,
Lai

**Comment by nbozhkov-ucl** [comment]
I linked it to another app registration (previously used for testing)  and it worked. Had to run "Refresh system API user refresh token" cron job to get the right credentials.  Thanks @weilai-irl .
