### ISSUE TITLE
Moodle 4.0 scheduled tasks: option "Run now" not available?

### ISSUE THREAD

**Issue by AntonT76** [microsoft/o365-moodle#2149]
Hello,

I'm testing Moodle 4.0 together with the newest o365 plugin set. In older Moodle versions (eg 3.9) there was the possibility to run several o365-tasks manually by using "Run now" option in "Site Administration - Server - Scheduled tasks". In Moodle 4.0 this option isn't available any more.

Is there any possibility to activate this option? If not, then it would be fine if this function were available again in the next plugin versions.

thanks, br Anton

**Comment by thebenkahn** [comment]
Hi Anton, this is not specific too the MS plugins, you need to configure your 4.0 site.

To be able to run individual scheduled tasks via 'Run now' links on the scheduled tasks page, 'Allow 'Run now' for scheduled tasks' (tool_task | enablerunnow) in Site administration / Security / Site security settings should be enabled AND 'Path to PHP CLI' (pathtophp) in Site administration / Server / System paths should be set.

https://docs.moodle.org/400/en/Scheduled_tasks#Running_individual_tasks

**Comment by weilai-irl** [comment]
Hi @AntonT76 and @thebenkahn,

There is actually a bit extra steps to @thebenkahn 's response on how to use "Run now" feature on scheduled tasks in the plugins. The root reason is Moodle 4.0 introduces a new level of control over which scheduled tasks can "Run now", and by default, tasks from local plugins cannot use the "Run now" feature, and from what I can see, this cannot be overridden from individual plugins of the type.

In my local environment, I applied a core patch to enable the feature for all local plugins. Add the following lines after https://github.com/moodle/moodle/blob/78f0557607ddb8900386eb68315524cf3a9c5bf2/lib/classes/plugininfo/local.php#L69 makes the option appear.
```
    public function is_enabled() {
        return true;
    }
```

Regards,
Lai

**Comment by AntonT76** [comment]
Dear @thebenkahn, @weilai-irl 

thank you for your answer. At the beginning I also thought that these settings were not set. But the settings are correct.

@weilai-irl:  thank you for this patch. As far as I understand, it is a problem in the 4.0 Moodle Core? So it would be better to create an issue in Moodle Tracker?

br Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

That is my understanding. I'm not sure Moodle core would treat this as an "issue", but yes, it does affect the operation in the local_o365 plugin.

Regards,
Lai

**Comment by AntonT76** [comment]
Dear @weilai-irl:
I have already found an entry in Moodle Tracker. It looks like a solution is being worked on: Scheduled Task: Run now is not appearing for Local Plugins (https://tracker.moodle.org/browse/MDL-75308)

br, Anton

**Comment by weilai-irl** [comment]
Hi @AntonT76,

Thank you for the update. Good to know Moodle HQ is working on it :)

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @AntonT76,

Since this is handled by Moodle HQ now, I'll close this issue.

Regards,
Lai
