### ISSUE TITLE
Site Administration not working. Displays error message:  Exception - Class 'local_o365\feature\sds\utils' not found

### ISSUE THREAD

**Issue by kuriansinu** [microsoft/o365-moodle#2152]
The Moodle Site Administration tab does not respond. It throws an error : "Exception - Class 'local_o365\feature\sds\utils' not found" while searching anything  in Site Administration search bar.
Recently I have updated the plugins of O365 and it failed and then cancelled.
Moodle Version : Moodle 3.11.6
O365 plugin :2021051700.zip

How to rectify this issue?

![Uploading site.JPG…]()

**Comment by weilai-irl** [comment]
Hi @kuriansinu,

This is an issue fixed in later versions of the plugin. Please download the latest version for Moodle 3.11 and try again. The version number at the time of writing should be 2021051725.

Regards,
Lai

**Comment by kuriansinu** [comment]
Thank you Lai for your quick response.

Could you please guide me to install the new version as the Plugin install
page in Moodle is not accessible.

I cannot access any site administration pages.

Regards

Kurian

**Comment by kuriansinu** [comment]
Can anyone help me on this?

**Comment by weilai-irl** [comment]
Hi @kuriansinu,

I don't quite understand why you can't access site admin pages. Can you not download the latest version of the plugin and upload to your server to the right path?

Regards,
Lai

**Comment by kuriansinu** [comment]
Greetings! Lai,

When I click on Site Administration, there is no response on the page. If I
type anything on the Search bar beneath it,  it throws the error message.

I have attached a screen video for your kind reference.


Regards

Kurian

**Comment by weilai-irl** [comment]
Hi @kuriansinu,

It looks like email replies to github can't handle video attachments.

Regardless, the error that you can't access Moodle site admin page sounds more like a general Moodle issue rather than something from the plugin. Could you remove local_o365 plugin from your code base (.i.e remove local/o365 folder) and try again? If that works, just redeploy code of the new version of local_o365 plugin to the same path.

Regards,
Lai

**Comment by kuriansinu** [comment]
Hi Lai,

It's working now. I removed the o365 folder and installed the updated
version of the plugin.

Thanks a lot for your support. Much appreciated.

Regards

Kurian
