### ISSUE TITLE
local_o365\task\groupcreate fails with "get_in_or_equal() does not accept empty arrays"

### ISSUE THREAD

**Issue by nairial** [Microsoft/o365-moodle#216]
I've been having issues with the 3.2.0.1 local plugin when I try to add groups.  The scheduled task fails with the error below.  Please let me know how I can help!

root@courses:~# php /var/www/wsts/admin/tool/task/cli/schedule_task.php --execute=\\local_o365\\task\\groupcreate
Execute scheduled task: Create user groups in Office 365 (local_o365\task\groupcreate)
... used 0 dbqueries
... used 0.040251970291138 seconds
Scheduled task failed: Create user groups in Office 365 (local_o365\task\groupcreate),Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays

**Comment by jamesmcq** [comment]
Thanks @nairial - this looks like a simple fix.

**Comment by jamesmcq** [comment]
The latest release should resolve this. If you have any more issues on this, feel free to open a new issue. Thanks for the report!
