### ISSUE TITLE
User's Language Preferences reverting to 'en' after sync

### ISSUE THREAD

**Issue by trevormccready** [microsoft/o365-moodle#2176]
User's preferred langauges were all set to 'en_us' or 'en_us_wp' (on workplace site) and after a subsequent sync, their preferred languages were changed to 'en'. This appears to be coded in https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/feature/usersync/main.php to strip languages with longer than 2 characters. Is there a reason why langauge preference won't allow sub-language packs like en_us to be used?

**Comment by weilai-irl** [comment]
Hi @trevormccready,

I confirm the purpose of the the strip is to remove invalid language settings, but I admin that this would affect preferred languages in your cases.

I can look at updating the implementation in the upcoming releases to support more language preferences.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @trevormccready,

I have made some initial changes to this by removing the strip function, but I have some questions. Could you explain me your situation please. I'd like to know the following:
 - The preferred language of the Microsoft account.
 - The original language of the Moodle account, before user sync task.
 - The language of the Moodle account after user sync task run.
 - This seems to be a no brainer, but could you confirm the field mapping setting applied to the language field please.

For a bit of background - Microsoft stores user preferred language in ISO 639-1 Code format, e.g. en-US. This doesn't alway match the language code in Moodle. This is why the strip function was introduced. Before I can safely remove the strip function, I need to ensure that removing it doesn't have any side effect.

Regards,
Lai

**Comment by trevormccready** [comment]
Thanks for working on this. Here are the answers to your questions:
The preferred language of the Microsoft account.
- English (United States)

The original language of the Moodle account, before user sync task.
- "en_us_wp" (which is the language subpack for Moodle Workplace English United States).

The language of the Moodle account after user sync task run.
- "en" (which is the standard Moodle language pack for international English)

This seems to be a no brainer, but could you confirm the field mapping setting applied to the language field please.

- Data mapping has field_map_lang = Language (and it's only set to update on Creation, NOT on every login and user sync task run, so the updates are happening even though it shouldn't be updating the language)
- 
![image](https://user-images.githubusercontent.com/19151717/198411983-d3144061-5912-4a16-93e9-6ff02ad6b783.png)

**Comment by weilai-irl** [comment]
Hi @trevormccready

The fix to the reported issue has been included in the release from today ([3.11.6](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m311), [4.0.3](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m400) and [4.1.1](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m410)). I'll mark this issue closed.

Feel free to reopen if the fix doesn't work for you.

Regards,
Lai
