### ISSUE TITLE
Problems synchro users on course

### ISSUE THREAD

**Issue by ETS-MB** [microsoft/o365-moodle#2178]
We get the following error message from the Microsoft API with certain users on the \local_o365\task\coursesync task :

ChangedProperties=[],NonDefaultProperties=[INTERNAL_ObjectReadCloned,INTERNAL_SingleResourceQuery]]' can only be present once as an add/remove change.

The task stops and the rest of the students are not synchronised to the team.

**Comment by weilai-irl** [comment]
@ETS-MB,

Please state your Moodle and plugins (auth_oidc and local_o365) version.

A quick Google search suggests this may be related to something like a user gets added to the same Team twice in one Graph API call, is this possible in your case?

Regards,
Lai

**Comment by ETS-MB** [comment]
Hello,

Thank you for your answer,  Moodle  3.11.9 (Build: 20220822) , local_o365 3.11.4 .

It is exactly the case, it tries to add the same personne twice . I think it happends when the user have two roles in the same course but I'm not sure, but instead of continuing with the rest, it tries 5 times and then stops and the other participants never join the team.

Regards,

Marcelo.

**Comment by weilai-irl** [comment]
Hi @ETS-MB,

Could you confirm if the user has more than one role in the course that has the "local/o365:teammember" or "local/o365:teamowner" capability please.

I'll try to reproduce it locally too.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @ETS-MB,

I managed to reproduce the issue locally. It happens when a user has multiple roles in a course, and some roles have the "local/o365:teamowner" cap and others have the "local/o365:teammember" cap.

I have provided a solution to fix the issue and link the pull requests here. They will be included in the next release after testing.

Regards,
Lai

**Comment by ETS-MB** [comment]
Thank you very much, we really appreciate your help.

**Comment by weilai-irl** [comment]
Hi @ETS-MB 

A fix to the reported issue has been included in the release from today ([3.11.6](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m311), [4.0.3](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m400) and [4.1.1](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m410)). I'll mark this issue closed.

Feel free to reopen if the fix doesn't work for you.

Regards,
Lai

**Comment by ETS-MB** [comment]
Hello,

Thank you very much, we will check it.

Regards,

***@***.***<http://etsmtl.ca/>
Marcelo Bellomo  |  Analyste de l'informatique
Services d'infrastructure
École de technologie supérieure  |  Université du Québec
1100, rue Notre-Dame Ouest, bureau E-5150.6
Montréal (Québec)  H3C 1K3
Tél. 514 396-8800, poste 7419 |  etsmtl.ca<http://etsmtl.ca/>
Retrouvez-nous sur Facebook<http://www.facebook.com/etsmtl> - Twitter<http://twitter.com/etsmtl> - YouTube<http://www.youtube.com/user/etsmtl> - LinkedIn<https://www.linkedin.com/school/etsmtl/>




De : Lai Wei ***@***.***>
Envoyé : 28 février 2023 07:14
À : microsoft/o365-moodle ***@***.***>
Cc : Bellomo, Marcelo ***@***.***>; Mention ***@***.***>
Objet : Re: [microsoft/o365-moodle] Problems synchro users on course (Issue #2178)


Hi @ETS-MB<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FETS-MB&data=05%7C01%7Cmarcelo.bellomo%40etsmtl.ca%7Cc277b73f6e244e78237208db1985440b%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C638131832393192562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y%2BWkWnhVIGre3jimtLsQEJiaLJpC%2FOvwiDPJOqloqk4%3D&reserved=0>

A fix to the reported issue has been included in the release from today (3.11.6<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fo365-moodle%2Freleases%2Ftag%2Fv20230228_m311&data=05%7C01%7Cmarcelo.bellomo%40etsmtl.ca%7Cc277b73f6e244e78237208db1985440b%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C638131832393192562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=odgzBafTNl4GtQfVO07xnjtvPWXIQh1TDGpKUhtCczQ%3D&reserved=0>, 4.0.3<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fo365-moodle%2Freleases%2Ftag%2Fv20230228_m400&data=05%7C01%7Cmarcelo.bellomo%40etsmtl.ca%7Cc277b73f6e244e78237208db1985440b%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C638131832393192562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cg0pP6K0QxJ6mtE29XIM5Ju5STNCwCNcXJFL6YfcP%2BQ%3D&reserved=0> and 4.1.1<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fo365-moodle%2Freleases%2Ftag%2Fv20230228_m410&data=05%7C01%7Cmarcelo.bellomo%40etsmtl.ca%7Cc277b73f6e244e78237208db1985440b%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C638131832393192562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Df7ok%2F6g2JKobsx0zspqsgUT%2BuP5D8%2BkJiGYp85H0NE%3D&reserved=0>). I'll mark this issue closed.

Feel free to reopen if the fix doesn't work for you.

Regards,
Lai

-
