### ISSUE TITLE
oidc based logins are overwriting idnumber

### ISSUE THREAD

**Issue by chriskincaid24** [Microsoft/o365-moodle#218]
when using oidc authentication, users idnumber fields are being overwritten on login.  Do not have idnumber filed set up to sync in the settings. Any thoughts? ALso, is there any database diagrams or workflow documentation for the plugin?

Plugin version 3.2 (latest build)
Moodle version: 3.2.1
MySQL 5.7.10
PHP 7.1

**Comment by chriskincaid24** [comment]
Plugin version 3.2 (latest build)
Moodle version: 3.2.1
MySQL 5.7.10
PHP 7.1

**Comment by chriskincaid24** [comment]
Found a work around.  in \local_o365\classes\observers, comment out line 272 ($updateduser->idnumber = '';)

**Comment by gunnar-restorff** [comment]
I have the same problem in Moodle 3.3 - I have to comment out that line (every time I update the system, before any user logs in!). Is there any reason for overwriting ID number with blanks?

**Comment by jamesmcq** [comment]
Thanks @gunnar-restorff @chriskincaid24 - yes I don't think this line needs to be there. I'll remove it in our next release.

**Comment by jamesmcq** [comment]
The latest release should resolve this. If you have any more issues on this, feel free to open a new issue. Thanks for the report!
