### ISSUE TITLE
matched users and linked to office 365 not switched to openid

### ISSUE THREAD

**Issue by ramzihosni** [microsoft/o365-moodle#2181]
Hi @weilai-irl,
Our users are matched to aad using their emails, the problem when they link their account to office 365 nothing happens and the account still manual instead of oicd. on the backend side of the plugin I can see that the status of users are connected, it's really confusing.
Could you please help fixing the issue?
Thank you

**Comment by nbozhkov-ucl** [comment]
hi @ramzihosni 

Try setting the authentication method for a user manually to OIDC and see if that works.

Also, in the yourmoodlesite/admin/settings.php?section=local_o365 plugin setting in Moodle see if you have the setting to switch users to OIDC enabled. 

![image](https://user-images.githubusercontent.com/107557440/190335797-8648e991-569e-4dcd-8377-d4018d703a05.png)

You can also look at the cron job azure user sync and see the log - that will tell you what it is doing for each user.

**Comment by ramzihosni** [comment]
Hi @nbozhkov-ucl,

I enabled the option to switch matched users to Microsoft 365 (OpenID Connect) authenticate.
The user status is connected under (Microsoft 365 Integration/Advanced/Manage User Connections), but his account still manual and can work if I change it to OpenID from the user profile.
The problem that most of the users use the manual method and I must force them to use OpenID Connect.
Thank you for your help.

**Comment by nbozhkov-ucl** [comment]
Check the cron job report. It might give you a clue of why it is not switching users to OIDC. Also, there is a setting on the minimum username length to switch. Check that as well. 
![image](https://user-images.githubusercontent.com/107557440/191201526-4b62ca44-5049-4674-a443-7c2930d455a6.png)

**Comment by ramzihosni** [comment]
Nothing found in the cron job report.

**Comment by ramzihosni** [comment]
The problem was related to OpenID Connect capabilities, I figure it out by allowing manage connection connect permission for authenticated users role.
Thank you
