### ISSUE TITLE
Syntax Error when running  local_o365\task\usersync

### ISSUE THREAD

**Issue by peta3000** [microsoft/o365-moodle#2184]
Hi @weilai-irl 
When running the usersync script a client receives the following syntax-error:
![usersync_syntax-error](https://user-images.githubusercontent.com/56640324/191227844-7f4a7361-3fcc-4ff6-a63d-3b12f611a07f.png)

Context:
database: postgres
moodle-version: 4.0.4
local_o365 version: 2022041905 (current master branch, 4.0.1 release)

According to the syntax of the "JOIN" clause the "ON" condition seems to be optional in MySQL but expected in other database-types: 
here a reference discussion on stackoverflow:
https://stackoverflow.com/questions/16470942/how-to-use-mysql-join-without-on-condition

the problematic sql-query seems to be at the end of this php-file:
https://github.com/microsoft/o365-moodle/blob/MOODLE_40_STABLE/local/o365/lib.php

Has there already been a patch in the meanwhile?

Thanks a lot!
With best regards!

peta3000

related issue(s):
#2173

**Comment by weilai-irl** [comment]
Hi @peta3000,

I have updated the code change fixing the linked issue #2173 to cater for this issue as well. You can try it out in your environment. The fix will be included in the next release.

Regards,
Lai

**Comment by peta3000** [comment]
Dear @weilai-irl 
Thanks a lot for your reply!
We are going to wait for the next release then :)

Many thanks and best regards

peta

**Comment by peta3000** [comment]
Thanks a lot for your efforts @weilai-irl !!!

Looking forward to giving it a try! :) 
Best regards
peta
