### ISSUE TITLE
moodle-block_skypeweb README documentation reflects old Azure portal

### ISSUE THREAD

**Issue by digitalsparky** [Microsoft/o365-moodle#219]
moodle-block_skypeweb's documentation for implementation reflects the steps needed to implement on the old Azure portal and needs to be updated to the latest portal for best usability

**Comment by jamesmcq** [comment]
Thanks @digitalsparky - I'll include an update in our next release.

**Comment by jamesmcq** [comment]
The latest release should resolve this. If you have any more issues on this, feel free to open a new issue. Thanks for the report!
