### ISSUE TITLE
How to install via Git - with solution

### ISSUE THREAD

**Issue by pcrispimMT** [microsoft/o365-moodle#2192]
I'm trying to install all plugins using sudo git clone git://github.com/Microsoft/o365-moodle/ . in the root folder of Moodle, but I get a Fatal error saying that the path already exists and that it is not an empty directory.
I suppose this is because I installed Moodle using Git, and that, in the root folder, there is already a .git directory for Moodle and thats why it won't let me install the Microsoft o365-moodle suite of plugins.

Is there a way to achieve this(to be able to install via Git)?

**Comment by pcrispimMT** [comment]
I made to install it.
I create to different .git directories (one for moodle and one for o365-moodle), and now I can call each separately using --git-dir=<name of dir>.

**Comment by weilai-irl** [comment]
Hi @pcrispimMT,

I'm glad to see you found the solution.
I'll close the issue now.

Regards,
Lai
