### ISSUE TITLE
Authentication Button

### ISSUE THREAD

**Issue by kueppersf** [microsoft/o365-moodle#2210]
Hi!

With the update from Moodle to 3.11.10 (20221018) and the oidc plugin version 3.11.5 from October 12, 2022, the login button for the authentication request disappeared. Our learners can no longer log in. The settings in Moodle have all remained the same.

Is this a problem in the plugin or can we install the plugin version for Moodle 4 for Moodle 3.11.10 and will that solve the problem?

Many greetings
Friedhelm

**Comment by weilai-irl** [comment]
Hi @kueppersf,

Thank you for reporting the issue.

I confirm this is not a known issue in the 3.11.5/4.0.2 release of the plugins. Effectively the two named releases contain pretty much the same code and exact same functionality, except for the Moodle version checks in version.php and upgrade script. You won't be able to install 4.0.2 release on a Moodle 3.11 site without modifying the version.php file.

Back to the issue itself, there was one change related to the display of auth_oidc login button in this release, and it was to support [multilang filter](https://docs.moodle.org/400/en/Multi-language_content_filter) in the "Provider Display Name" setting (auth_oidc | opname). But whether you use multilang content in the setting or not, it shouldn't "hide" the button.

I'd suggest you try these approaches and see if you can get more details:
 - Verify auth_oidc plugin settings and ensure all settings are correct and saved correctly.
 - Turn debugging options on in your Moodle site and see if you see any error on the page that the login button is supposed to display.
 - If you are using a custom theme, try loading the page using the default theme (boost) and see if the button appears.
 - Check if there are other customisations either in auth_oidc or in Moodle core that may affect the display of the login button.

Please perform the suggested steps and report back if you still see the issue.

Regards,
Lai

**Comment by kueppersf** [comment]
Hi Lai,

with us the field auth_oidc | tenantnameorguid to our problem. Because our authentication server Iserv does not provide any information for this. This field did not exist in the old oidc version or was not a mandatory field. Do you have a solution for this?

Trying to enter something there causes the button to appear again, but logging in leads to the following error message:

Regards,
Friedhelm
![oidc-Fehlermeldung](https://user-images.githubusercontent.com/59993876/198674975-3d4d399b-7034-4f3c-ac41-a25f4eab396d.PNG)

**Comment by weilai-irl** [comment]
Hi @kueppersf 

I confirm I'm aware of this issue and a fix is on the way.

Regards,
Lai

**Comment by kueppersf** [comment]
Hi Lai,

can we do something at short notice? The students and teachers of our two schools affected by the problem will return from vacation on November 1st, 2022 and will not be able to log into Moodle.

A hint would be nice!

Regards,
Friedhelm

**Comment by weilai-irl** [comment]
Hi @kueppersf,

I'd suggest you temporarily revert back to the previous version of the plugin.

The fix to the issue isn't that straightforward and the release process would take at least a week from when the code is ready to when the release is made.

Regards,
Lai

**Comment by kueppersf** [comment]
Hi Lai,
We update our plugins via Git. We have already tried to switch to the older version and that didn't work in Moodle with the message that a newer version was installed. If we delete the current plugin in Moodle to install the older one, we will lose the existing user accounts. If I only change the version number in version.php, Git only wants to update this file

Regards,
Friedhelm

**Comment by weilai-irl** [comment]
Hi @kueppersf,

Besides checking out the older version of the plugins from git, you will need to update your DB manually to "downgrade" your plugin, something like:
`UPDATE mdl_config_plugins SET value = '2021051725' WHERE plugin = 'auth_oidc' AND name = 'version'; // 2021051725 is the version for 3.11.4 release.`

Regards,
Lai

**Comment by kueppersf** [comment]
Hi Lai,

we have now copied the oidc version 3.11.4 into the two Moodle instances. It worked for one instance, the other now comes with the error "Error: Class 'auth_oidc\utils' not found"

Regards,
Friedhelm

**Comment by weilai-irl** [comment]
Hi @kueppersf,

Please make sure all files in the auth/oidc path are in your installation. The missing class is declared in /auth/oidc/classes/utils.php and the file is not a recent addition - it has been in the plugin for quite a few years.

Regards,
Lai

**Comment by kueppersf** [comment]
Hi Lai

The school administrator had entered the auth_oidc | tenantnameorguid simply entered "iserv". It may be that the change to the older oidc version caused this entry to cause the problem because it was not deleted. Now that we have gone back to the current version, I was able to log in again and the "iserv" entry was there again. It was therefore not previously deleted when switching to the older version. Where is the entry in the database? The folders and files were copied the same way in both instances and also contained the utils.php file in the oidc/classes/ directory

We're a bit at a loss as to why the conversion works sometimes and sometimes not, even though the same oidc folder was copied.

Thanks for the support!

Regards,
Friedhelm

**Comment by weilai-irl** [comment]
Hi @kueppersf

If you revert to the older version of the plugin (release 3.11.4), there should be no code checking or using configuration "auth_oidc | tenantnameorguid", therefore even if it's there, it's not doing anything and won't break anything.

If you have debug turned on, please try to investigate the details of the error reporting. Pay attention to the file in which the error "Error: Class 'auth_oidc\utils' not found" is reported, and try to figure out why it can't find the class. The class is defined at https://github.com/microsoft/o365-moodle/blob/v3.11.4/auth/oidc/classes/utils.php and the code at https://github.com/microsoft/o365-moodle/blob/46861cfe86a0cedf2866246f3909faf50de4a3d3/auth/oidc/classes/utils.php#L26-L33 should make class auto loading work.

Regards,
Lai

**Comment by hmoffatt** [comment]
I also have Moodle 3.11.11, and having just upgraded this plugin to the 2021051730 version found the login button disappeared. I reinstalled the 2021051725 version from https://moodle.org/plugins/auth_oidc/3.11.4/26880
