### ISSUE TITLE
Mapping to On-premises SAM account name field from Azure AD

### ISSUE THREAD

**Issue by tomklageshau** [microsoft/o365-moodle#2212]
Hi there,

I'm currently facing an issue whereby our identifiers in Active Directory and Azure Active Directory are different. The UPN in AAD is different to the ID of the user in AD, and ideally we'd map the _auth_oidc | field_map_idnumber_ field to the ID from AD. 

It is stored in AAD under the "On-premises SAM account name" field, but that's not one we can select from the list under the "field mappings" section.

If we were able to use the "On-premises SAM account name" field for the ID number field it would enable us to handle LDAP enrolments better (rather than relying on something like the mail field) and also would then have less of a knock on effect to our third party software providers who know our users by the samaccountname, rather than the UPN from AAD which would be different.

Can this additional field be mapped to from the claim?

Thanks
Tom

**Comment by weilai-irl** [comment]
@tomklageshau 

Thank you for reporting this.

I confirm this request is covered by related issue #2157, which will be implemented and included in the June 2023 release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @tomklageshau 

I have provided a solution which supports the sync of "onPremisesSamAccountName" from Azure AD to Moodle. Could you test it on your end please, since we don't have our Azure AD connected to on premises AD.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @tomklageshau 

The requested feature has been included in the latest release of the plugins today. Please check it out and test the feature.

I'm going to close this issue now. Please feel free to reopen if you have any questions.

Regards,
Lai
