### ISSUE TITLE
Error Auth Unknown State - PHP Error

### ISSUE THREAD

**Issue by aboarken** [microsoft/o365-moodle#2215]
Hello @weilai-irl ,

I am always getting this error on my php error file. I am using Moodle 3.11.10+ (Build: 20221104) - PHP 8.0

Error code: errorauthunknownstate
* line 287 of /auth/oidc/classes/loginflow/authcode.php: moodle_exception thrown
* line 133 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()
* line 168 of /auth/oidc/auth.php: call to auth_oidc\loginflow\authcode->handleredirect()
* line 31 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()

Kindly is there any solution to fix this issue?

Thanks in advance.

**Comment by weilai-irl** [comment]
Hi @aboarken,

In short, a "state" is a string that is sent to the Azure AD authorization endpoint as part of the request, and is returned unchanged in the response. It's a way to ensure the authorization response is sent to the request party. In Moodle, before initialising an authorisation request, Moodle would generate a 15 character random string to be used as "state", save it in the auth_oidc_state table, and send it as part of the payload of the authorization endpoint. Upon receiving the response, auth_oidc plugin would try to find the record with matching state in the auth_oidc_state table, and only process the successful authorization after a record is found and deleted.

If you keep seeing this error, I'd suggest you check:
1. If the table auth_oidc_state exists.
2. When you try to start logging in a user using auth_oidc, if a new record is created in the table.
3. If both 1 and 2 are working as expected, check the content of the authorization request and response, and confirm if the correct state values are included.

Regards,
Lai

**Comment by aboarken** [comment]
Hello @weilai-irl, that issue has been fixed. There was a connectivity issue with the cPanel resources leading to a login issue to schools' LMS Portal. You may close this issue. Thank you for your help.

**Comment by weilai-irl** [comment]
Hi @aboarken 

Thank you for your confirmation. I'll close the issue now.

Regards,
Lai
