### ISSUE TITLE
Problem with Integrating with Identityserver3

### ISSUE THREAD

**Issue by ajaykotnala** [Microsoft/o365-moodle#222]
Hi,

I am trying to consume this library with existing Identityserver 3 integration.
I am using 

$plugin->version = 2016120501;
$plugin->requires = 2016120500;
$plugin->component = 'auth_oidc';
$plugin->maturity = MATURITY_STABLE;
$plugin->release = '3.2.0.1';

and I have one client in Identityserver 3 with 
redirect URI 
Flow is Authorization code
Logout Uri and almost everything.
I have already tried this client(idsrv3) with another application and it is working fine.

In DashboardSite --> administration -->Plugins  -->Authentication -->OpenID Connect

i have configure 
Provider name =  OpenID Connect
ClientId = same as idsrv3
Authorization endpoint= https://myidentityserver3.com/identity
Token Endpoint= https://myidentityserver3.com/identity/connect/token
Redirect URI = https://localhost/moodle/auth/oidc/
Authentication Method = Authorization Code Flow (recommended)

but it is not showing any link or any changes on my login page. 
please suggest me if it works with identityserver3 or not.
if yes then what is I am missing?

Thanks,
ajay kotnala
kotnala.ajayk@gmail.com

**Comment by jamesmcq** [comment]
@ajaykotnala Have you enabled the authentication plugin in Moodle? The plugin must be "turned on" to modify the login page and add the "login with" section.

**Comment by ajaykotnala** [comment]
it got resolve . i was not able to see it becoz some silly compilation issue.
Thanks

**Comment by charettedavid** [comment]
@ajaykotnala i have the same issue, i configure IDS3 but i dont see any icon / link to initiate the login process. i did rebbot, clear cache, activate debug ... nothing.
I'm on 3.2
Any help will be much apreciated.
Thank you
