### ISSUE TITLE
User creation restriction - Employee ID

### ISSUE THREAD

**Issue by majidh8** [microsoft/o365-moodle#2233]
Hi, I would like to restrict user creation so that only users that have an employee ID can log into Moodle. I can see the setting for user creation restriction but how do I set it to only allow users who have an employee ID in Azure AD?
<img width="1240" alt="Screenshot 2022-11-22 at 11 30 51" src="https://user-images.githubusercontent.com/13693553/203303795-9d24b8d0-ce7d-476e-a483-51b8361d6d96.png">

**Comment by JGHZA** [comment]
Hey, saw this post you may yet have found a solution. If you wanted to ensure that only people who's Employee number is not-blank you could use a regular expression to do that. The expression could be simply: 
`.+ 
`
This regular expression matches any sequence of one or more characters (represented by the dot .) in a greedy manner (represented by the + quantifier). This means that it will match any string that contains at least one character, ensuring that the input is not empty.

**Comment by majidh8** [comment]
Hi @JGHZA Thanks for the help. Much appreciated.
