### ISSUE TITLE
Performance regression due to purging caches inside handle_config_log_created

### ISSUE THREAD

**Issue by brendanheywood** [microsoft/o365-moodle#2260]
Generally speaking purging caches in a prod site during heavy load is a bad thing which should be avoided at all costs.

The moodle-local_o365 has an event handler which watched for changes to the config log and then *regardless* of what was changes it purges the entire cache here:

https://github.com/microsoft/o365-moodle/blob/574ee58504c82dea29d84f17b59bce226b827703/local/o365/classes/observers.php#L893

Which means if you change any other admin setting, unrelated to anything MS then the whole site bogs down for a bit.

This purge shouldn't be needed at all, all of the calls the unset_config invalidate their own caches. If there is something specific to the MS plugins which need to be invalidates then it should invalidate the specific cache items not the whole thing.

Worst case, the handle could still purge the caches but **only** if something specific to the MS suite of plugins has changed

**Comment by weilai-irl** [comment]
Hi @brendanheywood 

Thank you very much for reporting this.

I acknowledge this is a genuine concern and it should have been handled better. I'll provide a fix to this issue in the next release.

Regards,
Lai

**Comment by brendanheywood** [comment]
thanks @weilai-irl for the extremely quick triage and response :)

**Comment by weilai-irl** [comment]
Hi @brendanheywood 

The fix to the reported issue has been included in the release from today ([3.11.6](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m311), [4.0.3](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m400) and [4.1.1](https://github.com/microsoft/o365-moodle/releases/tag/v20230228_m410)). I'll mark this issue closed.

Feel free to reopen if the fix doesn't work for you.

Regards,
Lai

**Comment by brendanheywood** [comment]
thanks @weilai-irl

**Comment by dmitriim** [comment]
Hi @weilai-irl and @brendanheywood 
I'd like to reopen this one as the fix looks like a workaround rather than a proper fix.  It's like a ticking bomb. It still can be fatal for big instances if someone changes plugin related settings during a peak period.

Any ideas why we need to purge caches? Can we purge just specific caches if we really need to do so?

**Comment by bwalkerl** [comment]
Hi @weilai-irl 
I agree that this should be reopened - it's clear the fixes here have alleviated some of the concern, but as mentioned above it can still cause serious issues for large sites when these specific settings are changed unknowingly.

I think changing this should be relatively straightforward for someone who understands why this was added and can test whether it's still needed and/or if an alternative works.
