### ISSUE TITLE
unable to connect azure app

### ISSUE THREAD

**Issue by daviddolibar** [microsoft/o365-moodle#2267]
good morning, we are trying to connect moodle with azure and we have allways the same error:
Error en OpenID Connect. Revise los registros para obtener más información.

[Más información sobre este error](https://docs.moodle.org/401/es/error/auth_oidc/erroroidccall)

Información de depuración:
Error code: erroroidccall×Descartar esta notificación
Trazado de la pila (stack):
line 49 of /auth/oidc/classes/utils.php: moodle_exception thrown
line 346 of /auth/oidc/classes/oidcclient.php: call to auth_oidc\utils::process_json_response()
line 303 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\oidcclient->tokenrequest()
line 133 of /auth/oidc/classes/loginflow/authcode.php: call to auth_oidc\loginflow\authcode->handleauthresponse()
line 168 of /auth/oidc/auth.php: call to auth_oidc\loginflow\authcode->handleredirect()
line 31 of /auth/oidc/index.php: call to auth_plugin_oidc->handleredirect()

We have a case opened in microsoft, but they say that from your side all is ok.
Can you help me to finish the integration?
Thanks in advance.

**Comment by daviddolibar** [comment]
done

**Comment by fc-admin** [comment]
Hi daviddolibar

How did you resolve this issue?
