### ISSUE TITLE
Moodle 3.3 compability?

### ISSUE THREAD

**Issue by Jarvil** [Microsoft/o365-moodle#227]
Hello,

is this plugin still being under development? Will this be Moodle 3.3 compatible?

**Comment by frathom** [comment]
+1

Waiting for this plug-in to be made compatible with Moodle 3.3.

**Comment by Jarvil** [comment]
So  @jamesmcq ?

**Comment by jamesmcq** [comment]
Yes this will have a 3.3. branch available with the next release, which will be available shortly.

**Comment by Jarvil** [comment]
Hello,

When is the Moodle 3.3 release coming?

**Comment by jamesmcq** [comment]
@Jarvil 3.3 release is now available in this repository - will be available in our component repositories and on Moodle.org shortly. Thanks!
