### ISSUE TITLE
Adopt the Moodle stable branch naming conventions

### ISSUE THREAD

**Issue by brendanheywood** [microsoft/o365-moodle#2270]
Recently it seems that the MOODLE_41_STABLE branch was renamed to MOODLE_410_STABLE:

https://github.com/microsoft/o365-moodle/tree/MOODLE_410_STABLE

I would encourage you to adopt the Moodle code naming conventions which means this should actually be named MOODLE_401_STABLE and not MOODLE_410_STABLE

https://github.com/moodle/moodle/tree/MOODLE_401_STABLE

This is a confusing thing that we've seen a lot of people (including ourselves) get wrong since the weirdness with moodle 3.10 and 3.11

**Comment by weilai-irl** [comment]
Hi @brendanheywood 

Thank you for pointing it out. The branch names have been fixed now.

Regards,
Lai
