### ISSUE TITLE
New branches for Moodle 4.1

### ISSUE THREAD

**Issue by dmitriim** [microsoft/o365-moodle#2271]
Hi team! 

We noticed that recently you renamed 4.1 branches in all moodle related repositories from MOODLE_41_STABLE to MOODLE_410_STABLE.

Assuming you are trying to match a name of the current core Moodle 4.1 branch. Howeve,r for moodle it's MOODLE_401_STABLE see https://github.com/moodle/moodle/tree/MOODLE_401_STABLE

**Comment by weilai-irl** [comment]
Hi @dmitriim 

Thank you for reporting this. I have changed the branch names accordingly.

Regards,
Lai
