### ISSUE TITLE
Performance issue in Sync users with Azure AD schedule task in PostgreSQL

### ISSUE THREAD

**Issue by sumaiyamannan** [microsoft/o365-moodle#2273]
Hi,

We have seen that local_o365 has a performance issue in 'Sync users with Azure AD' schedule task in PostgreSQL. The issue includes the task taking minutes to complete. 

Our site environment included:
- Moodle 4.1 
- local_o365 version 2022041910
- Database PostgreSQL

To replicate the issue, go to schedule task logs and see the duration of task usersync of local_o365
The fix of this issue is available here https://github.com/microsoft/o365-moodle/pull/2274

Note: To be able to see the result, you need to have enough test data.

Cheers,
Sumaiya

**Comment by weilai-irl** [comment]
@sumaiyamannan 

Thank you for reporting the issue and making the PR. It looks good to me. We will test this and include this in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @sumaiyamannan 

The solution provided in the linked PR has been included in the release from today. Thank you again for your contribution.

Regards,
Lai
