### ISSUE TITLE
Unable to Create Team 

### ISSUE THREAD

**Issue by EiffelD** [microsoft/o365-moodle#2276]
Unable to get a MS team created. The following message is seen under 365 plugin > advanced > manage team creations
Cannot create Team from group - no owner

Have removed the objectid entery in the db,course showed not connected. After the scheduled task ran the above message appeared again. 

Please advise how we can resolve this. 

Moodle 3.11.12

**Comment by patmr7** [comment]
Duplicate issue, reference: #2275
