### ISSUE TITLE
Moodle 4.x compatibility

### ISSUE THREAD

**Issue by levemar** [microsoft/o365-moodle#2278]
Among the elements to modify : 

- replace the calls of print_error (now deprecated) by moodle_exception
- remove the call to deprecated assign_get_completion_state

**Comment by weilai-irl** [comment]
Hi @levemar,

The proposed changes have been included in the release from today:

- [4.1.4 release for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401)
- [4.2.3 release for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402)
- [4.3.1 release for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403)

Thank you for your contribution.

Regards,
Lai
