### ISSUE TITLE
CSV file upload issue with MIME type validation in plugin option usermatch upload file

### ISSUE THREAD

**Issue by RicardoUIB** [microsoft/o365-moodle#2282]
We came across a small issue when trying to upload CSV files using your plugin on different browsers. It turns out that some browsers send a different MIME type when uploading the file, causing errors in the file upload. For example, Firefox sends the file with a MIME type of 'application/csv', resulting in the following error message: 'Type application/csv is not supported. Please upload a plain-text CSV.'.

According to the IANA standard, CSV files should have a MIME type of 'text/csv'. Therefore, we kindly request that you update the code in the local/o365/classes/page/acp.php file, line 433, replacing this line:

if (strtolower($type[0]) === 'text/plain') {

with this one:

if (strtolower($type[0]) === 'text/plain' || strtolower($type[0]) === 'text/csv' || strtolower($type[0]) === 'application/csv') {

With this modification, users will be able to upload CSV files correctly from any browser. Thanks in advance for your help!

**Comment by weilai-irl** [comment]
Hi @RicardoUIB 

The PRs derived from your submitted PR has been included in the release from today. Thank you for reporting the issue and submitting the solution.

I'll close the issue now.

Regards,
Lai
