### ISSUE TITLE
Moodle 4.2

### ISSUE THREAD

**Issue by thrombus77** [microsoft/o365-moodle#2287]
Hello

We have been using the plugins for a few years and are very happy with them. We have updated our site to version 4.2 and now we can no longer log in via O365. Is there a way to activate the plugin?

Many thanks and greetings
Sam

**Comment by weilai-irl** [comment]
Hi @thrombus77,

We have released the initial version of the plugins for Moodle 4.2 at https://github.com/microsoft/o365-moodle/releases/tag/v20230525_m402. They are available from the Moodle plugin directory too. Please check them out.

The latest version of the plugins for Moodle 4.1 should mostly work in Moodle 4.2 though - there have been some changes but they are relatively small.

If you see some particular errors when using the plugins in Moodle 4.2, please report them here.

Regards,
Lai
