### ISSUE TITLE
Adminlevel of the System API -user

### ISSUE THREAD

**Issue by kkiiskin** [Microsoft/o365-moodle#229]
There are several options for admin-roles in Azure AD (Service administrator, User administrator, ...).

What is the minimum adminlevel needed? Global administrator is not always suitable to grant in this case.

**Comment by jamesmcq** [comment]
Hi @kkiiskin there's not a hard restriction on admin level. We recommend a global administrator so there are no issues with permissions. The system API user is used to perform various system-level activities: user sync, for example. We recommend a global administrator so there will no unforeseen restrictions in these activities, but you can use an admin-level account. The only restriction is that the user must be able to provide consent grants for granted permissions, this is done while setting the system API user.
