### ISSUE TITLE
ID Number set during sync, not during login

### ISSUE THREAD

**Issue by johnmichaelbradley** [microsoft/o365-moodle#2294]
I have ID Number mapped to Employee ID in the OpenID Connect mappings, and each user's ID Number is setting correctly when done so through a sync or user match. ID Number does not set on login, although it is set to do so. This specific Moodle instance creates user accounts on first sign-in and needs the ID Number to be set on every account.

I assume ID Number is not being set on login because Employee ID is not included in the token at login, but I have been unable to find a way to include it.

I have auth_oidc & local_o365 (4.0.3, 2022041915) installed.

Thanks in advance.

**Comment by nenorojas** [comment]
Hi @johnmichaelbradley 

Unfortunately this version of the plugin is not being maintained anymore, only bug fixing for 4.1 and 4.2. 

If you upgrade and this issue still occurs, we can reopen this case. 

Regards

**Comment by johnmichaelbradley** [comment]
Thanks for the reply. I am not in control of our Moodle upgrade schedule, so this version of the plug-in is what I have to work with. For what it is worth, this is still the case in 4.0.4.

I am not sure this is a bug in the plug-in, but rather a lack of knowledge on my part in regards to adding employeeId as a claim to the token used for authentication. If anyone has any tips for this, I would be grateful for the help.
