### ISSUE TITLE
Third-Party OIDC Not mapping User Id from `sub` nor `oid`

### ISSUE THREAD

**Issue by Tchekda** [microsoft/o365-moodle#2295]
We are trying to setup the [moodle-auth_oidc](https://github.com/Microsoft/moodle-auth_oidc) plugin with @ivaoaero OpenID integration. 
But when we try to map IVAO users' Id to Moodle's user model, the value is null, although we selected `Object Id` in the mapping dropdown. 
By looking at the code, we thought that the `Object Id` would use the `sub` claim like here https://github.com/microsoft/o365-moodle/blob/254fce25e057ad964f7bb3954b3086bf9cf689e2/auth/oidc/classes/loginflow/base.php#L541-L544
But then I realized the mapping might come from another function where there is no fallback from `oid` to `sub` : https://github.com/microsoft/o365-moodle/blob/254fce25e057ad964f7bb3954b3086bf9cf689e2/auth/oidc/classes/loginflow/base.php#L225-L230
Although we added the `oid` claim to the id_token, the value is still not getting mapped for some reason. 
Here is the Id Token payload : 
```json
{
  "aud": "ecedb686-cab6-4613-b883-6c2d2278a5ce",
  "sub": 485573,
  "type": "id_token",
  "nonce": "PT0XGtxZaCi8wPa+s+twTH1SYdH62AObJczAjiJAcS4=",
  "oid": 485573,
  "given_name": "David",
  "family_name": "Tchekachev",
  "nickname": "David",
  "ivao.aero/permissions": "display_all_sessions ADMINISTRATOR display_all_names display_all_sessions display_all_supervisors SUPERVISOR",
  "ivao.aero/staff_positions": "WDM",
  "ivao.aero/division": "FR",
  "profile": "https://www.ivao.aero/Member.aspx?Id=485573",
  "iss": "https://api.ivao.aero",
  "iat": 1686574778,
  "exp": 1686576578,
  "jti": "7ohgDRWCZ/IJYmNw6USC3mi40F4/lIKrXgVdifpqwsU="
}
```
We are sure that the token is properly loaded since the first name, last name are properly mapped into the moodle user model.

**Comment by Tchekda** [comment]
Hi @weilai-irl I am responsible for the OpenID server and not the moodle setup. I'll ask my counterpart to test out the solution you sent above. If not possible, I'll setup my own moodle server to test this out. WIll keep you posted

BTW, I reached this far in the code by just looking at it and searching references to OpenID field mappings ;)

**Comment by Tchekda** [comment]
Hello @weilai-irl again.
After playing with a local installation of moodle, I finally figured it out. Look at this code : https://github.com/microsoft/o365-moodle/blob/254fce25e057ad964f7bb3954b3086bf9cf689e2/auth/oidc/classes/loginflow/base.php#L227-L229
It sets the `objectId` field only if the value is "false" which isn't correct. It should be 
```php
if ($objectid) {
```
or 
```php
if (!empty($objectid)) {
```
the latter is the format used for all the other fields and this is why I updated my PR to reflect this fix [here](https://github.com/microsoft/o365-moodle/pull/2296/files#diff-9c69f8312084c18fc5182c7c07428619e9bef86afba4ddbac9092853d106c1f2R231)
Now it works like a charm

**Comment by weilai-irl** [comment]
Hi @Tchekda 

Since my PR for the 2023-06 release doesn't contain changes in https://github.com/microsoft/o365-moodle/commit/e9670683424bda0b6ecac9d91e8fec5ad7420faf, I'm going to push this issue to the 2023-09 release.

Regards,
Lai

**Comment by Tchekda** [comment]
Hi @weilai-irl 
Do you need anything from me or not? 
Anyways, thank you very much for merging my fixed into Moodle's source code :+1: 
Best,

**Comment by weilai-irl** [comment]
Hi @Tchekda 

Nothing is required on your end. I'll merge the changes in your latest commit in the next release, scheduled in September.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @Tchekda,

The complete fix has been included in the latest release from today. Thank you again for your contribution.

Regards,
Lai
