### ISSUE TITLE
OneNote Assignment error

### ISSUE THREAD

**Issue by ellajona** [microsoft/o365-moodle#230]
When I try to create an assignment in OneNote that is linked to a Moodle cource I get this error.  I just update all plugins in Moodle into the newest today.
Any ideas??
![image](https://user-images.githubusercontent.com/32703092/32438594-fba8b42c-c2e2-11e7-98b5-b481a0e65373.png)

**Comment by kkiiskin** [comment]
I'm having the same issue.

I have configured the webservice according 
https://github.com/Microsoft/o365-moodle/blob/wip-MSFTMPP-326-m30/local/o365docs/onenotewebservices.md

And connected Class Notebook to Moodle ( version 3.3 ) and a specific course.

**Comment by conantk** [comment]
I'm having a similar issue. I cannot use any of the mapping functions or assignment functions without an error. I cannot even load Moodle from within OneNote. It says the page cannot be displayed.

Kim

**Comment by nenorojas** [comment]
Hi, 

I'm closing this ticket due to inactivity. Please try the latest version of the plugin with latest version of Moodle, if it's still an issue, please raise a new case with further details. 

Regards
