### ISSUE TITLE
Linked accounts and changing usernames

### ISSUE THREAD

**Issue by gunnar-restorff** [Microsoft/o365-moodle#231]
I have a problem with O365/Open ID/Moodle 3.3. This should be reproducable:
1. I have a user in the AD, let's call it: 1234@domain.com
2. I had a user "1234" in Moodle. 
3. I ran the job "Sync users with Azure AD" (in Scheduled tasks) until the user gets matched. 
4. I changed the auth method in the user's profile to "Open ID"
5. I confirmed that it is now possible to log in to the account using "Office 365". Several times and verified that there is only ONE user containing 1234 in the username.
6. I changed the username by uploading a csv file with two columns and two rows:
```
username,oldusername
1234@domain.com,1234
```
(and choosing Update existing & allow renames). 
7. I checked under "Site administration > Plugins > Local plugins > Microsoft Office 365 Integration > Tools > Connections (Manage User Connections)" that the user is matched (i.e. "Matched with existing user. Awaiting completion."). This is just as before the user signs into his/her account for the first time after it is matched.
8. I log in using my account on O365 - and a NEW user with username 1234 gets created, and everytime I log in, I am this new user. 
9. If I NOW erase this new user "1234", then the user "1234@domain.com" gets linked to my account, and I can use O365 credentials to log in. 

I do not understand what is causing this issue. I would like that all usernames are of the form username@domain.com. The same issue happens if run the job "Sync users with Azure AD" (in Scheduled tasks) until the user gets matched - then a new user gets created. If I use match queue, it responds that the users are already matched, but upon login, a new user gets created.

**Comment by jamesmcq** [comment]
@gunnar-restorff It looks like the username change is the issue here, I'm currently working on some improvements to the plugins to have them handle username changes more reliably. Until then, the best way to handle a username change is to disconnect the Moodle user from the Azure AD user, change the username in Moodle (and/or Azure AD if you're doing that as well), then reconnect the users.

**Comment by gunnar-restorff** [comment]
Thanks for the answer. I have tried to search for a long time, but I cannot find out how to disconnect a Moodle user from the Azure AD user. How do I do that?

**Comment by jamesmcq** [comment]
@gunnar-restorff  Best way to do this as an administrator is from the user connections management page. From the local plugin settings page, go to the "Advanced" tab, then "Connections".

**Comment by jamesmcq** [comment]
@gunnar-restorff The last release improved the way the plugins handle username changes - namely the auth_oidc_token table now includes a userid rather than relying on username. That should resolve any username change issues so I'm going to close this issue, but please open a new issue if you continue to experience problems.

**Comment by pcomadmin** [comment]
Hello jamesmcq,
It seems that you know your stuff about Moodle and Office 365 integration. I have an issue that I do not know how to fix and need immediate assistance.

I work at a college so will be talking about student accounts

Situation:

User 1: Krillin Son (email: kson@school.edu)

User 2: KaioShin Son (email: kson_inactive@school.edu) _inactive as they are no longer a student and needed to change it so Krillin Son could use kson@school.edu account. User 2 is no longer in AD, Office 365 or Azure. This account is only in Moodle.

User 1 can login to Moodle via basic login with username kson and their password and get into their account. But when they try to login via the Microsoft SSO button with email kson@school.edu and their password. It will show User 2's account.

After investigating and going to Gear>Plugins>Local Plugins>Microsoft Office 365 Integration>Advanced>Manage User Connections. I noticed that User 2 is still showing a connections to email address kson@school.edu. I enabled the Match button on User 1 and User 2 clicked Unmatch for User 2. But when User 1 logs in with kson@school.edu it still shows User 2 account. From the Manage User Connection section I have no other changes I can make to remove User 2's connection to kson@school.edu

Any help would be great.

thanks 

Alex
