### ISSUE TITLE
Full user sync (local_o365\task\usersync) hangs/fails with large number of users due to get_duplicate_email_address() SQL call

### ISSUE THREAD

**Issue by jwcatau** [microsoft/o365-moodle#2323]
Hi @weilai-irl,

We've discovered an issue with full user sync (`local_o365\task\usersync`) which hangs/fails with large number of users (178,440 users) in `mdl_user` table due to the `get_duplicate_email_address()` function SQL call in `local/o365/classes/feature/usersync/main.php`

We're seeing this on the `MOODLE_401_STABLE` branch, but the git blame for that function seems to indicate it's been around for a while (September 2, 2022), now that it's being used in usersync.

And it looks like the commit when it was brought in for use in usersync is: https://github.com/microsoft/o365-moodle/commit/e73a5f8984cc32411c5a6253549dc42fdfc7bbf2

Usersync calls it in https://github.com/microsoft/o365-moodle/blob/f48161bd10f2c8b7e0b7dd30a90542a7ea4e19f9/local/o365/classes/feature/usersync/main.php#L1038 which is where it hangs.

This was identified using `mtrace()` calls in and around those function calls and if/else blocks, and using `strace` on the process. `strace` was used to attach to the running process before it hung using (`strace -p <PID> -s 65535 -v`) until it eventually did hang, showing a successful "`write(9,...`" and then "`poll(9,`" on the `/proc/<PID>/fd/9` file descriptor. The `ls -al /proc/<PID>/fd/9` showed the file descriptor matched the ID of a socket, which, using `lsof | grep <SOCKETID>` showed it to be the TCP connection to the database, polling and waiting for a response.

I.e. an SQL had been sent to the DB, and the DB was churning away with a response (and did/would have eventually timed out/terminated, I presume) but was taking many, many minutes, and/or not succeeding.

The function is:
https://github.com/microsoft/o365-moodle/blob/f48161bd10f2c8b7e0b7dd30a90542a7ea4e19f9/local/o365/lib.php#L451

```
function local_o365_get_duplicate_emails() {
    global $DB;

    $sql = 'SELECT DISTINCT LOWER(a.email)
              FROM {user} a
              JOIN {user} b ON a.email LIKE b.email
             WHERE a.id < b.id 
               AND a.deleted = 0
               AND b.deleted = 0
               AND a.suspended = 0
               AND b.suspended = 0';

    $records = $DB->get_records_sql($sql);
    return array_keys($records);
}
```

The purpose seems to be to get a list of "all active users' duplicate email addresses".

This may be intentionally database agnostic by design, but in today's debugging, we were using a PostgreSQL database, so have developed a replacement query to do the same.

Replacement query for PostgreSQL which I believe provides the same results is much more efficient, running in only 1 second was:

```
SELECT LOWER(email) FROM mdl_user WHERE deleted = 0 AND suspended = 0 GROUP BY LOWER(email) HAVING COUNT(username) > 1 ORDER BY 1;
```

Below is the query analysis:

```
EXPLAIN ANALYZE SELECT LOWER(email) FROM mdl_user WHERE deleted = 0 AND suspended = 0 GROUP BY LOWER(email) HAVING COUNT(username) > 1 ORDER BY 1;
                                                          QUERY PLAN                                                           
-------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=34230.26..37880.01 rows=58358 width=32) (actual time=797.027..984.645 rows=43 loops=1)
   Group Key: (lower((email)::text))
   Filter: (count(username) > 1)
   Rows Removed by Filter: 177694
   ->  Sort  (cost=34230.26..34668.74 rows=175391 width=40) (actual time=782.336..923.383 rows=177806 loops=1)
         Sort Key: (lower((email)::text))
         Sort Method: external merge  Disk: 9872kB
         ->  Seq Scan on mdl_user  (cost=0.00..14155.02 rows=175391 width=40) (actual time=0.020..213.016 rows=177806 loops=1)
               Filter: ((deleted = 0) AND (suspended = 0))
               Rows Removed by Filter: 634
 Planning Time: 0.180 ms
 Execution Time: 986.658 ms
(12 rows)
```

This has been tested working in PostgreSQL, but may need testing/review for MySQL and/or other database platforms.

**Comment by weilai-irl** [comment]
Hi @jwcatau

Thank you for reporting the issue and submitting the PR. You are right that this is the same issue as #2273 and your solution is identical as #2274, which has been converted to the three linked PRs and will be included in the next release following test.

I'll close this one after the release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @jwcatau 

The solution has been included in the latest release from today. Thank you again for your contribution. I'll close the issue now.

Regards,
Lai
