### ISSUE TITLE
user sync (local_o365\task\usersync) stopping without reason

### ISSUE THREAD

**Issue by EduardoRS96** [microsoft/o365-moodle#2327]
Hello,

Im having a problem where usersync task just stop working when trying to create users on moodle. All of our others syncs are working correctly (coursesync and updates of manually created users from oidc). 

I was debugging the execute() function on \local\o365\classes\task\usersync.php and the script stops right after AD's API response with all users.

We have 60k users being allocated on the $users variable. This might be the problem?

I dont have access to server properties (php,apache,vm) and the cron task just dont show any type of error as below.

![image](https://github.com/microsoft/o365-moodle/assets/68596423/bea112ad-5346-409c-80c2-22ee95f1ce5b)

**Comment by weilai-irl** [comment]
Hi @EduardoRS96 

Please turn on debugging to the highest level and run the task again and see if it provides more details.

Regards,
Lai

**Comment by EduardoRS96** [comment]
Hello @weilai-irl ,

I was struggling on this because even with debugging in the highest level the script was stopping without any log.

But after debugging code, i could verify that it was happening because the loop on getting Ad users on  was taking too long.

On code: 
          while ($continue) {
                    [$returnedusers, $skiptoken] = $usersync->get_users('default', $skiptoken);
                    $users = array_merge($users, $returnedusers);
                    $continue = (!empty($skiptoken));
                }

It was taking more than 5 minutes and doesnt print out any mtrace during the loop. So Apache was killing it as was being a timeout request.

We changed apache timeout to solved this issue.
