### ISSUE TITLE
Profile Photos are not syncing after second+ logins

### ISSUE THREAD

**Issue by anormore** [Microsoft/o365-moodle#233]
Plugin is working great otherwise... However the user profile photos are not syncing!

I just end up with a generic user profile. 

Even if I upload something, when cron/login runs it fails, and gives me back the generic login profile... Where do I start?

**Comment by anormore** [comment]
I switched over to the legacy API rather than the default graph API and it's working. For my own user account only. Other accounts don't seem to be working...

**Comment by jamesmcq** [comment]
Hi @anormore - First step is to enable debug logging from the local plugin settings page, then click the link in the setting description to view the logs. Run a profile photo sync (Run the cron or login), and see if any logs appear. This would provide more information on what might be happening.

**Comment by cb526** [comment]
Just to confirm the issue still exists in latest version.

**Comment by jamesmcq** [comment]
@cb526 are you able to provide any logs by following the process I outlined above?

**Comment by anormore** [comment]
Hey all, we're still plagued by this issue. We're running the latest version now and re-focussed on this issue. Will keep everyone updated, but we're getting API errors.

...... Error in delta usersync: Error in API call: Invalid property: telephoneNumber

Would this lead to the exit of the sync script? Cheers.

**Comment by anormore** [comment]
Hi friend, I've been digging in to this... adding a bunch of logging diagnostics to the get_photo stuff. 

It's lead me down the rabbit hole to discover that the API simply does not detect any profile photo. More interestingly I think this next bit is important:

![image](https://user-images.githubusercontent.com/28155233/44595529-3e2f7d00-a797-11e8-915b-ceebaf93a77a.png)

So, the Graph API is not connecting. In previous versions of your plugin we had an option to disable the graph api, and we had photos working. We have just updated to the most recent version and this is the error we receive.

How do we fix this? :)

**Comment by anormore** [comment]
Additionally, when I run the Sync Users with Azure AD in scheduled tasks this is the output:

`Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
... started 12:35:23. Current memory use 15.5MB.
...... Starting sync
...... No skiptoken (delta) stored.
...... No deltatoken stored.
...... Using delta sync.
...... Contacting Azure AD...
...... Error in delta usersync: Error in API call: Invalid property: telephoneNumber
...... Resetting skip and delta tokens.
...... Got response from Azure AD
...... Clearing deltatoken (none received)
...... Clearing skiptoken (delta) (none received)
...... No users received to sync.
...... Sync process finished.
... used 4 dbqueries
... used 0.34740996360779 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\task\usersync)`

This may shed some light?

I have also enabled: $CFG->local_o365_forcelegacyapi = true;

This has made no impact.

**Comment by jamesmcq** [comment]
Thanks @anormore - I'm going to look at this further. Appreciate the details logs!

**Comment by anormore** [comment]
Hey @jamesmcq  just checking in with you, our team had a meeting today. This is affecting about 4000 users.

I see this is in progress, that's good!

Anything further I can do to assist you?

**Comment by anormore** [comment]
@cybercorey I can confirm that commenting these lines out has fixed some issue with Sync! Still don't have photos though.

**Comment by anormore** [comment]
Hey guys just checking in, been a month... I guess I'll have to.. fix myself? Here we go...?

**Comment by anormore** [comment]
Hey @gunnar-restorff  that's a GREAT find! I know how to debug this stuff, I will take over where you left off and see if I can't figure anything else out.

I do recall that if $size is empty the entire function will drop out. I'll try hacking some values in there to see if we can make anything stick. 

Again, great find, maybe this is it!

@jamesmcq  Thanks for your work on this, we at YorkvilleU.ca appreciate your massive undertaking.

**Comment by anormore** [comment]
Hi all, @gunnar-restorff your find was useful only in determining that indeed, the size is coming back because no resource is found.

  "error": {
    "code": "ResourceNotFound",
    "message": "Resource could not be discovered.",
    "innerError": {
      "request-id": "aaaaaaaaa-bbbb-ccc-ddd-eeeeeee",
      "date": "2018-10-26T16:50:48"
    }
  }

No idea where to go next.

@jamesmcq How can I help?

**Comment by anormore** [comment]
Bandaid fix for photos and user syncing can be found here: 

https://github.com/Microsoft/o365-moodle/issues/273

**Comment by jamesmcq** [comment]
Hi all - this should now be resolved in the latest release. Thanks for the report!
