### ISSUE TITLE
How to add students in a group or groups to a Teams Meeting LTI link?

### ISSUE THREAD

**Issue by sarathp06** [microsoft/o365-moodle#2333]
I have configured Teams Meeting LTI in my Moodle 4.1.3 site. I am able to create the meeting link, invite users and join the meeting. However, let's say I have 5 groups in my Moodle course and have 50 users in each group. I want to create a teams meeting link for a single group. I'll be doing the restrictions from the Moodle end but do I have to manually invite all 50 users or is there a way to add a group or groups so that only those students will see the join button?

**Comment by mmast-msft** [comment]
Unfortunately, the Teams Meeting LTI is not able to access LMS groups.  We do not yet have plans for this.  A prerequisite would be LTI NRPS support for course group memberships.  In the future, please direct any Teams Meetings LTI issues to https://aka.ms/edusupport.
