### ISSUE TITLE
Username overridden in Moodle regardless of sync setting

### ISSUE THREAD

**Issue by sporter23** [microsoft/o365-moodle#2337]
We have an odd issue where a few of our users have had the O365 sync override the moodle username by appending the domain. This is breaking some of our APIs. 
Whenever we strip out the domain from the username in Moodle, the sync overwrites it again. The sync language is, "User has been renamed in Microsoft; updating Moodle user record..." This occurs regardless of the sync settings on the Microsoft 365 Integration page. We have turned off "update all accounts in Moodle for users in AD" and we have, "Match Azure usernames to moodle emails instead of moodle usernames during the sync." We are wondering if this is a bug in the plugin or a misunderstanding on what should happen.
Additional note:
- Users with the domain appended and those without all have matching (same format) UPNs,  sAMAccountNames, and uid, but the system only overwrites some select users

**Comment by thebenkahn** [comment]
I can add a second report of this issue. I have a site that still uses an LDAP connection for user creation and authentication. The users have SamAccountName style usernames, with no email domain. The \local_o365\task\usersync task is changing the usernames to match the Azure UPN with an email domain for some users, resulting in the users not being able to login via LDAP.

We have the MS 365 plugin set to match existing users only, it should not be updating usernames from what I can see

MOODLE-4.1.3
local_o365 - 4.1.2 4.1.2 2022112810

These are the sync settings:

![Snag_5b012e2](https://github.com/microsoft/o365-moodle/assets/30783598/da7f65fa-ceca-4362-b1b0-63fb07cab18e)

The Azure user sync logs show entries like this

........ Syncing user username@myuniversityedu
......... User has been renamed in Microsoft; updating Moodle user record...

I looked through the sync settings in the updated plugins but don't see any option to enable/disable renaming of Moodle accounts.

For now I have manually renamed the accounts to the SamAccountName style and disabled the sync. However this could be a big problem for any other sites that use MS365 to match users but rely on some other auth method for matched accounts.

Looking at the table here for scenario 2 https://github.com/microsoft/o365-moodle/pull/2214

![Snag_5d58e86](https://github.com/microsoft/o365-moodle/assets/30783598/14eef0e5-d37b-4491-a52f-1b5fd8e6e989)

I could be wrong, but I think you are incorrectly assuming a user with an OIDC token has logged in via OIDC, when it can be the case that a user has an OIDC token when they have simply connected their account to Microsoft services but are not using OIDC?

**Comment by weilai-irl** [comment]
Hi @sporter23 and @thebenkahn 

I acknowledge the issue. I confirm it's related to the feature to support Microsoft UPN change, which was included in the last release of the plugin in June 2023. Besides some other bugs the feature contains, it didn't contain a toggle to allow Moodle site admins to turn this feature on or off. The default behaviour for any Moodle user who are connected to Microsoft accounts (regardless of the accounts are matched) is to keep Moodle account username synced with Microsoft UPN whereas possible. We realised this might not be the use case for some users of the integration. A solution will be included in the next release. Mainly it will contain two parts:

1. A toggle for site admins to turn this feature on or off, possibly in the form of a user sync option.
2. A logic to exclude manually matched users from rename.

I'll link the PR to the issue when they are ready.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @sporter23 and @thebenkahn 

I confirm the issue should be fixed by the latest release from today (4.0.5, 4.1.3 and 4.2.2). Please check out this release and confirm if it works as expected. I'll mark the issue closed for now. Feel free to reopen it if needed.

Regards,
Lai
