### ISSUE TITLE
Minimum required permissions for Azure API Admin user to sync Moodle users

### ISSUE THREAD

**Issue by upats** [Microsoft/o365-moodle#234]
I can't find this in the documentation anywhere--

We're trying to create a dedicated service account for Moodle in Azure that has the minimum required permissions to let it perform the cron job user sync script. All of the documentation says to use an Azure administrator account, but we really do not want a full Azure administrator account tied to Moodle.

If we create a new Azure role, what are the minimum required permissions we would need for the user sync script (and any other administrative tasks this user needs)?

Thanks!

**Comment by anieminen** [comment]
Hi,

I was wondering the same thing. From my limited experience it seems that a Global Administrator role is needed, but it really isn't good policy. And it is quite difficult to justify the need of a full Administrator account to a third party that maintains Azure AD with multiple tenants.

**Comment by jamesmcq** [comment]
Hi All,

For the system API user, we recommend using a global administrator to ensure there are no permission issues. However, you can create a user that meets your individual needs - global administrator privileges is not required. 

Each tenant and use case is a little different, there's not one single list I can provide for everyone, you can customize it to what you want to do in the plugins. If you are just interested in user sync, providing access to the users in your directory would be important. If you are interested in creating and maintaining user groups, access to manage groups is important, etc. @upats You mentioned specifically user sync, so providing this user access to see the users in question would be important.

The one critical component of the system API user is to provide consent for the application permissions set when setting up the application in Azure AD. This generally does require some sort of administrator, but it's also a one-time process - so if necessary, run through the system API user process with an administrator to provide consent, then set it to your dedicated service account.
