### ISSUE TITLE
Microsoft 365 and Moodle integration

### ISSUE THREAD

**Issue by greenfox75** [microsoft/o365-moodle#2353]
Hi all,
it's possibile the Microsoft 365 and Moodle integration with MS Teams in not Educational M365 tenants?
The users can use Microsoft Teams essential license and Office 365 E1 license?
Regards,
F.

**Comment by weilai-irl** [comment]
Hi @greenfox75 

It's possible to use the Teams integration feature without education license. The integration can detect if the tenant has either e1 or e3 license, if would use the education Graph API endpoint to create class teams if they present, or normal teams if they don't. This logic happens behind the scene and cannot be manually overridden.

Regards,
Lai
