### ISSUE TITLE
User Field Mapping - Additional Active Directory fields

### ISSUE THREAD

**Issue by callumlew** [microsoft/o365-moodle#237]
At present I am limited to some predefined options on user mapping from Active Directory. We currently have additional custom fields that we are not able to use. Is there the ability to map custom fields to this or is there the possibility of this in future developments?

Thanks

**Comment by jamesmcq** [comment]
Hi @callumlew - we do support mapping to Moodle custom user fields - is that what you are referring to?

**Comment by ChainsawBaby** [comment]
@jamesmcq I think he's meaning mapping to custom AD fields. Like extensions.
I'm having that issue right now, I need to fetch some data from an extension field

**Comment by jamesmcq** [comment]
@ChainsawBaby Gotcha, that makes sense. I'll look at this for a future new feature. Thanks!

**Comment by bradnielsen2981** [comment]
Is it possible for School Data Sync attributes in AAD to be brought into Moodle through Office 365 Field Mapping or other means? (By the way, I'm very impressed with the work so far on Moodle Office 365 integration. You are doing good work!)

**Comment by weilai-irl** [comment]
Hi all,

I know this is an extremely old post. I'm trying to make some progress here, either to implement the feature if the requirement is still valid, or to close it.

So the latest version of the plugins already supports a few more standard Azure AD user profile fields, plus the [15 onPremisesExtensionAttributes](https://docs.microsoft.com/en-us/graph/api/resources/onpremisesextensionattributes?view=graph-rest-1.0). Is there any other fields that need to be included?

SDS attributes might be a separate case. If it's still required, please log it in a different issue as feature request, and it will be processed accordingly.

Regards,
Lai

**Comment by VOOM108** [comment]
Does "latest version" only apply to the version for 3.11 or for 3.9 LTS as well? The 15 extAttr don't seem to be there on our 3.9 platform....

**Comment by weilai-irl** [comment]
Hi @VOOM108,

I confirm the onPremisesExtensionAttributes attributes were added to the version of plugins for Moodle 3.9 last year, and they are still there in the latest version for 3.9. In order to see them, you will need to configure integration between Moodle and Microsoft 365 and make sure the integration is up running, so that Graph API calls can be made to retrieve the attributes.

Regards,
Lai
