### ISSUE TITLE
Problem with Sync users with Azure AD scheduled job

### ISSUE THREAD

**Issue by mijalchev** [Microsoft/o365-moodle#238]
Hi,

We have installation of the o365 integration on Moodle 3.3.
The Azure user database contains few thousands users. When we run **Sync users with Azure AD** manually everything works. The job is running and parsing through around 1000 user and save the state. Than run again manually and it starts from where was before and the same until the all users in Azure AD are parsed. 

The problem is with auto Sync in Scheduled jobs. If the job is left on the default vaule * 1 * * * than it runs once and parsing only the first 1000 users. Than the next day it again starts from the beginning and never parse all the users. 

I tried to change the frequency of the job to * */1 * * * or 0 */1 * * * but as soon as I change the default values in the **Sync users with Azure AD** job it does not run at all. It never starts.

No errors in apache log. No errors in debugging mode.

**Comment by jamesmcq** [comment]
Hi @mijalchev - if you want to change the frequency to run more frequently, try changing the frequency to "* * * * *" - this would run every cron run. Moodle controls whether to run the job or not based on what you enter so unfortunately this is out of our control. Please see https://docs.moodle.org/34/en/Scheduled_tasks for more information on modifying this schedule. Thanks!

**Comment by mijalchev** [comment]
Hi,
Yes I went through the documentation before to report this.
Please see the attached screenshot.  This is how the Scheduled task is set at the moment.  The screenshot is taken 30 March 09.50AM.  
It says that the last time when the scheduled job run is 29 March  9:02  and that is the time when I manually activated and completed the sync.  
As you can see at the moment is set to run at the beginning of each hour.    The problem is that we have few thousands users in  Azure AD and the sync never goes to the end.   
For example I need to manually run the job several time to pars all the users on Azure AD and if I do that and the sync is compelted.  On Scheduled task it will clearly say tha  "Nest run" is set to the next hour.
When that hour comes the scheduled job runs sync the first 1000 users and the "Next run" is set as ASAP and stays like that forever and never completes the sync of the rest of the users.

![scheduled tasks](https://user-images.githubusercontent.com/20948466/38129913-3f397368-3401-11e8-8116-30f46c165bbf.png)

**Comment by jamesmcq** [comment]
@mijalchev To clarify - you're saying when you set to */1 the operation never runs - so it never even displays in the cron logs? The reason I closed this issue is if Moodle itself is never calling the cron task, there's nothing we can do on our side (our code never gets the chance to run). If I misunderstood and the task name does appear in the cron logs but doesn't process anything, that's a different issue. 

"*/1" should be supported by Moodle scheduled tasks, but I would try a few different values to see if that changes anything. If you still have no luck I'd try opening an issue on the Moodle tracker, as your problem would seem to be with Moodle core rather than the plugin.

**Comment by mijalchev** [comment]
It seems to me that Moodle responds correctly on the settings about frequency of running the job.  For example if there are only few users on Azure AD side the job will correctly run and there will not be a problem at all. It seems that problem appears when there are many users like in our case when the cron need to run multiple times and start syncing the users where it stopped the previous time until completely syncs all the users in Azure AD.  For example when I manually run the syncing I need to do it several time to do a complete sync, because each sync job is limited to around 1000 queries. Please let me know if you need some more info.

**Comment by jamesmcq** [comment]
Do you see the "Sync users with Azure AD" job in your cron logs? Or does the job not run at all?

**Comment by mijalchev** [comment]
Just as an update we still cannot find solution for this.  
We run  Moodle 3.3.9+ (Build: 20190201) and Microsoft Office 365 Integration 3.3.0.4

It runs only the first time according to the schedule and than it stacked to ASAP and never runs.  There is no "Sync users with Azure AD" job in the cron logs after the first run. 

After the update to 3.3.0.4 of the plugin something is changed.  In the previous version when you run manually run the job the users were retrieved alphabetically by their email addresses now it is a random order in the UI and  you do not know when the sync has passed all users and when it is completed.  IT also retrieves less users in one shots as **ijazhussain2015** commented above.
