### ISSUE TITLE
local_office365 plugin v4.1.3 Tries to Install theme_boost_o365teams plugin v4.2.0 Instead of v4.1.2

### ISSUE THREAD

**Issue by amorrowbellarmine** [microsoft/o365-moodle#2395]
Hi,

I'm trying to update the local_office365 plugin on my 4.1.6+ Moodle server from v4.1.1 to v4.1.3. Once I click the "Install this update" button, I get prompted to install a missing dependency, theme_boost_o365teams. But Moodle is trying to install v4.2.0 of the theme, which is not compatible with my server. Shouldn't the local_office365 plugin install theme_boost_o365teams v 4.1.0?

Moodle version
```
root@moodleweb2023ed:/var/www/html# cat moodle/version.php
<?php
defined('MOODLE_INTERNAL') || die();

$version  = 2022112806.02;              // 20221128      = branching date YYYYMMDD - do not modify!
                                        //         RR    = release increments - 00 in DEV branches.
                                        //           .XX = incremental changes.
$release  = '4.1.6+ (Build: 20231020)'; // Human-friendly version name
$branch   = '401';                     // This version's branch.
$maturity = MATURITY_STABLE;             // This version's maturity level.
```

Screenshot of my plugins overview page:
![image](https://github.com/microsoft/o365-moodle/assets/46689625/570f0f81-cac1-4665-ad80-a9d250b52f0c)
Screenshot of my plugins overview page after I click "Install this Update"
![image](https://github.com/microsoft/o365-moodle/assets/46689625/547efadb-70fc-4870-93e4-69eb3bff9bf9)
Screenshot showing the theme plugin failure:
![image](https://github.com/microsoft/o365-moodle/assets/46689625/bb58683b-8ea3-42cf-87e3-a55736278bbb)

In the version.php info file for the office365 plugin I see that is requires theme version 2022112810. https://github.com/microsoft/o365-moodle/blob/9f8176befac22bb7481d6bf76bb74a745656a835/local/office365/version.php#L38
And the theme plugin version says that version corresponds to release v4.1.2 https://github.com/microsoft/o365-moodle/blob/9f8176befac22bb7481d6bf76bb74a745656a835/theme/boost_o365teams/version.php#L29
But, Moodle's plugin repo does not list 4.1.2 has available for download yet. It looks like this needs to be fixed so installation from the Moodle plugins repo works correctly. https://moodle.org/plugins/theme_boost_o365teams/versions
![image](https://github.com/microsoft/o365-moodle/assets/46689625/5dc7dc00-406e-48e1-8bb3-172d120f9f86)

**Comment by weilai-irl** [comment]
Hi @amorrowbellarmine,

I have made 4.2.1 and 4.1.2 releases of the theme_boost_o365teams plugin available again. Please check if this solves the issue.

This two versions were pulled back because of some issues in other plugins (auth_oidc and local_o365), and we forgot to make them available again when newer versions of them with fixed were released.

Thank you for reporting this.

Regards,
Lai

**Comment by amorrowbellarmine** [comment]
Yes. the issue is now resolved. Apologies for the delayed response. Today was the first time I had the chance to test the plugin upgrade in our test environment.
