### ISSUE TITLE
Sync Moodle Courses to Teams Error

### ISSUE THREAD

**Issue by IFarr87** [microsoft/o365-moodle#2397]
Hi, 
Moodle Verson: [3.11.17 (Build: 20231009)
Microsoft 365 Integration Version: 3.11.6

I'm New to Moodle/Azure Plugin, User sync is working well but having trouble creating MS teams using Course Sync. 
I followed this guide for reference for setup: https://learn.microsoft.com/en-us/microsoftteams/install-moodle-integration
 
**Our configuration:**  
Under Sync settings The cource sync attribute is Customize
![image](https://github.com/microsoft/o365-moodle/assets/149045941/f9a06276-9c3c-49c8-aa04-898a3b763092)
We have selected one course to sync. 
![image](https://github.com/microsoft/o365-moodle/assets/149045941/1fdb104a-2803-4f0e-ba12-5730e64db909)
Manage Team Connections under the Advanced Tab, Tools is displaying the Course as not connected.
![image](https://github.com/microsoft/o365-moodle/assets/149045941/44b2ca1d-f6eb-44bd-82df-8126e0ff3dbc)

**The Problem:**
Sync Moodle courses to Microsoft Teams Task Log displays the below.

`Execute scheduled task: Sync Moodle courses to Microsoft Teams (local_o365\task\coursesync)
... started 17:51:03. Current memory use 7.9MB.
Start syncing courses.
Tenant has education license: yes
Restore groups that have been soft-deleted...
Processing courses without groups...
... Processing course #1133
...... Creating education group for course #1133
......... Could not create educationClass group for course #1133. Reason: Error in API call: Required roles claim values are not provided.
... All courses have groups created.
Processing courses without teams...
... Processing course #1183
...... Adding 0 owners and 0 members to group with ID fdcf82a1-09a4-488c-b48a-0f98eafeda16
......... Finished adding owners and members to group.
...... Creating class team from education group with ID fdcf82a1-09a4-488c-b48a-0f98eafeda16 for course #1183
......... Could not create class team from education group. Reason: Error in API call: Failed to execute Templates backend request CreateTeamFromGroupWithTemplateRequest. Request Url: https://teams.microsoft.com/fabric/apac/templates/api/groups/fdcf82a1-09a4-488c-b48a-0f98eafeda16/team, Request Method: PUT, Response Status Code: BadRequest, Response Headers: Strict-Transport-Security: max-age=2592000
x-operationid: 5972189f2c8544839d584534b0729331
x-telemetryid: 00-5972189f2c8544839d584534b0729331-cd18c0446cbcbe87-01
X-MSEdge-Ref: Ref A: FC01164116304ECDB28184F9F963CE30 Ref B: SYD03EDGE0808 Ref C: 2023-10-26T07:51:14Z
Date: Thu, 26 Oct 2023 07:51:13 GMT
, ErrorMessage : {&quot;errors&quot;:[{&quot;message&quot;:&quot;Team with template 'educationClass' can not be provisioned using a group which does not belong to a class.&quot;,&quot;errorCode&quot;:&quot;Unknown&quot;}],&quot;operationId&quot;:&quot;5972189f2c8544839d584534b0729331&quot;}
......... Failed to create class team from education group with ID fdcf82a1-09a4-488c-b48a-0f98eafeda16 for course #1183
... All courses have teams created.
Updating teams cache...
... Building existing teams cache records
... Updating teams cache records
... Deleting old teams cache records
... used 89 dbqueries
... used 63.483898162842 seconds
Scheduled task complete: Sync Moodle courses to Microsoft Teams (local_o365\task\coursesync)
`
Can anyone shed some light on the issue? (FYI OpenLMS host our Moodle PHP Environment)

**Comment by weilai-irl** [comment]
Hi @IFarr87,

Support for 3.11 version of the plugin has finished a while ago. If you have later version of the Moodle, please do upgrade your plugins.

As for the errors themselves, the first thing you need to check is if the application has the required permissions. Go to the "Microsoft 365 Integration" configuration page, in the "Setup" tab, click the "Update" button in the "Verify setup" section, and check the results. Add any missing permissions to the app, and try again. This solves most problems.

Regards,
Lai

**Comment by IFarr87** [comment]
Thanks Lai
Verify setup Result: "The The Microsoft Graph API was not found in this application" this is concerning. 
![image](https://github.com/microsoft/o365-moodle/assets/149045941/cf2c026a-66b7-46aa-91b9-acd364e6d925)
But the Azure App Reg API Permissions in Look Good. Any idea's 
![image](https://github.com/microsoft/o365-moodle/assets/149045941/8c1ae4e8-bb5d-4dba-801d-ef0d80ccbd1a)

I will priorities getting Moodle and Microsoft 365 Integration Version's updated as soon as possible.

**Comment by weilai-irl** [comment]
Hi @IFarr87 

I'd like to make two points:

1. The list of permissions seems out of date. The application should have around 30 permissions in total. Maybe an old version of the documentation was used for the setup? Please update according to https://docs.moodle.org/311/en/Microsoft_365#Permissions.
2. The error you got "Microsoft Graph API was not found in this application" basically means Moodle cannot get an application token to communicate with Microsoft Graph API. Please go through the manual setup steps again, in particular, make sure admin consent is granted on both Azure portal and Moodle configuration page.

Regards,
Lai

**Comment by IFarr87** [comment]
Thanks Lai. 
I will schedule some downtime of the Moodle service, any information I should now about relinking Moodle to Microsoft? 
for example, Account duplication in moodle, etc? 

Thanks 
Isaac

**Comment by IFarr87** [comment]
Hi Lai, Its hard to see in the image below but we now have 37 API Permissions in Azure for the Moodle App. 
I added the permissions from the azure side and referenced the Azure app permissions section of the documentation you provided us. https://docs.moodle.org/311/en/Microsoft_365#Permissions. I have also provided admin consent. 
Verify Setup step still fails, any idea's 

![image](https://github.com/microsoft/o365-moodle/assets/149045941/dd160f42-47de-4dc2-b03c-203d473fb385)

**Comment by IFarr87** [comment]
Hi All. 
Posting this to anyone who has a similar issue in the future. Register the Application in Azure using PowerShell script again, name the application something new and enter APP ID and Secret into Moodle. FYI, maximum Secret timeout length is now a year.
