### ISSUE TITLE
"Support_Microsoft_account_UPN_changes" does not convert Moodle usernames to lower case

### ISSUE THREAD

**Issue by mariofroeschl** [microsoft/o365-moodle#2399]
It seems the new Feature "Support_Microsoft_account_UPN_changes" (https://docs.moodle.org/401/en/Microsoft_365#Support_Microsoft_account_UPN_changes) does not correctly convert the retrieved UPN to lower case, when it should be used as Moodle username.

Example:

Precondition:
Support_Microsoft_account_UPN_changes enabled
User in Moodle: old.test1@example.com
Related user in Azure (UPN): New.Test1@example.com

Actual result after synch (when user tries to login):
Error: "The username must be in lower case".

Expected:
The plugin converts the UPN to lower case, when using it as username.
-> new.test1@example.com

Tested on Moodle 4.1.6

**Comment by skuti-is** [comment]
I have issue with "Support_Microsoft_account_UPN_changes" and am trying to find why, Is there a change regarding this from OpenID Connect / auth_oidc 4.2.0 to 4.2.2?

**Comment by weilai-irl** [comment]
Hi @mariofroeschl 

Thank you for reporting the issue. I acknowledge the issue - I managed to recreate it in my environment.

I have provided a fix in the linked PRs. They will be tested and included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @skuti-is

UPN change support is a new feature added in release 4.2.1, so it wouldn't exist in 4.2.0 release. The feature is disabled by default.

If you have any particular question about the feature, please ask in a separate issue.

Regards,
Lai

**Comment by kkiiskin** [comment]
Hi @weilai-irl 

is the fix for uppercase UPN problem going to be released soon?
We have lots of problems with that.

**Comment by weilai-irl** [comment]
Hi @kkiiskin 

The release will happen either between 11th and 14th of March, or 8th and 12th of April, depending on how the testing goes. The testing is starting from this week. We apologise for the delay, which is caused by a some sponsored feature requests to be included in this release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi all,

The fix to this issue has been included in the releases from today.

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Thank you very much for reporting the issue. Please check the latest version out and see if it works.

Regards,
Lai
