### ISSUE TITLE
Students are not allowed to visit Sharepoint course page and use its files in OneDrive for Business repository

### ISSUE THREAD

**Issue by gleidsonlm** [Microsoft/o365-moodle#240]
Moodle is configured to use authorization workflow and Sharepoint to sync site to all courses. Moodle is using Graph API and "local_o365 | azuresetup" check at local_o365 settings returns all green, no permission missing. Both teacher and student are using OpenID Connect authorization to login.

Teacher user is able to go to Sharepoint course site from the Microsoft block, comment and upload files. Then reuse those files in the Moodle course using the OneDrive for Business (repository_office365), Sharepoint (courses) directory.

Student user is not able to go to Sharepoint course site from the Microsoft block, it displays a page telling him he needs permission to see that page:
Page title: Access required
Message: You need permission to access this site. 
And a form to request permission.
https://content.screencast.com/users/gleidson.medeiros/folders/Jing/media/1c11a602-48f7-4346-a388-93f6e13f551b/00000211.png

**Question:** Shouldn't the Microsoft Office365 integration plugin already authorize and control access for users enroled as students or other role in the course, granting them the required access to the Sharepoint course site?

**Comment by nimojg-microsoft** [comment]
Have you tried using the Groups functionality instead of the SharePoint functionality in the plugin? Office 365 Groups that are created for each Moodle course come with their own SharePoint site and that site by default is permissioned for all members of the Group (i.e. Course) to have access.

**Comment by gleidsonlm** [comment]
Thanks for your reply!

Yes, I've tried and seems to work. Anyway, I'd like to confirm the expected functioning of the integration, if users enroled in the course as students are expected to access the course sharepoint site.

**Comment by jamesmcq** [comment]
Hi @gleidsonlm - the SharePoint functionality was originally intended to just provide a shared document repository for teachers, so student access was not an intended part of the feature. Office 365 groups is a better solution for this use case. Thanks for checking!
