### ISSUE TITLE
Microsoft LTI class not launching in Moodle due to missing Azure AD sync

### ISSUE THREAD

**Issue by sureshswayam** [microsoft/o365-moodle#2405]
On the Moodle application I am trying to add the Microsoft LTI external tool plugin for Classes and meetings. But the classes are not able to launch and I get an error saying one final step is missing. After checking the Azure AD sync with Moodle, we found that the Faculty/Teacher sync does not happen.
To investigate further, I created a new faculty account (sk_test_faculty@example_domain.edu) in the Azure admin center and added the user as a student for a Moodle course. After running the Moodle user sync job, I confirmed the member was added to the Azure AD group.
I then modified the same user as a Teacher in Moodle, ran the Moodle course sync, and ran the user sync job again. However, the user was not synced to Azure AD with the Teacher role for that course.

See the class launching issue,
![image](https://github.com/microsoft/o365-moodle/assets/122286993/20035d56-895e-420c-b116-b28a1b6c9767)

**Comment by sureshswayam** [comment]
I have verified the application configuration with v-maritorres@microsoft.com and v-pmetai@microsoft.com. According to the Microsoft configuration documents, it has been completed. The only problem I am having is with launching the Teams classes external tool.
However, the Teams meeting appears to be launching, as shown in the screenshot below:
![image](https://github.com/microsoft/o365-moodle/assets/122286993/15661a41-6ff0-4f86-b89b-9ea8fcc4a954)

**Comment by aspark21** [comment]
I think you’re doing it right @sureshswayam 

It’s just intentional bad design from Microsoft - it’s an aberration to describe this as being an LTI. It breaks all concepts of LTIs and adopts a provision ahead of time only. It doesn’t handle on the fly provisioning

**Comment by sureshswayam** [comment]
Thank you for your response @aspark21 

Thank you for the clarification on Microsoft's Teams integration. However, the core issue I am facing still remains unresolved.
The Teacher role is not syncing properly to a specific course in Azure AD after being assigned in Moodle and synced.
To elaborate, when I assign a user the Teacher role for a particular course in Moodle, then sync Moodle courses and users to Azure AD, that user does not get the Teacher role for that course in Azure AD.
I've tried re-syncing courses and users, but the Teacher role still does not get applied in Azure AD after being assigned in Moodle. This is the core sync issue I'm facing between role assignments in Moodle and Azure AD on a per-course level.    

I would still appreciate guidance on how to troubleshoot or resolve the Teacher role sync issue from Moodle to Azure AD.

**Comment by weilai-irl** [comment]
The issue has been confirmed fixed in private channels following explanation in the last note.
Closing call.
