### ISSUE TITLE
Local O365: Groups and Teams endpoints needs pagination

### ISSUE THREAD

**Issue by joaop221** [microsoft/o365-moodle#2417]
Some Azure user's fields (e.g.: Groups and Teams) has an one to N relationship, so them need to be called with pagination.

Graph Docs:

- [List joinedTeams - Graph](https://learn.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http);
- [List member of - Graph](https://learn.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http);
- [List transitive member of - Graph](https://learn.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http).

Non paginated API calls:

- https://github.com/microsoft/o365-moodle/blob/f796d9dfc27fdede24225cbc1ce445fb417fc1cb/local/o365/classes/rest/unified.php#L959
- https://github.com/microsoft/o365-moodle/blob/f796d9dfc27fdede24225cbc1ce445fb417fc1cb/local/o365/classes/rest/unified.php#L976
- https://github.com/microsoft/o365-moodle/blob/f796d9dfc27fdede24225cbc1ce445fb417fc1cb/local/o365/classes/rest/unified.php#L988

Implemented API calls with pagination:

- https://github.com/microsoft/o365-moodle/blob/f796d9dfc27fdede24225cbc1ce445fb417fc1cb/local/o365/classes/feature/usersync/main.php#L332

The proposal is add support to query user info with there pagination.

**Comment by douglasfernandesjr** [comment]
Great fix! In real world organizations user have a lot of groups. This gonna help me a lot

**Comment by weilai-irl** [comment]
Hi @joaop221 

We are aiming for the week of 11th of March if testing goes smoothly; otherwise it will be the week of 8th of April. I'm away for the three weeks in between.

Sorry for the delay.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @joaop221 

Changes in this issue are included in the releases from today.

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Thank you very much for reporting the issue and providing the solution.

Regards,
Lai
