### ISSUE TITLE
Local o365 [PostgreSQL]: The upgrade fails in sites with more than 65535 users, when $oldversion < 2023042407

### ISSUE THREAD

**Issue by Undreli-Studios** [microsoft/o365-moodle#2418]
Good day team. As per the title, the upgrade of local_o365 is failing when $oldversion < 2023042407 because there is a query being executed that uses an `IN` clause whose parameters are deleted users, which on PostgreSQL fails when there are more than 65535 users being deleted.

**Preconditions**

Have a Moodle instance with:

- local_o365 installed with any version older than 2023042407.
- PostgreSQL database.
- 65535 users or more being deleted (having `deleted = 1` in the table `mdl_user`).

**Steps to replicate**

1. Get any newer version of local_o365, newer than 2023042407.
2. Add the plugin code from step 1 to the Moodle instance.
3. Run the database upgrade (via GUI, or by doing `php admin/cli/upgrade.php`.

**Observed behavior**

This error appears:

```
-->local_o365
Default exception handler: Error writing to database Debug: number of parameters must be between 0 and 65535
DELETE FROM mdl_local_o365_calidmap
                          WHERE userid IN (VALUES ($1::text),($2::text),($3::text),($4::text),($5::text),($6::text),($7::text),($8::text),($9::text),($10::text),($11::text),
                          ...
                          ...
```

**Expected behavior**

The upgrade of local_o365 is completed correctly.

**Explanation**

PostgreSQL in certain instances can't handle more than 2bit of parameters passed into an `IN` clause. Apparently MySQL also has a ceiling to the number of parameters that can be passed to an `IN` clause, but the ceiling there is much much higher.

**Possible solution**

I modified the offending query, in both PostgreSQL and MySQL, to basically exchange the `IN` clause for a `JOIN` (MySQL), or a `USING WHERE` clause (PostgreSQL):

```
if ($oldversion < 2023042407) {
        $deleteduserids = $DB->get_fieldset_select('user', 'id', 'deleted = 1');

        if ($deleteduserids) {
            // Delete records in local_o365_calidmap.
            if ($DB->get_dbfamily() == 'mysql') {
                $sql = "DELETE idmap FROM {local_o365_calidmap} idmap JOIN {user} user 
                            ON idmap.userid = user.id AND user.deleted = 1";
                $DB->execute($sql);
            } else if ($DB->get_dbfamily() == 'postgres') {
                $sql = "DELETE FROM {local_o365_calidmap} idmap USING {user} user
                            WHERE idmap.userid = user.id AND user.deleted = 1";
                $DB->execute($sql);
            } else {
                $sql = "DELETE FROM {local_o365_calidmap}
                          WHERE userid {$useridsql}";
                $DB->execute($sql, $params);
            }

            // Delete records in local_o365_calsettings.
            if ($DB->get_dbfamily() == 'mysql') {
                $sql = "DELETE settings FROM {local_o365_calsettings} settings JOIN {user} user 
                            ON settings.user_id = user.id AND user.deleted = 1";
                $DB->execute($sql);
            } else if ($DB->get_dbfamily() == 'postgres') {
                $sql = "DELETE FROM {local_o365_calsettings} settings USING {user} user
                            WHERE settings.user_id = user.id AND user.deleted = 1";
                $DB->execute($sql);
            } else {
                $sql = "DELETE FROM {local_o365_calsettings}
                          WHERE user_id {$useridsql}";
                $DB->execute($sql, $params);
            }

            // Delete records in local_o365_calsub.
            if ($DB->get_dbfamily() == 'mysql') {
                $sql = "DELETE sub FROM {local_o365_calsub} sub JOIN {user} user 
                            ON sub.user_id = user.id AND user.deleted = 1";
                $DB->execute($sql);
            } else if ($DB->get_dbfamily() == 'postgres') {
                $sql = "DELETE FROM {local_o365_calsub} sub USING {user} user
                            WHERE sub.user_id = user.id AND user.deleted = 1";
                $DB->execute($sql);
            } else {
                $sql = "DELETE FROM {local_o365_calsub}
                          WHERE user_id {$useridsql}";
                $DB->execute($sql, $params);
            }
        }

        upgrade_plugin_savepoint(true, 2023042407, 'local', 'o365');
    }
```

The reason I had to do two different queries, for MySQL and PostgreSQL, `DELETE JOIN` doesn't work on PostgreSQL, and `DELETE USING WHERE` doesn't work on MySQL, or at least I couldn't find a way to make it work for both cases, but maybe there are ways to achieve it with a single query.

**Comment by weilai-irl** [comment]
Hi @Undreli-Studios 

I acknowledge the issue. The root of the issue is PostgreSQL doesn't support more than 65535 params. We had to make changes in other database queries with potentially large number of params for PostgreSQL before. I'll try to do the same here.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @Undreli-Studios 

First of all, I think Moodle HD has been trying to fix this issue in the core DB API. I see a few Moodle issues related to this, e.g. this one and this one. Some are marked closed, others still open. So the ultimate solution is on their hands.

If we are talking about a (temporary) solution at the plugin level - what you proposed would work. Without testing it, it looks like it supports all database variant.

Before accepting the solution, I'd like to propose another simpler solution, which has been used elsewhere in the local_o365 plugin (in the logic to handle user sync responses).

```
    if ($oldversion < 2023042407) {
        // Delete records in local_o365_calidmap for deleted users.
        $deleteduserids = $DB->get_fieldset_select('user', 'id', 'deleted = 1');

        if ($deleteduserids) {
            $chunk = array_chunk($deleteduserids, 10000);
            foreach ($chunk as $chunkdeleteduserids) {
                [$useridsql, $params] = $DB->get_in_or_equal($chunkdeleteduserids);
                $sql = "DELETE FROM {local_o365_calidmap}
                          WHERE userid {$useridsql}";
                $DB->execute($sql, $params);

                // Delete records in local_o365_calsettings.
                $sql = "DELETE FROM {local_o365_calsettings}
                          WHERE user_id {$useridsql}";
                $DB->execute($sql, $params);

                // Delete records in local_o365_calsub.
                $sql = "DELETE FROM {local_o365_calsub}
                          WHERE user_id {$useridsql}";
                $DB->execute($sql, $params);
            }
        }

        upgrade_plugin_savepoint(true, 2023042407, 'local', 'o365');
    }
```

The idea is simple - divide the results into smaller chunks of 10,000 records each, and process one chunk at a time.

Do you think this is also acceptable?

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @Undreli-Studios 

The fix to the issue has been included in the releases from today:

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Thank you very much for reporting the issue.

Regards,
Lai
