### ISSUE TITLE
moodle 4.3.1 oidc auth error

### ISSUE THREAD

**Issue by grantcolin** [microsoft/o365-moodle#2421]
After upgrade to Moodle 4.3.1 oidc authenticated users now see this error after they login and are not able to complete login :

Exception - update_internal_user_password(): Argument #2 ($password) must be of type string, null given, called in [dirroot]/lib/moodlelib.php on line 4497

User is then redirected back to the login screen.

**Comment by weilai-irl** [comment]
Hi @grantcolin 

We are upgrading the plugins to Moodle 4.3 and hope to release it before the end of the year. It will contain fix to this issue.

Regards,
Lai

**Comment by aspark21** [comment]
If you can’t wait that long, the fix is here https://github.com/microsoft/o365-moodle/pull/2393 ;)

**Comment by weilai-irl** [comment]
Hi all,

Please check out the latest release of the plugin v4.3.1 from today (https://moodle.org/plugins/auth_oidc/4.3.0/30700), which contains the fix to the issue.

Regards,
Lai
