### ISSUE TITLE
Control creation of Office groups for Moodle course groups.

### ISSUE THREAD

**Issue by jamesmcq** [microsoft/o365-moodle#243]
Currently Office groups are automatically created for user groups within a Moodle course, if that course has course groups enabled. Some users have a large amount of Moodle user groups within each course, or have no use for Office groups for each Moodle user group, and just want the single Office group for the course.

Adding a setting within the "Customize" setting for course sync to enable or disable Office groups for Moodle user groups would be a quick way to solve this for these users.

@nimojg-microsoft FYI

**Comment by celoxgroup** [comment]
Any updates on that? I am exactly looking to sync Moodle Groups with Teams Channels... ANy good pointers?

**Comment by weilai-irl** [comment]
The feature to create Microsoft groups from Moodle course groups have been removed from the integration. Moodle courses are synced to Teams (technically groups) now.

I'm closing this thread.

Regards,
Lai
