### ISSUE TITLE
Undefined array key "expires_on" and "resource" in .../local/o365/classes/oauth2/apptoken.php on line 54

### ISSUE THREAD

**Issue by teufelm** [microsoft/o365-moodle#2434]
I'm running Moodle 4.2.5+ (Build: 20240104) with Plugin local_o365 (4.2.2 2023042410) a have lot of 
     Undefined array key "expires_on" in .../local/o365/classes/oauth2/apptoken.php on line 54
     Undefined array key "resource" in .../local/o365/classes/oauth2/apptoken.php on line 54
messages in http error log. Auth is not working.

I did the intergration setup according https://docs.moodle.org/402/en/Microsoft_365.

Any Idea on that issue?

**Comment by weilai-irl** [comment]
Hi @teufelm 

The fix to the issue has been included in the releases from today.

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Thank you very much for reporting the issue.

Regards,
Lai
