### ISSUE TITLE
Feature request: Setting for choosing recipient of app secret expiry messages

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#2438]
Hi

the messages regarding app secret expiry (or invalid ones) seem to be sent to the email address of the main admin of Moodle.

This is not ideal sometimes, so it would be better to be able to choose user(s) or emailaddress(es) where they are sent.

**Comment by weilai-irl** [comment]
Hi @kkiiskin 

The requested feature has been included in the release from today.

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Please test it out in the latest versions of the plugins.

Regards,
Lai
