### ISSUE TITLE
Custom User Field Mapping

### ISSUE THREAD

**Issue by michael-LTS1** [Microsoft/o365-moodle#245]
Just wondering where I can find instructions on mapping AD fields to custom Moodle fields or if this is possible within the plugin?  Within the GUI you only have the option for limited predefined fields.

Moodle 3.4, 
OpenID Connectauth_oidc | 3.4.0.0
Office 365repository_office365 | 3.4.0.12017111301
Microsoft Office 365 Integrationlocal_o365 | 3.4.0.12017111301

Thanks

<img width="396" alt="user-fields" src="https://user-images.githubusercontent.com/33850075/39497564-3ee01782-4de7-11e8-8cbe-ca1d4c9271b8.PNG">

![image](https://user-images.githubusercontent.com/33850075/39498032-4663ff94-4de9-11e8-93bd-ab2334b7d20f.png)

**Comment by ChainsawBaby** [comment]
It seems like these fields are hardcoded into te plugin, and defaults to the mapping that o365 uses. If you're having custom fields on AAD, you will have to edit the plugin yourself to add the missing fields.

**Comment by jamesmcq** [comment]
@michael-LTS1 @chris-let @ChainsawBaby We do have support for Moodle custom fields - they should show up in the "Moodle field" select box. We do not currently have support for Azure custom fields, but I think you're all referring to Moodle custom fields - correct?

If you're not seeing the custom fields in the Moodle select box, can you post some additional information on the fields you have configured? Shortname, data type, etc. I just double-checked over here and am seeing the Moodle custom fields so if you're not we'll need some investigation.

**Comment by michael-LTS1** [comment]
Thanks James, profile field not showing up due to type, created a text entry field and seems to be working.

**Comment by chris-let** [comment]
Thanks all. I was particularly interested in custom AD fields, but have found another solution.

**Comment by bradnielsen2981** [comment]
Actually,we would be interested in Custom Azure Fields mapping. We are currently using the Office 365 Department Fields as a means of link Parents to Students within Moodle as it has a 64 character limit. It is not ideal, as we would like to use the Department field for other things. A Custom Azure field that could map with a Moodle Custom Field would be perfect...
