### ISSUE TITLE
Incorrect array key name referenced on isset for the get_userinfo function in the loginflow processing

### ISSUE THREAD

**Issue by TyDelean** [microsoft/o365-moodle#2456]
In the get_userinfo function within the file classes\loginflow\base.php (line 188)

When checking the token claim for the 'email' attribute, if found the $userdata['mail']  array key is updated, however on the next iteration, the check for if (!isset($userdata['email'])) occurs. This will always evaluate as false, given that the actual key name written was 'mail' and not 'email'.

Changing the key name in the isset check operation from 'email' to 'mail' resolves this issue.

**Comment by weilai-irl** [comment]
Hi @TyDelean 

Thank you for reporting this. I confirm this is indeed a bug - the first check for 'email' would always fail. I'll fix this in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
@TyDelean 

The fix to the issue has been included in the releases from today.

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Thank you very much for reporting the issue.

Regards,
Lai
