### ISSUE TITLE
moodle username digits only and azure ad sync not working

### ISSUE THREAD

**Issue by gavrielsl** [microsoft/o365-moodle#2457]
Hello, 
We run into an issue that we have moodle accounts with digits only (ex 494334334) (student id numbers) and diffrent mail for each student like (test@gmail.com)
we add o365 to integration with our institution that all users start with 494334334@student.onmicrosoft.com
we noticed that the user sync not working for those users and we have a lot of them.

configuration is like that
<img width="667" alt="image" src="https://github.com/microsoft/o365-moodle/assets/3612886/97aa27f1-ac5d-49bb-9590-f1fb3523186e">

we add some logs to try to find the problem 

<img width="306" alt="image" src="https://github.com/microsoft/o365-moodle/assets/3612886/5c20f4a2-53bd-461f-a6da-34d8aaa336ca">

we found that this array 
<img width="473" alt="image" src="https://github.com/microsoft/o365-moodle/assets/3612886/cb9c08ba-7dfa-4fa4-a1b4-95b5cfb38452">

not found the objects that contain upn with numbers only 

this is the dump object from existing users array

<img width="164" alt="image" src="https://github.com/microsoft/o365-moodle/assets/3612886/586f7ca3-5181-4acd-a31e-6f7eae8cd811">

can you help us to understand what we can do to fix that issue

**Comment by weilai-irl** [comment]
Hi @gavrielsl 

Thank you for reporting the issue. I remember we had issues with users having digits only usernames previously. I'll try to confirm the issue reported and if confirmed, provide a solution soon.

Regards,
Lai

**Comment by gavrielsl** [comment]
@weilai-irl we fix the issue also we will pull request it.

the problem was the index of the array, when you have numbers the index is destroyed after the array_marge.

our solution was to add 0 digit to the username in the existingusers array.

**Comment by weilai-irl** [comment]
@gavrielsl 

The fix to the reported issue has been included in the release from today.

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Thank you very much for reporting the issue.

Regards,
Lai
