### ISSUE TITLE
The onenote_assign_pages.teacher_lastviewed field is different based on fresh install vs upgrade path

### ISSUE THREAD

**Issue by polothy** [microsoft/o365-moodle#246]
In the install file, it is defined as `int(10)`: https://github.com/Microsoft/moodle-local_onenote/blob/master/db/install.xml#L27

In the upgrade path, it is defined as `varchar(255)`: https://github.com/Microsoft/moodle-local_onenote/blob/master/db/upgrade.php#L83

I think the `int(10)` is the correct one based on comments.  Likely low risk to fix the field in the upgrade path from varchar to int.

**Comment by jamesmcq** [comment]
Thanks for the heads-up @polothy. I'll get them consistent.

**Comment by jamesmcq** [comment]
Hi @polothy - I had this scheduled for today's release but ran into some upgrade issues at the last minute. This will be resolved shortly.

**Comment by chrisoconnor** [comment]
Hi @polothy
Thank you for reporting this.
The fix for this issue has been merged into the release 3.9.9, 3.10.6, 3.11.3 on 06/04/2022.
I'll close this ticket.

Chris
