### ISSUE TITLE
Problem setting up multitenancy

### ISSUE THREAD

**Issue by chris-let** [Microsoft/o365-moodle#247]
Hi all
I'm trying to test out multitenancy using Moodle 3.2, a trial Azure account and the latest version of this plugin. Everything seems to be set up correctly - users are being synced via OpenID Connect, but when I try to add an additional tenant, I'm getting "Please complete the plugin setup process before adding additional tenants." - I can't see what I need to do to complete setup. Any help appreciated. I posted here: https://moodle.org/mod/forum/discuss.php?d=368694 but no answers so far. The health check is fine - saying "Office 365 API calls are executing at full speed."
Any ideas?
Thanks in advance.

**Comment by zckb** [comment]
@chris-let - Thanks for raising the issue here. In the local plugin Microsoft Office 365 Integration setup, are you using the System API User or App-Only permissions model?

**Comment by chris-let** [comment]
Hi Zion

Thanks for getting back to me. I had been using the App only method - when
I switched to the System API user it resolved the issue. Any idea why that
may have happened?


Chris

Chris Baldwin
Founder/Head consultant
eLearning Path
www.elearning-path.com

**Comment by zckb** [comment]
Hi Chris, 
We haven't seen the issue previously, so I'm not sure yet. I'll try to repro and add as bug if/when confirmed.

**Comment by chris-let** [comment]
Thanks for that. Let me know if you need any info from my end to try to
reproduce.


Chris

Chris Baldwin
Founder/Head consultant
eLearning Path
www.elearning-path.com

**Comment by jamesmcq** [comment]
@chris-let Thanks for the report! A fix has been completed and will be released shortly.

**Comment by enavas05** [comment]
hi everybody, have a question respect to office 365 integration, what is the solution that you was find? now i traying to configure the aplications and this is my problem.
