### ISSUE TITLE
New users cannot login as appRoleAssignment is not set during user sync

### ISSUE THREAD

**Issue by zckb** [microsoft/o365-moodle#248]
Issue: Newly created Azure AD users cannot login. Moodle Azure AD usersync is not syncing the AppRoleAssignment even though assign users on sync is set in Office 365 Integration settings. 

Cause: Unknown. Suspect appRoleAssignment available via Microsoft Graph /beta endpoint only (https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/approleassignment) or appRoleAssignment not available thru App-Only model. Fix needs additional investigation. 

Repro: Create new user in Azure AD. Run Moodle cron. Sign in to Moodle with newly created user's Azure AD account. Authentication to Moodle fails. Sign in to Azure Portal and assign user to Azure AD's Moodle application settings. Sign in to Moodle with user's Azure AD account. Authentication to Moodle succeeds. 

Error:  Moodle cron shows Syncing user jsmith@contoso.onmicrosoft.com Could not assign user "jsmith@contoso.onmicrosoft.com"

Workaround: In Azure Portal > Azure Active Directory > Enterprise applications, change "User assignment required?" setting for Moodle application to No OR manually assign users or groups to Moodle application from within Azure AD.

**Comment by jamesmcq** [comment]
@zckb Thanks for the detailed report - I'll check it out.

**Comment by weilai-irl** [comment]
Hi @zckb,

I know this has been an extremely long shot. Sorry for not getting back to you sooner.

I retested the feature in the latest version of the plugins for Moodle 3.9/3.10/3.11, and I confirm the app assign option in user sync works as expected in all 3 versions.

I'll close this issue for now. If you still see this issue, feel free to re-open this issue (or create a new one). We will take a look sooner this time.

Regards,
Lai
