### ISSUE TITLE
Feature request: User creation restriction with group object id besides group name

### ISSUE THREAD

**Issue by jeremycarre38** [microsoft/o365-moodle#2485]
Hello,

I would like to know if it is possible to restrict user creation based on the object id of the group rather than the group name?

The "usersynccreationrestriction" parameter allows selecting "Microsoft 365 Group Membership," which seems to correspond to group names.

If it is not possible, do you have any idea if an update is planned?

Thank you in advance,

Have a good day.

**Comment by weilai-irl** [comment]
Hi @jeremycarre38 

The requested feature has been included in the release from today.

- [Release 4.1.4 for Moodle 4.1](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m401).
- [Release 4.2.3 for Moodle 4.2](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m402).
- [Release 4.3.1 for Moodle 4.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240311_m403).

Please test the feature out in the latest versions of the plugins.

Regards,
Lai
