### ISSUE TITLE
auth_oidc_token Duplicate issue

### ISSUE THREAD

**Issue by joshwillcock** [Microsoft/o365-moodle#249]
Hello,

We've identified an issue where users are unable to login with their oidc account. 

`The Office 365 user is connected to a Moodle Account, but OpenID Connect login is not enabled for the Moodle account. Please log in to Moodle account using the accounts defined authentication method to use Office 365 features.
`
Is the error the user receives. It appears  to only be solved when deleting the older duplicate in auth_oidc_token. I am struggling to work out why the plugin creates two and doesn't remove the old one if it has expired?

Issue on Moodle 3.3/3.4/3.5 MariaDB/MySQL Ubuntu16/Ubuntu17/Centos7

**Comment by jamesmcq** [comment]
Hi @joshwillcock - is there any difference between the two records other than the token/auth code values? Different usernames maybe?

Does this occur for all users or is there some identifiable special thing about the users it happens to?

**Comment by joshwillcock** [comment]
Hey James,

The record id (obviously), oidcuniqid, authcode, token, expiry, refreshtoken and idtoken are different for the two records.

Given the type of data I can email you a copy of these two records. This has happened on 3 different O365 setups and has happened to multiple users. We've deleted the duplicate record for all of these users except one (which I'm currently looking at). When I say I am talking about multiple users I'd say I've seen this happen to over 50 accounts (assuming more have this issue but have never logged in). As we don't control O365 it's hard for us to debug what can cause this. I've been informed that these users haven't been deleted and re-added to office 365.

**Comment by joshwillcock** [comment]
Hello James, any idea about this?

**Comment by joshwillcock** [comment]
Hey James, 

Could you clarify the expected behaviour of the tokens in the auth_oidc_token table?

**Comment by jamesmcq** [comment]
@joshwillcock You mentioned the "oidcuniqid" is different in the different records - this is usually the Azure AD username - are you changing usernames in Azure AD by any chance? If so, it's a known issue I'm working to resolve.

**Comment by joshwillcock** [comment]
Hello James,

I have been able to see that the oidcusername in some occasions has had a capital in one version but not in another. However these users have not reported issues. The users who have reported issues have the same oidcusername and different oidcuniqueid's, refreshcodes and idtokens.

If you wish to see a 'unedited' example if you drop me your email address I'll send it over. Alternatively, this is the data with 5 characters changed in each id/token and with the users name changed (changed to mine):
`
[josh.willcock-changed-values.xlsx](https://github.com/Microsoft/o365-moodle/files/2325629/josh.willcock-changed-values.xlsx)

`
I think this issue could be fixed solely by in the auth section SELECTing one token (with the furthest expiry time)

**Comment by jamesmcq** [comment]
@joshwillcock The oidcuniqueid should be a unique, unchanging value that we get from Azure AD that refers to a single user - you're saying you're seeing different oidcuniqueids but for the same user? Or do you have multiple users with the same username by any chance?

**Comment by joshwillcock** [comment]
It's the same username and email. I have spoken to three different office 365 management departments with 3 instances and all 3 insist the user accounts haven't been replaced. It is very strange. Each user only appears once when fetching all users from office 365

**Comment by jamesmcq** [comment]
@joshwillcock Thanks, if the oidcuniqueids are different they should refer to different users. Are you able to see multiple users in the Azure AD admin site?

**Comment by joshwillcock** [comment]
There is only one user on the admin section. Is it possible that the user was removed and re-added? As Moodle is unable to log the user in after this occurs?

**Comment by jamesmcq** [comment]
@joshwillcock Could be - if the user was removed and re-added, even though the information may be the same, the user is different as far as Moodle is concerned. Other than deleting the token in auth_oidc_token as you mentioned, you can also try manually disconnecting the Moodle and Office 365 users from the Moodle side (Site Admin > Plugins > Local plugins > Microsoft Office 365 Integration > Advanced > Manage user connections). Then reconnect using the new/current Office 365 user.

I'm going to close this issue now as I believe there's not much further we can go, but please feel free to open a new issue if anything else occurs. Thanks!
