### ISSUE TITLE
"Auth plugin not supported here" on user upload

### ISSUE THREAD

**Issue by OxyOCE** [microsoft/o365-moodle#2494]
When uploading users via csv, if `auth` method is set to `oidc` the uploader receives the warning "Auth plugin not supported here". This doesn't affect the outcome of the upload, therefore the warning is misleading.

The fix for this issue will also allow OIDC to be selected as a default if the auth method is not included in the csv.

Fixed in the following pull requests:

403: #2495 
402: #2520
401: #2521

Previous examples of this issue are discussed here: [MDL-59306](https://tracker.moodle.org/browse/MDL-59306)

**Comment by weilai-irl** [comment]
Hi @OxyOCE

The changes in this issue/PR has been included in the release from today. Thank you again for making the PR.

Regards,
Lai
