### ISSUE TITLE
local_o365 removes course team channel memberships when Moodle user enrolments are updated

### ISSUE THREAD

**Issue by jonof** [microsoft/o365-moodle#2503]
# The fault

The local_o365 plugin (v4.1.2, on Moodle 4.1.9) removes a member from a course Team's channels when trivial changes to the member's Moodle enrolment occur, such as adjusting the enrolment end date.
This is a consequence of the local_o365 plugin removing and re-adding the user in the team in reaction to the `core\event\user_enrolment_updated` Moodle event, with no apparent determination first made of whether there is a need to change the user's team/channel owner/member status.

# Reproducing the fault

1. In Moodle, prepare a course with some Student-role participants and yourself as a Teacher. Connect the course to Teams.
2. In Teams, activate the team and ensure the students are present as members.
3. In Teams, create a private channel in the course's team. Add the student members to the new channel.
4. In Moodle, edit the enrolment of one of the students you added in the Teams channel and set the enrolment end date to some (different) date in the future. Save the edit.
5. In Teams, view the members list of the private channel and observe the student you edited has been removed from the channel.

## Moodle–Teams communications backtraces

These are backtraces of each relevant API call made from Moodle to Microsoft APIs in the course of handling the `core\event\user_enrolment_updated` Moodle event. For brevity, frames for `local_o365\rest\o365api::apicall` and `local_o365\rest\unified::betaapicall`, and any frames higher than `local_o365\observers::handle_user_enrolment_updated` are omitted.

    local_o365\feature\coursesync\utils::sync_user_role_in_course_group (Line 705)
     >> local_o365\feature\coursesync\main::__construct (Line 89)
      >> local_o365\rest\unified::has_education_license
    array (
      ...
      2 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/main.php',
        'line' => 89,
        'function' => 'has_education_license',
        'class' => 'local_o365\\rest\\unified',
        'type' => '->',
      ),
      3 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/utils.php',
        'line' => 705,
        'function' => '__construct',
        'class' => 'local_o365\\feature\\coursesync\\main',
        'type' => '->',
      ),
      4 =>
      array (
        'file' => '.../local/o365/classes/observers.php',
        'line' => 430,
        'function' => 'sync_user_role_in_course_group',
        'class' => 'local_o365\\feature\\coursesync\\utils',
        'type' => '::',
      ),
      5 =>
      array (
        'function' => 'handle_user_enrolment_updated',
        'class' => 'local_o365\\observers',
        'type' => '::',
      ),
      ...
    )

    local_o365\feature\coursesync\utils::sync_user_role_in_course_group (Line 772)
     >> local_o365\feature\coursesync\main::remove_owner_from_group (Line 1399)
      >> local_o365\rest\unified::get_aad_user_conversation_member_id
    array (
      ...
      2 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/main.php',
        'line' => 1399,
        'function' => 'get_aad_user_conversation_member_id',
        'class' => 'local_o365\\rest\\unified',
        'type' => '->',
      ),
      3 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/utils.php',
        'line' => 772,
        'function' => 'remove_owner_from_group',
        'class' => 'local_o365\\feature\\coursesync\\main',
        'type' => '->',
      ),
      4 =>
      array (
        'file' => '.../local/o365/classes/observers.php',
        'line' => 430,
        'function' => 'sync_user_role_in_course_group',
        'class' => 'local_o365\\feature\\coursesync\\utils',
        'type' => '::',
      ),
      5 =>
      array (
        'function' => 'handle_user_enrolment_updated',
        'class' => 'local_o365\\observers',
        'type' => '::',
      ),
      ...
    )

    local_o365\feature\coursesync\utils::sync_user_role_in_course_group (Line 772)
     >> local_o365\feature\coursesync\main::remove_owner_from_group (Line 1405)
      >> local_o365\rest\unified::remove_owner_and_member_from_group_using_teams_api
    array (
      ...
      2 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/main.php',
        'line' => 1405,
        'function' => 'remove_owner_and_member_from_group_using_teams_api',
        'class' => 'local_o365\\rest\\unified',
        'type' => '->',
      ),
      3 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/utils.php',
        'line' => 772,
        'function' => 'remove_owner_from_group',
        'class' => 'local_o365\\feature\\coursesync\\main',
        'type' => '->',
      ),
      4 =>
      array (
        'file' => '.../local/o365/classes/observers.php',
        'line' => 430,
        'function' => 'sync_user_role_in_course_group',
        'class' => 'local_o365\\feature\\coursesync\\utils',
        'type' => '::',
      ),
      5 =>
      array (
        'function' => 'handle_user_enrolment_updated',
        'class' => 'local_o365\\observers',
        'type' => '::',
      ),
      ...
    )

    local_o365\feature\coursesync\utils::sync_user_role_in_course_group (Line 772)
     >> local_o365\feature\coursesync\main::remove_owner_from_group (Line 1414)
      >> local_o365\rest\unified::remove_member_from_group_using_group_api
    array (
      ...
      2 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/main.php',
        'line' => 1414,
        'function' => 'remove_member_from_group_using_group_api',
        'class' => 'local_o365\\rest\\unified',
        'type' => '->',
      ),
      3 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/utils.php',
        'line' => 772,
        'function' => 'remove_owner_from_group',
        'class' => 'local_o365\\feature\\coursesync\\main',
        'type' => '->',
      ),
      4 =>
      array (
        'file' => '.../local/o365/classes/observers.php',
        'line' => 430,
        'function' => 'sync_user_role_in_course_group',
        'class' => 'local_o365\\feature\\coursesync\\utils',
        'type' => '::',
      ),
      5 =>
      array (
        'function' => 'handle_user_enrolment_updated',
        'class' => 'local_o365\\observers',
        'type' => '::',
      ),
      ...
    )

    local_o365\feature\coursesync\utils::sync_user_role_in_course_group (Line 772)
     >> local_o365\feature\coursesync\main::remove_owner_from_group (Line 1415)
      >> local_o365\rest\unified::remove_owner_from_group_using_group_api
    array (
      ...
      2 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/main.php',
        'line' => 1415,
        'function' => 'remove_owner_from_group_using_group_api',
        'class' => 'local_o365\\rest\\unified',
        'type' => '->',
      ),
      3 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/utils.php',
        'line' => 772,
        'function' => 'remove_owner_from_group',
        'class' => 'local_o365\\feature\\coursesync\\main',
        'type' => '->',
      ),
      4 =>
      array (
        'file' => '.../local/o365/classes/observers.php',
        'line' => 430,
        'function' => 'sync_user_role_in_course_group',
        'class' => 'local_o365\\feature\\coursesync\\utils',
        'type' => '::',
      ),
      5 =>
      array (
        'function' => 'handle_user_enrolment_updated',
        'class' => 'local_o365\\observers',
        'type' => '::',
      ),
      ...
    )

    local_o365\feature\coursesync\utils::sync_user_role_in_course_group (Line 773)
     >> local_o365\feature\coursesync\main::add_member_to_group (Line 1319)
      >> local_o365\rest\unified::add_member_to_group_using_teams_api
    array (
      ...
      2 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/main.php',
        'line' => 1319,
        'function' => 'add_member_to_group_using_teams_api',
        'class' => 'local_o365\\rest\\unified',
        'type' => '->',
      ),
      3 =>
      array (
        'file' => '.../local/o365/classes/feature/coursesync/utils.php',
        'line' => 773,
        'function' => 'add_member_to_group',
        'class' => 'local_o365\\feature\\coursesync\\main',
        'type' => '->',
      ),
      4 =>
      array (
        'file' => '.../local/o365/classes/observers.php',
        'line' => 430,
        'function' => 'sync_user_role_in_course_group',
        'class' => 'local_o365\\feature\\coursesync\\utils',
        'type' => '::',
      ),
      5 =>
      array (
        'function' => 'handle_user_enrolment_updated',
        'class' => 'local_o365\\observers',
        'type' => '::',
      ),
      ...
    )

**Comment by weilai-irl** [comment]
Hi @jonof

Thank you for reporting the issue.

I acknowledge the issue. I have provided a solution in the PR linked to the issue. They will be tested and included in the next release.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @jonof 

The fix to the issue has been included in release [4.1.6](https://github.com/microsoft/o365-moodle/releases/tag/v20240412_m401), [4.2.5](https://github.com/microsoft/o365-moodle/releases/tag/v20240412_m402) and [4.3.3](https://github.com/microsoft/o365-moodle/releases/tag/v20240412_m403) from today. You can download them from [Moodle plugin directory](https://moodle.org/plugins/) and test them out.

I'll mark the issue as closed for now. Please feel free to reopen the issue if it's not resolved.

Regards,
Lai
