### ISSUE TITLE
Invalid field definition in table {local_o365_course_request}: XMLDB_TYPE_INTEGER field "courseid" has invalid default

### ISSUE THREAD

**Issue by montanae** [microsoft/o365-moodle#2528]
Hi,

I tried to install local_o365 4.1.4 (2022112825) on Moodle 4.1.9+ and had this error during the database upgrade:

Invalid field definition in table {local_o365_course_request}: XMLDB_TYPE_INTEGER field "courseid" has invalid default

I modified the local/o365/db/install.xml file and replaced 
<FIELD NAME="courseid" TYPE="int" LENGTH="10" NOTNULL="false" DEFAULT="null" SEQUENCE="false"/>
with 
<FIELD NAME="courseid" TYPE="int" LENGTH="10" NOTNULL="false" DEFAULT="0" SEQUENCE="false"/>

at line 200 and the install worked fine

This is not a durable solution for me, I would like to know if there is another way to fix this

Thanks

**Comment by weilai-irl** [comment]
Hi @montanae 

I acknowledge the issue. We will publish an emergency release to fix it. It will be available in the next 1-2 days.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @montanae 

We have made a new release of the local_o365 which contains the fix to the issue. Please check it out from https://moodle.org/plugins/local_o365 and try it out.

Regards,
Lai

**Comment by montanae** [comment]
Hi,
the problem is solved, I have been able to install the plugin

Thank you

**Comment by weilai-irl** [comment]
@montanae 

Thank you for your confirmation. And thank you for reporting the issue in the first place.

Regards,
Lai
