### ISSUE TITLE
local_o365 unit test errors in 3.5

### ISSUE THREAD

**Issue by danmarsden** [Microsoft/o365-moodle#253]
1) local_o365_webservices_onenoteassignment_testcase::test_assignment_read
Creating default object from empty value

/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:165
/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:249
/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:292
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "local_o365_webservices_onenoteassignment_testcase" local/o365/tests/webservices_onenoteassignment_test.php

2) local_o365_webservices_onenoteassignment_testcase::test_assignment_update
Creating default object from empty value

/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:165
/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:341
/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:459
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "local_o365_webservices_onenoteassignment_testcase" local/o365/tests/webservices_onenoteassignment_test.php

3) local_o365_webservices_onenoteassignment_testcase::test_assignment_delete
Creating default object from empty value

/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:165
/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:510
/var/www/html/local/o365/tests/webservices_onenoteassignment_test.php:532
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

**Comment by jamesmcq** [comment]
Thanks @danmarsden - I've merged your pull request and scheduled for next release. Appreciate it!

**Comment by jamesmcq** [comment]
This has been released. Thanks for the contribution!
