### ISSUE TITLE
master branch is stale

### ISSUE THREAD

**Issue by danmarsden** [Microsoft/o365-moodle#254]
Looks like the "master" branch is stale and quite a few changes are in the STABLE/DEV branches that aren't in the main master branch.

if "master" is not in use I'd suggest deleting it from the repo - otherwise people will be looking for the latest code and getting an old branch instead.

**Comment by jamesmcq** [comment]
@danmarsden Thanks for the heads-up, I've updated master. Work generally gets done in the STABLE branches but it's nice to have master as the newest version for the newest version of Moodle.

**Comment by danmarsden** [comment]
Hi @jamesmcq If you're not really using the master branch it would probably be better to delete the branch completely otherwise you'll end up with people doing dev in the wrong place or not remembering to update it again.
