### ISSUE TITLE
Moodle app tab name in teams

### ISSUE THREAD

**Issue by chemamss** [microsoft/o365-moodle#2542]
Hi, I have Moodle sync with Microsoft Teams, so when I create a class in Moodle a teams team is created with a tab that links directly to the Moodle class. The default tab name that is set is Moodle, as shown in the picture attached:

![image](https://github.com/microsoft/o365-moodle/assets/165811219/8e5b8118-9d5d-4c55-9cb0-ff5861d3c4e8)

What I would like is that name to appear 'Online Class' instead of 'Moodle' by default.How can I make that happen? I don't want to go team by team changing the name manually.

**Comment by weilai-irl** [comment]
Hi @chemamss 

Currently you can customise the language string "tab_moodle" of the local_o365 plugin to make this change. It makes more sense to make this a configuration setting, rather than a language string, so I have made the change the PR.

It will be tested and included in the next release.

Regards,
Lai

**Comment by chemamss** [comment]
> Hi @chemamss
> 
> Currently you can customise the language string "tab_moodle" of the local_o365 plugin to make this change. It makes more sense to make this a configuration setting, rather than a language string, so I have made the change the PR.
> 
> It will be tested and included in the next release.
> 
> Regards, Lai

Hi Lai,
Thanks for starting the implementation. For the moment, where can I edit `tab_moodle'. Thanks.

**Comment by weilai-irl** [comment]
Hi @chemamss 

Please follow documentation at https://docs.moodle.org/404/en/Language_customisation#:~:text=Go%20to%20Site%20administration%20%3E%20Language%20%3E%20Language%20customization.,on%20the%20'Continue'%20button to see how to customise language strings. The string you need to edit is in plugin local_o365, with identifier "tab_moodle".

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @chemamss 

The changes made in relation to this feature request have been included in the latest release of the plugins 4.1.7, 4.2.6 and 4.3.4 from today. Please checkout the latest versions.

I'll mark the issue as closed.

Regards,
Lai
