### ISSUE TITLE
Unable to access Teams Course through LTI Moodle

### ISSUE THREAD

**Issue by JuaniV2002** [microsoft/o365-moodle#2545]
![Screenshot 2024-04-10 at 2 43 15 PM](https://github.com/microsoft/o365-moodle/assets/98132290/2a7df1ef-1431-4c77-b174-7716b2e1a1c2)

Moodle version: 4.3

I view the following article it shows external tool option, however, it's no longer available in the newer version of moodle: https://support.microsoft.com/en-us/topic/use-microsoft-teams-classes-in-your-lms-ac6a1e34-32f7-45e6-b83e-094185a1e78a#ID0EBD&ID0EBD=Instructure_Canvas

There are no issues syncing the members or users between Entra, Teams and Moodle.

I have the HAR file when issue is reproduced

**Comment by nbozhkov-ucl** [comment]
Have you done this step https://support.microsoft.com/en-us/topic/activate-early-access-class-teams-created-by-your-it-admin-0d154696-66ab-4fcf-b22f-c3d9a82aaf78 ?
