### ISSUE TITLE
Creation of dynamic property is deprecated with PHP 8.2+

### ISSUE THREAD

**Issue by opitz** [microsoft/o365-moodle#2547]
To see the issue run a Moodle instance on PHP 8.2 with local_o356 installed.
Log in as admin, set debugging to developer and (try to) open to the plugin overview page.

You will see an error:
`Creation of dynamic property local_o365\adminsetting\tabs::$component is deprecated`
A similar issue appears with ...\tabs::$theme.

This can be fixed by explicitly declaring $component and $theme in the constructor method.

**Comment by weilai-irl** [comment]
Hi @opitz 

Could you paste the full stack trace of the error/warning please? I can't seem to find where the errors would be triggered.

Regards,
Lai

**Comment by weilai-irl** [comment]
@opitz 

Thank you for the updates and providing the solution.

I have created PR for Moodle 4.2 and 4.3, and they will be included in the next release. Moodle 4.1 doesn't support PHP 8.2, so the fix doesn't apply there.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @opitz 

The fix to this issue has been included in release 4.1.7, 4.2.6 and 4.3.4 on 2nd of July 2024.

Thank you again for reporting the issue and providing the solution.

Regards,
Lai
