### ISSUE TITLE
We need o365-joomla plugin for Single Sign-On and Integration

### ISSUE THREAD

**Issue by aboarken** [microsoft/o365-moodle#2548]
Hello @weilai-irl ,

Hope you are doing well. I am sorry to open this issue but I kindly request Microsoft Team to create a similar plugin for Joomla CMS as Joomla 5 and Joomla 6 CMS versions are so promising based on their roadmaps.

We kindly request if similar plugin is created for Joomla CMS and I am ready to involve all Joomla Developers (Contributors) to help achieve this plugin knowing that I am part of the Joomla Community: https://volunteers.joomla.org/joomlers/1709-ahmad-moussa

Looking forward to hearing from you.

Regards,
Ahmad Moussa

**Comment by weilai-irl** [comment]
Hi @aboarken 

Thank you for posting here.

I'm afraid I'm not familiar enough with Joomla as a developer, and I don't have the capacity/availability for any Joomla development. I can't help in case myself unfortunately.

This is an open source project so feel free to point anyone in your community who's interested in taking up the work to this project and reuse the code whereas possible.

Good luck in your project.

Regards,
Lai

**Comment by aboarken** [comment]
@weilai-irl Thank you.
