### ISSUE TITLE
Error setting up integration "Could not get app or system token"

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#2552]
Hi

trying to set up the integration in Moodle 4.1.9. The Entra ID side is configured with necessary permissions but 
we get errors: 

- local_o365\page\ajax::mode_checksetup (unified): Could not get app or system token Data: Array ( [file] => /.../moodle/local/o365/classes/utils.php [line] => 113 [message] => Could not get app or system token )
- local_o365\oauth2\token::instance:103: Cannot retrieve a token for the base resource. Data: (null)
- local_o365\oauth2\apptoken::get_app_token: Problem encountered getting a new token. Data: Array ( [tokenresult] => [resource] => https://graph.microsoft.com )

Could firewall be an issue? Because outpund connections are only opened to https://login.microsoftonline.com/ and https://graph.microsoft.com/

Plugin versions are 4.1.3 (2022112815)

**Comment by kkiiskin** [comment]
@weilai-irl do you have any view on this?

**Comment by weilai-irl** [comment]
Hi @kkiiskin 

It looks like the error suggesting the integration cannot get a token from the configured token endpoint. Assuming the token endpoint configured is in the https://login.microsoftonline.com/ domain, allowing outgoing traffic to it should be enough to get a token. There is no request to other domains AFAIK in this process. Requests to https://graph.microsoft.com/ should only be made after an application token is fetched and stored successfully.

The request to get token is made at https://github.com/microsoft/o365-moodle/blob/cff3d937b6bbd5f8971351562ddddf0b28bdc6bc/local/o365/classes/oauth2/token.php#L168. I'd suggest you printing the parameters and return values of this function call and try to work out what went wrong.

Hope this helps. 

Regards,
Lai
