### ISSUE TITLE
local_o365 unit test failures in 3.5 (part 2)

### ISSUE THREAD

**Issue by danmarsden** [Microsoft/o365-moodle#256]
1) local_o365_observers_testcase::test_user_disconnected
Failed asserting that true is false.

/var/www/html/local/o365/tests/observers_test.php:55
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "local_o365_observers_testcase" local/o365/tests/observers_test.php

2) local_o365_observers_testcase::test_user_deleted
Failed asserting that true is false.

/var/www/html/local/o365/tests/observers_test.php:67
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "local_o365_observers_testcase" local/o365/tests/observers_test.php

**Comment by danmarsden** [comment]
I think this is because the observers for \auth_oidc\event\user_disconnected and \core\event\user_deleted have internal set to false and the unit tests are being run within a transaction.

**Comment by jamesmcq** [comment]
Thanks @danmarsden - I've merged this into an issue branch and scheduled for next release. Appreciate it!

**Comment by jamesmcq** [comment]
This has been released. Thanks for the contribution!
