### ISSUE TITLE
Running \local_o365\task\usersync Error

### ISSUE THREAD

**Issue by nbozhkov-ucl** [microsoft/o365-moodle#2561]
Trying to run \local_o365\task\usersync with Moodle 4.3.4+ and lastest versions 4.3.3 2023100915  of the auth/oidc and local/o365 plugin for a first time i.e. an instance where users are not matched or synced with Entra results with the following error after around 24-25 hours or running. Note we sync around 500k users.

`Stack trace:
#0 /data/apache/htdocs/moodle/SNAPSHOT_43-1881/lib/dml/mysqli_native_moodle_database.php(1394): mysqli_native_moodle_database->emulate_bound_params('SELECT RELEASE_...', Array)
#1 /data/apache/htdocs/moodle/SNAPSHOT_43-1881/lib/dml/moodle_database.php(1683): mysqli_native_moodle_database->get_records_sql('SELECT RELEASE_...', Array, 0, 0)
#2 /data/apache/htdocs/moodle/SNAPSHOT_43-1881/lib/classes/lock/mysql_lock_factory.php(144): moodle_database->get_record_sql('SELECT RELEASE_...', Array)
#3 /data/apache/htdocs/moodle/SNAPSHOT_43-1881/lib/classes/lock/lock.php(100): core\lock\mysql_lock_factory->release_lock(Object(core\lock\lock))
#4 /data/apache/htdocs/moodle/SNAPSHOT_43-1881/lib/classes/lock/lock.php(114): core\lock\lock->release()
#5 [internal function]: core\lock\lock->__destruct()
#6 {main}
  thrown in /data/apache/htdocs/moodle/SNAPSHOT_43-1881/lib/dml/mysqli_native_moodle_database.php on line 1265`

Has anyone else experienced similar error?

**Comment by Bala0909** [comment]
I am also Experiencing the same..

**Comment by nbozhkov-ucl** [comment]
Thanks @weilai-irl for your reply.

What did resolve the issue for us were the following changes:

1)set php memory_limit setting to 3072M
2) add $CFG->lock_factory = "\\core\\lock\\db_record_lock_factory"; in config.php as we were getting task lock error after setting 1).

The task now takes from 55 minutes to 1h 17minutes depending on how many new users it has to create.
