### ISSUE TITLE
Are the following plugins still maintained ?

### ISSUE THREAD

**Issue by owngr** [microsoft/o365-moodle#2585]
Hello,

I couldn't help but notice that the following repositories have been archived:

- https://github.com/Microsoft/moodle-repository_office365
- https://github.com/Microsoft/moodle-auth_oidc
- https://github.com/microsoft/moodle-assignfeedback_onenote
- https://github.com/microsoft/moodle-assignsubmission_onenote

Does it mean that they won't get any updates any more?

We rely on submodules to add your plugins to our customers, and therefore the actual repository structure with a single repo per plugin is really helpful for us.

**Comment by weilai-irl** [comment]
Hi @owngr 

I can confirm they are still maintained.

I have confirmed the the repositories were not archived by anyone on the maintainers team. The repositories are owned by Microsoft, and we are trying to find out if this was done on their end.

Rest assured, the plugins are still actively maintained.

Regards,
Lai

**Comment by owngr** [comment]
Hi @weilai-irl ,

Thanks a lot for the prompt answer.

Regards,
Olivier
