### ISSUE TITLE
SDS Sync: Allow unenrolment of users during membersync if removed from SDS course.

### ISSUE THREAD

**Issue by kenneth-hendricks** [microsoft/o365-moodle#259]
Hi all,

I realize this is still a preview feature and development is not yet complete, however it would be great if the ability to allow unenrolments to automatically occur when users are removed from a SDS course was implemented. 

Something to bear in mind for your road map. 

Thanks,
KC

**Comment by jamesmcq** [comment]
Hi @kenneth-hendricks - thanks for the suggestion, I've made a note for the SDS roadmap.

**Comment by cbrherms** [comment]
I'd also like to +1 this request.

**Comment by bradnielsen2981** [comment]
I actually got a Moodle Partner Catalyst to make this change. It might be worth asking them about it.

The changes were as follows:

  1.  Teachers are never suspended
  2.  Students who disappear from the SDS have their Moodle Enrolment Suspended
  3.  Students who reappear in the SDS have their Moodle Enrolment Unsuspended

The only thing I found was the if Office 365 Course syncing is turned on, if you add or remove students, it messes with the SDS. I also found that once a Moodle Course Group has been synced with an Office 365 Group, it doesnt turn off when you click Custom in Syncing, an uncheck the box.

cheers,
Brad



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by weilai-irl** [comment]
Hi all,

I confirm this feature is already implemented in the latest December 2021 release of the plugins for Moodle 3.9, 3.10 and 3.11.

Please checkout the latest version for this feature.

Regards,
Lai
