### ISSUE TITLE
moodle-auth_oidc - Creation of dynamic property is deprecated with PHP 8.2+ 

### ISSUE THREAD

**Issue by steveorulez** [microsoft/o365-moodle#2594]
Hello,
we just upgraded Moodle from 4.1 to 4.3 with the latest auth_oidc plugin installed (4.3.3 - 2023100915) on a test server and this message appear with debugging activated on DEVELOPER when you visit https://moodlesiste.com/auth/oidc/

Deprecated: Creation of dynamic property auth_oidc\oidcclient::$scope is deprecated in /path/auth/oidc/classes/oidcclient.php on line 93

There is no blocking error, just a message.

It's the same issue that was fixed #2547

have a nice day
christian

**Comment by steveorulez** [comment]
An easy fix is to declare it at the beginning of the class oidcclient on line 57 of the file classes/oidcclient.php

/** @var string The scope. */
protected $scope;

christian

**Comment by rafaelatopen** [comment]
Hello, 
the same deprecation can be found in blocks/microsoft/block_microsoft.php line 43. Reporting here instead of creating a new issue to avoid spamming.
Thx.

**Comment by weilai-irl** [comment]
Hi @steveorulez 

The fix to the issue has been included in the release from yesterday. Thank you again for reporting the issue.

Regards,
Lai
