### ISSUE TITLE
Moodle Smartphone App

### ISSUE THREAD

**Issue by edgarronceroblanco** [microsoft/o365-moodle#2599]
Hello, Is it possible to authenticate the Moodle App using OpenID Connect? Because I don't see the icon/login method.

**Comment by AntonT76** [comment]
Hi,

as far as I know, it is not possible to use OIDC directly in the Moodle app. But in the Moodle backend you can configure the login via (external) browser. Then it should work.

Open: Moodle Administration - General - Mobile app - Mobile authentication
set: Type of Login = via a browser window (for SSO Plugins)

hope, this will help
br, Anton
