### ISSUE TITLE
Remove Temporary Write Access From Controlled Links - Task Fails

### ISSUE THREAD

**Issue by aboarken** [microsoft/o365-moodle#2608]
Please I am getting this task error after updating Moodle 4.4.1+ (Build: 20240719) and plugin to latest version. Kindly for your support.

Execute scheduled task: Remove temporary write access from controlled links (repository_onedrive\remove_temp_access_task)
... started 09:05:39. Current memory use 21.9 MB.
Debugging increased temporarily due to faildelay of 86400
... used 2 dbqueries
... used 0.01578688621521 seconds
Scheduled task failed: Remove temporary write access from controlled links (repository_onedrive\remove_temp_access_task),Can't find data record in database table oauth2_issuer. (SELECT * FROM {oauth2_issuer} WHERE id = ?
[array (
  0 => 1,
)])
Debug info:
SELECT * FROM {oauth2_issuer} WHERE id = ?
[array (
  0 => 1,
)]
Backtrace:
* line 1635 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 461 of /lib/classes/persistent.php: call to moodle_database->get_record()
* line 57 of /lib/classes/persistent.php: call to core\persistent->read()
* line 137 of /lib/classes/oauth2/api.php: call to core\persistent->__construct()
* line 65 of /repository/onedrive/classes/remove_temp_access_task.php: call to core\oauth2\api::get_issuer()
* line 410 of /lib/classes/cron.php: call to repository_onedrive\remove_temp_access_task->execute()
* line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()

**Comment by justrunis** [comment]
Hey, [aboarken](https://github.com/aboarken) have you managed to find a solution for this problem because i am also having the same issue?

**Comment by asi-jake** [comment]
I have been having this same issue for a little while now as well. With all of the research into this, I have found many supposed solutions that don't have any effect. The only workaround I've come up with is to disable the OneDrive integration altogether. It's not ideal, but it's the only thing I've come up with so far until a real solution is found.

**Comment by nsheehan** [comment]
This has popped up on one of my sites as well. The message doesn't provide much to go on. Site is running 4.4.2+ wasn't having this issue with 4.3.x

Cheers

**Comment by weilai-irl** [comment]
Hi all,

The issue reported here is for repository_onedrive, which is a part of Moodle core. It's different from the repository_office365 delivered as part of this project. Please use the main Moodle tracker (https://tracker.moodle.org/) to report core Moodle issues.

Regards,
Lai
