### ISSUE TITLE
Open ID Settings form icons are loaded incorrectly in Boost

### ISSUE THREAD

**Issue by guillalva06** [Microsoft/o365-moodle#261]
Some icons that are loaded in the settings form for the Open ID plugin are not rendered correctly in Boost. I have found that the icons on folder t/ (i.e  t/approve, t/more) are different from the icons stored on /pix/t folder at the settings page. One example is t/go icon is displayed in settings page as a gray square instead of a green circle.

This is a problem because the icon is renderer correctly in the login page but it is not consistent with the representation that the admin user choose in the settings form. So, the admin user chose the gray square but he will see the green circle in its login view. This problem is not present in the clean theme.

A possible solution is change line 96 in /auth/oidc/classes/form/adminsetting/iconselect.php file from:

`$iconhtml = $OUTPUT->pix_icon($icon['pix'], $icon['alt'], $icon['component']);`

to

`$iconhtml = $OUTPUT->image_icon($icon['pix'], $icon['alt'], $icon['component']);`

This way, the plugin is getting the right html for all icons on settings page independent of which theme is been used in the platform.

**Comment by jamesmcq** [comment]
Hi @guillalva06 - thanks for the report! You're correct, the change you proposed solves the problem. If you'd like credit (i.e. a commit in the plugin history), feel free to submit a pull request - otherwise I'll make the change and include it in the next release.

**Comment by jamesmcq** [comment]
This should now be resolved in the latest release. Thanks!
