### ISSUE TITLE
Owner removal check incorrect when role is removed from user

### ISSUE THREAD

**Issue by darius-m** [microsoft/o365-moodle#2614]
When a user's role assignment is changed, the plugin currently checks whether the user is currently an owner of the team using [in_array](https://github.com/microsoft/o365-moodle/blob/master/local/o365/classes/feature/coursesync/utils.php#L797) to determine whether the user has been demoted to a normal member (e.g. transitioned from a teacher to student).

However, the `get_group_owners` function returns an associative array in the form `{ "userid_1": user_representation_1, "userid_2": user_representation_2 }`, so the check using `in_array` always returns false. Since the user IDs are the keys of the array, the function should instead use `array_key_exists`.

**Comment by weilai-irl** [comment]
Hi @darius-m 

Thank you for reporting the issue. The fix to it has been included in the release from yesterday. Please check it out.

Regards,
Lai
