### ISSUE TITLE
Azure AD fields in mapping screen of local Microsoft 365 intergration

### ISSUE THREAD

**Issue by albertramsbottom** [Microsoft/o365-moodle#262]
Are these static? As we need to map the Student ID from Azure AD through to Student ID in Moodle. At the moment it OpenID Connect brings through the email address of the student and this is causing major issues with Moodle and Mahara

Cheers

**Comment by jamesmcq** [comment]
These are configurable in the "Sync options" tab on the local plugin settings page - see heading "User Field Mapping".
