### ISSUE TITLE
Call Graph API function to update user details is skipped (caused by a bad get_config call?) 

### ISSUE THREAD

**Issue by jayuqar** [microsoft/o365-moodle#2624]
Hi!

We updated our Moodle a couple of months ago and have just realized that certain fields in user profiles are no longer updating when they log in.

Here our setup **_before_** the update : 
Moodle 4.1.3 (Build: 20230424)
Plugin local_o365 4.1.1 (2022112805)
Plugin auth_oidc 4.1.1 (2022112805)

And **_after_** the update :
Moodle 4.3.5+ (Build: 20240614)
Plugin local_o365 4.3.3 (2023100915)
Plugin auth_oidc 4.3.3 (2023100915)

We also have a test environment that is updated more regularly:
Moodle 4.3.6+ (Build: 20240821)
Plugin local_o365 4.3.5 (202310092)
Plugin auth_oidc 4.3.4 (2023100920)

I’m fairly certain the synchronization was working correctly before the update, but now it’s not working in both our test and production environments.

After investigating, I think I may have found the root of the issue.

This line : 
https://github.com/microsoft/o365-moodle/blob/591e1debc7ce7f97129d06e3c3b28cbe369e47c2/auth/oidc/classes/loginflow/base.php#L127

was modified in December 2023:
![image](https://github.com/user-attachments/assets/d21e22db-6cbc-4bdf-992f-c68367ebe63e)

The commit in question :
[https://github.com/microsoft/o365-moodle/commit/9f84a45cdd5c14ed612d8f0cfa74650108b57b83](https://github.com/microsoft/o365-moodle/commit/9f84a45cdd5c14ed612d8f0cfa74650108b57b83)

If I understand this code correctly, it compares the value of the configuration “microsofttenantid” with the tenant ID of the currently used token. If they are not the same, it assumes the user is from another tenant and synchronizes only the fields contained in the token (UPN, first name, last name, email). If the tenant IDs are the same, a call is made to the Graph API to retrieve more fields to sync in the Moodle user profile (e.g., city, department, etc.):
 
![image](https://github.com/user-attachments/assets/b7340c03-4514-494b-b423-9c8a284d368c)

I realized that the call to the Graph API is never made because get_config('local_o365', 'microsofttenantid') always returns an empty value. I checked our mdl_config_plugin table, and this configuration ('local_o365', 'microsofttenantid') does not exist:
![image](https://github.com/user-attachments/assets/242f6fbf-cdc2-4bc1-9f60-601b121b5f29)

Is it possible that this line (L127 of base.php) should be:
$hostingtenantid = get_config('local_o365', '**entra**tenantid');
instead of 
$hostingtenantid = get_config('local_o365', '**microsoft**tenantid');

Thanks **so much**!

**Comment by Syxton** [comment]
This seems like a clear and obvious issue. +1

**Comment by weilai-irl** [comment]
Hi @jayuqar 

Thank you for reporting the issue. The fix to the issue has been included in the release from yesterday. Please check it out.

Regards,
Lai

**Comment by jaysarf** [comment]
Thanks so much, @weilai-irl !
I'll be back at work in a couple of weeks, I'll test that and keep you posted once it's done ! :)

**Comment by jayuqar** [comment]
Thanks so much, @weilai-irl !
I'll be back at work in a couple of weeks, I'll test that and keep you posted once it's done ! :)

Sincerely,
Jay
