### ISSUE TITLE
Moodle OIDC plugin with Keycloak - limited number of external fields for mapping

### ISSUE THREAD

**Issue by volver-13** [microsoft/o365-moodle#2626]
Hello,

We are running an Angular based website with KeyCloak for authentication and then using SSO with OIDC to seamlessly access Moodle.

We managed to configure SSO for Moodle but we're having issues with external fields for the mapping. When trying to setup the mapping ( OpenID Connect -> Field mappings) only the following fields can be set: Object ID, Username (UPN), Given name, Surname, Email. We would like to configure the mapping for the country which is available as a claim in the token.

![image](https://github.com/user-attachments/assets/748ca145-7165-45e6-8774-ae5960f812f8)

@weilai-irl would you be able to help with this?

KeyCloak 21.1.2
Moodle 4.3.1 
auth_oidc | 4.3.4

Would be great to improve the documentation as it seems to be centered around Microsoft EntraID/AD and has a really poor coverage for any other OIDC provides.

**Comment by weilai-irl** [comment]
Hi @volver-13 

When you use the "Other" IdP type to connect to non-Microsoft IdPs such as KeyCloak, the remote fields available for sync is limited to those defined in the OpenID Connect standard, which should be implemented by all IdP following the standard. Adding any other option to the list would be technically incorrect and misleading. Therefore fields cannot be added to the release version of the plugin.

However, you can create and maintain local patches with any value you want to add, as long as they present in the token claims. New items can be added after https://github.com/microsoft/o365-moodle/blob/820d5250ce98c611fa4fd571d17dec269007daa7/auth/oidc/lib.php#L306. 

Hope this helps.

Regards,
Lai

**Comment by volver-13** [comment]
Hi @weilai-irl 

Please correct me if I'm wrong but there's the list of standard claims:
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
which is longer than what's available in the oidc plugin

**Comment by vaustinov-collab** [comment]
Faced with the same problem. Please tell me how to create a local patch to add the necessary fields that are present in the token (quid, department, title, student_group)
