### ISSUE TITLE
Sync issue with pictures

### ISSUE THREAD

**Issue by usmlit** [Microsoft/o365-moodle#263]
For the "Sync Office 365 profile photos to Moodle in cron job " is the photo coming down from Azure into Moodle or the other way around?

We are getting:
Syncing user ealbert@usml.edu
Could not assign profile photo to user "ealbert@usml.edu" Reason: Could not refresh token
Found a user in Azure AD that seems to match a user in Moodle
moodle username: ealbert, aad upn: ealbert@usml.edu
User is already matched.

**Comment by jamesmcq** [comment]
@usmlit This sync option copies the profile photo from Azure into Moodle. Looking at the logs, it looks like this is a brand new user, correct? i.e. this sync process was both attempting to sync the profile photo and match the user at the same time?

**Comment by jamesmcq** [comment]
@usmlit The latest release resolved some issues with profile photo syncing, likely what you were experiencing here. I'm going to close this issue as resolved by the last release, but please open a new issue if you continue to experience problems. Thanks!
