### ISSUE TITLE
function get_enabled_courses(), error in code

### ISSUE THREAD

**Issue by pmatabiau** [microsoft/o365-moodle#2631]
hi,
I think there are a error here :
[classes/feature/coursesync/utils.php](https://github.com/microsoft/moodle-local_o365/blob/master/classes/feature/coursesync/utils.php), function get_enabled_courses : 
```
            $coursesenabled = get_config('local_o365', 'coursesynccustom');
            $coursesenabled = @json_decode($coursesenabled, true);
            if (!empty($coursesenabled) && is_array($coursesenabled)) {
                $changed = false;
                $courseids = array_keys($coursesenabled);
                foreach ($courseids as $courseid => $value) {
                    if (!$DB->record_exists('course', ['id' => $courseid])) {
                        unset($coursesenabled[$courseid]);
                        $changed = true;
                    }
                }
```
coursesynccustom is like `{"405":true,"409":true,"417":true,"437":true}`
We have an _array_keys()_, so `$courseids` is an array of ids. But the _foreach_ use `$courseid => $value`, so the ids is in `$value`, not in `$courseid`.
Fix : maybe change the _foreach_ like 
`foreach ($courseids as $courseid) `
OR
replace `$courseid` by `$value` every where inside this _foreach_.

**Comment by weilai-irl** [comment]
Hi @pmatabiau 

Thank you for reporting the issue and solution. I have included in the fix in the latest release from yesterday.

Regards,
Lai
