### ISSUE TITLE
SSO issues when signing into Microsoft 365 | Teams Moodle App

### ISSUE THREAD

**Issue by dhirajr69** [microsoft/o365-moodle#2633]
Good day, 

We have issues when we try to add the App to Teams channel. We see the sign in Options 'Login to Microsoft 365' however when we select this option a window pops up and nothing happens, this window stays open until manually closed. 
When we close this, we are presented with the ScholarLMS log in window. We then select the 'OpenID Connect' the screen just refreshes we receive no error. 

Could this be related to Microsoft Teams, ScholarLMS or the Moodle app manifest? 
Microsoft Teams Version: 24231.512.3106.6573
Client Version: 49/24081700419

Moodle app manifest version: 1.3

**Comment by weilai-irl** [comment]
Hi @dhirajr69 

I'd recommend you reaching out to the ScholarLMS support team about this issue. AFAIK ScholarLMS is based on Moodle but there are many additions on top of it. The Microsoft plugins are designed to work with standard Moodle installation, therefore may not be fully compatible with ScholarLMS.

Regards,
Lai
