### ISSUE TITLE
Error in API call: Specified $skiptoken is invalid

### ISSUE THREAD

**Issue by yousrifarouk** [Microsoft/o365-moodle#264]
Moodle Ver. 3.3:

I have been suffering from below error since last Thursday, when i try to sync Moodle users with Azure active directory :

php /data/admin/tool/task/cli/schedule_task.php --execute=\\local_o365\\task\\usersync --showdebugging

Scheduled task failed: Sync users with Azure AD. (local_o365\task\usersync),Error in API call: Specified $skiptoken is invalid.
Backtrace:
* line 387 of /local/o365/classes/rest/azuread.php: call to local_o365\rest\o365api->process_apicall_response()
* line 220 of /local/o365/classes/feature/usersync/main.php: call to local_o365\rest\azuread->get_users()
* line 81 of /local/o365/classes/task/usersync.php: call to local_o365\feature\usersync\main->get_users()
* line 146 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\usersync->execute()

any help please?

**Comment by zckb** [comment]
@yousrifarouk - Can you review issue #258 and confirm/reject as a duplicate to the issue you are raising here? If duplicate, then you may use the temporary workaround described in #258 or wait for the fix to be available in the next release.

**Comment by henhell** [comment]
I have the exact same problem, tried the "solution" in #258, sadly without success.

**Comment by henhell** [comment]
My quick fix for this is in pull request #268

**Comment by yousrifarouk** [comment]
thanks @henhell for your reply

**Comment by zckb** [comment]
@henhell - Thanks for the PR. @jamesmcq - Can you confirm if the fix for this issue will be included in the next release?

**Comment by yousrifarouk** [comment]
@zckb @henhell 
it is working thanks you so much.
