### ISSUE TITLE
Urgent Help: O365 passing different email domain for the user in the user object? Or other issue?

### ISSUE THREAD

**Issue by teddielong** [microsoft/o365-moodle#266]
Hi everyone

We're trying to implement Open ID Connect with AD for a client, but have hit a bit of a snag.

We are auto assigning users based on their email domain - .e.g if a user if john@example.com, it will automatically place him in Example Group.  However, we think O365 is passing a different email domain for the user in the user object - e.g. maybe it is prepended with a microsoft domain or perhaps passing across the username of john123 instead of john@example.com?

This is causing the domain to mismatch and then resulting in them not being allocated appropriately.  

Is there a way we can better understand what information AD is passing and a possible workaround for this solution?

**Comment by teddielong** [comment]
As a lay-person, with minimal understanding, perhaps someone could explain how the permissions actually work (e.g. does "read and write" access mean that technically our Moodle can edit the data contained within the AD - as this would be a big no no for us).

If we're solely trying to achieve user details sync between the AD and Moodle via the OpenID Connect plugin, would the following in bold only be ok or would it be too restrictive?  Or, indeed, could it be restricted further? 

Application Permissions:
Read and write domains
**Read and write all users' full profiles**
Read and write all OneNote notebooks
**Read and write all groups
Read directory data**
Read and write calendars in all mailboxes
Read and write files in all site collections

Delegated Permissions:
Read and write all OneNote notebooks that user can access
**Sign in and read user profile
Read and write all users' full profiles
Read and write all groups
Read and write directory data
Access directory as the signed in user**
Have full access to user calendars
Have full access to user files
Read items in all site collections
**Sign users in**

**Comment by zckb** [comment]
@teddielong - In Office 365, are User Principal Names (UPN) different from user email addresses?

**Comment by jamesmcq** [comment]
Closing this issue since it's been around for a while without any new information. If there's still an issue or you need any further assistence, please open a new issue. Thanks!
