### ISSUE TITLE
Teams Meetings LTI iframe does not show meeting recordings anymore

### ISSUE THREAD

**Issue by stmpk** [microsoft/o365-moodle#2673]
Hi,

We're using Moodle LTS 4.1.12 (Build: 20240812) with Teams Meetings LTI enabled. 

OpenID Connect auth_oidc version  4.1.7202211283

Microsoft 365 Integration local_o365 version  4.1.82022112836 are installed.

 Teams iframe used to look like this in classes, recordings were shown under meetings on calendar.

<details><summary>Before</summary>
<p>

![Image](https://github.com/user-attachments/assets/f3d58a54-87de-4e83-85ae-5dd56b739d8b)

</p>
</details> 

Now no recordings are shown under meetings. Neither teachers nor students can see the recordings from the iframe.

<details><summary>After</summary>
<p>
![Image](https://github.com/user-attachments/assets/658c7d64-4305-469f-bee5-d5e644a28e36)

</p>
</details> 

I did inspect the page code after reloading iframe in MS Edge browser, Console tab had a massive error list. here's the error log copied from console tab  [teams iframe console log.txt](https://github.com/user-attachments/files/17308693/teams.iframe.console.log.txt) 

We did not change any setting from Moodle side. 

 We've changed teams settings on teams admin side, organizational policies to enable lobby in meetings, and changed who will bypass lobby setting to "only organizers and co-organizers" so students can't start meetings before teachers. How can we check why meeting recordings are not shown in iframe?

P.S. somehow after image is not loading,[ here's imgur link ](https://i.imgur.com/W1H5Flp.png)

**Comment by weilai-irl** [comment]
Hi @stmpk 

I didn't look into technical details, but from the look of it, this is an issue in the content of the iframe, which is 100% controlled by the Teams LTI feature. As long as the LTI tool is displayed, Moodle and its plugins don't have any control over the iframe content.

You may want to report the issue to the Teams LTI part of the Microsoft community, which linked at the bottom of the page at the link https://support.microsoft.com/en-us/topic/use-microsoft-teams-meetings-in-your-lms-11b6095d-f90b-42b9-ab77-4dcff2bb3b76. 

Regards,
Lai

**Comment by stmpk** [comment]
Thanks, 

We'll try to reach TeamsLTI support on Microsoft.
