### ISSUE TITLE
Release for Moodle 4.5 LTS

### ISSUE THREAD

**Issue by michael-milette** [microsoft/o365-moodle#2689]
Good day,

When do you think we can expect to see a release for Moodle 4.5 LTS?

Best regards,

Michael Milette

**Comment by patmr7** [comment]
Hi Michael,

The new release is now available. New versions can be found both in the MOODLE_405_STABLE branch and in the Moodle Plugins directory:

- [OpenID Connect](https://moodle.org/plugins/auth_oidc/4.5.0/34000)
- [Microsoft Block](https://moodle.org/plugins/block_microsoft/4.5.0/34001)
- [Microsoft 365 Integration](https://moodle.org/plugins/local_o365/4.5.0/34002)
- [Microsoft 365 Integration (shell plugin)](https://moodle.org/plugins/local_office365/4.5.0/34004)
- [Microsoft OneNote](https://moodle.org/plugins/local_onenote/4.5.0/34003)
- [OneNote Feedback](https://moodle.org/plugins/assignfeedback_onenote/4.5.0/34008)
- [OneNote submissions](https://moodle.org/plugins/assignsubmission_onenote/4.5.0/34007)
- [Microsoft 365 Repository](https://moodle.org/plugins/repository_office365/4.5.0/34005)
- [Microsoft 365 Teams Theme](https://moodle.org/plugins/theme_boost_o365teams/versions)

Each plugin also has a separate GitHub repository:

- [OpenID Connect](https://github.com/microsoft/moodle-auth_oidc)
- [Microsoft Block](https://github.com/microsoft/moodle-block_microsoft)
- [Microsoft 365 Integration](https://github.com/microsoft/moodle-local_o365)
- [Microsoft 365 Integration (shell plugin)](https://github.com/microsoft/moodle-local_office365)
- [Microsoft OneNote](https://github.com/microsoft/moodle-local_onenote)
- [OneNote Feedback](https://github.com/microsoft/moodle-assignfeedback_onenote)
- [OneNote submissions](https://github.com/microsoft/moodle-assignsubmission_onenote)
- [Microsoft 365 Repository](https://github.com/microsoft/moodle-repository_office365)
- [Microsoft 365 Teams Theme](https://github.com/microsoft/moodle-theme_boost_o365teams)

Best Regards,
Patryk
