### ISSUE TITLE
Could not get app or system token

### ISSUE THREAD

**Issue by michael-LTS1** [Microsoft/o365-moodle#269]
OpenID Connect | auth_oidc | 3.5.0.0 | 2018051700
Microsoft Office 365 Integration | local_o365 | 3.5.0.0 | 2018051700
Moodle 3.5.2

New users able to log in correctly however no profile fields are brought across.  Running scheduled tasks "Refresh system API user refresh token" and "Sync users with Azure AD" give below errors.

Refresh system API user refresh token
Execute scheduled task: Refresh system API user refresh token (local_o365\task\refreshsystemrefreshtoken)
... started 09:06:36. Current memory use 32.3MB.
... used 0 dbqueries
... used 0.18127202987671 seconds
Scheduled task failed: Refresh system API user refresh token (local_o365\task\refreshsystemrefreshtoken),Could not get app or system token
Backtrace:
* line 50 of /local/o365/classes/task/refreshsystemrefreshtoken.php: call to local_o365\utils::get_app_or_system_token()
* line 105 of /lib/cronlib.php: call to local_o365\task\refreshsystemrefreshtoken->execute()
* line 297 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 91 of /admin/tool/task/schedule_task.php: call to cron_run_single_task()

Sync users with Azure AD.
Execute scheduled task: Sync users with Azure AD. (local_o365\task\usersync)
... started 09:07:19. Current memory use 32.4MB.
...... Starting sync
...... No skiptoken (full) stored.
...... Forcing full sync.
...... Contacting Azure AD...
...... Error in full usersync: Could not get app or system token
...... Resetting skip and delta tokens.
...... Got response from Azure AD
...... Clearing skiptoken (full) (none received)
...... No users received to sync.
...... Sync process finished.
... used 2 dbqueries
... used 0.2279851436615 seconds
Scheduled task complete: Sync users with Azure AD. (local_o365\task\usersync)

-----------------------------------------------------------------------

Logs from an existing user successfully logging in using o365 credentials.

11 October 2018, 9:05 AM	-	-	System	Microsoft Office 365 Integration	API failure	get_additional_user_info: No token available for system user. Please run local_o365 health check. Data: Array ( [file] => /opt/www/html/local/o365/classes/utils.php [line] => 309 [message] => No token available for system user. Please run local_o365 health check. )

11 October 2018, 9:05 AM	-	-	System	Microsoft Office 365 Integration	API failure	local_o365\oauth2\token::get_for_new_resource: Problem encountered getting a new token. Data: Array ( [tokenresult] => [resource] => https://graph.microsoft.com )

**Comment by jamesmcq** [comment]
@anormore This will be fixed in the next release.

**Comment by anormore** [comment]
Fantastic to hear! I had no choice, we had so many tickets coming in I had to do SOMETHING. Look forward to your next release, whenever it comes :)

**Comment by Bananamoon** [comment]
I'm also having this issue. Is there any fallback we can implement now, until the next release?

**Comment by Richardvi** [comment]
I'm also running in the same problem, latest version.

![sharedscreenshot](https://user-images.githubusercontent.com/5486910/52556416-c6104e80-2dec-11e9-98a5-6d06d977d8c9.jpg)

**Comment by Richardvi** [comment]
We are using Moodle 3.5, Office 365 plugin 3.5.0.0 (2018051700)

We are NOT using the legacy api.

**Comment by michael-LTS1** [comment]
Still getting "Could not check reply url." but does not affect functionality from what I can see, logins are working and sync works fine.  Our problem ended up being server / firewall not the plugin.

**Comment by Bananamoon** [comment]
Just wanted to mention what our issue was: We connected the plugin with a system API user. Apparently permissions changed and we needed to re-activate the account in the plugin.
