### ISSUE TITLE
OneNote Assign submissiontype is mandatory

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#270]
If teachers adds multiple submission types to Assignment, student cannot save the submission 
without adding OneNote submisison, even thought you would expect all the different types to be optional.

**Comment by kkiiskin** [comment]
Hi

is there a fix coming to this issue? Or is this intended behaviour?

**Comment by kkiiskin** [comment]
I have to ask again, is there an explanation for this or a fix?

**Comment by jamesmcq** [comment]
Hi @kkiiskin - sorry I haven't had a comment for you on this, but I am looking into it and will provide more information when I have it. Appreciate you taking the time to report this.

**Comment by Jarvil** [comment]
Hello,

@jamesmcq any progress on this?

**Comment by nenorojas** [comment]
Hi @kkiiskin , @Jarvil,

Can you please try the latest version of the plugin with latest version of Moodle and let us know if this is still an issue?

Regards
