### ISSUE TITLE
Delete option not working in user sync

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#272]
Enabling 'Delete previously synced accounts in Moodle when they are deleted from Azure AD' option in Sync Settings doesn't seem to work.

I created a new user in Azure AD and it was created in Moodle when synced. But when the user was deleted from Azure AD, it stayed in Moodle. The user was deleted from Azure AD firstly with 'Delete user' from 'All users' view, then with 'Delete permanently' from 'Deleted users' view. Sync was run in between and after, nothing happend to the Moodle-user.

I have 3.5.0.0 -versions of both auth_oidc and local_365 on Moodle 3.5.1

**Comment by jamesmcq** [comment]
Hi @kkiiskin - are you able to provide the cron logs for the user sync task that would delete the users?

**Comment by joshwillcock** [comment]
Hello @jamesmcq,

I am having a similar issue, could you tell me exactly where in the task the user deletion process is? Currently I can only see something in the test and not the actual tasks?

Thanks

Josh

**Comment by jamie-biddulph** [comment]
The same issues as the OP are still occuring with version 3.5.0.3 of local_o365 & auth_oidc with Moodle version 3.5.5.

**Comment by jamesmcq** [comment]
@jamie-biddulph - are you able to provide the cron logs for the user sync task?

**Comment by jamie-biddulph** [comment]
@jamesmcq - Sorry for the delay. I've attached the log of the scheduled task ( \local_o365\task\usersync).

As you'll see it doesn't process any deletions. I've taken a look at the [usersync](https://github.com/microsoft/o365-moodle/blob/a03afb52dec5d231d78f445ea1ba57ed864ea20b/local/o365/classes/task/usersync.php) file but cannot see a delete function.

[local_o365_usersync_log.txt](https://github.com/microsoft/o365-moodle/files/3339619/local_o365_usersync_log.txt)

**Comment by jamesmcq** [comment]
Thanks @jamie-biddulph - looking into it.

**Comment by Fehler12** [comment]
Same issue here. If you need any further logs please notify me.

**Comment by kkiiskin** [comment]
Hi @jamesmcq, is there any progress on this?

Seems that when user is marked as deleted in Azure AD, it doesn't come at all to Moodle. 
So when the code tests for aad.isDeleted, there isn't any users that would match.

**Comment by haiksu** [comment]
Any progress on this issue?

**Comment by Nab59** [comment]
Hi 
I am on Moodle 3.8.2 with all plugin updated but facing this issue.

Any updates ??

**Comment by nenorojas** [comment]
Hi, 

Just to let you know that James is not maintaining the plugins anymore. I've included this case in our queue to be investigated soon.  

Regards

**Comment by avegys** [comment]
Hi all,

Thank you all for your input. New version of the local_o365 was released with updated users deletion feature for Moodle 3.7 and Moodle 3.8. Please update your plugins and the issue should be gone.
Deleted users who are in the deleted users list in Azure will be suspended. Those users who are permanently deleted from Azure, first of all will be suspended with the first usersync scheduled task run (if they were not yet) and with the next usersync scheduled task run those suspended users will be deleted from Moodle.
By default this scheduled task runs once a day at 1 am. In such case, permanently deleted users first will be suspended if they  were not suspended yet and suspended users will be deleted from Moodle.

Best regards,
Andrius

**Comment by Nab59** [comment]
Hi 
We have updated our plugins and now we have the following error

Sync users with Azure AD.
Execute scheduled task: Synchroniser des utilisateurs avec Azure AD. (local_o365\task\usersync)
**Cannot obtain task lock**

**Comment by joshwillcock** [comment]
> Hi
> We have updated our plugins and now we have the following error
> 
> Sync users with Azure AD.
> Execute scheduled task: Synchroniser des utilisateurs avec Azure AD. (local_o365\task\usersync)
> **Cannot obtain task lock**

Hi Nab.

This is a Moodle warning letting you know that there are already tasks running, to stop them colliding they lock certain tasks. If you ran this task manually then your scheduled tasks were already running.

If you did this to test you would be best to move the time from 1am in Moodle or suspend the automated running before manually running.

**Comment by Nab59** [comment]
Hi,
Following your recommendation, now the cron task works.

But unfortunemy, many users account no longer exist in Azur are not deleted in Moodle.

My option **Delete previously synced accounts in Moodle when they are deleted from Azure AD is correctly set.**

Please help.
Thank you
