### ISSUE TITLE
[FIX] LEGACY API NOT WORKING

### ISSUE THREAD

**Issue by anormore** [Microsoft/o365-moodle#273]
Hey there. There are quite a few bugs with the new Graph API.

I have hacked a bunch of functions, things work well with legacy API still.

Have you hard coded this to no longer work or something? With this setting, things are still using Graph.

I'd like to go back to Legacy until the new version is fixed (profile photos).

$CFG->local_o365_forcelegacyapi = true; // THIS DOES NOTHING! Must hack the function (see GitHub: https://github.com/Microsoft/o365-moodle/issues/273)

**Comment by anormore** [comment]
I got my photos back!

Even though I set the config options, it wasn't working correctly in the unified library. So I hacked it.

Everything starts to work again. So if you have the latest version of the plugin and are afraid to downgrade like me, this has worked wonders.

Add a return false; in \local\o365\classes\rest

`    public static function is_enabled() {
        global $CFG;
		
		// ANormore@Yorkvilleu.ca
		// Set this to FORCE legacy api on
		return false;
		
        if (!empty($CFG->local_o365_forcelegacyapi)) {
            return false;
        }
        return true;
    }
`

**Comment by anormore** [comment]
This will let us limp by, in addition to the "telephone fix" as below: 

/local/o365/classes/rest/unified.php

    protected function get_default_user_fields() {
        return [
            'id',
            'userPrincipalName',
            'displayName',
            'givenName',
            'surname',
            'mail',
            'streetAddress',
            'city',
            'postalCode',
            'state',
            'country',
            'jobTitle',
            'department',
            'companyName',
            'preferredLanguage',
//            'telephoneNumber',
//            'facsimileTelephoneNumber',
//            'mobile',
        ];
    }

**Comment by anormore** [comment]
Last note: TRUNCATE YOUR TABLE!

mdl_local_o365_appassign

Then log back in to get photos back online.

**Comment by jamesmcq** [comment]
@anormore The legacy API is currently unsupported and very close to being removed completely. We have progressively made it more difficult to use (over a year or more) to encourage people to move to the graph API. Good to hear you have a temporary solution - the photos and user fields are both items that will be fixed in the upcoming release, so stay tuned!
