### ISSUE TITLE
Verify Setup step in configuration now systematically reports 'Could not check reply URL'

### ISSUE THREAD

**Issue by dlm-sadge** [Microsoft/o365-moodle#274]
We have configured the local_o365 plugin for numerous Moodle platforms over time. In the past the "Verify Setup" step in configuration has come back with all green lights.
We are currently configuring some new platforms and are systematically running into the same issue. See the screenshot below.
We have checked the plugin versions that are being used - we are on the most recent version.

![image](https://user-images.githubusercontent.com/21176465/47628680-a18ab200-db2e-11e8-9302-d059331d1552.png)

**Comment by jamesmcq** [comment]
Hi @dlm-sadge, thanks for the report. This is a known issue that will be fixed with our next release, scheduled for a few days from now.

**Comment by Richardvi** [comment]
We are also having this issue with the latest release: 3.5.0.0 (2018051700)

We are using Moodle 3.5.1

Has this been fixed or is it just back?
