### ISSUE TITLE
Extraneous enableunifiedapi language strings

### ISSUE THREAD

**Issue by tmuras** [microsoft/o365-moodle#276]
There are 2 language strings in es and pt (and possibly other) language files:
settings_enableunifiedapi
settings_enableunifiedapi_details

That do not exist in English language pack. I assume they were deleted at some point - you may want to remove them from all language packs.

**Comment by weilai-irl** [comment]
Hi @tmuras, 

Fix to this issue has been included in the latest release for 3.7, 3.8 and 3.9.
The issue will be closed.

Regards,
Lai
