### ISSUE TITLE
Logging in as a Guest

### ISSUE THREAD

**Issue by pendurocher1** [Microsoft/o365-moodle#38]
When I log in using my office365 account to moodle it is logging me in as a guest and can not access anything

**Comment by jamesmcq** [comment]
Hi pendurocher1 - Can you describe a little more exactly what's happening? If I understand correctly you're using the OpenID Connect authentication plugin to log in, but you're not being logged in? After clicking the "OpenID Connect" identity provider on the login page, are you brought to the Office login screen? After logging in there, are you returned to Moodle?

**Comment by pendurocher1** [comment]
Hi. 
I went through the DB and Actually removed that user and tired again. It worked, But now when my users first log in using there 365 account it is not saving the emails and users are getting prompted to update their email address and then of course they are getting the message that they changed their email and would get an email with their update..

**Comment by jamesmcq** [comment]
This is caused by Moodle having difficulty communicating with Office365. Have you set the system API user in the Microsoft Office 365 Integration local plugin? If so, can you click the "health check" link on that same settings page and see if it reports any issues?

**Comment by pendurocher1** [comment]
Hi, 
Our Health check reports fine.

**Comment by jamesmcq** [comment]
Can you update to the latest plugins and run the "Azure Setup" tool in the local plugin's settings page and see if it reports any issues?
