### ISSUE TITLE
Support for 'Shared with Me' in OneDrive for Business Repository

### ISSUE THREAD

**Issue by wezley98** [microsoft/o365-moodle#40]
Will this plugin set support the 'Shared with Me' folders as shown on the OneDrive for Business UI?

**Comment by jamesmcq** [comment]
This is something we're looking at, but I don't have a timeline or details at the moment.

**Comment by nenorojas** [comment]
Hi @wezley98,

This enhancement request is not in the plans for the foreseeable future, so I'm closing this request. 

Regards
