### ISSUE TITLE
Support for Azure AAD B2C and B2B

### ISSUE THREAD

**Issue by frodeste** [Microsoft/o365-moodle#54]
Is there any support for the Azure AAD B2C and B2B in Moodle?

**Comment by Alvaromp** [comment]
Any news on AAD B2C in Moodle?

**Comment by j2s** [comment]
James - Any thoughts on when this might be progressed - even a roadmap would be useful? 
Would external input help?

**Comment by nimojg-microsoft** [comment]
@j2s  This is currently not on our roadmap. External help/contributions would indeed be appreciated.
