### ISSUE TITLE
Authentication of OIDC 

### ISSUE THREAD

**Issue by frodeste** [Microsoft/o365-moodle#55]
Authentication failes with error

AADB2C90019: The application with client id '1b798af1-5d39-480f-813f-f8fb730f392c' does not contain a secret called 'client_secret'.

Moodle has been configured with client secret.

**Comment by jamesmcq** [comment]
Hi frodeste, 

Just to confirm - the client secret you entered in Moodle is the same as the "Key" generated when creating the Azure application? You may want to try generating a new key in the Azure application and pasting the new value in Moodle just to be sure.

Let me know how it goes - thanks!

**Comment by frodeste** [comment]
Yes. I have tried both.  With new key and old. I have also tries with Azure AAD B2C and AAD

**Comment by jamesmcq** [comment]
This issue was closed as part of an automated cleanup of old issues. If you are still experiencing a problem, please feel free to create a new issue with any recent developments. Thank you!
