### ISSUE TITLE
O365 group creation error from crontab

### ISSUE THREAD

**Issue by eabcdev** [Microsoft/o365-moodle#58]
Hi team, We have Moodle 2.7 with latest plugins version. 

I think We've found a bug in course / group creation functionality in this integration.
We've found that some groups are created and some are not in O365. We get this error with some courses in crontab debug:

Could not create group for course #28
array(1) {
  ["odata.error"]=>
  array(3) {
    ["code"]=>
    string(18) "Request_BadRequest"
    ["message"]=>
    array(2) {
      ["lang"]=>
      string(2) "en"
      ["value"]=>
      string(72) "Invalid value specified for property 'mailNickname' of resource 'Group'."
    }
    
We guess this is cause Moodle course shortname has an space character, is this possible? can you check it?

UPDATE 2015 10 21
Hi James, we installed plugins version v20151019_m27 and we have this error also creating groups from crontab:

task_groupcreate
Error in API call: The request body contains unexpected chracters/content for the specified content type and encoding.

I guess this is cause some unicode characters in course fullname.
thanks!

Gabriel

**Comment by jamesmcq** [comment]
This should be resolved with the latest release - please let me know if this is still a problem for you and reopen if necessary.
