### ISSUE TITLE
Duplicated calendar events

### ISSUE THREAD

**Issue by eabcdev** [Microsoft/o365-moodle#62]
Hi team, We have Moodle 2.7 with latest plugins version. 

We have an issue with duplicated calendar events, this are the steps in order to reproduce them

1- Calendar event is created in moodle course calendar
2- Calendar events are synchronized with O365, and they appear as personal events
3- As we have configured that events are synchronized in both directions,after cron execution, events are created in Moodle as personal events, so they are duplicated 

![image](https://cloud.githubusercontent.com/assets/14235324/10612602/d949a426-7727-11e5-98d8-47fe7f66723a.png)

In O365, calendar remains with no duplicity.

Other issues:
4- If teacher then changes course event in Moodle, only that event is changed, not personal one (its ok, but personal one must no exist)
![image](https://cloud.githubusercontent.com/assets/14235324/10612680/370b5d2a-7728-11e5-9a6f-6d6fbc71c3ec.png)

5- If teacher changes course event in O365, change is not synchronized into moodle. (this happens with personal events also)

best,
Gabriel

**Comment by jamesmcq** [comment]
Thanks Gabriel, I've added this to our backlog of issues to look at - should be worked on shortly.

**Comment by rlcharles** [comment]
@eabcdev I've attempted to duplicate this issue without success. Can I get the exact version of the local_o365 and local_onenote plugins you are using ?

**Comment by eabcdev** [comment]
Hi Charles, versions are:
 local_o365: 27.0.0.18
 local_onenote: 27.0.0.6
We detected that it happens with a user with student role only, it does not happens with a teacher role user.

**Comment by jamesmcq** [comment]
@eabcdev Are you still seeing this happen with the current release? If so, please reopen or create a new issue. Thanks!
