### ISSUE TITLE
OIDC AUTH when first using a Microsoft tool

### ISSUE THREAD

**Issue by upats** [Microsoft/o365-moodle#68]
Hi James,

I believe I recall when we previously used the local_msaccount plugin, it would always ask you to authenticate into OneNote, Onedrive, etc the first time you try and use a tool. Now that we've switched to local_o365, it doesn't seem to try to authenticate you on first use of a tool. It looks like the only way to connect your account to o365 is by using the Microsoft block. Is this the intended behavior? It was much nicer before when you could tie your Moodle -> Office account whenever attempting to use a tool for the first time.

Thanks!

**Comment by jamesmcq** [comment]
Originally there was no support for OneNote using the Office 365 APIs, so we included the consumer-OneNote (where you log in with a separate account) as a temporary feature until Office 365 support was ready. Now that Office 365 support for OneNote exists, the Office 365 account you're logged in to Moodle with is used to access OneNote, removing the need for another login.

However, we realize some people has separate accounts set up or prefer to log in to OneNote separately, so in the user control panel (Microsoft block > Preferences), click the "OneNote" section and you can disable Office 365 OneNote. This will revert operation to the original method - logging in separately with a Microsoft account.

Hope that helps!
