### ISSUE TITLE
The capability "auth/oidc:manageconnection" doesn't seem to work at all.

### ISSUE THREAD

**Issue by Jarvil** [Microsoft/o365-moodle#70]
Hello,

I have Microsoft-block on the Moodle front page and I have set that "Authenticated user on frontpage" is the front page role.

I prohibited auth/oidc:manageconnection from "Authenticated user on frontpage" and still users can access "Manage Office 365 connection" page without a problem and connect their Moodle account to o365 account without a problem." I'm referring to James's answer here:

https://tracker.moodle.org/browse/CONTRIB-6108

**Comment by jamesmcq** [comment]
Thanks Jarvil - this is scheduled to be fixed shortly - thanks for the report!

**Comment by jamesmcq** [comment]
A fix for this has been released. Another fix to take care of the connected-account setups mentioned in the Moodle tracker issue is coming shortly.
