### ISSUE TITLE
Onenote-submissions amount in Assignment-activity.

### ISSUE THREAD

**Issue by Jarvil** [Microsoft/o365-moodle#71]
Hello,

In the assignment-activity settings you can choose "OneNote submissions" as one of the submission types. When you have enabled onenote-submissions you can choose "Maximum number of uploaded OneNote pages" but this dropdownmenu is limited only to 1. 

Is this the purpose or can I add maximum number of uploaded onenotepages higher than 1 ? Is this a configuration issue on my part?

**Comment by jamesmcq** [comment]
This is the current limit - it may change in the future so what you're seeing is the groundwork for that, but there's nothing wrong in your setup, that's the limit for now.

**Comment by Jarvil** [comment]
Hello,

Thank you for the information.
