### ISSUE TITLE
Calendar sync FROM Outlook doesn't seem to work

### ISSUE THREAD

**Issue by Jarvil** [Microsoft/o365-moodle#72]
Hello,

Should calendar events sync from Office 365 Outlook to Moodle at the moment? I can only seem to get it work from Moodle to Outlook but not from Outlook to Moodle. 

When I run cron job manually It gives an error:

Syncing events for user #50

Error: Error in API call: The time zone information is missing on the DateTimeOffset value '2016-02-04T12:14:27'. A DateTimeOffset value must contain the time zone information.

**Comment by Jarvil** [comment]
Is this a configuration issue on my part?

**Comment by jamesmcq** [comment]
Thanks for the report - I'm not seeing that issue here but I've had one or two reports similar to this so I've created a work item to look further at this.

**Comment by jamesmcq** [comment]
Fix for this was included in the latest release. Thanks for the report!
