### ISSUE TITLE
Process Match Queue \local_o365\task\processmatchqueue fails if o365 not configured

### ISSUE THREAD

**Issue by BenKelada** [Microsoft/o365-moodle#73]
Process Match Queue \local_o365\task\processmatchqueue fails if o365 not configured

Other cron tasks check if o365 has basic configuration before running, the processmatchqueue task just runs and fails.
other tasks contain code such as 
`        $oidcconfig = get_config('auth_oidc');
        if (!empty($oidcconfig)) {`
or
`        if (\local_o365\utils::is_configured() !== true) {
            return false;
        }`
in their execute() function
processmatchqueue.php does not have this check and throws an exception when o365 is not configured.

**Comment by BenKelada** [comment]
On closer inspection it is failing because the sql query doesnt work on postgres
`Scheduled task failed: Process Match Queue (local_o365\task\processmatchqueue),Error reading from database
Debug info:
ERROR:  zero-length delimited identifier at or near """"
LINE 11: ...            WHERE mq.completed = $1 AND mq.errormessage = ""
                                                                      ^
SELECT mq.*,
                       u.id as muserid,
                       muserconn.id as muserexistingconnectionid,
                       officeconn.id as officeuserexistingconnectionid,
                       oidctok.id as officeuserexistingoidctoken
                  FROM mdl_local_o365_matchqueue mq
             LEFT JOIN mdl_user u ON mq.musername = u.username
             LEFT JOIN mdl_local_o365_connections muserconn ON muserconn.muserid = u.id
             LEFT JOIN mdl_local_o365_connections officeconn ON officeconn.aadupn = mq.o365username
             LEFT JOIN mdl_auth_oidc_token oidctok ON oidctok.oidcusername = mq.o365username
                 WHERE mq.completed = $1 AND mq.errormessage = ""
              ORDER BY mq.id ASC
                 LIMIT 0, 100
[array (
  0 => '0',
)]
Backtrace:
* line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
* line 723 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 87 of /local/o365/classes/task/processmatchqueue.php: call to pgsql_native_moodle_database->get_recordset_sql()
* line 137 of /admin/tool/task/cli/schedule_task.php: call to local_o365\task\processmatchqueue->execute()`

both the
`AND mq.errormessage = "" `
and
`LIMIT 0, 100`
are not supported
the = "" needs to be `''` or escaped -`\'\'`
instead of using the limit -,100 `$DB->get_recordset_sql($sql, $params, 0, 100);`
cheers,
Ben

**Comment by jamesmcq** [comment]
Thanks Ben - the postgres-related fixes will be out with the next release (should be a day or two), but I've created a work item to skip the task entirely if the plugins aren't configured. Thanks for the report!

**Comment by jamesmcq** [comment]
The postgres fix has been released, and the upcoming release will stop this task early as you mentioned. Thanks!

**Comment by BenKelada** [comment]
thanks james

**Comment by jamesmcq** [comment]
Fix for this was included in the latest release. Thanks for the report!
