### ISSUE TITLE
local onenote plugin dependant on block onenote

### ISSUE THREAD

**Issue by BenKelada** [Microsoft/o365-moodle#74]
local/onenote/classes/api/base.php:381 
`$notebookname = get_string('notebookname', 'block_onenote');`

the onenote api is dependant on a string in the onenote block,
we are using single sign on and dont need the block so there is an error when creating a onenote page:
```
Invalid get_string() identifier: 'notebookname' or component 'block_onenote'. Perhaps you are missing $string['notebookname'] = ''; in /lang/en/block_onenote.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 6675 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 381 of /local/onenote/classes/api/base.php: call to get_string()
line 747 of /local/onenote/classes/api/base.php: call to local_onenote\api\base->sync_notebook_data()
line 583 of /local/onenote/classes/api/base.php: call to local_onenote\api\base->get_section()
line 39 of /local/onenote/onenote_actions.php: call to local_onenote\api\base->get_page()
```

i've moved the string to the local plugin, and posting here for consideration

**Comment by jamesmcq** [comment]
Thanks for this Ben! This sheds light on another error some people were reporting.

**Comment by jamesmcq** [comment]
Fix for this was included in the latest release. Thanks for the report!
