### ISSUE TITLE
Provide admin configuration for the Microsoft block for each link.

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#77]
Some setups do not use calendar sync, for example, so provide an admin-level option to hide each of the entries in the Microsoft block. There is already an admin setting to show/hide the "Get Office 365" link, so that can be used as a template for the other links. Default should be ON.

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/80

**Comment by jamesmcq** [comment]
Looks good!
