### ISSUE TITLE
Add support for Microsoft Graph to users using Office 365 for China

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#81]
The Microsoft Graph API is now available for Office 365 for China, we should add the unique endpoint to the code to support it. Details are outlined at: http://dev.office.com/blogs/Microsoft-Graph-is-now-generally-available-in-China

**Comment by vinhub** [comment]
PR for this issue: https://github.com/Microsoft/o365-moodle/pull/90
