### ISSUE TITLE
Add support for "Trending Around Me" in the OneDrive for Business repository.

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#82]
The Graph API has support for files that are trending around the current user, as mentioned in the Office graph docs - http://graph.microsoft.io/en-us/docs

We should add this list of files to the OneDrive for Business repository as another top-level folder (Alongside my files and courses), so users have access to these files. They should be able to use these files like they can use their personal files or course files (i.e. copy them into Moodle or set aliases).

**Comment by vinhub** [comment]
Coding for this issue is complete, but we are still trying to figure out how to test it. We haven't yet figured out how to make something show up in "trending around".

**Comment by vinhub** [comment]
PR with all changes: https://github.com/Microsoft/o365-moodle/pull/108

**Comment by vinhub** [comment]
New PR with simplified diff and squished commits: https://github.com/Microsoft/o365-moodle/pull/129
