### ISSUE TITLE
Creating o365 objects in usersync

### ISSUE THREAD

**Issue by kkiiskin** [microsoft/o365-moodle#823]
When running usersync with only "Create accounts in Moodle for users in Azure AD" checked, the sync still creates o365 objects for users it matches in existing Moodleaccounts:

..Syncing user username@domain.com
..Found a user in Azure AD that seems to match a user in Moodle
..moodle username: username, aad upn: username@domain.com
..Not matching user because that sync option is disabled.
..Adding o365 object record for user.
..User is now synced.

Why is this and does it effect those existing users in any way?

**Comment by jamesmcq** [comment]
@kkiiskin Can you check the local_o365_objects table and see if the newly created records are referencing the correct user?

**Comment by jamesmcq** [comment]
Closing this issue during issue cleanup. If you need any more information or are experiencing problems, please open a new issue. Thanks!
