### ISSUE TITLE
OneNote Submission plugin in Moodle 3.6.1 causes assignment creation to fail

### ISSUE THREAD

**Issue by ThomasITS** [microsoft/o365-moodle#824]
After upgrading from Moodle 3.5.2 to 3.6.1, we were unable to create new assignments.  The error in our PHP logs was: 
PHP Warning:  require_once(C:\Moodle/lib/eventslib.php): failed to open stream: No such file or directory in C:\Moodle\mod\assign\submission\onenote\locallib.php on line 26
Uninstalling the OneNote submission plugin allowed us to create assignments.

**Comment by jeyaprakashk** [comment]
Is there any fix or any upgrade for 3.6?

**Comment by Richardvi** [comment]
Experiencing the same error after upgrade to 3.6.2:

Warning: require_once(/home/learn/public_html/lib/eventslib.php): failed to open stream: No such file or directory in /home/learn/public_html/mod/assign/submission/onenote/locallib.php on line 26

Fatal error: require_once(): Failed opening required '/home/learn/public_html/lib/eventslib.php' (include_path='/home/learn/public_html/lib/pear:.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/learn/public_html/mod/assign/submission/onenote/locallib.php on line 26

**Comment by jamesmcq** [comment]
Hi @ThomasITS @Richardvi - thanks for this report - I'm not seeing this on my Moodle 3.6 development site but will continue to investigate and update you as I have more information.

**Comment by jamesmcq** [comment]
Hi all, this should be resolved in the current version for Moodle 3.5+. If you continue to experience issues, please open a new issue. Thanks!
