### ISSUE TITLE
Add PowerBI to oEmbed Filter

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#83]

**Comment by vinhub** [comment]
PR for adding Power BI support: https://github.com/Microsoft/o365-moodle/pull/89

**Comment by jamesmcq** [comment]
Had some issues using this with PowerBI - can you take another look at this, or if it's working for you post some usage instructions.

**Comment by vinhub** [comment]
Added instructions to the new o365docs plugin for the steps you need to take to embed Power BI reports. Please let us know if it is still not working.
