### ISSUE TITLE
Moodle don't sync AAD users having characters in UPN outside the range of accepted characters.

### ISSUE THREAD

**Issue by sushantgawali** [Microsoft/o365-moodle#84]
Moodle only accepts usernames that have:
- lower case alphabet
- numbers
- dot (.)
- underscore (_)
- at (@)

AAD users having characters in UPN other than these can't by synced in Moodle.

**Comment by sushantgawali** [comment]
This issue is already being discussed here https://github.com/Microsoft/moodle-auth_oidc/issues/12.

**Comment by chadcarlton** [comment]
This is more than just UPN.  The moodle Username constraints also don't allow the full set of characters that are allowable in email addresses.

One example I run into occasionally is the plus (+) sign. I often use chad.carlton+ABBREVIATED_SITENAME@gmail.com

i..e chad.carlton+ghb@gmail.com  or chad.carlton+ntflx@gmail.com
(gmail's + support allows for infiinite email adresses)

My email address (which again is a valid email address according to RFC), would be denied by moodle if someone decided to put email address into the username field.

**Comment by jamesmcq** [comment]
This issue was closed as part of an automated cleanup of old issues. If you are still experiencing a problem, please feel free to create a new issue with any recent developments. Thank you!
