### ISSUE TITLE
Could not assign user. Reason: Error writing to database

### ISSUE THREAD

**Issue by sushantgawali** [Microsoft/o365-moodle#85]
- This error occurs when checkbox  'Assign users to application during sync' is checked on Microsoft Office 365 Integration settings page and we run cron.php.

- This is because mysql error : 'Field 'photoupdated' doesn't have a default value' during assign users process.

- When first time cron is running, when assigning users to application, we are not inserting value for 'photoupdated' field and as it does not have default value set and it is not null, mysql is giving error here.

**Comment by vinhub** [comment]
Fix: https://github.com/Microsoft/o365-moodle/pull/99

**Comment by jamesmcq** [comment]
Patches in wip-MSFTMPP-431-m27, wip-MSFTMPP-431-m28, wip-MSFTMPP-431-m29, and wip-MSFTMPP-431-m30
