### ISSUE TITLE
Enable/Disable or Show/Hide Connect with Office 365/Log in with Microsoft Account

### ISSUE THREAD

**Issue by 15kspec** [Microsoft/o365-moodle#86]
Hi,
Our school only uses Office 365, we dont want users to get confused with Microsoft/personal accounts.

Please could we get an option to disable/enable or show/hide within the Microsoft block:
Connect to Office 365
and
Log in with Microsoft Account

Thanks

**Comment by jamesmcq** [comment]
Hello - this is now available. Please update to the latest release, and you will be able to enable or disable links from the Microsoft block settings page.
