### ISSUE TITLE
cant grade onenote submissions as a teacher, if no one note account

### ISSUE THREAD

**Issue by BenKelada** [Microsoft/o365-moodle#87]
If a student submits a one note submission, the submission is zipped and submitted/copied to moodle
If a teacher/admin/marker goes to mark the assessment but is not logged in using o365, they cannot see the submission - they get an error saying no one note connection (even though the submission is actually within moodle)

Note to reproduce this you must be _really really_ signed out of one note.
i.e. if you are signed in to o365/one note as a completely different user, you can still view the submission.

**Comment by jamesmcq** [comment]
Are you using the "View Submission" link? That link goes directly to OneNote so there's not much we can do to allow someone without a OneNote account to use that link. You're right that there is a zip file of the page within Moodle - is the teacher able to download that zip and view it locally? That's about the only option to view it if the marking teacher does not have a OneNote account.
