### ISSUE TITLE
Clarify username/password auth flow does not create a session in O365

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#91]
The username/password auth flow does not create a session in O365 since authentication happens via background API. Some users are confused by this. We should add something/clarify the language to make this clear.

Tricky part here is that OpenID Connect should be as generic as possible, so try to keep language generic as well. For example:

Note: Using the username/password authentication flow will authorize you with your identity provider, but will not create a session on your identity provider's site. For example, if using Office 365 with OpenID Connect, you will be logged in to Moodle but not the Office 365 web applications. Using the authorization request is recommended if you want users to be logged in to both Moodle and your identity provider.

**Comment by vinhub** [comment]
PR for this fix: https://github.com/Microsoft/o365-moodle/pull/93
