### ISSUE TITLE
Migrate users using old OpenID Connect endpoints to new endpoints

### ISSUE THREAD

**Issue by jamesmcq** [Microsoft/o365-moodle#92]
Ensure that any users using the older OpenID Connect Office 365 endpoints are migrated to the new endpoints.

Commit 9e3053a19b353c20f9428435048d5201163b8a15 is where the defaults were updated, we should add an upgrade step to migrate anyone using the old "login.windows.net" endpoints to the new "login.microsoftonline.com" endpoints.

**Comment by vinhub** [comment]
PR with this fix: https://github.com/Microsoft/o365-moodle/pull/94

**Comment by vinhub** [comment]
PR to fix this issue: https://github.com/Microsoft/o365-moodle/pull/95
