### ISSUE TITLE
Config-check produces fatal error with PHP 5.4

### ISSUE THREAD

**Issue by kkiiskin** [Microsoft/o365-moodle#96]
From documentation for empty() -function in php.net

_Note:
Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false_

This occurs in block_microsoft at least in line 150:
&& !empty(get_config('block_microsoft', 'settings_showcoursespsite'))) {

**Comment by vinhub** [comment]
PR with fix: https://github.com/Microsoft/o365-moodle/pull/98
